Repository CDCgov/prime-reportstream, pull requests merged in 2020-11, with the labels that each got.

#51 Contributing.md and PR template
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: documentation, engineering

#50 HL7 Messages: Part 2
  prime-router/metadata/schemas/AZ/az-covid-19-hl7.schema
  prime-router/metadata/schemas/PrimeDataInput/pdi-covid-19.schema
  prime-router/metadata/schemas/covid-19.schema
  prime-router/pom.xml
  prime-router/src/main/kotlin/CsvConverter.kt
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/FakeTable.kt
  prime-router/src/main/kotlin/Hl7Converter.kt
  prime-router/src/main/kotlin/MappableTable.kt
  prime-router/src/main/kotlin/Mappers.kt
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/Schema.kt
  prime-router/src/main/kotlin/Translators.kt
  prime-router/src/test/kotlin/CsvConvertTests.kt
  prime-router/src/test/kotlin/MapperTests.kt
  prime-router/src/test/kotlin/TranslatorTests.kt
Labels: engineering, enhancement

#52 Azure support
  prime-router/.java-version
  prime-router/README.md
  prime-router/host.json
  prime-router/local.settings.json
  prime-router/pom.xml
  prime-router/src/main/kotlin/MappableTable.kt
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/azure/ProcessFunction.kt
  prime-router/src/main/kotlin/azure/TableStorage.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/test/kotlin/CsvConverterTests.kt
  prime-router/src/test/kotlin/CsvFileTests.kt
  prime-router/src/test/kotlin/ReceiverTests.kt
Labels: engineering, enhancement

#53 HL7 Work Part 3
  .gitignore
  prime-router/metadata/schemas/AZ/az-covid-19-hl7.schema
  prime-router/metadata/schemas/covid-19.schema
  prime-router/metadata/valuesets/common.valuesets
  prime-router/pom.xml
  prime-router/src/main/kotlin/Hl7Converter.kt
  prime-router/src/main/resources/build.properties
Labels: engineering, enhancement

#86 Basic structure for SFTP transport with happy path
  .gitignore
  prime-router/local.settings.json
  prime-router/metadata/receivers.yml
  prime-router/pom.xml
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/kotlin/transport/SftpTransport.kt
Labels: engineering

#84 Report refactoring
  prime-router/docker-compose.yml
  prime-router/docs/assets/entity-relationships.png
  prime-router/docs/engineering.md
  prime-router/metadata/organizations.yml
  prime-router/metadata/receivers.yml
  prime-router/pom.xml
  prime-router/src/main/kotlin/CsvConverter.kt
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/FakeReport.kt
  prime-router/src/main/kotlin/Hl7Converter.kt
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/Organization.kt
  prime-router/src/main/kotlin/OrganizationClient.kt
  prime-router/src/main/kotlin/OrganizationService.kt
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/Schema.kt
  prime-router/src/main/kotlin/azure/BlobStorage.kt
  prime-router/src/main/kotlin/azure/IngestedFile.kt
  prime-router/src/main/kotlin/azure/ProcessFunction.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/main/kotlin/transport/SftpTransport.kt
  prime-router/src/test/csv_test_files/input/test-organizations.yml
  prime-router/src/test/csv_test_files/input/test-receivers.yml
  prime-router/src/test/kotlin/CsvConverterTests.kt
  prime-router/src/test/kotlin/CsvFileTests.kt
  prime-router/src/test/kotlin/FakeReportTests.kt
  prime-router/src/test/kotlin/Hl7ConverterTests.kt
  prime-router/src/test/kotlin/MappableTableTests.kt
  prime-router/src/test/kotlin/MetadataTests.kt
  prime-router/src/test/kotlin/OrganizationTests.kt
  prime-router/src/test/kotlin/ReceiverTests.kt
  prime-router/src/test/kotlin/ReportTests.kt
  prime-router/src/test/unit_test_files/organizations.yml
Labels: engineering

#92 Connect Ingest to Process to Send Function
  prime-router/docs/assets/data-flow.png
  prime-router/docs/engineering.md
  prime-router/metadata/organizations.yml
  prime-router/pom.xml
  prime-router/src/main/kotlin/CsvConverter.kt
  prime-router/src/main/kotlin/Hl7Converter.kt
  prime-router/src/main/kotlin/Mappers.kt
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/OrganizationClient.kt
  prime-router/src/main/kotlin/OrganizationService.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/Schema.kt
  prime-router/src/main/kotlin/Source.kt
  prime-router/src/main/kotlin/azure/AzureStorage.kt
  prime-router/src/main/kotlin/azure/BlobStorage.kt
  prime-router/src/main/kotlin/azure/IngestFunction.kt
  prime-router/src/main/kotlin/azure/IngestedFile.kt
  prime-router/src/main/kotlin/azure/ProcessFunction.kt
  prime-router/src/main/kotlin/azure/ReportQueue.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/main/kotlin/transport/SftpTransport.kt
  prime-router/src/test/kotlin/Azure/ReportQueueTests.kt
  prime-router/src/test/kotlin/OrganizationTests.kt
  prime-router/src/test/unit_test_files/organizations.yml
Labels: engineering, enhancement

#93 Move AZ back to CSV files
  prime-router/metadata/organizations.yml
Labels: engineering, onboarding
