Repository CDCgov/prime-reportstream, pull requests merged in 2021-10, with the labels that each got.

#2441 Rhood/2398 Changes to All-In-One-Health schema
  prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
  prime-router/docs/schema_documentation/experity-experity-covid-19.md
  prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
  prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
  prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema
  prime-router/metadata/valuesets/sender-automation.valuesets
Labels: onboarding, sender-automation

#2486 Fix #2347: Fill the OBX-17.2 field with equipment model
  prime-router/metadata/schemas/covid-19.schema
Labels: receiver

#2471 Update direct schema to use reporting_facility_name
  prime-router/docs/schema_documentation/direct-anavasidx-covid-19.md
  prime-router/docs/schema_documentation/direct-cue-covid-19.md
  prime-router/docs/schema_documentation/direct-direct-covid-19.md
  prime-router/docs/schema_documentation/direct-imagemover-covid-19.md
  prime-router/docs/schema_documentation/direct-inbios-covid-19.md
  prime-router/docs/schema_documentation/direct-safehealth-covid-19.md
  prime-router/docs/schema_documentation/hhsprotect-hhsprotect-covid-19.md
  prime-router/metadata/schemas/direct/direct-covid-19.schema
  prime-router/metadata/schemas/hhsprotect/hhsprotect-covid-19.schema
Labels: sender-pipeline

#2351 #1974 - add customerStatus to sender and receiver
  prime-router/settings/SETTINGS-TEST-ORG.yml
  prime-router/settings/organizations-prod.yml
  prime-router/settings/organizations-test.yml
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/Sender.kt
  prime-router/src/main/kotlin/SettingsProvider.kt
  prime-router/src/main/kotlin/azure/SettingsFacade.kt
  prime-router/src/main/kotlin/cli/ProcessDataCommands.kt
  prime-router/src/main/kotlin/cli/tests/WatersAuthTests.kt
  prime-router/src/scripts/db_one_off/1974_customer_status.sql
  prime-router/src/test/csv_test_files/input/test-organizations.yml
  prime-router/src/test/kotlin/FileSettingsTests.kt
  prime-router/src/test/kotlin/JurisdictionalFilterTests.kt
  prime-router/src/test/kotlin/ReceiverTests.kt
  prime-router/src/test/kotlin/ReportTests.kt
  prime-router/src/test/kotlin/TranslatorTests.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/azure/SettingFacadeTests.kt
  prime-router/src/test/kotlin/azure/TokenFunctionTests.kt
  prime-router/src/test/kotlin/azure/WorkflowEngineTests.kt
  prime-router/src/test/kotlin/tokens/TokenAuthenticationTests.kt
Labels: onboarding

#2472 React Org Dropdown
  frontend-react/src/App.tsx
  frontend-react/src/components/GlobalContextProvider.tsx
  frontend-react/src/components/ReportStreamHeader.tsx
  frontend-react/src/components/header/HowItWorksDropdown.tsx
  frontend-react/src/components/header/OrgDropdown.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/components/header/SignInOrUser.tsx
  frontend-react/src/content/live.json
  frontend-react/src/pages/Login.tsx
  frontend-react/src/pages/daily/Daily.tsx
  frontend-react/src/pages/daily/Table/TableReports.tsx
  frontend-react/src/pages/details/Details.tsx
  frontend-react/src/pages/details/FacilitiesTable.tsx
  frontend-react/src/pages/details/Summary.tsx
  frontend-react/src/resources/AuthResource.ts
  frontend-react/src/resources/FacilityResource.ts
  frontend-react/src/utils/OrganizationUtils.ts
  frontend-react/src/utils/ReportUtils.ts
  frontend-react/src/utils/UserUtils.ts
Labels: front-end, react, website

#2507 Facilities call done with rest-hooks
  frontend-react/src/content/live.json
  frontend-react/src/pages/details/FacilitiesTable.tsx
  frontend-react/src/resources/FacilityResource.ts
Labels: front-end, react, website

#2520 fix: Frontend CI not running
  .github/workflows/build_frontend.yaml
Labels: DevOps, front-end

#2515 Get uswds trussworks scss build working
  frontend-react/craco.config.js
  frontend-react/gulpfile.js
  frontend-react/package.json
  frontend-react/src/App.css
  frontend-react/src/App.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/global.scss
  frontend-react/src/index.tsx
  frontend-react/src/styles/_print.scss
  frontend-react/src/styles/_reportstream.scss
  frontend-react/src/styles/_uswds_overrides.scss
  frontend-react/src/styles/_uswds_settings.scss
  frontend-react/yarn.lock
Labels: react

#2513 change `npm` to `yarn` for build_frontend_react's package management
  .github/workflows/build_frontend.yaml
  .github/workflows/release.yml
Labels: github_actions, react

#2536 rhood/2448 Add Zip Codes
  prime-router/metadata/tables/zip-code-data.csv
Labels: sender-automation

#2559 Increase database instance size
  operations/app/src/modules/database/main.tf
Labels: DevOps

#2563 Rhood/2528 changes to all in one schema
  prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
  prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema
Labels: sender-automation

#2538 Update PR template to remove downloading file from api/download
  .github/pull_request_template.md
Labels: sender-pipeline

#1965 Jorgel/githooks/ktlint
  .environment/ktlint/Dockerfile
  .environment/ktlint/run-ktlintCheck.sh
  .environment/pre-commit.runner.sh
Labels: Onboarding & Ops

#2612 rhood/2607 CUC - Add RightSign Antibody Test
  prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
  prime-router/docs/schema_documentation/experity-experity-covid-19.md
  prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
  prime-router/metadata/schemas/Experity/CUC-AL-covid-19.schema
  prime-router/metadata/schemas/Experity/GUC-LA-covid-19.schema
  prime-router/metadata/schemas/Experity/experity-covid-19.schema
Labels: Onboarding & Ops

#2627 rhood/2626 Add Zip Codes
  prime-router/metadata/tables/zip-code-data.csv
Labels: Onboarding & Ops

#2633 Production Load Simulator, first pass
  prime-router/settings/organizations.yml
  prime-router/settings/staging/0047-load-simulation-rcvr1.yml
  prime-router/settings/staging/0048-load-simulation-rcvr2.yml
  prime-router/settings/staging/0049-hhsprotect-timing.yml
  prime-router/src/main/kotlin/cli/tests/Simulator.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
Labels: sender-pipeline

#2836 Revert the Palo Alto in production
  operations/app/src/environments/configurations/prod.tfvars
Labels: DevOps
