Repository CDCgov/prime-reportstream, pull requests merged in 2021-08, with the labels that each got.

#1761 GitHub run_gitleaks Action Fix
  .environment/gitleaks/gitleaks-config.toml
  .environment/gitleaks/run-gitleaks.sh
  .github/workflows/run_gitleaks.yaml
Labels: DevOps, Robustness, bug, github_actions, security

#1725 Update the GitHub Action to use slots for deployments to production
  .github/workflows/release.yml
Labels: DevOps

#1802 gitleaks: fixing false positives
  .environment/gitleaks/gitleaks-config.toml
Labels: DevOps, security, chore

#1803 gitleaks: adding exclusion for commit that is about to come
  .environment/gitleaks/gitleaks-config.toml
Labels: DevOps, security

#1804 gitleaks: further suppressions
  .environment/gitleaks/gitleaks-config.toml
Labels: DevOps, security

#1805 td/1779 document gitleaks suppression
  .environment/gitleaks/gitleaks-config.toml
  prime-router/docs/allowlist-gitleaks-false-positives.md
  prime-router/docs/getting_started.md
Labels: documentation, DevOps, security, chore

#1806 Connect WA-PHD to WA UAT (test)
  prime-router/settings/prod/0037-wa-uat.yml
  prime-router/settings/staging/0037-wa-uat.yml
Labels: onboarding, receiver, support

#1808 Bg 1787 ca onboarding
  prime-router/docs/proposals/0001-authentication.md
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/azure/HttpUtilities.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/main/resources/clitests/compare-test-files/test-0001-az-covid-19-hl7.hl7
  prime-router/src/main/resources/clitests/compare-test-files/test-0001-input-covid-19.hl7
  prime-router/src/test/hl7_test_files/batch_message.hl7
  prime-router/src/test/hl7_test_files/single_message.hl7
  prime-router/src/test/kotlin/serializers/CsvSerializerTests.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt.orig
  prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-batch-pdi-20210608-0001.hl7
  prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-single-pdi-20210608-0002.hl7
Labels: receiver

#1819 docs: Adding instructions on how to activate the OpenVPN tunnel on Linux
  prime-router/docs/vpn.md
Labels: documentation, DevOps

#1825 gitleaks: fix 2021-08-10 run
  .environment/gitleaks/gitleaks-config.toml
Labels: DevOps, security

#1824 gitleaks workflow: output the non-sensitive log after a gitleaks run
  .github/workflows/run_gitleaks.yaml
Labels: DevOps, security, github_actions

#1829 Updates the Storage Queue Docker Dependencies
  frontend/Dockerfile_dev
  frontend/gulpfile.js
  frontend/package-lock.json
  frontend/package.json
  prime-router/build.gradle.kts
  prime-router/docker-compose.yml
Labels: receiver

#1837 Adds Pem File Credentials for SFTP Login
  prime-router/src/main/kotlin/azure/HttpUtilities.kt
  prime-router/src/main/kotlin/azure/SettingsFacade.kt
  prime-router/src/main/kotlin/cli/CredentialsCli.kt
  prime-router/src/main/kotlin/cli/tests/TestKeys.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/cli/tests/WatersAuthTests.kt
  prime-router/src/main/kotlin/credentials/Credential.kt
  prime-router/src/main/kotlin/transport/SftpTransport.kt
  prime-router/src/test/kotlin/MapperTests.kt
  prime-router/src/test/kotlin/TranslatorTests.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
  prime-router/src/test/kotlin/tokens/TokenAuthenticationTests.kt
Labels: receiver, pipeline-capabilities

#1838 Onboarding of Reddy Family Medical Clinic sender
  prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
  prime-router/metadata/schemas/iPatientCare/ReddyFMC-LA-covid-19.schema
Labels: onboarding, sender-automation

#1846 Bg bugfix replaceValue
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/TranslatorTests.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
Labels: receiver

#1852 Bg 1848 20 char limit
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
  prime-router/src/test/unit_test_files/ak_test_file.csv
Labels: engineering, receiver

#1859 Updates to Reddy schema based on input from LADOH
  prime-router/docs/schema_documentation/ipatientcare-ipatientcare-covid-19.md
  prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
  prime-router/metadata/schemas/iPatientCare/ReddyFMC-LA-covid-19.schema
  prime-router/metadata/schemas/iPatientCare/iPatientCare-covid-19.schema
Labels: onboarding, sender-automation

#1735 added dual template function
  prime-router/src/main/kotlin/azure/EmailEngineFunction.kt
Labels: send-grid

#1898 changes to support windows
  .environment/gitleaks/run-gitleaks.sh
Labels: engineering, DevOps, security, chore

#1900 Point WA to Prod
  prime-router/settings/prod/0039-wa-prod.yml
Labels: onboarding, receiver, setting-change

#1895 Add GitHub Actions for automatic deployment branches (closes #1851)
  .github/workflows/prepare_deployment_branch.yaml
Labels: engineering, DevOps, github_actions, chore

#1618 add badHl7 tests
  prime-router/src/main/kotlin/cli/tests/Hl7Tests.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
Labels: testing

#1915 Add Reddy FMC to the HHSProtect jurisdictional filter
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0040-hhsprotect.yml
  prime-router/settings/staging/0039-hhsprotect.yml
Labels: onboarding, sender-automation

#1918 Update STLT live map and list
  frontend/src/_data/content/where-were-live.yaml
  frontend/src/assets/img/rs-live-stlt-20200811.svg
  frontend/src/assets/img/rs-live-stlt.svg
Labels: Design, website

#1953 Document Deployment Process
  DEPLOYMENTS.md
Labels: documentation, DevOps

#1844 Fixes for NH feedback
  prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
  prime-router/docs/schema_documentation/az-pima-az-covid-19.md
  prime-router/docs/schema_documentation/co-co-covid-19-redox.md
  prime-router/docs/schema_documentation/covid-19-redox.md
  prime-router/docs/schema_documentation/covid-19.md
  prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
  prime-router/docs/schema_documentation/direct-primary-covid-19.md
  prime-router/docs/schema_documentation/fl-fl-covid-19.md
  prime-router/docs/schema_documentation/gu-gu-covid-19.md
  prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19.md
  prime-router/docs/schema_documentation/ipatientcare-ipatientcare-covid-19.md
  prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
  prime-router/docs/schema_documentation/la-la-covid-19.md
  prime-router/docs/schema_documentation/mt-mt-covid-19-csv.md
  prime-router/docs/schema_documentation/mt-mt-covid-19.md
  prime-router/docs/schema_documentation/nd-nd-covid-19.md
  prime-router/docs/schema_documentation/nm-nm-covid-19.md
  prime-router/docs/schema_documentation/oh-oh-covid-19.md
  prime-router/docs/schema_documentation/or-or-covid-19-hl7.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-redox.md
  prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
  prime-router/docs/schema_documentation/standard-standard-covid-19.md
  prime-router/docs/schema_documentation/strac-strac-covid-19.md
  prime-router/docs/schema_documentation/tpca-tpca-covid-19.md
  prime-router/docs/schema_documentation/tx-tx-covid-19.md
  prime-router/docs/schema_documentation/vt-vt-covid-19.md
  prime-router/metadata/schemas/covid-19.schema
  prime-router/metadata/valuesets/common.valuesets
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/TranslatorConfiguration.kt
  prime-router/src/main/kotlin/azure/EmailEngineFunction.kt
  prime-router/src/main/kotlin/cli/FileUtilities.kt
  prime-router/src/main/kotlin/cli/ProcessDataCommands.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/main/kotlin/transport/SftpTransport.kt
  prime-router/src/test/hl7_test_files/batch_message.hl7
  prime-router/src/test/hl7_test_files/single_message.hl7
  prime-router/src/test/kotlin/serializers/CsvSerializerTests.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
  prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-batch-pdi-20210608-0001.hl7
  prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-batch-pdi-20210816-0001.hl7
  prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-batch-pdi-20210824-0001.hl7
  prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-single-pdi-20210608-0002.csv
  prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-single-pdi-20210608-0002.hl7
  prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-single-pdi-20210816-0002.hl7
  prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-single-pdi-20210824-0002.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: Scale-States, receiver

#1978 Fix for #1977: Only run terraform format check hook when there are terraform changes
  .environment/terraform-fmt/run-terraform-fmt.sh
Labels: engineering, DevOps, terraform, chore

#2019 gitleaks: fix 2021-08-{28-30} runs
  .environment/gitleaks/gitleaks-config.toml
Labels: engineering, chore

#2006 Bg HD truncation
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
  prime-router/src/test/unit_test_files/ak_test_file.csv
Labels: engineering, onboarding, receiver

#1988 Fix patient age encoding in HL7
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/HistoryFunctions.kt
  prime-router/src/main/kotlin/cli/tests/Hl7Tests.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
Labels: HL7, receiver

#1943 Adds depbot check playbook
  prime-router/docs/playbooks/dependabot-updates.md
Labels: documentation, receiver

#1896 Palo Alto: Base VNET Setup
  operations/Dockerfile
  operations/Makefile
  operations/app/src/environments/01-network/main.tf
  operations/app/src/environments/02-config/main.tf
  operations/app/src/environments/03-persistent/main.tf
  operations/app/src/environments/04-app/main.tf
  operations/app/src/modules/common/vnet_dns_zones/main.tf
  operations/app/src/modules/common/vnet_dns_zones/variables.tf
  operations/app/src/modules/network/data.tf
  operations/app/src/modules/network/dns.tf
  operations/app/src/modules/network/main.tf
  operations/app/src/modules/network/old-vnet.tf
  operations/app/src/modules/network/vpn.tf
  operations/docker-compose.yml
Labels: engineering, DevOps, terraform

#2046 1827 Turn on App Insights profiling
  operations/app/src/modules/function_app/main.tf
  prime-router/host.json
Labels: DevOps
