Repository CDCgov/prime-reportstream, pull requests merged in 2021-01, with the labels that each got.

#228 PA and STRAC onboarding using Redox
  .github/workflows/release.yml
  .gitignore
  prime-router/.editorconfig
  prime-router/docker-compose.yml
  prime-router/docs/schema_mappings/12_29 PA DOH __ STRAX PRIME HL7 Mapping.xlsx
  prime-router/metadata/organizations-local.yml
  prime-router/metadata/organizations-prod.yml
  prime-router/metadata/organizations-test.yml
  prime-router/metadata/organizations.yml
  prime-router/metadata/schemas/AZ/az-covid-19-csv.schema
  prime-router/metadata/schemas/AZ/pima-az-covid-19-csv.schema
  prime-router/metadata/schemas/CO/co-covid-19-redox.schema
  prime-router/metadata/schemas/PA/pa-covid-19-hl7.schema
  prime-router/metadata/schemas/PA/pa-covid-19-redox.schema
  prime-router/metadata/schemas/PrimeDataInput/pdi-covid-19.schema
  prime-router/metadata/schemas/STRAC/strac-covid-19.schema
  prime-router/metadata/schemas/covid-19-redox.schema
  prime-router/metadata/schemas/covid-19.schema
  prime-router/metadata/valuesets/covid-19.valuesets
  prime-router/pom.xml
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/FakeReport.kt
  prime-router/src/main/kotlin/JurisdictionalFilters.kt
  prime-router/src/main/kotlin/Mappers.kt
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/OrganizationService.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/Schema.kt
  prime-router/src/main/kotlin/Translator.kt
  prime-router/src/main/kotlin/TransportType.kt
  prime-router/src/main/kotlin/azure/BatchFunction.kt
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/Event.kt
  prime-router/src/main/kotlin/azure/QueueAccess.kt
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/main/kotlin/serializers/CsvSerializer.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/main/kotlin/serializers/ReadResult.kt
  prime-router/src/main/kotlin/serializers/RedoxSerializer.kt
  prime-router/src/main/kotlin/transport/ITransport.kt
  prime-router/src/main/kotlin/transport/RedoxTransport.kt
  prime-router/src/main/kotlin/transport/RetryToken.kt
  prime-router/src/main/kotlin/transport/SftpTransport.kt
  prime-router/src/main/resources/db/migration/V2__retry_token.sql
  prime-router/src/test/kotlin/CsvFileTests.kt
  prime-router/src/test/kotlin/MetadataTests.kt
  prime-router/src/test/kotlin/SimpleReportTests.kt
  prime-router/src/test/kotlin/TranslatorTests.kt
  prime-router/src/test/kotlin/azure/EventTest.kt
  prime-router/src/test/kotlin/azure/SendFunctionTests.kt
  prime-router/src/test/kotlin/azure/WorkflowEngineTests.kt
  prime-router/src/test/kotlin/serializers/CsvSerializersTests.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
  prime-router/src/test/redox/initializerJson.json
  prime-router/src/test/redox/mockserver.properties
Labels: engineering, enhancement, onboarding

#272 Bug Fix: Chester and Montgomery County
  prime-router/metadata/organizations-local.yml
  prime-router/metadata/organizations-prod.yml
  prime-router/metadata/organizations-test.yml
  prime-router/metadata/organizations.yml
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/test/kotlin/MetadataTests.kt
Labels: bug, engineering

#281 CO/Redox Fix
  prime-router/metadata/organizations-local.yml
  prime-router/metadata/organizations-test.yml
  prime-router/src/main/kotlin/transport/RedoxTransport.kt
  prime-router/src/test/redox/initializerJson.json
Labels: bug

#290 Add a patient_id for STRAC when none exists
  prime-router/metadata/schemas/PA/pa-covid-19-redox.schema
  prime-router/metadata/schemas/STRAC/strac-covid-19.schema
  prime-router/src/main/kotlin/serializers/RedoxSerializer.kt
Labels: bug

#273 Auth Proposal
  prime-router/docs/assets/backend-service-authorization-diagram.png
  prime-router/docs/proposals/authentication.md
Labels: devops, enhancement

#271 Make actions work for external PRs
  .github/workflows/build.yml
  .github/workflows/release.yml
  prime-router/pom.xml
Labels: devops

#365 setting redirect directly
  prime-router/src/main/kotlin/azure/DownloadFunction.kt
Labels: bug

#366 Redox ResultsStatus typo
  prime-router/metadata/schemas/covid-19-redox.schema
Labels: bug

#274 Fake data improvements
  prime-router/metadata/schemas/AZ/pima-az-covid-19-csv.schema
  prime-router/metadata/schemas/FL/fl-covid-19.schema
  prime-router/metadata/valuesets/florida.valuesets
  prime-router/metadata/valuesets/snomed.valuesets
  prime-router/quick-test.sh
  prime-router/src/main/kotlin/CsvComparer.kt
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/FakeReport.kt
  prime-router/src/main/kotlin/Mappers.kt
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/ValueSet.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/main/kotlin/serializers/CsvSerializer.kt
  prime-router/src/test/kotlin/ElementTests.kt
  prime-router/src/test/kotlin/FakeReportTests.kt
  prime-router/src/test/kotlin/MapperTests.kt
  prime-router/src/test/kotlin/MetadataTests.kt
  prime-router/src/test/kotlin/SimpleReportTests.kt
Labels: Blocked, engineering, enhancement

#328 Create a Proposal Process read-me
  prime-router/docs/proposals/0000-proposal-process-readme.md
  prime-router/docs/proposals/0001-authentication.md
  prime-router/docs/proposals/0002-secrets-management.md
  prime-router/docs/proposals/0003-lineage/README.md
  prime-router/docs/proposals/0003-lineage/lineage-er-diagram.jpeg
  prime-router/docs/proposals/0003-lineage/recursive-parent-child-test.sql
Labels: engineering
