Repository CDCgov/prime-reportstream, pull requests merged in 2021-12, with the labels that each got.

#3268 rhood/3224 A1H Changes based on Testing
  prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
  prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema
Labels: onboarding-ops

#3280 rhood/3275-Add Zip Codes
  prime-router/metadata/tables/zip-code-data.csv
Labels: onboarding-ops

#3298 json-schema package upgrade
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: experience

#3276 Josiahsiegel/#1048 generate GitHub releases
  .github/workflows/github_release.yaml
Labels: DevOps

#3282 Get .env switching working for staging
  .github/workflows/build_frontend.yaml
  frontend-react/.env
  frontend-react/.env.development
  frontend-react/.env.production
  frontend-react/.env.staging
  frontend-react/.env.test
  frontend-react/package.json
  frontend-react/src/App.tsx
  frontend-react/src/pages/Upload.tsx
  frontend-react/src/pages/daily/Table/ReportLink.tsx
  frontend-react/src/pages/how-it-works/WebReceiverGuide.tsx
  frontend-react/src/pages/tos-sign/TermsOfServiceForm.tsx
  frontend-react/src/resources/AuthResource.ts
  frontend-react/src/resources/CardResource.ts
  frontend-react/src/resources/FacilityResource.ts
  frontend-react/src/resources/OrganizationResource.ts
  frontend-react/src/resources/ReportResource.ts
  frontend-react/src/resources/SenderOrganizationResource.ts
  frontend-react/yarn.lock
Labels: experience

#3113 Removing no longer used test_result_report_date field
  prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
  prime-router/docs/schema_documentation/covid-19.md
  prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
  prime-router/docs/schema_documentation/direct-hca-covid-19.md
  prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19.md
  prime-router/docs/schema_documentation/hl7-lifepoint-covid-19.md
  prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
  prime-router/docs/schema_documentation/hl7-primary-covid-19.md
  prime-router/docs/schema_documentation/hl7-test-covid-19.md
  prime-router/docs/schema_documentation/la-la-covid-19.md
  prime-router/docs/schema_documentation/mt-mt-covid-19.md
  prime-router/docs/schema_documentation/nm-nm-covid-19.md
  prime-router/docs/schema_documentation/or-or-covid-19-hl7.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
  prime-router/docs/schema_documentation/standard-standard-covid-19.md
  prime-router/docs/schema_documentation/tx-tx-covid-19.md
  prime-router/docs/schema_documentation/vt-vt-covid-19.md
  prime-router/metadata/schemas/covid-19.schema
Labels: onboarding-ops

#3335 rhood/3310-A1H Add Default Provider
  prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
  prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema
Labels: onboarding-ops

#3334 rhood/3333-CUC Zip Code Updates
  prime-router/metadata/tables/zip-code-data.csv
Labels: onboarding-ops

#3122 Server Side Cursor Based Pagination
  prime-router/docs/openapi.yml
  prime-router/src/main/kotlin/Submission.kt
  prime-router/src/main/kotlin/azure/Authentication.kt
  prime-router/src/main/kotlin/azure/DatabaseSubmissionsAccess.kt
  prime-router/src/main/kotlin/azure/SubmissionFunction.kt
  prime-router/src/main/kotlin/azure/SubmissionsFacade.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/cli/tests/TestSubmissionsAPI.kt
  prime-router/src/test/kotlin/azure/HttpTestUtils.kt
  prime-router/src/test/kotlin/azure/SubmissionFunctionTests.kt
  prime-router/src/test/kotlin/azure/TokenFunctionTests.kt
Labels: sender

#3339 Josiahsiegel/#1048 generate GitHub releases
  .github/workflows/github_release.yaml
Labels: DevOps

#3058 Small edits to reflect the changes in prod and staging
  prime-router/settings/prod/0049-update-vt-doh.yml
  prime-router/settings/staging/0048-setup-clarkcounty-oh-doh.yml
  prime-router/settings/staging/0049-update-vt-doh.yml
  prime-router/settings/staging/0050-update-mn-doh.yml
Labels: onboarding-ops

#3126 3125 Moved fips-county table to the database
  .environment/gitleaks/gitleaks-config.toml
  .github/workflows/build_hub.yml
  .github/workflows/release.yml
  prime-router/settings/put-local-settings.py
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/CheckFunction.kt
  prime-router/src/main/kotlin/azure/EmailEngineFunction.kt
  prime-router/src/main/kotlin/azure/SettingsFacade.kt
  prime-router/src/main/kotlin/azure/TokenFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/main/kotlin/tokens/TokenAuthentication.kt
  prime-router/src/main/kotlin/transport/AS2Transport.kt
  prime-router/src/main/kotlin/transport/GAENTransport.kt
  prime-router/src/main/kotlin/transport/SoapTransport.kt
  prime-router/src/test/kotlin/CsvFileTests.kt
  prime-router/src/test/kotlin/FakeReportTests.kt
  prime-router/src/test/kotlin/MetadataTests.kt
  prime-router/src/test/kotlin/ReportTests.kt
  prime-router/src/test/kotlin/TranslatorTests.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/azure/SendFunctionTests.kt
  prime-router/src/test/kotlin/azure/SettingFacadeTests.kt
  prime-router/src/test/kotlin/azure/TokenFunctionTests.kt
  prime-router/src/test/kotlin/azure/WorkflowEngineTests.kt
  prime-router/src/test/kotlin/metadata/LookupTableTests.kt
  prime-router/src/test/kotlin/serializers/CsvSerializerTests.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
  prime-router/src/test/kotlin/transport/RedoxTransportTests.kt
  prime-router/src/test/kotlin/unittest/UnitTestUtils.kt
  prime-router/src/test/resources/metadata/tables/README.md
  prime-router/src/test/resources/metadata/tables/fips-county.csv
  prime-router/src/testIntegration/kotlin/FakeReportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/FileNameTemplateIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/MetadataIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/SimpleReportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/serializers/Hl7SerializerIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/AS2TransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/GAENTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/SoapTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/TransportIntegrationTests.kt
Labels: pipeline

#3337 3271 Added wait for API to be available to settings command
  .github/workflows/build_hub.yml
  prime-router/docker-compose.yml
  prime-router/settings/Dockerfile
  prime-router/settings/put-local-settings.py
  prime-router/settings/readme.md
  prime-router/settings/requirements.txt
  prime-router/src/main/kotlin/azure/LookupTableFunctions.kt
  prime-router/src/main/kotlin/cli/CommandUtilities.kt
  prime-router/src/main/kotlin/cli/LookupTableCommands.kt
  prime-router/src/main/kotlin/cli/SettingCommands.kt
  prime-router/start_func.sh
Labels: pipeline

#3376 rhood/3375 Add Zip Codes - 2021-12-09
  prime-router/metadata/tables/zip-code-data.csv
Labels: onboarding-ops

#3377 Fix 404 page copy for staging and production
  frontend-react/package.json
Labels: bug, experience

#3384 How It Works bad path fix
  frontend-react/src/pages/how-it-works/HowItWorks.tsx
Labels: bug, frontend, experience

#3389 Fix all the broken unit tests (2)
  frontend-react/package.json
  frontend-react/src/components/Title.test.tsx
  frontend-react/src/content/content.json
  frontend-react/src/pages/home/Home.test.tsx
  frontend-react/src/pages/home/Home.tsx
  frontend-react/src/pages/tos-sign/SuccessPage.test.tsx
  frontend-react/src/pages/tos-sign/SuccessPage.tsx
  frontend-react/src/pages/tos-sign/TermsOfServiceForm.test.tsx
  frontend-react/src/pages/tos-sign/TermsOfServiceForm.tsx
  frontend-react/yarn.lock
Labels: bug, experience, tech-debt

#3403 Added check for last modified time to settings CLI
  prime-router/build.gradle.kts
  prime-router/docs/getting-started/faster-development.md
  prime-router/src/main/kotlin/azure/HttpUtilities.kt
  prime-router/src/main/kotlin/cli/LookupTableCommands.kt
  prime-router/src/main/kotlin/cli/SettingCommands.kt
  prime-router/start_func.sh
Labels: pipeline

#3404 Run automated checks on regular PR (NOT master or production)
  .github/workflows/build_frontend.yaml
  frontend-react/package.json
  frontend-react/src/pages/tos-sign/TermsOfServiceForm.test.tsx
Labels: experience, tech-debt

#3397 Updated gitleaks version, commands, and flags
  .environment/gitleaks/run-gitleaks.sh
Labels: bug, DevOps

#3439 Fixing 2 bugs with token request
  prime-router/src/main/kotlin/azure/TokenFunction.kt
  prime-router/src/main/kotlin/tokens/SenderUtils.kt
Labels: bug, onboarding-ops

#3429 Fixes issue with the new truncation logic truncating fields it should not be
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
Labels: bug, onboarding-ops

#3472 Onboarding sender PMG
  prime-router/docs/schema_documentation/direct-pmg-covid-19.md
  prime-router/metadata/schemas/direct/pmg-covid-19.schema
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0055-pmg.yml
  prime-router/settings/staging/0055-pmg.yml
Labels: onboarding-ops

#3230 Removed auth needed for TOS form
  frontend-react/src/App.tsx
  frontend-react/src/pages/tos-sign/TermsOfServiceForm.tsx
  prime-router/src/main/kotlin/azure/EmailSenderFunction.kt
Labels: experience

#3463 Add testkit lookup table
  prime-router/src/test/resources/metadata/tables/testkit-lookup.csv
Labels: experience

#3392 Local frontend, backend, and vpn actions. closes #3386
  .github/actions/build-frontend/action.yml
  .github/actions/deploy-backend/action.yml
  .github/actions/deploy-frontend/action.yml
  .github/actions/vpn-azure/action.yml
  .github/workflows/build_frontend.yaml
  .github/workflows/github_release.yaml
  .github/workflows/release.yml
  DEPLOYMENTS.md
Labels: backend, DevOps, frontend

#3293 3231: Schema markdown doc type CODE cleanup
  prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
  prime-router/docs/schema_documentation/az-az-covid-19.md
  prime-router/docs/schema_documentation/az-az-ihs-covid-19.md
  prime-router/docs/schema_documentation/az-pima-az-covid-19.md
  prime-router/docs/schema_documentation/ca-ca-scc-covid-19.md
  prime-router/docs/schema_documentation/co-co-covid-19-redox.md
  prime-router/docs/schema_documentation/covid-19-gaen.md
  prime-router/docs/schema_documentation/covid-19-redox.md
  prime-router/docs/schema_documentation/covid-19.md
  prime-router/docs/schema_documentation/direct-abbott-covid-19.md
  prime-router/docs/schema_documentation/direct-anavasidx-covid-19.md
  prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
  prime-router/docs/schema_documentation/direct-cue-covid-19.md
  prime-router/docs/schema_documentation/direct-direct-covid-19.md
  prime-router/docs/schema_documentation/direct-directlite-covid-19.md
  prime-router/docs/schema_documentation/direct-hca-covid-19.md
  prime-router/docs/schema_documentation/direct-imagemover-covid-19.md
  prime-router/docs/schema_documentation/direct-inbios-covid-19.md
  prime-router/docs/schema_documentation/direct-pmg-covid-19.md
  prime-router/docs/schema_documentation/direct-safehealth-covid-19.md
  prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
  prime-router/docs/schema_documentation/experity-experity-covid-19.md
  prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
  prime-router/docs/schema_documentation/fl-fl-covid-19.md
  prime-router/docs/schema_documentation/fl-fl-hillsborough-covid-19-csv.md
  prime-router/docs/schema_documentation/gu-gu-covid-19.md
  prime-router/docs/schema_documentation/hhsprotect-hhsprotect-covid-19.md
  prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19.md
  prime-router/docs/schema_documentation/hl7-lifepoint-covid-19.md
  prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
  prime-router/docs/schema_documentation/hl7-primary-covid-19.md
  prime-router/docs/schema_documentation/hl7-test-covid-19.md
  prime-router/docs/schema_documentation/ipatientcare-ipatientcare-covid-19.md
  prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
  prime-router/docs/schema_documentation/la-la-covid-19.md
  prime-router/docs/schema_documentation/mt-mt-covid-19-csv.md
  prime-router/docs/schema_documentation/mt-mt-covid-19.md
  prime-router/docs/schema_documentation/nd-nd-covid-19.md
  prime-router/docs/schema_documentation/nm-nm-covid-19-csv.md
  prime-router/docs/schema_documentation/nm-nm-covid-19.md
  prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
  prime-router/docs/schema_documentation/oh-oh-covid-19.md
  prime-router/docs/schema_documentation/or-or-covid-19-hl7.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-redox.md
  prime-router/docs/schema_documentation/pa-pa-covid-19.md
  prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
  prime-router/docs/schema_documentation/standard-standard-covid-19.md
  prime-router/docs/schema_documentation/strac-strac-covid-19.md
  prime-router/docs/schema_documentation/tpca-tpca-covid-19.md
  prime-router/docs/schema_documentation/tx-tx-covid-19.md
  prime-router/docs/schema_documentation/vt-vt-covid-19.md
  prime-router/docs/schema_documentation/waters-waters-covid-19.md
  prime-router/src/main/kotlin/DocumentationFactory.kt
  prime-router/src/test/kotlin/DocumentationTests.kt
Labels: pipeline

#3504 fixes #1048 add config file to github release
  .github/changelog_config.json
  .github/workflows/github_release.yaml
Labels: DevOps

#3517 OO/3507/A1H Make Patient County Optional
  prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
  prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema
Labels: onboarding-ops

#3529 3527 Increased read timeouts for Settings CLI operations
  prime-router/src/main/kotlin/cli/LookupTableCommands.kt
  prime-router/src/main/kotlin/cli/SettingCommands.kt
  prime-router/src/main/kotlin/cli/SettingsUtilities.kt
Labels: pipeline

#3519 3175 LIVD Lookup handles non-unique lookup values
  prime-router/src/main/kotlin/FakeReport.kt
  prime-router/src/main/kotlin/Mappers.kt
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/azure/MetaDataFunction.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/metadata/DatabaseLookupTable.kt
  prime-router/src/main/kotlin/metadata/LookupTable.kt
  prime-router/src/test/kotlin/FakeReportTests.kt
  prime-router/src/test/kotlin/MapperTests.kt
  prime-router/src/test/kotlin/MetadataTests.kt
  prime-router/src/test/kotlin/metadata/DatabaseLookupTableTests.kt
  prime-router/src/test/kotlin/metadata/LookupTableTests.kt
  prime-router/src/testIntegration/kotlin/FakeReportIntegrationTests.kt
Labels: pipeline

#3415 Adding padding to the postal codes when it doesn't match the regex
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/test/kotlin/ElementTests.kt
Labels: bug, onboarding-ops, data-issue

#3522 3295: Schema markdown cleanup add schema basic info
  prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
  prime-router/docs/schema_documentation/az-az-covid-19.md
  prime-router/docs/schema_documentation/az-az-ihs-covid-19.md
  prime-router/docs/schema_documentation/az-pima-az-covid-19.md
  prime-router/docs/schema_documentation/ca-ca-scc-covid-19.md
  prime-router/docs/schema_documentation/co-co-covid-19-redox.md
  prime-router/docs/schema_documentation/covid-19-gaen.md
  prime-router/docs/schema_documentation/covid-19-redox.md
  prime-router/docs/schema_documentation/covid-19.md
  prime-router/docs/schema_documentation/direct-abbott-covid-19.md
  prime-router/docs/schema_documentation/direct-anavasidx-covid-19.md
  prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
  prime-router/docs/schema_documentation/direct-cue-covid-19.md
  prime-router/docs/schema_documentation/direct-direct-covid-19.md
  prime-router/docs/schema_documentation/direct-directlite-covid-19.md
  prime-router/docs/schema_documentation/direct-hca-covid-19.md
  prime-router/docs/schema_documentation/direct-imagemover-covid-19.md
  prime-router/docs/schema_documentation/direct-inbios-covid-19.md
  prime-router/docs/schema_documentation/direct-pmg-covid-19.md
  prime-router/docs/schema_documentation/direct-safehealth-covid-19.md
  prime-router/docs/schema_documentation/empty.md
  prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
  prime-router/docs/schema_documentation/experity-experity-covid-19.md
  prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
  prime-router/docs/schema_documentation/fl-fl-covid-19.md
  prime-router/docs/schema_documentation/fl-fl-hillsborough-covid-19-csv.md
  prime-router/docs/schema_documentation/gu-gu-covid-19.md
  prime-router/docs/schema_documentation/hhsprotect-hhsprotect-covid-19.md
  prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19.md
  prime-router/docs/schema_documentation/hl7-lifepoint-covid-19.md
  prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
  prime-router/docs/schema_documentation/hl7-primary-covid-19.md
  prime-router/docs/schema_documentation/hl7-test-covid-19.md
  prime-router/docs/schema_documentation/ipatientcare-ipatientcare-covid-19.md
  prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
  prime-router/docs/schema_documentation/la-la-covid-19.md
  prime-router/docs/schema_documentation/mt-mt-covid-19-csv.md
  prime-router/docs/schema_documentation/mt-mt-covid-19.md
  prime-router/docs/schema_documentation/nd-nd-covid-19.md
  prime-router/docs/schema_documentation/nm-nm-covid-19-csv.md
  prime-router/docs/schema_documentation/nm-nm-covid-19.md
  prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
  prime-router/docs/schema_documentation/oh-oh-covid-19.md
  prime-router/docs/schema_documentation/or-or-covid-19-hl7.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-redox.md
  prime-router/docs/schema_documentation/pa-pa-covid-19.md
  prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
  prime-router/docs/schema_documentation/sample-fed1-sample.md
  prime-router/docs/schema_documentation/sample-phd1-sample.md
  prime-router/docs/schema_documentation/sample-phd2-sample.md
  prime-router/docs/schema_documentation/standard-standard-covid-19.md
  prime-router/docs/schema_documentation/strac-strac-covid-19.md
  prime-router/docs/schema_documentation/tpca-tpca-covid-19.md
  prime-router/docs/schema_documentation/tx-tx-covid-19.md
  prime-router/docs/schema_documentation/upload-covid-19.md
  prime-router/docs/schema_documentation/vt-vt-covid-19.md
  prime-router/docs/schema_documentation/waters-waters-covid-19.md
  prime-router/src/main/kotlin/DocumentationFactory.kt
  prime-router/src/test/kotlin/DocumentationTests.kt
Labels: pipeline

#3564 Clark County to CSV Format - Download Site
  prime-router/docs/schema_documentation/oh-oh-clark-covid-19-csv.md
  prime-router/metadata/schemas/OH/oh-clark-covid-19-csv.schema
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0055-update-il-phd.yml
  prime-router/settings/prod/0056-update-nj-doh.yml
  prime-router/settings/prod/0057-update-vt-doh.yml
  prime-router/settings/prod/0058-update-clark-county-oh-doh.yml
  prime-router/settings/staging/0055-update-il-phd.yml
  prime-router/settings/staging/0056-update-nj-doh.yml
  prime-router/settings/staging/0057-update-vt-doh.yml
  prime-router/settings/staging/0058-update-clark-county-oh-doh.yml
Labels: onboarding-ops

#3582 Removing the fuzzy csv library from the application
  prime-router/build.gradle.kts
Labels: security

#3591 OO/3590- A1H Equipment Model Required
  prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
  prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema
Labels: onboarding-ops, High Priority, experience

#3589 OO/3583- CUC - Add Zip Codes
  prime-router/metadata/tables/zip-code-data.csv
Labels: onboarding-ops, High Priority

#3588 OO/3584-Experity/CUC Make Patient County Optional
  prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
  prime-router/docs/schema_documentation/experity-experity-covid-19.md
  prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
  prime-router/metadata/schemas/Experity/experity-covid-19.schema
Labels: onboarding-ops, High Priority, Enhancement

#3595 OO/3592- ReddyFMC-County Optional and Provider Changes
  prime-router/docs/schema_documentation/ipatientcare-ipatientcare-covid-19.md
  prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
  prime-router/metadata/schemas/iPatientCare/ReddyFMC-LA-covid-19.schema
  prime-router/metadata/schemas/iPatientCare/iPatientCare-covid-19.schema
Labels: onboarding-ops, High Priority, Enhancement

#3596 Onboarding AnavasiDX
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0058-anavasidx.yml
  prime-router/settings/staging/0058-anavasidx.yml
Labels: onboarding-ops

#3593 3378: PRIME CLI Download latest LOINC Test Code.
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/cli/LivdTableDownload.kt
  prime-router/src/main/kotlin/cli/main.kt
Labels: pipeline

#3597 MA Missing OBX-24
  prime-router/docs/schema_documentation/strac-strac-covid-19.md
  prime-router/metadata/schemas/STRAC/strac-covid-19.schema
Labels: onboarding-ops

#3609 3594: Cleaned up the compile warning messages
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/FileSettings.kt
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/ReportStreamFilter.kt
  prime-router/src/main/kotlin/ReportStreamFilterDefinition.kt
  prime-router/src/main/kotlin/Translator.kt
  prime-router/src/main/kotlin/azure/EmailEngineFunction.kt
  prime-router/src/main/kotlin/azure/EmailSenderFunction.kt
  prime-router/src/main/kotlin/azure/MetaDataFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/cli/CredentialsCli.kt
  prime-router/src/main/kotlin/cli/tests/CompareData.kt
  prime-router/src/main/kotlin/cli/tests/SftpcheckTest.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/transport/RetryToken.kt
  prime-router/src/main/kotlin/transport/SoapTransport.kt
  prime-router/src/test/kotlin/azure/SubmissionFunctionTests.kt
Labels: pipeline

#3636 TOS Email Bug Fix
  frontend-react/src/pages/tos-sign/SuccessPage.tsx
  prime-router/src/main/kotlin/azure/EmailSenderFunction.kt
Labels: bug, backend, experience
