Repository CDCgov/prime-reportstream, pull requests merged in 2021-05, with the labels that each got.

#977 Bug Fix Settings Authentication Bug
  prime-router/src/main/kotlin/azure/Authentication.kt
  prime-router/src/test/kotlin/azure/AuthenticationTests.kt
Labels: bug

#1011 Final (really) bug fixes
  frontend/src/data-show.html
  frontend/src/js/prime-web-receiver-pre.js
  prime-router/src/main/kotlin/azure/HistoryFunctions.kt
Labels: bug

#1056 More flexible LIVD Lookup
  prime-router/metadata/schemas/covid-19.schema
  prime-router/src/main/kotlin/FakeReport.kt
  prime-router/src/main/kotlin/LookupTable.kt
  prime-router/src/main/kotlin/Mappers.kt
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/serializers/CsvSerializer.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/MapperTests.kt
Labels: engineering, enhancement

#1167 Add Allegheny county destination
  prime-router/settings/prod/0025-update-pa-allegheny.yml
Labels: Scale-Local, Scale-States, onboarding

#1072 Proposal: EmailSchedule Service
  prime-router/docs/proposals/0007-email-notification/0007-email-notification.md
  prime-router/docs/proposals/0007-email-notification/openapi.emailservice.yml
Labels: proposal
