Repository CDCgov/prime-reportstream, pull requests merged in 2021-06, with the labels that each got.

#1198 Ignore Database Size in Terraform
  operations/app/src/modules/database/main.tf
Labels: DevOps, bug

#1218 Fixes sofia look up bug in LIVD table
  prime-router/src/main/kotlin/LookupTable.kt
  prime-router/src/main/kotlin/Mappers.kt
  prime-router/src/main/kotlin/cli/TestReportStream.kt
  prime-router/src/test/kotlin/MapperTests.kt
Labels: engineering

#1265 Enhancements to the operations' Makefile
  operations/Makefile
Labels: DevOps

#1314 Enforce TLS 1.2 and disable public access on main storage account
  operations/app/src/modules/storage/main.tf
Labels: DevOps

#1216 Added ktlint to gradle
  prime-router/build.gradle.kts
  prime-router/settings.gradle.kts
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/DocumentationFactory.kt
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/FakeReport.kt
  prime-router/src/main/kotlin/JurisdictionalFilters.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/Translator.kt
  prime-router/src/main/kotlin/azure/BatchFunction.kt
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/main/kotlin/azure/CheckFunction.kt
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/DownloadFunction.kt
  prime-router/src/main/kotlin/azure/HistoryFunctions.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/kotlin/azure/SettingsFacade.kt
  prime-router/src/main/kotlin/cli/FileUtilities.kt
  prime-router/src/main/kotlin/cli/TestReportStream.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/main/kotlin/serializers/CsvSerializer.kt
  prime-router/src/main/kotlin/transport/AS2Transport.kt
  prime-router/src/main/kotlin/transport/BlobStoreTransport.kt
  prime-router/src/main/kotlin/transport/RedoxTransport.kt
  prime-router/src/main/kotlin/transport/SftpTransport.kt
  prime-router/src/test/kotlin/FileNameTemplateTests.kt
  prime-router/src/test/kotlin/JurisdictionalFilterTests.kt
  prime-router/src/test/kotlin/ReportTests.kt
  prime-router/src/test/kotlin/serializers/CsvSerializerTests.kt
  prime-router/src/test/kotlin/serializers/datatests/ObservationMessageTests.kt
  prime-router/src/test/kotlin/transport/AS2TransportTests.kt
  prime-router/src/test/kotlin/transport/RedoxTransportTests.kt
Labels: chore

#1222 #1075 Multi Organization Support
  frontend/src/_includes/navbar.liquid
  frontend/src/js/prime-web-receiver-pre.js
  prime-router/src/main/kotlin/azure/HistoryFunctions.kt
Labels: enhancement, front-end

#1267 1213 Add CSV to HL7 integration tests
  .github/workflows/build_hub.yml
  prime-router/build.gradle.kts
  prime-router/docker-compose.yml
  prime-router/src/main/kotlin/Mappers.kt
  prime-router/src/main/kotlin/azure/HistoryFunctions.kt
  prime-router/src/testIntegration/kotlin/datatests/ConversionTest.kt
  prime-router/src/testIntegration/kotlin/datatests/CsvToHl7ConversionTests.kt
  prime-router/src/testIntegration/kotlin/datatests/Hl7ToCsvConversionTests.kt
  prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-batch-pdi-20210608-0001.csv
  prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-batch-pdi-20210608-0001.hl7
  prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-single-pdi-20210608-0002.csv
  prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-single-pdi-20210608-0002.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_CSV/CE-20200415-0001.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_CSV/CE-20200415-0001.internal.csv
  prime-router/src/testIntegration/resources/datatests/HL7_to_CSV/EHT-20210316-0001.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_CSV/EHT-20210316-0001.internal.csv
  prime-router/src/testIntegration/resources/datatests/HL7_to_CSV/FLFHospital-SARSCOV2-20200317-0001.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_CSV/FLFHospital-SARSCOV2-20200317-0001.internal.csv
Labels: HL7

#1279 1138 Added support to decode email from HL7
  operations/app/src/environments/tf
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
  prime-router/src/testIntegration/kotlin/datatests/CsvToHl7ConversionTests.kt
  prototypes/as2/gradlew
  prototypes/as2/gradlew.bat
Labels: HL7

#1316 1139 Add HL7 ingest optional field test and code coverage
  .github/workflows/build_hub.yml
  operations/app/src/environments/tf
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/testIntegration/resources/datatests/HL7_to_CSV/EHT-20210316-0001.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_CSV/FLFHospital-SARSCOV2-20200317-0001.hl7
Labels: HL7

#1327 Canned data for localhost
  frontend/eleventy.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/_layouts/protected.liquid
  frontend/src/js/localhost_data.js
  frontend/src/js/prime-web-receiver-pre.js
Labels: front-end

#1377 Create issue template for security-related issues and pull requests templates that require a specific focus on security during the review
  .github/ISSUE_TEMPLATE/security_issue.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/vulnerability.md
  .github/pull_request_template.md
  SECURITY.md
Labels: documentation

#1386 Remove the security_issue.md file
  .github/ISSUE_TEMPLATE/security_issue.md
Labels: documentation

#1395 Add playbook for shutting down resources
  operations/README.md
  prime-router/docs/playbooks/shutdown.md
Labels: DevOps

#1297 Fixed idle timer
  frontend/src/js/prime-web-receiver-post.js
  frontend/src/js/prime-web-receiver-pre.js
Labels: bug, front-end

#1296 Application Insights script
  frontend/src/_layouts/protected.liquid
  frontend/src/js/application-insights.js
  workspace.code-workspace
Labels: front-end

#1434 Update daily email template
  prime-router/assets/email-templates/css/custom.css
  prime-router/assets/email-templates/css/foundation-emails.css
  prime-router/assets/email-templates/scheduled-daily-email.html
  prime-router/assets/email-templates/scheduled-daily-email_inline.html
  prime-router/assets/email-templates/test-results-ready__inline.html
Labels: Content, Design, front-end

#1407 Proposal: IP Address CIDR Request
  prime-router/docs/proposals/0008-cdc-ip-space.md
Labels: DevOps, proposal
