Repository CDCgov/prime-reportstream, pull requests merged in 2021-02, with the labels that each got.

#417 Added Okta CSS subresource integrity fingerprint.
  prime-router/assets/csv-download-site/login__inline.html
Labels: Robustness

#398 Added an example for`api/report` with fake data
  prime-router/devenv-infrastructure.sh
  prime-router/examples/upload-fake-data/example.sh
  prime-router/examples/upload-fake-data/readme.md
Labels: documentation

#452 Fix for the HL7 Batch
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/azure/ReportFunction.kt
Labels: bug

#465 Rick/hl7 batch fix2
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/Translator.kt
  prime-router/src/main/kotlin/azure/BatchFunction.kt
Labels: bug

#437 Upgrade Log4j for Security
  prime-router/pom.xml
Labels: devops, security

#432 Added an example for data lineage with PostgreSQL queries
  .gitignore
  prime-router/examples/data-lineage/example-ancestors.sh
  prime-router/examples/data-lineage/example-cousins.sh
  prime-router/examples/data-lineage/example-full.sh
  prime-router/examples/data-lineage/example-never-sent.sh
  prime-router/examples/data-lineage/example-sent.sh
  prime-router/examples/data-lineage/example-setup.sh
  prime-router/examples/data-lineage/lineage-ancestors.sql
  prime-router/examples/data-lineage/lineage-cousins.sql
  prime-router/examples/data-lineage/lineage-full.sql
  prime-router/examples/data-lineage/lineage-never-sent.sql
  prime-router/examples/data-lineage/lineage-sent.sql
  prime-router/examples/data-lineage/readme.md
  prime-router/examples/upload-fake-data/example.sh
Labels: documentation

#471 Disable PR
  prime-router/metadata/organizations-local.yml
  prime-router/metadata/organizations-test.yml
Labels: bug, onboarding

#526 Add a pentest org to the test deployment
  prime-router/metadata/organizations-test.yml
Labels: security
