Repository CDCgov/prime-reportstream, pull requests merged in 2021-11, with the labels that each got.

#2553 ErrorBoundary and ErrorPage upgrades
  frontend-react/src/App.tsx
  frontend-react/src/pages/Upload.tsx
  frontend-react/src/pages/daily/Daily.tsx
  frontend-react/src/pages/details/Details.tsx
  frontend-react/src/pages/error/ErrorPage.tsx
Labels: frontend, experience

#2812 2824: Fix KTLint git hook on a M1 Mac
  .environment/ktlint/run-ktlintCheck.sh
Labels: DevOps

#2827 fix: Update CORS entries
  operations/app/src/modules/function_app/main.tf
  operations/app/src/modules/network/old-vnet.tf
Labels: DevOps

#2831 Updates baseUrl to include cache query by current date as ISOString
  frontend-react/src/resources/ReportResource.ts
Labels: experience

#2855 Add directions for using the VPN profile creation script
  prime-router/docs/vpn.md
Labels: DevOps

#2840 2751 Integrate database lookup tables
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/FakeReport.kt
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/SettingsFacade.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/cli/LookupTableCommands.kt
  prime-router/src/main/kotlin/cli/ProcessDataCommands.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/metadata/DatabaseLookupTable.kt
  prime-router/src/main/kotlin/metadata/LookupTable.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/main/resources/log4j2.xml
  prime-router/src/test/kotlin/FakeReportTests.kt
  prime-router/src/test/kotlin/FileNameTemplateTests.kt
  prime-router/src/test/kotlin/MapperTests.kt
  prime-router/src/test/kotlin/MetadataTests.kt
  prime-router/src/test/kotlin/ReportTests.kt
  prime-router/src/test/kotlin/SimpleReportTests.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/azure/SendFunctionTests.kt
  prime-router/src/test/kotlin/metadata/DatabaseLookupTableTests.kt
  prime-router/src/test/kotlin/metadata/LookupTableTests.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
  prime-router/src/test/kotlin/transport/AS2TransportTests.kt
  prime-router/src/test/kotlin/transport/RedoxTransportTests.kt
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
  prime-router/src/testIntegration/kotlin/quicktests/QuickTestUtils.kt
Labels: pipeline

#2860 Updates remote check timing to something less aggressive than every five minutes
  prime-router/local.settings.json
Labels: onboarding-ops

#2956 AZ Missing Lab Name and Specimen ID
  prime-router/docs/schema_documentation/az-az-covid-19.md
  prime-router/docs/schema_documentation/az-az-ihs-covid-19.md
  prime-router/metadata/schemas/AZ/az-covid-19-csv.schema
Labels: onboarding-ops

#2940 Bg concat obx23 2709
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
Labels: onboarding-ops

#2867 Bg 2550 hillsborough hl7to csv
  prime-router/docs/schema_documentation/fl-fl-hillsborough-covid-19-csv.md
  prime-router/metadata/schemas/FL/fl-hillsborough-covid-19-csv.schema
  prime-router/settings/organizations.yml
Labels: onboarding-ops

#2928 2714 Refactored environment settings to be in a common place
  prime-router/src/main/kotlin/azure/HttpUtilities.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/cli/OktaCommands.kt
  prime-router/src/main/kotlin/cli/SenderUtilsCommand.kt
  prime-router/src/main/kotlin/cli/SettingCommands.kt
  prime-router/src/main/kotlin/cli/tests/CompareData.kt
  prime-router/src/main/kotlin/cli/tests/Hl7Tests.kt
  prime-router/src/main/kotlin/cli/tests/SettingsTest.kt
  prime-router/src/main/kotlin/cli/tests/Simulator.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/cli/tests/WatersAuthTests.kt
  prime-router/src/main/kotlin/common/Environment.kt
  prime-router/src/main/kotlin/tokens/OktaAuthentication.kt
  prime-router/src/main/kotlin/tokens/SenderUtils.kt
  prime-router/src/main/kotlin/transport/RedoxTransport.kt
  prime-router/src/main/kotlin/transport/SftpTransport.kt
Labels: pipeline

#2993 Design bug fixes for react launch
  frontend-react/src/components/ReportStreamFooter.tsx
  frontend-react/src/content/content.json
  frontend-react/src/pages/About.tsx
  frontend-react/src/pages/Login.tsx
  frontend-react/src/pages/TermsOfService.tsx
  frontend-react/src/pages/daily/Table/TableReports.tsx
  frontend-react/src/pages/details/FacilitiesTable.tsx
  frontend-react/src/pages/home/Features/DeliveryMethodsFeature.tsx
  frontend-react/src/pages/home/Hero.tsx
  frontend-react/src/pages/home/Home.tsx
  frontend-react/src/pages/home/Sections/CtaSection.tsx
  frontend-react/src/pages/home/Sections/LiveMapSection.tsx
  frontend-react/src/pages/how-it-works/HowItWorks.tsx
  frontend-react/src/pages/how-it-works/WebReceiverGuide.tsx
  frontend-react/src/styles/_reportstream.scss
  frontend-react/src/styles/_uswds_overrides.scss
  frontend-react/src/styles/_uswds_settings.scss
Labels: bug, design, frontend

#3007 Okta widget img path now reflects React release image path
  frontend-react/src/oktaConfig.ts
  frontend-react/src/utils/UserUtils.ts
Labels: bug, experience

#3023 MA Missing OBR-22 In Messages From STRAC
  prime-router/docs/schema_documentation/strac-strac-covid-19.md
  prime-router/metadata/schemas/STRAC/strac-covid-19.schema
Labels: onboarding-ops, support

#3010 MN - Suppresses SPM-2-1
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0050-update-mn-doh.yml
  prime-router/settings/staging/0050-update-mn-doh.yml
Labels: onboarding-ops, support

#3024 Updates to Lifepoint and Abbott schemas
  prime-router/docs/schema_documentation/direct-abbott-covid-19.md
  prime-router/docs/schema_documentation/direct-directlite-covid-19.md
  prime-router/docs/schema_documentation/hl7-lifepoint-covid-19.md
  prime-router/metadata/schemas/HL7/lifepoint-covid-19.schema
  prime-router/metadata/schemas/direct/abbott-covid-19.schema
  prime-router/metadata/schemas/direct/directlite-covid-19.schema
Labels: onboarding-ops

#3036 Onboard prescryptive
  prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
  prime-router/metadata/schemas/HL7/prescryptive-covid-19.schema
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0051-prescryptive.yml
  prime-router/settings/staging/0051-prescryptive.yml
Labels: onboarding-ops

#3025 Remove cache query for reports url
  frontend-react/src/resources/ReportResource.ts
Labels: frontend, experience

#3062 fixes #3035 update dev env to use react fe
  frontend-react/Dockerfile
  prime-router/docker-compose.yml
Labels: bug

#2994 2985 LIVD lookup with model value variation
  prime-router/src/main/kotlin/Mappers.kt
  prime-router/src/test/kotlin/MapperTests.kt
Labels: pipeline

#2988 2885 Load lookup tables locally for testing
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/azure/DatabaseLookupTableAccess.kt
  prime-router/src/main/kotlin/cli/LookupTableCommands.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/test/kotlin/azure/DatabaseLookupTableAccessTests.kt
  prime-router/src/test/resources/metadata/tables/README.md
  prime-router/start_func.sh
Labels: pipeline

#2948 Fix typescript errors on login page
  frontend-react/package.json
  frontend-react/src/App.tsx
  frontend-react/src/content/README.md
  frontend-react/src/pages/Login.tsx
  frontend-react/src/pages/error/ErrorPage.test.tsx
  frontend-react/src/pages/home/Home.tsx
  frontend-react/src/pages/home/Sections/LiveMapSection.tsx
  frontend-react/src/pages/how-it-works/WhereWereLive.tsx
Labels: experience

#3044 2713 Add Jacoco in-file coverage
  prime-router/build.gradle.kts
Labels: pipeline

#3008 fixes #3000 local tf false azure requirment set
  operations/app/src/environments/tf
Labels: bug, DevOps

#3090 Primary Health to production
  prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
  prime-router/docs/schema_documentation/az-az-covid-19.md
  prime-router/docs/schema_documentation/az-az-ihs-covid-19.md
  prime-router/docs/schema_documentation/az-pima-az-covid-19.md
  prime-router/docs/schema_documentation/ca-ca-scc-covid-19.md
  prime-router/docs/schema_documentation/co-co-covid-19-redox.md
  prime-router/docs/schema_documentation/covid-19-redox.md
  prime-router/docs/schema_documentation/covid-19.md
  prime-router/docs/schema_documentation/direct-abbott-covid-19.md
  prime-router/docs/schema_documentation/direct-anavasidx-covid-19.md
  prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
  prime-router/docs/schema_documentation/direct-cue-covid-19.md
  prime-router/docs/schema_documentation/direct-direct-covid-19.md
  prime-router/docs/schema_documentation/direct-directlite-covid-19.md
  prime-router/docs/schema_documentation/direct-hca-covid-19.md
  prime-router/docs/schema_documentation/direct-imagemover-covid-19.md
  prime-router/docs/schema_documentation/direct-inbios-covid-19.md
  prime-router/docs/schema_documentation/direct-safehealth-covid-19.md
  prime-router/docs/schema_documentation/fl-fl-covid-19.md
  prime-router/docs/schema_documentation/fl-fl-hillsborough-covid-19-csv.md
  prime-router/docs/schema_documentation/gu-gu-covid-19.md
  prime-router/docs/schema_documentation/hhsprotect-hhsprotect-covid-19.md
  prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19.md
  prime-router/docs/schema_documentation/hl7-lifepoint-covid-19.md
  prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
  prime-router/docs/schema_documentation/hl7-primary-covid-19.md
  prime-router/docs/schema_documentation/la-la-covid-19.md
  prime-router/docs/schema_documentation/mt-mt-covid-19-csv.md
  prime-router/docs/schema_documentation/mt-mt-covid-19.md
  prime-router/docs/schema_documentation/nd-nd-covid-19.md
  prime-router/docs/schema_documentation/nm-nm-covid-19-csv.md
  prime-router/docs/schema_documentation/nm-nm-covid-19.md
  prime-router/docs/schema_documentation/oh-oh-covid-19.md
  prime-router/docs/schema_documentation/or-or-covid-19-hl7.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-redox.md
  prime-router/docs/schema_documentation/pa-pa-covid-19.md
  prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
  prime-router/docs/schema_documentation/standard-standard-covid-19.md
  prime-router/docs/schema_documentation/strac-strac-covid-19.md
  prime-router/docs/schema_documentation/tpca-tpca-covid-19.md
  prime-router/docs/schema_documentation/tx-tx-covid-19.md
  prime-router/docs/schema_documentation/vt-vt-covid-19.md
  prime-router/docs/schema_documentation/waters-waters-covid-19.md
  prime-router/metadata/schemas/HL7/primary-covid-19.schema
  prime-router/metadata/valuesets/covid-19.valuesets
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0052-primary.yml
  prime-router/settings/staging/0052-primary.yml
  prime-router/src/main/kotlin/Mappers.kt
Labels: onboarding-ops

#3012 2978 Add a new sftpcehck CoolTest that checks all the ignore receivers.
  prime-router/src/main/kotlin/cli/tests/SftpcheckTest.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
Labels: pipeline

#2937 1911 - Fixed Patient_age display negative
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/test/kotlin/ReportTests.kt
Labels: pipeline

#2886 #2455: Updates to consolidated error and warning messaging
  frontend-react/src/pages/Upload.tsx
  prime-router/docs/releases/2021-11-04-release-notes.md
  prime-router/src/main/kotlin/azure/ActionHistory.kt
Labels: backend, experience

#3119 Simplified ktlint prehook script
  .environment/ktlint/Dockerfile
  .environment/ktlint/run-ktlintCheck.sh
Labels: pipeline

#2662 Terms of Services Agreement Form
  email-templates/scheduled-daily-email-no-data_inline.html
  frontend-react/package.json
  frontend-react/src/App.tsx
  frontend-react/src/components/Title.tsx
  frontend-react/src/content/site.json
  frontend-react/src/pages/tos-sign/SuccessPage.test.tsx
  frontend-react/src/pages/tos-sign/SuccessPage.tsx
  frontend-react/src/pages/tos-sign/TermsOfServiceForm.test.tsx
  frontend-react/src/pages/tos-sign/TermsOfServiceForm.tsx
  frontend-react/src/utils/OrganizationUtils.ts
  frontend-react/yarn.lock
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/azure/EmailSenderFunction.kt
Labels: experience

#3138 Move all in one to prod
  prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
  prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema
Labels: onboarding-ops

#3136 Fixes the /report-details page refresh bug
  frontend-react/package.json
  frontend-react/src/components/header/OrgDropdown.tsx
  frontend-react/src/pages/daily/Table/ReportLink.tsx
  frontend-react/src/pages/details/Details.tsx
  frontend-react/src/pages/details/FacilitiesTable.tsx
  frontend-react/yarn.lock
  prime-router/src/main/kotlin/azure/HistoryFunctions.kt
Labels: backend, frontend, experience

#3147 fixes #3141 change dev-inf.sh interp from sh to bash
  prime-router/devenv-infrastructure.sh
Labels: DevOps

#2970 2775 GAEN Transport for WANOTIFY
  prime-router/docs/schema_documentation/covid-19-gaen.md
  prime-router/metadata/schemas/covid-19-gaen.schema
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0051-wa-gaen.yml
  prime-router/settings/staging/0051-wa-gaen.yml
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/TranslatorConfiguration.kt
  prime-router/src/main/kotlin/TransportType.kt
  prime-router/src/main/kotlin/azure/BatchFunction.kt
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/cli/CredentialsCli.kt
  prime-router/src/main/kotlin/cli/FileUtilities.kt
  prime-router/src/main/kotlin/cli/ProcessDataCommands.kt
  prime-router/src/main/kotlin/credentials/Credential.kt
  prime-router/src/main/kotlin/credentials/CredentialManagement.kt
  prime-router/src/main/kotlin/credentials/CredentialService.kt
  prime-router/src/main/kotlin/transport/AS2Transport.kt
  prime-router/src/main/kotlin/transport/FTPSTransport.kt
  prime-router/src/main/kotlin/transport/GAENTransport.kt
  prime-router/src/main/kotlin/transport/SftpTransport.kt
  prime-router/src/test/kotlin/transport/GAENTransportTests.kt
Labels: onboarding-ops, support

#2961 PA Redox Conversion
  .environment/gitleaks/gitleaks-config.toml
  .environment/soap_service/README.md
  .environment/soap_service/soap/operation/v2/6j63DO.opr
  .environment/soap_service/soap/operation/v2/CTZklI.opr
  .environment/soap_service/soap/port/v2/KvNydr.port
  .environment/soap_service/soap/port/v2/WHa8Op.port
  .environment/soap_service/soap/project/v2/eUAvaN.prj
  .environment/soap_service/soap/resource/v2/HRVbuD.rsc
  .environment/soap_service/soap/resource/v2/wsdl/HRVbuD.rsc
  .environment/soap_service/soap/response/v2/PRBkKQ.res
  .environment/soap_service/soap/response/v2/sjIvfk.res
  .environment/soap_service/user/ig8mfM.user
  .gitignore
  prime-router/build.gradle.kts
  prime-router/docker-compose.yml
  prime-router/docs/schema_documentation/strac-strac-covid-19.md
  prime-router/metadata/file_name_templates/file-name-templates.yml
  prime-router/metadata/schemas/STRAC/strac-covid-19.schema
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0053-pa-soap-transports.yml
  prime-router/settings/staging/0053-pa-soap-transports.yml
  prime-router/src/main/kotlin/DocumentationFactory.kt
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/TranslatorConfiguration.kt
  prime-router/src/main/kotlin/TransportType.kt
  prime-router/src/main/kotlin/ValueSet.kt
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/cli/ConvertFileCommands.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/main/kotlin/credentials/Credential.kt
  prime-router/src/main/kotlin/credentials/CredentialService.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/main/kotlin/serializers/SoapSerializer.kt
  prime-router/src/main/kotlin/serializers/soapimpl/PAELRImpl.kt
  prime-router/src/main/kotlin/transport/SoapTransport.kt
  prime-router/src/main/resources/db/migration/V26__convert_action_result_to_text.sql
  prime-router/src/main/resources/db/migration/V27__upsize_report_file_transport_result.sql
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
  prime-router/src/test/kotlin/serializers/SoapSerializerTests.kt
  prime-router/src/test/kotlin/transport/SoapTransportTests.kt
Labels: onboarding-ops

#3226 Rhood/3094-CUC-Add New BD Veritor COVID Flu Panel
  prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
  prime-router/metadata/schemas/Experity/CUC-AL-covid-19.schema
Labels: onboarding-ops
