Repository CDCgov/prime-reportstream, pull requests merged in 2021-07, with the labels that each got.

#1295 Faster docker-compose sessions by optimizing the settings script
  prime-router/docker-compose.yml
  prime-router/docs/openapi.yml
  prime-router/settings/put-local-settings.py
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/HttpUtilities.kt
  prime-router/src/main/kotlin/azure/SettingsFacade.kt
  prime-router/src/main/kotlin/azure/SettingsFunctions.kt
Labels: engineering

#1521 Td/dct docs
  prime-router/docs/docker-content-trust.md
Labels: DevOps, documentation

#1543 Updates docs to reflect the current reality
  prime-router/docs/getting_started.md
  prime-router/docs/how-to-onboard-a-receiver.md
  prime-router/docs/how-to-run-static-site.md
Labels: documentation, receiver

#1540 Updates node packages to clear dependabot security vulnerabilities
  frontend/package-lock.json
Labels: receiver, security, web, web-receiver

#1545 1384 Added smoke test to gradle script
  prime-router/build.gradle.kts
  prime-router/gradle.properties
Labels: sender-pipeline

#1439 Updating licensing
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: receiver

#1442 Updating README
  README.md
Labels: receiver

#1441 Frontend (REACT)
  .github/workflows/build_frontend.yaml
  .github/workflows/release.yml
  frontend-react/.gitignore
  frontend-react/package-lock.json
  frontend-react/package.json
  frontend-react/public/assets/assessment.svg
  frontend-react/public/assets/cdc-logo.svg
  frontend-react/public/assets/close.svg
  frontend-react/public/assets/cloud.svg
  frontend-react/public/assets/code.svg
  frontend-react/public/assets/content_copy.svg
  frontend-react/public/assets/file_present.svg
  frontend-react/public/assets/insights.svg
  frontend-react/public/assets/pdf/PRIME-1-pager.pdf
  frontend-react/public/assets/pdf/ReportStream-ELR-Onboarding-Guide-April-2021.pdf
  frontend-react/public/assets/pdf/ReportStream-Web-Receiver-Onboarding-Guide-April-2021.pdf
  frontend-react/public/assets/report-stream-application.png
  frontend-react/public/assets/send.svg
  frontend-react/public/assets/shield.svg
  frontend-react/public/favicon.ico
  frontend-react/public/index.html
  frontend-react/public/manifest.json
  frontend-react/public/robots.txt
  frontend-react/src/App.css
  frontend-react/src/App.tsx
  frontend-react/src/components/OktaSignInWidget.jsx
  frontend-react/src/components/ReportStreamFooter.tsx
  frontend-react/src/components/ReportStreamHeader.tsx
  frontend-react/src/content/content.json
  frontend-react/src/content/site.json
  frontend-react/src/index.css
  frontend-react/src/index.tsx
  frontend-react/src/oktaConfig.ts
  frontend-react/src/pages/Daily.tsx
  frontend-react/src/pages/Details.tsx
  frontend-react/src/pages/Documentation.tsx
  frontend-react/src/pages/Home.tsx
  frontend-react/src/pages/Login.tsx
  frontend-react/src/pages/TermsOfService.tsx
  frontend-react/src/pages/documentation/About.tsx
  frontend-react/src/pages/documentation/ELRIntegration.tsx
  frontend-react/src/pages/documentation/SecurityPractices.tsx
  frontend-react/src/pages/documentation/WebReceiverGuide.tsx
  frontend-react/src/react-app-env.d.ts
  frontend-react/src/reportWebVitals.js
  frontend-react/src/resources/ActionResource.ts
  frontend-react/src/resources/AuthResource.ts
  frontend-react/src/resources/CardResource.ts
  frontend-react/src/resources/FacilityResource.ts
  frontend-react/src/resources/OrganizationResource.ts
  frontend-react/src/resources/ReportResource.ts
  frontend-react/src/webreceiver-utils.ts
  frontend-react/tsconfig.json
  frontend/src/_layouts/protected.liquid
  prime-router/src/main/kotlin/azure/HistoryFunctions.kt
  prime-router/start_func.sh
Labels: front-end, receiver

#1584 1416 Add folders to organize files in Blob Store
  frontend/src/js/prime-web-receiver-pre.js
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/resources/clitests/compare-test-files/test-0001-az-covid-19-hl7.hl7
  prime-router/src/main/resources/clitests/compare-test-files/test-0001-pima-az-covid-19.csv
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/azure/WorkflowEngineTests.kt
Labels: sender-pipeline

#1318 Zero Downtime Deployment Using Candidate Slot
  .github/vpn/dev.ovpn
  .github/workflows/release.yml
  operations/Makefile
  operations/app/src/modules/database/main.tf
  operations/app/src/modules/function_app/candidate_slot.tf
  operations/app/src/modules/function_app/data.tf
  operations/app/src/modules/function_app/main.tf
  operations/app/src/modules/storage/candidate_slot.tf
Labels: DevOps

#1430 Bg 1364 oregon hl7 schema
  prime-router/docs/schema_documentation/or-or-covid-19-hl7.md
  prime-router/metadata/schemas/OR/or-covid-19-hl7.schema
  prime-router/quick-test.sh
Labels: receiver

#1628 frontend-react: adding containerization and abillity to run container
  frontend-react/.dockerignore
  frontend-react/Dockerfile
  frontend-react/run.container.sh
Labels: docker, front-end

#1684 Add external name to receiver
  prime-router/build.gradle.kts
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/Sender.kt
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/EmailEngineFunction.kt
  prime-router/src/main/kotlin/azure/HistoryFunctions.kt
  prime-router/src/main/kotlin/azure/SettingsFacade.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/ReceiverTests.kt
  prime-router/src/test/kotlin/azure/WorkflowEngineTests.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
Labels: engineering, receiver

#1692 Enable CI for Forks
  .github/workflows/build_frontend.yaml
  .github/workflows/build_hub.yml
Labels: DevOps

#1586 add error handling to js
  frontend/src/js/prime-web-receiver-post.js
Labels: bug

#1699 Mo/report UUID mismatch
  prime-router/src/main/kotlin/FileNameTemplate.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/test/kotlin/FileNameTemplateTests.kt
Labels: receiver

#1274 OTC Frontend
  .gitignore
  frontend/src/_includes/table_reports.liquid
  frontend/src/_layouts/protected.liquid
  frontend/src/assets/stylesheets/tabs.css
  frontend/src/js/prime-web-receiver-post.js
  frontend/src/js/prime-web-receiver-pre.js
  prime-router/docker-compose.yml
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/azure/HistoryFunctions.kt
  prime-router/src/test/kotlin/serializers/CsvSerializerTests.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
Labels: Blocked, front-end, receiver

#1668 Terraform GitHub Action
  .github/workflows/build_docker.yaml
  .github/workflows/build_hub.yml
  .github/workflows/publish_docker.yaml
  .github/workflows/validate_terraform.yml
  operations/Dockerfile
  operations/Makefile
  operations/app/plan/.gitignore
  operations/app/src/environments/tf
  operations/app/src/modules/key_vault/main.tf
  operations/docker-compose.yml
Labels: DevOps, security

#1742 More OTC Front End Improvements
  frontend/package-lock.json
  frontend/package.json
  frontend/src/js/prime-web-receiver-post.js
  frontend/src/js/prime-web-receiver-pre.js
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/HistoryFunctions.kt
Labels: receiver

#1674 Introduction of gitleaks as a pre-commit git hook to prevent secrets from getting committed once activated
  .environment/githooks.sh
  .environment/gitleaks/gitleaks-config.toml
  .environment/gitleaks/run-gitleaks.sh
  .environment/pre-commit.hook.sh
  .environment/pre-commit.runner.sh
  .github/workflows/run_gitleaks.yaml
  .gitignore
  prime-router/cleanslate.sh
  prime-router/docs/getting_started.md
  prime-router/end-to-end-test.sh
  prime-router/examples/data-lineage/example-setup.sh
  prime-router/examples/upload-fake-data/example.sh
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/azure/CheckFunction.kt
  prime-router/src/scripts/loop.sh
  prime-router/test-ingest.sh
Labels: DevOps, Robustness, dev-sync, github_actions, pipeline-capabilities, security

#1683 bumping Terraform from 0.14.2 to 1.0.3
  operations/Dockerfile
  operations/app/src/environments/01-network/main.tf
  operations/app/src/environments/02-config/main.tf
  operations/app/src/environments/03-persistent/main.tf
  operations/app/src/environments/04-app/main.tf
  operations/docker-compose.yml
Labels: DevOps, Robustness, chore, docker, engineering, terraform

#1751 OTC Bug Bash Fixes
  frontend/package-lock.json
  frontend/package.json
  frontend/src/_includes/details_report.liquid
  frontend/src/_layouts/protected.liquid
  frontend/src/assets/stylesheets/font-awesome-all.css
  frontend/src/assets/webfonts/fa-brands-400.eot
  frontend/src/assets/webfonts/fa-brands-400.svg
  frontend/src/assets/webfonts/fa-brands-400.ttf
  frontend/src/assets/webfonts/fa-brands-400.woff
  frontend/src/assets/webfonts/fa-brands-400.woff2
  frontend/src/assets/webfonts/fa-regular-400.eot
  frontend/src/assets/webfonts/fa-regular-400.svg
  frontend/src/assets/webfonts/fa-regular-400.ttf
  frontend/src/assets/webfonts/fa-regular-400.woff
  frontend/src/assets/webfonts/fa-regular-400.woff2
  frontend/src/assets/webfonts/fa-solid-900.eot
  frontend/src/assets/webfonts/fa-solid-900.svg
  frontend/src/assets/webfonts/fa-solid-900.ttf
  frontend/src/assets/webfonts/fa-solid-900.woff
  frontend/src/assets/webfonts/fa-solid-900.woff2
  frontend/src/js/prime-web-receiver-pre.js
  prime-router/docs/releases/2021-08-03-release-notes.md
Labels: receiver, web, web-receiver
