Repository CDCgov/prime-reportstream, pull requests merged in 2022-03, with the labels that each got.

#4406 Cle/2030 duplicate detektor
  prime-router/docs/release-notes.md
  prime-router/src/main/kotlin/Sender.kt
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/resources/db/migration/V41__digest_index.sql
  prime-router/src/test/kotlin/azure/HttpTestUtils.kt
  prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
  prime-router/src/test/kotlin/azure/WorkflowEngineTests.kt
Labels: pipeline, release_notes

#4631 4428: NJ ORC-12.3 and OBR-16.3 truncation
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0086-update-nj-truncate-orc-12-3-and-obr-16-3.yml
  prime-router/settings/staging/0086-update-nj-truncate-orc-12-3-and-obr-16-3.yml
Labels: onboarding-ops

#4622 Submissions API: Added optional parameter for date range filtering
  prime-router/src/main/kotlin/azure/DatabaseSubmissionsAccess.kt
  prime-router/src/main/kotlin/azure/SubmissionFunction.kt
  prime-router/src/main/kotlin/azure/SubmissionsFacade.kt
  prime-router/src/test/kotlin/azure/SubmissionFunctionTests.kt
Labels: backend, experience, release_notes

#4004 Added Iowa and Delaware to map and list of states
  frontend-react/src/content/live.json
  frontend-react/src/content/usa_w_territories.svg
  frontend-react/src/pages/how-it-works/SystemsAndSettings.tsx
  frontend-react/src/pages/how-it-works/WhereWereLive.tsx
  frontend-react/src/styles/_reportstream.scss
Labels: onboarding-ops, experience

#4599 3555: WA Do Not Need Tribal Affiliation Transmitted
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0086-update-wa-doh-suppressed-tribal.yml
  prime-router/settings/staging/0086-update-wa-doh-suppressed-tribal.yml
Labels: onboarding-ops

#4645 Frontend build support for a test site
  frontend-react/.env.staging
  frontend-react/.env.test
  frontend-react/package.json
  frontend-react/src/__mocks__/HistoryMockServer.ts
Labels: frontend

#4658 Payload Name header extraction fix
  prime-router/src/main/kotlin/azure/ReportFunction.kt
Labels: bug, experience

#4619 4471 Consistent timestamp format in API responses
  frontend-react/src/resources/ActionDetailsResource.ts
  frontend-react/src/resources/TestResponse.ts
  prime-router/build.gradle.kts
  prime-router/docs/release-notes.md
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/Submission.kt
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/HttpUtilities.kt
  prime-router/src/main/kotlin/azure/SubmissionFunction.kt
  prime-router/src/main/kotlin/azure/SubmissionsFacade.kt
  prime-router/src/main/kotlin/cli/OktaCommands.kt
  prime-router/src/main/kotlin/cli/SenderFilesCommand.kt
  prime-router/src/main/kotlin/cli/SettingCommands.kt
  prime-router/src/main/kotlin/common/Environment.kt
  prime-router/src/main/kotlin/common/JacksonMapperUtilities.kt
  prime-router/src/main/kotlin/tokens/TokenAuthentication.kt
  prime-router/src/test/kotlin/azure/SubmissionFunctionTests.kt
  prime-router/src/test/kotlin/common/JacksonMapperUtilitiesTests.kt
Labels: pipeline, release_notes

#4661 Filter out failed submissions in list on backend
  frontend-react/src/pages/submissions/SubmissionsTable.tsx
  frontend-react/src/resources/SubmissionsResource.ts
  prime-router/docs/release-notes.md
  prime-router/src/main/kotlin/azure/DatabaseSubmissionsAccess.kt
  prime-router/src/main/kotlin/azure/SubmissionFunction.kt
  prime-router/src/main/kotlin/azure/SubmissionsFacade.kt
  prime-router/src/test/kotlin/azure/SubmissionFunctionTests.kt
Labels: bug, backend, experience

#4201 Bunch of small fixes found by code scanning process
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/cli/LivdTableDownload.kt
  prime-router/src/main/kotlin/cli/tests/CompareData.kt
  prime-router/src/main/kotlin/transport/FTPSTransport.kt
  prime-router/src/main/kotlin/transport/SftpTransport.kt
  prime-router/src/testIntegration/kotlin/FakeReportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/SimpleReportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
Labels: backend

#4629 Databases will only have private endpoints for vnets assigned that are in matching regions
  operations/app/terraform/modules/common/private_endpoint/main.tf
  operations/app/terraform/modules/common/private_endpoint/variables.tf
  operations/app/terraform/modules/database/main.tf
  operations/app/terraform/modules/database/~inputs.tf
  operations/app/terraform/modules/vnet/data.tf
  operations/app/terraform/modules/vnet/~outputs.tf
  operations/app/terraform/vars/dev/main.tf
  operations/app/terraform/vars/staging/main.tf
  operations/app/terraform/vars/staging/variables.tf
  operations/app/terraform/vars/test/main.tf
  operations/app/terraform/vars/test/variables.tf
Labels: DevOps

#4673 Add missing fields to edit sender settings page
  frontend-react/src/__mocks__/SettingsMockServer.ts
  frontend-react/src/components/Admin/EditSenderSettings.test.tsx
  frontend-react/src/components/Admin/EditSenderSettings.tsx
  frontend-react/src/resources/OrgSenderSettingsResource.ts
  frontend-react/src/resources/TestResponse.ts
  frontend-react/yarn.lock
  yarn.lock
Labels: frontend, experience

#4697 OO/rhood/4696-Add new CSV Sender - Precision Clinical Laboratories, CA
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0090-pcl-ca.yml
  prime-router/settings/staging/0090-pcl-ca.yml
Labels: onboarding-ops

#4688 OO/rhood/4660/CSV schema - Add State to sender automation valuesets
  prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
  prime-router/docs/schema_documentation/experity-experity-covid-19.md
  prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
  prime-router/docs/schema_documentation/ipatientcare-ipatientcare-covid-19.md
  prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
  prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
  prime-router/docs/schema_documentation/upload-covid-19.md
  prime-router/metadata/schemas/upload-covid-19.schema
  prime-router/metadata/valuesets/sender-automation.valuesets
Labels: onboarding-ops

#4681 4657 Add metadata to HL7 errors and warnings
  frontend-react/src/pages/Upload.tsx
  prime-router/src/main/kotlin/ActionLogDetail.kt
  prime-router/src/main/kotlin/ElementErrors.kt
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
  prime-router/src/testIntegration/kotlin/serializers/Hl7SerializerIntegrationTests.kt
Labels: pipeline

#4741 OO/rhood/4727 - Add three new CSV Senders
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0092-touroedu-ca.yml
  prime-router/settings/prod/0093-rollinghillsclinic-ca.yml
  prime-router/settings/prod/0094-quantgene-ca.yml
  prime-router/settings/staging/0092-touroedu-ca.yml
  prime-router/settings/staging/0093-rollinghillsclinic-ca.yml
  prime-router/settings/staging/0094-quantgene-ca.yml
Labels: onboarding-ops

#4748 Added ectomy code
  prime-router/src/main/kotlin/credentials/Credential.kt
  prime-router/src/test/kotlin/credentials/CredentialTests.kt
Labels: tech-debt

#4722 Hooks to trigger pagerduty on SendFunction and ProcessFunction failures (Ticket 3736)
  prime-router/src/main/kotlin/Translator.kt
  prime-router/src/main/kotlin/azure/BatchFunction.kt
  prime-router/src/main/kotlin/azure/ProcessFunction.kt
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/resources/log4j2.xml
  prime-router/src/test/kotlin/azure/BatchFunctionTests.kt
  prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
  prime-router/src/test/kotlin/azure/SendFunctionTests.kt
  prime-router/src/test/kotlin/azure/WorkflowEngineTests.kt
Labels: backend, tech-debt

#4746 Add handling for Cue Eurofins flag containing a regular dash or en-dash
  prime-router/docs/schema_documentation/direct-cue-covid-19.md
  prime-router/metadata/schemas/direct/cue-covid-19.schema
Labels: onboarding-ops

#4747 Add service to organization title for submission history
  frontend-react/src/pages/submissions/SubmissionDetails.test.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.tsx
  frontend-react/src/resources/TestResponse.ts
Labels: frontend, experience

#4761 OO/rhood/4744/Change Experity Schemas to use equipment model name and add cardinality: ONE
  prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
  prime-router/docs/schema_documentation/experity-experity-covid-19.md
  prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
  prime-router/docs/schema_documentation/ipatientcare-ipatientcare-covid-19.md
  prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
  prime-router/metadata/schemas/Experity/CUC-AL-covid-19.schema
  prime-router/metadata/schemas/Experity/GUC-LA-covid-19.schema
  prime-router/metadata/schemas/Experity/experity-covid-19.schema
  prime-router/metadata/schemas/iPatientCare/iPatientCare-covid-19.schema
Labels: onboarding-ops

#4740 4417 consolidate action logs in submission API response
  prime-router/src/main/kotlin/ActionLog.kt
  prime-router/src/main/kotlin/ActionLogDetail.kt
  prime-router/src/main/kotlin/ActionMessages.kt
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/ElementErrors.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/Submission.kt
  prime-router/src/main/kotlin/Translator.kt
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/cli/ProcessDataCommands.kt
  prime-router/src/main/kotlin/metadata/LivdMappers.kt
  prime-router/src/main/kotlin/serializers/CsvSerializer.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/main/kotlin/serializers/ReadResult.kt
  prime-router/src/test/kotlin/ActionLogTests.kt
  prime-router/src/test/kotlin/CsvFileTests.kt
  prime-router/src/test/kotlin/ElementTests.kt
  prime-router/src/test/kotlin/SubmissionTests.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/metadata/MapperTests.kt
  prime-router/src/test/kotlin/serializers/CsvSerializerTests.kt
  prime-router/src/testIntegration/kotlin/SimpleReportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
Labels: pipeline

#4749 4710: NV Data Quality Issue
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/TranslatorConfiguration.kt
  prime-router/src/main/kotlin/ValueSet.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
Labels: onboarding-ops

#4743 Submissions: Filter by date-range
  frontend-react/src/contexts/FilterContext.tsx
  frontend-react/src/hooks/UsePaginator.tsx
  frontend-react/src/pages/submissions/SubmissionFilters.test.tsx
  frontend-react/src/pages/submissions/SubmissionFilters.tsx
  frontend-react/src/pages/submissions/SubmissionPages.css
  frontend-react/src/pages/submissions/SubmissionTable.tsx
  frontend-react/src/pages/submissions/Submissions.tsx
  frontend-react/src/pages/submissions/SubmissionsTable.tsx
  prime-router/src/main/kotlin/azure/SubmissionsFacade.kt
Labels: frontend, experience

#4771 Add Idaho to live map/list
  frontend-react/src/content/live.json
  frontend-react/src/content/usa_w_territories.svg
Labels: frontend, experience

#4803 Warn and highlight json mistakes
  frontend-react/src/components/Admin/AdminFormEdit.tsx
Labels: experience

#4805 WA Settings Change - Routing Filter for OBX11 Only F, S, P, C, X, and I
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0096-update-wa-phd-obx11.yml
  prime-router/settings/staging/0096-update-wa-phd-obx11.yml
Labels: onboarding-ops

#4791 Add our own compare dialog with editable text to replace monaco-editor
  frontend-react/package.json
  frontend-react/src/App.tsx
  frontend-react/src/components/Admin/CompareJsonModal.tsx
  frontend-react/src/components/Admin/DiffEditorComponent.tsx
  frontend-react/src/components/Admin/EditReceiverSettings.tsx
  frontend-react/src/components/Admin/EditSenderSettings.tsx
  frontend-react/src/components/Admin/NewSetting.tsx
  frontend-react/src/components/AlertNotifications.tsx
  frontend-react/src/components/EditableCompare.tsx
  frontend-react/src/components/Spinner.tsx
  frontend-react/src/pages/admin/AdminMain.tsx
  frontend-react/src/pages/admin/AdminOrgEdit.tsx
  frontend-react/src/pages/details/Details.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.tsx
  frontend-react/src/styles/_reportstream.scss
  frontend-react/src/utils/diff.test.ts
  frontend-react/src/utils/diff.ts
  frontend-react/src/utils/misc.test.ts
  frontend-react/src/utils/misc.ts
  frontend-react/yarn.lock
Labels: experience

#4813 Remove featureflag for diff editor since it works
  frontend-react/src/components/Admin/CompareJsonModal.tsx
Labels: experience

#4709 Onboarding ops/oslynn/4467/tx incorrect datatype in obx 2 and obx 5 and missing snomed codes
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
Labels: onboarding-ops

#4588 Fixes issue where an organization name being blank or empty string was overwriting ORC-21
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
Labels: bug, onboarding-ops

#4816 Change minimum access level for SubmissionFunction
  prime-router/src/main/kotlin/azure/SubmissionFunction.kt
Labels: backend, experience

#4563 restore db workflow and actions
  .github/actions/db-backup/action.yml
  .github/actions/db-query/action.yml
  .github/actions/db-restore/action.yml
  .github/actions/mount-share/action.yml
  .github/workflows/restore_databases.yml
Labels: DevOps

#4795 Adding Xtrava schema and settings
  prime-router/docs/schema_documentation/direct-xtrava-covid-19.md
  prime-router/metadata/schemas/direct/xtrava-covid-19.schema
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0084-xtrava.yml
  prime-router/settings/staging/0084-xtrava.yml
Labels: onboarding-ops

#4814 Make json validator work fo diff editor
  frontend-react/src/components/Admin/AdminFormEdit.tsx
  frontend-react/src/components/AlertNotifications.tsx
  frontend-react/src/components/EditableCompare.tsx
  frontend-react/src/utils/misc.ts
Labels: experience

#4838 Remove fortawesome/fontawesome
  frontend-react/package.json
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/content/right-left-arrows.svg
  frontend-react/src/global.scss
  frontend-react/src/pages/Upload.tsx
  frontend-react/src/styles/_reportstream.scss
  frontend-react/yarn.lock
Labels: experience, tech-debt

#4849 Allow local devs to test CSP
  frontend-react/.env.dev.csp
  frontend-react/README.md
  frontend-react/package.json
  frontend-react/public/index.html
Labels: experience

#4829 Updated DB restore UI input options
  .github/workflows/restore_databases.yml
Labels: DevOps

#4846 Onboarding site warning added for inactive and testing senders
  frontend-react/src/App.tsx
  frontend-react/src/__mocks__/HistoryMockServer.ts
  frontend-react/src/__mocks__/OrganizationMockServer.ts
  frontend-react/src/components/Admin/EditReceiverSettings.tsx
  frontend-react/src/components/Admin/EditSenderSettings.tsx
  frontend-react/src/components/Admin/OrgsTable.tsx
  frontend-react/src/components/GlobalContextProvider.test.tsx
  frontend-react/src/components/GlobalContextProvider.tsx
  frontend-react/src/components/SenderModeBanner.test.tsx
  frontend-react/src/components/SenderModeBanner.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/contexts/FilterContext.tsx
  frontend-react/src/contexts/SessionStorageContext.test.tsx
  frontend-react/src/contexts/SessionStorageContext.tsx
  frontend-react/src/contexts/SessionStorageTools.test.ts
  frontend-react/src/contexts/SessionStorageTools.ts
  frontend-react/src/hooks/UseSenderMode.test.ts
  frontend-react/src/hooks/UseSenderMode.ts
  frontend-react/src/hooks/UseSessionStorage.test.ts
  frontend-react/src/hooks/UseSessionStorage.ts
  frontend-react/src/network/api/Api.test.ts
  frontend-react/src/network/api/Api.ts
  frontend-react/src/network/api/History.test.ts
  frontend-react/src/network/api/History.ts
  frontend-react/src/network/api/OrgApi.test.ts
  frontend-react/src/network/api/OrgApi.ts
  frontend-react/src/network/config.ts
  frontend-react/src/network/hooks/useNetwork.test.ts
  frontend-react/src/network/hooks/useNetwork.ts
  frontend-react/src/pages/Login.tsx
  frontend-react/src/pages/Upload.tsx
  frontend-react/src/pages/admin/AdminOrgEdit.tsx
  frontend-react/src/pages/daily/Table/ReportLink.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.tsx
  frontend-react/src/resources/AuthResource.ts
  frontend-react/src/resources/SenderAuthResource.ts
  frontend-react/src/utils/CustomRenderUtils.tsx
  frontend-react/src/utils/OrganizationUtils.ts
  frontend-react/src/utils/UserUtils.ts
  frontend-react/src/webreceiver-utils.ts
Labels: experience

#4883 Fix okta group name parsing
  frontend-react/src/contexts/SessionStorageTools.ts
  frontend-react/src/utils/OrganizationUtils.test.ts
  frontend-react/src/utils/OrganizationUtils.ts
  frontend-react/src/webreceiver-utils.ts
Labels: bug, experience

#4889 OO/rhood/4848/Std CSV - Change auto-generation of patient_id and message_id
  prime-router/docs/schema_documentation/upload-covid-19.md
  prime-router/metadata/schemas/upload-covid-19.schema
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0091-jrslab-ca.yml
  prime-router/settings/prod/0100-mycarelabs-ca.yml
  prime-router/settings/staging/0100-mycarelabs-ca.yml
Labels: onboarding-ops

#4847 3534 Reports API response matches Submission API
  frontend-react/src/pages/Upload.tsx
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/ActionMessages.kt
  prime-router/src/main/kotlin/Submission.kt
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/DatabaseSubmissionsAccess.kt
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/azure/RequeueFunction.kt
  prime-router/src/main/kotlin/azure/SubmissionFunction.kt
  prime-router/src/main/kotlin/azure/SubmissionsFacade.kt
  prime-router/src/main/kotlin/azure/TokenFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/cli/OktaCommands.kt
  prime-router/src/main/kotlin/cli/tests/BasicTests.kt
  prime-router/src/main/kotlin/cli/tests/HistoryApiTest.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/test/kotlin/SubmissionTests.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
  prime-router/src/test/kotlin/azure/SubmissionFunctionTests.kt
  prime-router/src/test/kotlin/azure/SubmissionsFacadeTests.kt
Labels: pipeline

#4887 Onboarding PMG to production mode
  prime-router/docs/schema_documentation/direct-pmg-covid-19.md
  prime-router/metadata/schemas/direct/pmg-covid-19.schema
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0100-pmg-exclude-nm-ca.yml
  prime-router/settings/staging/0100-pmg-exclude-nm-ca.yml
Labels: onboarding-ops, sender

#4869 4591: Add option for value sets to output null or blank if the value …
  prime-router/src/main/kotlin/FakeReport.kt
Labels: onboarding-ops

#4835 3869: Accept Internatinal Phone Number
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
Labels: onboarding-ops

#4914 4878: Fixed Undesired expansion of HL7 field with type ID
  prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
  prime-router/docs/schema_documentation/covid-19.md
  prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
  prime-router/docs/schema_documentation/direct-hca-covid-19.md
  prime-router/docs/schema_documentation/fl-fl-covid-19.md
  prime-router/docs/schema_documentation/gu-gu-covid-19.md
  prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19.md
  prime-router/docs/schema_documentation/hl7-lifepoint-covid-19.md
  prime-router/docs/schema_documentation/hl7-mns-covid-19.md
  prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
  prime-router/docs/schema_documentation/hl7-primary-covid-19.md
  prime-router/docs/schema_documentation/hl7-test-covid-19.md
  prime-router/docs/schema_documentation/la-la-covid-19.md
  prime-router/docs/schema_documentation/mt-mt-covid-19.md
  prime-router/docs/schema_documentation/nd-nd-covid-19.md
  prime-router/docs/schema_documentation/nm-nm-covid-19.md
  prime-router/docs/schema_documentation/oh-oh-covid-19.md
  prime-router/docs/schema_documentation/or-or-covid-19-hl7.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
  prime-router/docs/schema_documentation/standard-standard-covid-19.md
  prime-router/docs/schema_documentation/tx-tx-covid-19.md
  prime-router/docs/schema_documentation/vt-vt-covid-19.md
  prime-router/metadata/schemas/covid-19.schema
  prime-router/settings/organizations.yml
Labels: onboarding-ops

#4910 Refactor permission and organization utility functions
  frontend-react/src/App.tsx
  frontend-react/src/components/AuthorizedRoute.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/contexts/SessionStorageTools.test.ts
  frontend-react/src/contexts/SessionStorageTools.ts
  frontend-react/src/hooks/UseOrgName.ts
  frontend-react/src/pages/Login.tsx
  frontend-react/src/pages/Upload.tsx
  frontend-react/src/pages/daily/Daily.tsx
  frontend-react/src/pages/details/Summary.tsx
  frontend-react/src/pages/submissions/Submissions.tsx
  frontend-react/src/pages/tos-sign/TermsOfServiceForm.tsx
  frontend-react/src/resources/PermissionsResource.ts
  frontend-react/src/utils/OrganizationUtils.test.ts
  frontend-react/src/utils/OrganizationUtils.ts
  frontend-react/src/utils/PermissionsUtils.test.ts
  frontend-react/src/utils/PermissionsUtils.ts
  frontend-react/src/utils/StateTerritories.ts
  frontend-react/src/utils/TestUtils.test.ts
  frontend-react/src/utils/TestUtils.ts
  frontend-react/src/webreceiver-utils.ts
Labels: experience, tech-debt

#4917 Fix wrapping and max width issues for setting controls.
  frontend-react/src/components/Admin/AdminFormEdit.tsx
  frontend-react/src/styles/_reportstream.scss
Labels: experience

#4936 Refresh Diff Editor Modal content when show multiple times.
  frontend-react/src/components/Admin/CompareJsonModal.tsx
  frontend-react/src/components/Admin/EditReceiverSettings.tsx
  frontend-react/src/components/Admin/EditSenderSettings.tsx
  frontend-react/src/components/EditableCompare.tsx
  frontend-react/src/pages/admin/AdminOrgEdit.tsx
Labels: experience

#4965 Fix EditableCompare bug introduced by #4936
  frontend-react/src/components/EditableCompare.tsx
Labels: experience

#4895 Enforce TF < 3.0 and disabled function FTP
  operations/app/terraform/modules/function_app/main.tf
  operations/app/terraform/vars/dev/azure.tf
  operations/app/terraform/vars/staging/azure.tf
  operations/app/terraform/vars/test/azure.tf
Labels: DevOps, security
