Repository CDCgov/prime-reportstream, pull requests merged in 2022-06, with the labels that each got.

#5661 Fix Lookup Table tests after a change to a library broke them
  prime-router/src/test/kotlin/azure/LookupTableFunctionsTests.kt
Labels: pipeline

#5601 Markdown-driven static pages: building the framework
  frontend-react/package.json
  frontend-react/src/App.tsx
  frontend-react/src/components/Markdown/DirectoryAsPage.test.tsx
  frontend-react/src/components/Markdown/DirectoryAsPage.tsx
  frontend-react/src/components/Markdown/GeneratedSideNav.test.tsx
  frontend-react/src/components/Markdown/GeneratedSideNav.tsx
  frontend-react/src/components/Markdown/MarkdownContent.tsx
  frontend-react/src/components/Markdown/MarkdownDirectory.test.ts
  frontend-react/src/components/Markdown/MarkdownDirectory.ts
  frontend-react/src/components/Markdown/StaticPageFromDirectories.test.tsx
  frontend-react/src/components/Markdown/StaticPageFromDirectories.tsx
  frontend-react/src/components/header/AdminDropdownNav.tsx
  frontend-react/src/components/header/DropdownNav.test.tsx
  frontend-react/src/components/header/DropdownNav.tsx
  frontend-react/src/components/header/GettingStartedDropdown.tsx
  frontend-react/src/components/header/HowItWorksDropdown.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/content/built-for-you/2022-june.md
  frontend-react/src/content/built-for-you/2022-may.md
  frontend-react/src/content/internal-user-guides/make-markdown-pages.md
  frontend-react/src/content/markdown-test.md
  frontend-react/src/pages/admin/InternalUserGuides.tsx
  frontend-react/src/pages/built-for-you/BuiltForYouIndex.test.tsx
  frontend-react/src/pages/built-for-you/BuiltForYouIndex.tsx
  frontend-react/src/pages/misc/FeatureFlags.tsx
  frontend-react/src/react-app-env.d.ts
  frontend-react/src/styles/_reportstream.scss
  frontend-react/yarn.lock
Labels: frontend, experience

#5648 Fixed Cardinality:ONE doesn't work with mapper
  prime-router/src/main/kotlin/Element.kt
Labels: onboarding-ops

#5664 Fixed the Hl7Serializer.setTelephoneComponent Error out On Blank Value
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
Labels: onboarding-ops

#5640 Update pagination props only after fetch resolves
  frontend-react/package.json
  frontend-react/src/components/Table/Pagination.test.tsx
  frontend-react/src/components/Table/Pagination.tsx
  frontend-react/src/hooks/UsePagination.test.ts
  frontend-react/src/hooks/UsePagination.ts
  frontend-react/src/pages/submissions/SubmissionTable.tsx
  frontend-react/yarn.lock
Labels: experience

#5657 Use numbered pagination for the submissions table
  frontend-react/src/components/Table/Table.tsx
  frontend-react/src/components/Table/TableFilters.tsx
  frontend-react/src/hooks/UsePagination.test.ts
  frontend-react/src/hooks/UsePagination.ts
  frontend-react/src/pages/submissions/SubmissionTable.test.tsx
  frontend-react/src/pages/submissions/SubmissionTable.tsx
Labels: experience

#5674 update alerts
  .devcontainer/devcontainer.json
  operations/app/terraform/modules/application_insights/alert_availability.tf
  operations/app/terraform/modules/application_insights/main.tf
  operations/app/terraform/modules/application_insights/~inputs.tf
  operations/app/terraform/modules/application_insights/~outputs.tf
  operations/app/terraform/modules/log_analytics_workspace/alert_rules.tf
  operations/app/terraform/modules/log_analytics_workspace/~inputs.tf
  operations/app/terraform/vars/dev/data.tf
  operations/app/terraform/vars/prod/data.tf
  operations/app/terraform/vars/prod/main.tf
  operations/app/terraform/vars/staging/data.tf
  operations/app/terraform/vars/staging/main.tf
  operations/app/terraform/vars/test/data.tf
  operations/app/terraform/vars/test/main.tf
Labels: DevOps

#5650 5271 Translate HL7 full-ELR ORC segment to FHIR
  prime-router/metadata/fhir_mapping/fhir/resourcemapping.yml
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Address.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/ContactPoint.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/HumanName.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Identifier_SystemID.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Identifier_var.yml
  prime-router/metadata/fhir_mapping/hl7/extension/ExtensionMeta.yml
  prime-router/metadata/fhir_mapping/hl7/message/ORU_R01.yml
  prime-router/metadata/fhir_mapping/hl7/resource/DiagnosticReport.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Location.yml
  prime-router/metadata/fhir_mapping/hl7/resource/MessageSender.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Organization.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Practitioner.yml
  prime-router/metadata/fhir_mapping/hl7/resource/PractitionerRole.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Provenance.yml
  prime-router/metadata/fhir_mapping/hl7/resource/ServiceRequest.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/ProvenanceAgent.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/Source.yml
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir
Labels: pipeline

#5589 Adds memberships to SessionContext
  .github/actions/build-frontend/action.yml
  frontend-react/package.json
  frontend-react/src/App.tsx
  frontend-react/src/__mocks__/sample.ts
  frontend-react/src/components/Admin/OrgsTable.tsx
  frontend-react/src/components/AuthorizedRoute.tsx
  frontend-react/src/components/SenderModeBanner.test.tsx
  frontend-react/src/components/SenderModeBanner.tsx
  frontend-react/src/components/header/ReportStreamHeader.test.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/contexts/SessionContext.tsx
  frontend-react/src/contexts/SessionStorageContext.test.tsx
  frontend-react/src/contexts/SessionStorageContext.tsx
  frontend-react/src/contexts/__mocks__/SessionContext.tsx
  frontend-react/src/hooks/UseOktaMemberships.test.ts
  frontend-react/src/hooks/UseOktaMemberships.ts
  frontend-react/src/hooks/UseOrgName.ts
  frontend-react/src/hooks/UseSenderMode.test.ts
  frontend-react/src/hooks/UseSenderMode.ts
  frontend-react/src/index.tsx
  frontend-react/src/pages/Login.tsx
  frontend-react/src/utils/CustomRenderUtils.tsx
  frontend-react/src/utils/OrganizationUtils.test.ts
  frontend-react/src/utils/OrganizationUtils.ts
  frontend-react/tsconfig.json
  frontend-react/yarn.lock
Labels: frontend, experience

#5690 Improve Zip code de-identification signed
  prime-router/metadata/tables/local/restricted_zip_code.csv
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/test/kotlin/ReportTests.kt
  prime-router/src/test/unit_test_files/ca_test_file.csv
  prime-router/src/testIntegration/kotlin/serializers/Hl7SerializerIntegrationTests.kt
Labels: onboarding-ops

#5712 feat: update programmers guide pdf to 2.2 [experience-4874]
  frontend-react/public/assets/pdf/ReportStream-Programmers-Guide-v2.1.pdf
  frontend-react/public/assets/pdf/ReportStream-Programmers-Guide-v2.2.pdf
  frontend-react/src/pages/getting-started/testing-facilities/Overview.tsx
  prime-router/docs/ReportStream-Programmers-Guide-v2.1.docx
  prime-router/docs/ReportStream-Programmers-Guide-v2.2.docx
Labels: experience, documentation

#5758 Updates dependabot ignore settings to exclude SSHJ from update notifications
  .github/dependabot.yml
Labels: onboarding-ops

#5733 fix: update Api instances with up to date session credentials [unticketed]
  frontend-react/src/contexts/SessionStorageTools.ts
  frontend-react/src/hooks/UseSenderMode.ts
  frontend-react/src/network/Apis.ts
  frontend-react/src/network/api/Api.test.ts
  frontend-react/src/network/api/Api.ts
  frontend-react/src/network/api/LookupTableApi.test.ts
  frontend-react/src/network/api/LookupTableApi.ts
  frontend-react/src/network/api/OrgApi.test.ts
  frontend-react/src/network/api/OrgApi.ts
  frontend-react/src/network/config.ts
Labels: experience

#5777 Add csvuploader sender to SimpleReport org
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0117-update-simplereport-add-csvuploader.yml
  prime-router/settings/staging/0117-update-simplereport-add-csvuploader.yml
Labels: onboarding-ops, experience

#5795 NH ELR Replace MSH-4 with CDC PRIME^11D2030855^CLIA
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0118-NH-replace-msh-4.yml
  prime-router/settings/staging/0118-NH-replace-msh-4.yml
Labels: onboarding-ops

#5687 Update reportstream-team-member-offboarding.md
  .github/ISSUE_TEMPLATE/reportstream-team-member-offboarding.md
Labels: offboarding

#5797 Api interface tools refactor: Api configurations
  frontend-react/src/contexts/SessionContext.tsx
  frontend-react/src/network/api/NewApi.test.ts
  frontend-react/src/network/api/NewApi.ts
  frontend-react/src/network/api/readme.md
Labels: frontend, experience, tech-debt

#5806 offboarding workflow additions - outlook away message
  .github/ISSUE_TEMPLATE/reportstream-team-member-offboarding.md
Labels: offboarding

#5844 React hook conventions implemented
  frontend-react/src/hooks/UseLookupTable.test.ts
  frontend-react/src/hooks/UseLookupTable.ts
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.tsx
Labels: frontend, experience

#5857 Add support for ISO date parsing and two-digit-years
  prime-router/src/main/kotlin/common/DateUtilities.kt
  prime-router/src/test/kotlin/common/DateUtilitiesTests.kt
Labels: onboarding-ops

#5848 Experience/5442 add table row
  frontend-react/src/components/Table/Table.test.tsx
  frontend-react/src/components/Table/Table.tsx
  frontend-react/src/components/Table/TableRows.tsx
  frontend-react/src/components/Table/TestTable.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
Labels: experience

#5812 Onboarding Neurolab
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0119-neurolab.yml
  prime-router/settings/staging/0119-neurolab.yml
Labels: onboarding-ops

#5862 Experience/5442 remove legend etc
  frontend-react/src/hooks/UseLookupTable.test.ts
  frontend-react/src/hooks/UseLookupTable.ts
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.test.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
  frontend-react/src/utils/misc.test.ts
  frontend-react/src/utils/misc.ts
Labels: experience

#5889 ignore hidden tags and Terraform use locals
  operations/app/terraform/modules/function_app/candidate_slot.tf
  operations/app/terraform/vars/prod/azure.tf
  operations/app/terraform/vars/prod/data.tf
  operations/app/terraform/vars/prod/locals.tf
  operations/app/terraform/vars/prod/main.tf
  operations/app/terraform/vars/prod/variables.tf
  operations/app/terraform/vars/staging/azure.tf
  operations/app/terraform/vars/staging/data.tf
  operations/app/terraform/vars/staging/locals.tf
  operations/app/terraform/vars/staging/main.tf
  operations/app/terraform/vars/staging/variables.tf
  operations/app/terraform/vars/test/azure.tf
  operations/app/terraform/vars/test/data.tf
  operations/app/terraform/vars/test/locals.tf
  operations/app/terraform/vars/test/main.tf
  operations/app/terraform/vars/test/variables.tf
Labels: DevOps

#5880 Nova Labnetics onboarding
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0119-limsabc-nova.yml
  prime-router/settings/staging/0119-limsabc-nova.yml
Labels: onboarding-ops, HL7, sender

#5894 Adds transition banner to upload page
  frontend-react/src/pages/Upload.tsx
Labels: frontend, experience

#5899 5278 Translate HL7 full-ELR NTE segment to FHIR
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Annotation.yml
  prime-router/metadata/fhir_mapping/hl7/message/ORU_R01.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Patient.yml
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir
Labels: pipeline

#5898 for non-prod, do not enable an alert about alerts
  operations/app/terraform/modules/application_insights/alert_exception.tf
  operations/app/terraform/modules/application_insights/main.tf
Labels: DevOps

#5903 5269 Translate HL7 full-ELR NK1segment to FHIR
  prime-router/metadata/fhir_mapping/hl7/codesystem/CodingSystemMapping.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Organization.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Patient.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/Contact.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/PatientContact.yml
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir
Labels: pipeline

#5925 Josiahsiegel/create/demo dns
  operations/dnsmasq/config/demo1/dns.conf
  operations/dnsmasq/config/demo1/hosts.local
  operations/dnsmasq/config/demo2/dns.conf
  operations/dnsmasq/config/demo2/hosts.local
  operations/dnsmasq/config/demo3/dns.conf
  operations/dnsmasq/config/demo3/hosts.local
Labels: DevOps

#5928 fix: allow adding rows with empty fields [experience-5442]
  frontend-react/src/components/Table/TableRows.tsx
Labels: experience

#5828 Missouri onboarding
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0119-Mo-Onboarding.yml
  prime-router/settings/staging/0119-Mo-Onboarding.yml
Labels: onboarding-ops

#5893 New API interfacing tools for React frontend
  frontend-react/src/__mocks__/OrganizationMockServer.ts
  frontend-react/src/components/SenderModeBanner.test.tsx
  frontend-react/src/components/SenderModeBanner.tsx
  frontend-react/src/contexts/SessionContext.tsx
  frontend-react/src/hooks/UseOktaMemberships.ts
  frontend-react/src/hooks/UseSenderMode.test.ts
  frontend-react/src/hooks/UseSenderMode.ts
  frontend-react/src/hooks/network/UseRequestConfig.test.ts
  frontend-react/src/hooks/network/UseRequestConfig.ts
  frontend-react/src/network/api/NewApi.test.ts
  frontend-react/src/network/api/NewApi.ts
  frontend-react/src/network/api/OrgApi.test.ts
  frontend-react/src/network/api/OrgApi.ts
  frontend-react/src/network/api/mocks/MockApi.ts
  frontend-react/src/network/api/readme.md
  frontend-react/src/utils/UsefulTypes.ts
Labels: frontend, experience, tech-debt

#5941 Experience/5442: fix to update/activate calls
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
Labels: frontend

#5942 fix: default admin defined sender names [experience-5938]
  frontend-react/src/components/Admin/OrgsTable.tsx
  frontend-react/src/pages/Upload.tsx
Labels: experience

#5930 feat: error and success messaging for value sets edits [experience-5443]
  frontend-react/src/components/StaticAlert.test.tsx
  frontend-react/src/components/StaticAlert.tsx
  frontend-react/src/hooks/UseLookupTable.test.ts
  frontend-react/src/hooks/UseLookupTable.ts
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.test.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.tsx
  frontend-react/src/utils/ErrorUtils.tsx
Labels: experience

#5953 set dns image alpine:3.14.2
  operations/dnsmasq/Dockerfile
Labels: DevOps

#5958 updating dns container to 3.15.4
  operations/dnsmasq/Dockerfile
Labels: DevOps

#5951 Experience/5304 deprecate meta
  frontend-react/src/__mocks__/OrganizationMockServer.ts
  frontend-react/src/components/Admin/DisplayMeta.test.tsx
  frontend-react/src/components/Admin/DisplayMeta.tsx
  frontend-react/src/components/Admin/EditReceiverSettings.tsx
  frontend-react/src/components/Admin/EditSenderSettings.tsx
  frontend-react/src/components/Admin/OrgReceiverTable.tsx
  frontend-react/src/components/Admin/OrgSenderTable.tsx
  frontend-react/src/components/Admin/OrgsTable.tsx
  frontend-react/src/pages/admin/AdminOrgEdit.tsx
  frontend-react/src/pages/admin/AdminOrgNew.test.tsx
  frontend-react/src/resources/OrgSettingsBaseResource.ts
  frontend-react/src/resources/OrgSettingsResource.ts
  frontend-react/src/resources/TestResponse.ts
  frontend-react/src/utils/JsonSortReplacer.test.ts
  frontend-react/src/utils/misc.test.ts
  frontend-react/src/utils/misc.ts
Labels: experience

#5968 Update transition banner
  frontend-react/src/pages/Upload.tsx
Labels: experience

#5950 ReportsTable refactor to remove rest-hooks
  frontend-react/src/__mocks__/HistoryMockServer.ts
  frontend-react/src/components/SenderModeBanner.tsx
  frontend-react/src/hooks/filters/UseFilterManager.ts
  frontend-react/src/hooks/filters/UsePages.ts
  frontend-react/src/hooks/network/History/ReportsHooks.test.ts
  frontend-react/src/hooks/network/History/ReportsHooks.ts
  frontend-react/src/network/api/History/Reports.ts
  frontend-react/src/network/api/NewApi.ts
  frontend-react/src/network/api/mocks/MockApi.ts
  frontend-react/src/pages/daily/Table/ReportsTable.test.tsx
  frontend-react/src/pages/daily/Table/ReportsTable.tsx
  frontend-react/src/pages/daily/Table/ReportsUtils.ts
  frontend-react/src/utils/ReportUtils.ts
Labels: frontend, experience
