Repository CDCgov/prime-reportstream, pull requests merged in 2022-11, with the labels that each got.

#7163 Validation front-end design updates
  frontend-react/src/components/FileHandlers/FileHandler.test.tsx
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.test.tsx
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx
  frontend-react/src/components/tooltips/ObjectTooltip.tsx
  frontend-react/src/pages/Validate.tsx
  frontend-react/src/styles/_reportstream.scss
Labels: frontend, experience

#7200 Fetch Refactor: Sender Details
  frontend-react/src/components/FileHandlers/FileHandler.test.tsx
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/components/SenderModeBanner.test.tsx
  frontend-react/src/components/SenderModeBanner.tsx
  frontend-react/src/config/endpoints/services.ts
  frontend-react/src/hooks/UseSenderResource.test.ts
  frontend-react/src/hooks/UseSenderResource.ts
  frontend-react/src/hooks/__mocks__/UseSenderResource.ts
Labels: frontend, experience, tech-debt

#7187 Experience/6986 Receiver Data UI
  frontend-react/src/components/MessageTracker/MessageDetails.test.tsx
  frontend-react/src/components/MessageTracker/MessageDetails.tsx
  frontend-react/src/components/MessageTracker/MessageReceivers.test.tsx
  frontend-react/src/components/MessageTracker/MessageReceivers.tsx
  frontend-react/src/components/MessageTracker/MessageSender.test.tsx
  frontend-react/src/components/MessageTracker/MessageSender.tsx
  frontend-react/src/components/MessageTracker/MessageTracker.tsx
  frontend-react/src/components/MessageTracker/QualityFilters.test.tsx
  frontend-react/src/components/MessageTracker/QualityFilters.tsx
  frontend-react/src/components/MessageTracker/WarningsErrors.test.tsx
  frontend-react/src/components/MessageTracker/WarningsErrors.tsx
  frontend-react/src/config/endpoints/messageTracker.ts
  frontend-react/yarn.lock
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/MessagesFunctions.kt
  prime-router/src/main/kotlin/messageTracker/Message.kt
  prime-router/src/test/kotlin/azure/MessagesFunctionsTests.kt
Labels: backend, frontend, experience

#7199 Dependabot config for custom actions
  .github/dependabot.yml
Labels: DevOps, dependencies

#7218 experience/6931: [Message ID][Search][UI][API] Complete
  frontend-react/src/__mocks__/MessageTrackerMockServer.ts
  frontend-react/src/components/MessageTracker/MessageTracker.test.tsx
  frontend-react/src/components/MessageTracker/MessageTracker.tsx
  frontend-react/src/config/endpoints/messageTracker.ts
  frontend-react/src/hooks/network/MessageTracker/MessageTrackerHooks.test.ts
  frontend-react/src/hooks/network/MessageTracker/MessageTrackerHooks.ts
Labels: frontend

#7223 Add RI and MO to live state map and list
  frontend-react/src/content/live.json
  frontend-react/src/content/usa_w_territories.svg
Labels: onboarding-ops, experience

#7239 Experience/7190: [Message ID][Details][UI][API] Complete
  frontend-react/src/AppRouter.tsx
  frontend-react/src/__mocks__/MessageTrackerMockServer.ts
  frontend-react/src/components/MessageTracker/MessageDetails.test.tsx
  frontend-react/src/components/MessageTracker/MessageDetails.tsx
  frontend-react/src/components/MessageTracker/MessageReceivers.tsx
  frontend-react/src/components/MessageTracker/MessageTracker.tsx
  frontend-react/src/components/MessageTracker/WarningsErrors.tsx
  frontend-react/src/config/endpoints/messageTracker.ts
  frontend-react/src/hooks/network/MessageTracker/MessageTrackerHooks.test.ts
  frontend-react/src/hooks/network/MessageTracker/MessageTrackerHooks.ts
  frontend-react/src/hooks/network/MessageTracker/__mocks__/MessageTrackerHooks.ts
Labels: frontend, experience

#7233 Bump @xmldom/xmldom from 0.7.6 to 0.7.8 in /frontend-react
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: security, dependencies, javascript

#7167 Disable FTP/FTPS deployments
  operations/app/terraform/modules/metabase/main.tf
Labels: DevOps, security

#7267 Experience/7190 Patch
  frontend-react/src/components/MessageTracker/MessageDetails.test.tsx
  frontend-react/src/components/MessageTracker/MessageDetails.tsx
  frontend-react/src/components/MessageTracker/MessageTracker.tsx
Labels: frontend, experience

#7268 experience/7262: optimize messages functions queries
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
Labels: experience

#7278 Bump loader-utils from 2.0.2 to 2.0.3 in /frontend-react
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: security, dependencies, javascript

#7177 Add additional reporting output file options
  frontend-react/src/pages/resources/legacy-page-content/CsvSchemaDocumentation.tsx
  frontend-react/src/pages/resources/legacy-page-content/CsvUploadGuide.tsx
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/main/kotlin/docgenerators/CsvDocumentationFactory.kt
  prime-router/src/main/kotlin/docgenerators/DocumentationFactory.kt
  prime-router/src/main/kotlin/docgenerators/ExcelDocumentationFactory.kt
  prime-router/src/main/kotlin/docgenerators/HtmlDocumentationFactory.kt
  prime-router/src/main/kotlin/docgenerators/MarkdownDocumentationFactory.kt
  prime-router/src/test/kotlin/DocumentationTests.kt
Labels: onboarding-ops

#7291 Bump Node.js from v16.18.0 to v16.18.1
  .github/actions/build-frontend/action.yml
  frontend-react/.nvmrc
Labels: security, experience, dependencies

#7296 Experience/7190 Update to title when calling WarningsErrors component
  frontend-react/src/components/MessageTracker/MessageDetails.tsx
Labels: frontend, experience

#7293 Updates axios to 0.27.2
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: experience, tech-debt

#7303 Fixed RI Error Message missing OBR-4, OBX-3.2, OBX-17
  prime-router/metadata/tables/livd/LIVD-Supplemental.csv
Labels: onboarding-ops

#7290 Validation Service: Updated error messages
  prime-router/src/main/kotlin/ActionMessages.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
Labels: backend, experience, API

#7317 move bzdlabs to full production
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0146-update-bzdlabs-to-prod.yml
  prime-router/settings/staging/0146-update-bzdlabs-to-prod.yml
Labels: onboarding-ops, sender

#7321 7054 Fetch report lineage by report ID
  prime-router/src/main/kotlin/history/azure/DatabaseDeliveryAccess.kt
  prime-router/src/main/kotlin/history/azure/DatabaseSubmissionsAccess.kt
  prime-router/src/main/kotlin/history/azure/HistoryDatabaseAccess.kt
  prime-router/src/main/kotlin/history/azure/SubmissionsFacade.kt
  prime-router/src/test/kotlin/history/azure/SubmissionsFacadeTests.kt
Labels: pipeline

#7362 experience/7310: make message tracker search form... a form
  frontend-react/src/components/MessageTracker/MessageTracker.tsx
  frontend-react/src/styles/_reportstream.scss
Labels: experience

#7368 4859 Daily Data pagination
  frontend-react/src/__mocks__/DeliveriesMockServer.ts
  frontend-react/src/hooks/network/History/DeliveryHooks.test.ts
  frontend-react/src/hooks/network/History/DeliveryHooks.ts
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.test.tsx
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.tsx
  frontend-react/src/pages/submissions/SubmissionTable.test.tsx
  frontend-react/src/resources/SubmissionsResource.ts
  prime-router/src/main/kotlin/history/azure/DatabaseDeliveryAccess.kt
  prime-router/src/main/kotlin/history/azure/DeliveryFacade.kt
  prime-router/src/main/kotlin/history/azure/DeliveryFunction.kt
  prime-router/src/main/kotlin/history/azure/ReportFileFunction.kt
  prime-router/src/main/kotlin/history/azure/SubmissionFunction.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFunctionTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionFunctionTests.kt
Labels: frontend, experience

#7376 updating FA version for prod from ~3 -> ~4
  operations/app/terraform/vars/prod/locals.tf
Labels: DevOps, reportstream

#7316 Allow test result in any OBX iteration
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
  prime-router/src/testIntegration/kotlin/serializers/Hl7SerializerIntegrationTests.kt
  prime-router/src/testIntegration/resources/serializers/test_result_first_rep.hl7
  prime-router/src/testIntegration/resources/serializers/test_result_not_first_rep.hl7
Labels: onboarding-ops

#7261 App Insights React integration prototype
  frontend-react/.env.production
  frontend-react/.env.staging
  frontend-react/package.json
  frontend-react/src/TelemetryService.ts
  frontend-react/src/components/AppWrapper.tsx
  frontend-react/src/index.tsx
  frontend-react/yarn.lock
Labels: frontend, experience, insights

#7375 Oo/oslynn/6188/co no longer requires negative result
  prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
  prime-router/metadata/schemas/PrimeDataInput/pdi-covid-19.schema
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/ReportStreamFilterDefinition.kt
  prime-router/src/test/kotlin/TranslatorTests.kt
Labels: onboarding-ops

#7412 Bump mockk from 1.12.7 to 1.13.1 in /prime-router
  prime-router/build.gradle.kts
Labels: dependencies, java

#7286 Receiver Settings Check for SFTP connections
  frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx
  frontend-react/src/components/Admin/OrgReceiverTable.test.tsx
  frontend-react/src/components/Admin/OrgReceiverTable.tsx
  frontend-react/src/components/Admin/OrgSenderTable.test.tsx
  frontend-react/src/network/api/CheckSettingCmd.ts
  frontend-react/src/styles/_reportstream.scss
  prime-router/docs/api/check.yml
  prime-router/src/main/kotlin/azure/CheckFunction.kt
Labels: onboarding-ops, frontend, API

#7423 Experience/7359
  frontend-react/src/components/Table/Table.tsx
Labels: experience

#7417 Experience/6523
  frontend-react/src/__mocks__/OrganizationMockServer.ts
  frontend-react/src/components/FileHandlers/FileHandler.test.tsx
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/config/endpoints/settings.ts
  frontend-react/src/hooks/UseOktaMemberships.ts
  frontend-react/src/hooks/UseOrgName.ts
  frontend-react/src/hooks/UseOrganizationResource.ts
  frontend-react/src/hooks/UseOrganizationSettings.test.ts
  frontend-react/src/hooks/UseOrganizationSettings.ts
  frontend-react/src/hooks/UseSenderResource.ts
  frontend-react/src/network/api/NewApi.ts
  frontend-react/src/pages/deliveries/Deliveries.tsx
  frontend-react/src/pages/deliveries/details/Summary.tsx
  frontend-react/src/pages/submissions/Submissions.tsx
  frontend-react/src/utils/CustomRenderUtils.tsx
Labels: experience

#7443 7403 remove header within Resources and Support child pages
  frontend-react/src/components/Content/Templates/IACardGridTemplate.test.tsx
  frontend-react/src/components/Content/Templates/IACardGridTemplate.tsx
  frontend-react/src/components/Content/Templates/IATemplate.tsx
  frontend-react/src/pages/resources/Resources.tsx
  frontend-react/src/pages/support/Support.tsx
Labels: frontend, experience

#7451 fix githook script
  .environment/githooks.sh
Labels: DevOps

#7472 [Fix] Download link from Daily Data table
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.test.tsx
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.tsx
Labels: bug, experience, engineering

#7416 Added constants to the FHIR Path tool
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
Labels: pipeline

#7475 Onboarding ops/greene858/7224/wa phd migrate to rest
  .environment/rest_service/data.json
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/credentials/Credential.kt
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
Labels: onboarding-ops, Washington

#7470 Fixed MO Prod data Missing ORC-2.1 and OBR-2.1
  prime-router/.swo
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0147-MO-Update-ORC-2.1-and-OBR-2-1.yml
  prime-router/settings/staging/0147-MO-Update-ORC-2.1-and-OBR-2-1.yml
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
Labels: onboarding-ops

#7408 Lockdown ktlint version
  prime-router/build.gradle.kts
  prime-router/docs/getting-started/getting-started.md
Labels: pipeline

#7468 Experience/7220 Moved Validate and User Upload to Admin menu
  frontend-react/src/components/Content/MarkdownDirectory.tsx
  frontend-react/src/components/header/DropdownNav.test.tsx
  frontend-react/src/components/header/DropdownNav.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
Labels: frontend, experience

#7458 Experience/7280 removed out dated CSV related resources
  frontend-react/src/content/resources/index.ts
Labels: frontend, experience

#7510 7280 - fixed removed out dated CSV related resources
  frontend-react/src/content/resources/index.ts
Labels: frontend, experience

#7388 7047 - Added functionality to support the reverseQualityFilter flag
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/DefaultFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
Labels: pipeline
