Repository CDCgov/prime-reportstream, pull requests merged in 2022-07, with the labels that each got.

#5987 DOMPurify unsanitized html
  frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx
  frontend-react/src/components/EditableCompare.tsx
  frontend-react/src/pages/getting-started/testing-facilities/CsvSchemaDocumentation.tsx
Labels: experience

#5932 Experience/5709: Upload HL7 file via Validation Service UI
  frontend-react/cypress.config.ts
  frontend-react/cypress.json
  frontend-react/cypress/fixtures/example.json
  frontend-react/cypress/integration/pages/Validate.test.tsx
  frontend-react/cypress/support/commands.js
  frontend-react/cypress/support/commands.ts
  frontend-react/cypress/support/e2e.ts
  frontend-react/cypress/support/index.js
  frontend-react/package.json
  frontend-react/src/App.tsx
  frontend-react/src/__mocks__/WatersMockServer.ts
  frontend-react/src/components/Admin/OrgsTable.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/hooks/UseOrgName.ts
  frontend-react/src/hooks/UseOrganizationResouce.tsx
  frontend-react/src/hooks/network/UseRequestConfig.ts
  frontend-react/src/network/api/OrganizationsApi.ts
  frontend-react/src/network/api/WatersApi.test.ts
  frontend-react/src/network/api/WatersApi.ts
  frontend-react/src/network/api/WatersApiFunctions.test.ts
  frontend-react/src/network/api/WatersApiFunctions.ts
  frontend-react/src/pages/Validate.test.tsx
  frontend-react/src/pages/Validate.tsx
  frontend-react/src/pages/misc/FeatureFlags.tsx
  frontend-react/yarn.lock
Labels: experience

#5902 Bumps Kotlin to the latest version - v1.7.0
  prime-router/build.gradle.kts
Labels: onboarding-ops

#5900 Removes FTPS from the application
  .github/workflows/build_hub.yml
  frontend-react/src/utils/TemporarySettingsAPITypes.ts
  prime-router/Makefile
  prime-router/build.gradle.kts
  prime-router/cleanslate.sh
  prime-router/devenv-infrastructure.sh
  prime-router/docker-compose.yml
  prime-router/docs/getting-started/Using-an-apple-silicon-mac.md
  prime-router/src/main/kotlin/TransportType.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/credentials/CredentialService.kt
  prime-router/src/main/kotlin/transport/FTPSTransport.kt
Labels: onboarding-ops

#6010 Fixed IN Onboarding Failed Test Messages
  prime-router/metadata/tables/livd/LIVD-Supplemental.csv
Labels: onboarding-ops

#6021 Fixed IN Onboarding Failed Test Messages
  prime-router/metadata/tables/livd/LIVD-Supplemental.csv
Labels: onboarding-ops

#6024 Add CE truncation limits
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
Labels: onboarding-ops

#6040 Onboard CLX Health
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0120-clxhealth.yml
  prime-router/settings/staging/0120-clxhealth.yml
Labels: onboarding-ops, HL7, sender

#6052 MO Messages Validation
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0121-Mo-Fixed-PID-15-3_ORC-21-1_OBX-23-1.yml
  prime-router/settings/staging/0121-Mo-Fixed-PID-15-3_ORC-21-1_OBX-23-1.yml
Labels: onboarding-ops

#6059 6058 Added NK1 segment for FHIR generation
  prime-router/metadata/fhir_mapping/hl7/message/ORU_R01.yml
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir
Labels: pipeline

#6081 Fixed AL-PHD SFTP Failure in staging
  prime-router/settings/staging/0122-al-phd-remove-transport.yml
Labels: onboarding-ops

#6082 Removed transport from al-phd.elr
  prime-router/settings/staging/0122-al-phd-remove-transport.yml
Labels: onboarding-ops

#6054 Migrate `daily-data` to new API tools
  frontend-react/src/__mocks__/HistoryMockServer.ts
  frontend-react/src/components/SenderModeBanner.tsx
  frontend-react/src/components/Table/Table.tsx
  frontend-react/src/hooks/UseOrganizationResouce.tsx
  frontend-react/src/hooks/filters/UseCursorManager.ts
  frontend-react/src/hooks/filters/UseFilterManager.ts
  frontend-react/src/hooks/filters/UsePages.ts
  frontend-react/src/hooks/network/History/ReportsHooks.test.ts
  frontend-react/src/hooks/network/History/ReportsHooks.ts
  frontend-react/src/network/api/History/Reports.ts
  frontend-react/src/network/api/NewApi.ts
  frontend-react/src/network/api/OrganizationsApi.ts
  frontend-react/src/network/api/WatersApi.test.ts
  frontend-react/src/network/api/WatersApi.ts
  frontend-react/src/network/api/WatersApiFunctions.ts
  frontend-react/src/network/api/mocks/MockApi.ts
  frontend-react/src/pages/daily/Table/ReportsTable.test.tsx
  frontend-react/src/pages/daily/Table/ReportsTable.tsx
  frontend-react/src/pages/daily/Table/ReportsUtils.ts
  frontend-react/src/pages/submissions/SubmissionTable.test.tsx
  frontend-react/src/pages/submissions/SubmissionTable.tsx
  frontend-react/src/utils/ReportUtils.ts
Labels: frontend, experience, tech-debt

#6107 set function app runtime as parameter and set test env to ~4
  operations/app/terraform/modules/function_app/candidate_slot.tf
  operations/app/terraform/modules/function_app/main.tf
  operations/app/terraform/modules/function_app/~inputs.tf
  operations/app/terraform/vars/prod/locals.tf
  operations/app/terraform/vars/prod/main.tf
  operations/app/terraform/vars/staging/locals.tf
  operations/app/terraform/vars/staging/main.tf
  operations/app/terraform/vars/test/locals.tf
  operations/app/terraform/vars/test/main.tf
Labels: DevOps

#6122 Adds Indiana to where we're live map and list
  frontend-react/src/content/live.json
  frontend-react/src/content/usa_w_territories.svg
Labels: onboarding-ops, frontend, experience

#6079 Experience/validation UI design
  frontend-react/src/pages/Validate.tsx
  frontend-react/src/styles/_reportstream.scss
Labels: experience

#6158 Fixes link in HIW dropwdown
  frontend-react/src/components/header/DropdownNav.test.tsx
  frontend-react/src/components/header/DropdownNav.tsx
Labels: bug, frontend, experience

#5986 Add new `adm/resend` api endpoint
  frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx
  prime-router/src/main/kotlin/azure/RequeueFunction.kt
Labels: onboarding-ops, pipeline, API

#6152 ReportStream Public Information Makeover (behind Feature Flag)
  .vscode/settings.json
  frontend-react/src/App.tsx
  frontend-react/src/components/Crumbs.test.tsx
  frontend-react/src/components/Crumbs.tsx
  frontend-react/src/components/IACard.tsx
  frontend-react/src/components/Markdown/DirectoryAsPage.tsx
  frontend-react/src/components/Markdown/DirectoryGenerationTools.tsx
  frontend-react/src/components/Markdown/GeneratedSideNav.tsx
  frontend-react/src/components/Markdown/MarkdownDirectory.ts
  frontend-react/src/components/Markdown/MarkdownDirectory.tsx
  frontend-react/src/components/Markdown/StaticPageFromDirectories.test.tsx
  frontend-react/src/components/Markdown/StaticPageFromDirectories.tsx
  frontend-react/src/components/Markdown/StaticPagesFromDirectories.tsx
  frontend-react/src/components/header/DropdownNav.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/content/built-for-you/2022-june.md
  frontend-react/src/content/product/product-index.md
  frontend-react/src/content/product/release-notes.md
  frontend-react/src/content/resources/referral-guide.md
  frontend-react/src/content/resources/resources-index.md
  frontend-react/src/content/site.json
  frontend-react/src/content/support/contact.md
  frontend-react/src/content/support/faq.md
  frontend-react/src/global.scss
  frontend-react/src/pages/admin/InternalUserGuides.tsx
  frontend-react/src/pages/built-for-you/BuiltForYouIndex.tsx
  frontend-react/src/pages/how-it-works/HowItWorks.tsx
  frontend-react/src/pages/how-it-works/SystemAndSettings.tsx
  frontend-react/src/pages/misc/FeatureFlags.tsx
  frontend-react/src/pages/product/ProductIndex.tsx
  frontend-react/src/pages/product/ReleaseNotes.tsx
  frontend-react/src/pages/product/WhereWereLive.tsx
  frontend-react/src/pages/resources/AccountRegistrationGuide.tsx
  frontend-react/src/pages/resources/CsvUploadGuide.tsx
  frontend-react/src/pages/resources/DataDownloadGuide.tsx
  frontend-react/src/pages/resources/ElrChecklist.tsx
  frontend-react/src/pages/resources/GettingStartedPhd.tsx
  frontend-react/src/pages/resources/ResourcesIndex.tsx
  frontend-react/src/pages/resources/SecurityPractices.tsx
  frontend-react/src/pages/resources/SystemAndSettings.tsx
  frontend-react/src/pages/resources/programmers-guide/ProgrammersGuide.tsx
  frontend-react/src/pages/support/Contact.tsx
  frontend-react/src/pages/support/Faq.tsx
  frontend-react/src/pages/support/SupportIndex.tsx
  frontend-react/src/styles/_color.scss
  frontend-react/src/styles/_reportstream.scss
  frontend-react/src/styles/_typography.scss
  frontend-react/src/styles/_uswds_settings.scss
Labels: frontend, High Priority, experience

#6026 Monkeypox HL7 ELR Message Handling
  prime-router/Dockerfile.build
  prime-router/Dockerfile.dev
  prime-router/build.gradle.kts
  prime-router/cleanslate.sh
  prime-router/docs/schema_documentation/dcipher-dcipher-monkeypox.md
  prime-router/docs/schema_documentation/monkeypox.md
  prime-router/metadata/schemas/dcipher/dcipher-monkeypox.schema
  prime-router/metadata/schemas/monkeypox.schema
  prime-router/metadata/valuesets/monkeypox.valuesets
  prime-router/prime
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/ReportStreamFilter.kt
  prime-router/src/main/kotlin/Sender.kt
  prime-router/src/main/kotlin/SettingsProvider.kt
  prime-router/src/main/kotlin/SubmissionReceiver.kt
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/cli/ProcessDataCommands.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/main/resources/db/migration/V51__add_elr_metadata_results_table.sql
  prime-router/src/test/kotlin/SubmissionReceiverTests.kt
  prime-router/start_func.sh
Labels: monkeypox

#6130 feat: new upload page [experience-6111]
  frontend-react/src/App.tsx
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx
  frontend-react/src/components/StaticAlert.tsx
  frontend-react/src/components/header/DropdownNav.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/pages/UploadToPipeline.tsx
  frontend-react/src/pages/Validate.tsx
  frontend-react/src/pages/misc/FeatureFlags.tsx
  frontend-react/src/utils/DateTimeUtils.ts
Labels: experience

#6181 Experience/content tools coverage
  frontend-react/src/components/Content/DirectoryAsPage.test.tsx
  frontend-react/src/components/Content/DirectoryAsPage.tsx
  frontend-react/src/components/Content/GeneratedSideNav.test.tsx
  frontend-react/src/components/Content/GeneratedSideNav.tsx
  frontend-react/src/components/Content/MarkdownContent.tsx
  frontend-react/src/components/Content/MarkdownDirectory.test.tsx
  frontend-react/src/components/Content/MarkdownDirectory.tsx
  frontend-react/src/components/Content/PageGenerationTools.test.tsx
  frontend-react/src/components/Content/PageGenerationTools.tsx
  frontend-react/src/components/Content/StaticPageFromDirectories.test.tsx
  frontend-react/src/components/Content/StaticPagesFromDirectories.tsx
  frontend-react/src/components/IACard.tsx
  frontend-react/src/components/Markdown/MarkdownDirectory.test.ts
  frontend-react/src/components/header/DropdownNav.tsx
  frontend-react/src/pages/admin/InternalUserGuides.tsx
  frontend-react/src/pages/built-for-you/BuiltForYouIndex.tsx
  frontend-react/src/pages/product/ProductIndex.tsx
  frontend-react/src/pages/resources/ResourcesIndex.tsx
  frontend-react/src/pages/support/SupportIndex.tsx
Labels: frontend, experience

#6191 Farewell to old IA
  frontend-react/src/App.tsx
  frontend-react/src/components/ReportStreamFooter.tsx
  frontend-react/src/components/header/DropdownNav.test.tsx
  frontend-react/src/components/header/DropdownNav.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/content/content.json
  frontend-react/src/content/resources/referral-guide.md
  frontend-react/src/pages/About.tsx
  frontend-react/src/pages/TermsOfService.tsx
  frontend-react/src/pages/built-for-you/BuiltForYouIndex.test.tsx
  frontend-react/src/pages/built-for-you/BuiltForYouIndex.tsx
  frontend-react/src/pages/getting-started/public-health-departments/DataDownloadGuide.tsx
  frontend-react/src/pages/getting-started/public-health-departments/ElrChecklist.tsx
  frontend-react/src/pages/getting-started/public-health-departments/Overview.tsx
  frontend-react/src/pages/getting-started/public-health-departments/index.tsx
  frontend-react/src/pages/getting-started/testing-facilities/AccountRegistrationGuide.tsx
  frontend-react/src/pages/getting-started/testing-facilities/CsvSchemaDocumentation.test.tsx
  frontend-react/src/pages/getting-started/testing-facilities/CsvSchemaDocumentation.tsx
  frontend-react/src/pages/getting-started/testing-facilities/CsvUploadGuide.tsx
  frontend-react/src/pages/getting-started/testing-facilities/Overview.tsx
  frontend-react/src/pages/getting-started/testing-facilities/RegisterAnAccount.tsx
  frontend-react/src/pages/getting-started/testing-facilities/index.tsx
  frontend-react/src/pages/how-it-works/About.tsx
  frontend-react/src/pages/how-it-works/HowItWorks.tsx
  frontend-react/src/pages/how-it-works/SecurityPractices.tsx
  frontend-react/src/pages/how-it-works/SystemAndSettings.tsx
  frontend-react/src/pages/how-it-works/WhereWereLive.tsx
  frontend-react/src/pages/product/ProductIndex.tsx
  frontend-react/src/pages/product/WhereWereLive.tsx
  frontend-react/src/pages/resources/CsvSchemaDocumentation.tsx
  frontend-react/src/pages/resources/ElrChecklist.tsx
  frontend-react/src/pages/resources/GettingStartedPhd.tsx
  frontend-react/src/pages/resources/__snapshots__/CsvSchemaDocumentation.test.tsx.snap
  frontend-react/src/pages/resources/programmers-guide/ProgrammersGuide.tsx
  frontend-react/src/pages/support/Contact.tsx
  frontend-react/src/pages/support/Faq.tsx
  frontend-react/src/styles/_reportstream.scss
Labels: frontend, experience, feature

#6195 referral typo guide
  frontend-react/src/content/resources/referral-guide.md
Labels: content, experience

#6186 feat: validation & upload warnings [experience-6090]
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx
  frontend-react/src/network/api/WatersApi.ts
Labels: experience

#6166 6102 Convert non-repeating HL7 segments from FHIR
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/Exceptions.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReader.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/HL7Utils.kt
  prime-router/src/main/resources/log4j2.xml
  prime-router/src/test/kotlin/fhirengine/translation/hl7/ExceptionTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReaderTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/FhirPathUtilsTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/Hl7UtilsTests.kt
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01/header.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01/patient-identification.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01/patient.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-02/ORU_R01_incomplete.yml
Labels: pipeline

#6211 Onboarding ops/5798/testkit and equip uid for sr
  prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
  prime-router/metadata/schemas/PrimeDataInput/pdi-covid-19.schema
Labels: onboarding-ops, simplereport

#6210 Fixed date-time sequence for fake data generator
  prime-router/src/main/kotlin/FakeReport.kt
Labels: onboarding-ops

#6196 Refactors instantiation pattern for ContentDirectory children
  frontend-react/src/components/Content/DirectoryAsPage.test.tsx
  frontend-react/src/components/Content/GeneratedSideNav.test.tsx
  frontend-react/src/components/Content/MarkdownDirectory.test.tsx
  frontend-react/src/components/Content/MarkdownDirectory.tsx
  frontend-react/src/components/Content/StaticPageFromDirectories.test.tsx
  frontend-react/src/components/IACard.tsx
  frontend-react/src/components/header/DropdownNav.tsx
  frontend-react/src/pages/admin/InternalUserGuides.tsx
  frontend-react/src/pages/product/ProductIndex.tsx
  frontend-react/src/pages/resources/ResourcesIndex.tsx
  frontend-react/src/pages/support/SupportIndex.tsx
Labels: frontend, experience

#6223 experience/5924: Retire unused lookupSenderValuesets mapper
  prime-router/metadata/tables/local/sender_valuesets.csv
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/metadata/Mappers.kt
  prime-router/src/test/kotlin/metadata/MapperTests.kt
  prime-router/src/test/resources/metadata/tables/sender_valuesets.csv
Labels: experience

#6213 6103 FHIR to HL7 library converts repeating segments
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/ConstantResolverTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/FhirPathUtilsTests.kt
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01/observation.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01/order-observation.yml
Labels: pipeline

#6227 5306 Removed meta from settings API response
  .environment/soap_service/soap/response/v2/PRBkKQ.res
  .environment/soap_service/soap/response/v2/sjIvfk.res
  .gitignore
  prime-router/src/main/kotlin/Sender.kt
  prime-router/src/main/kotlin/azure/SettingsFacade.kt
Labels: pipeline

#6229 Removed C. Felix and Rick from deployment PR assignees
  .github/workflows/prepare_deployment_branch.yaml
Labels: pipeline

#6234 Fixed Mo's HL7 Validation
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0125-Mo-Fixed-OBX23-10_OBX15-1_MSH3_MSH5_MSH6.yml
  prime-router/settings/staging/0125-Mo-Fixed-OBX23-10_OBX15-1_MSH3_MSH5_MSH6.yml
Labels: onboarding-ops

#6201 Experience/6169 file handler reducer
  frontend-react/package.json
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/components/FileHandlers/FileHandlerForm.tsx
  frontend-react/src/hooks/UseFileHandler.test.ts
  frontend-react/src/hooks/UseFileHandler.ts
  frontend-react/src/network/api/WatersApi.ts
  frontend-react/src/utils/FileUtils.test.ts
  frontend-react/src/utils/FileUtils.ts
  frontend-react/yarn.lock
Labels: experience

#6214 Fixes authorization bug for `/settings/receivers` list API endpoint
  prime-router/src/main/kotlin/azure/SettingsFunctions.kt
Labels: bug, experience

#5719 Bump org.jsoup:jsoup from 1.14.1 to 1.14.2 in /prime-router
  prime-router/build.gradle.kts
Labels: security, dependencies, java

#6248 Fix slug/content issue
  frontend-react/src/pages/support/SupportIndex.tsx
Labels: experience

#6249 Monkeypox schema updates
  prime-router/docs/schema_documentation/dcipher-dcipher-monkeypox.md
  prime-router/metadata/schemas/dcipher/dcipher-monkeypox.schema
Labels: monkeypox

#6203 Adds fix for the comment not carrying over on inbound HL7 messages
  prime-router/docs/schema_documentation/dcipher-dcipher-monkeypox.md
  prime-router/docs/schema_documentation/monkeypox.md
  prime-router/metadata/schemas/monkeypox.schema
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
Labels: monkeypox

#6163 Receiver CRON network results dashboard
  frontend-react/src/App.tsx
  frontend-react/src/components/Admin/AdminReceiverDashboard.test.tsx
  frontend-react/src/components/Admin/AdminReceiverDashboard.tsx
  frontend-react/src/components/header/DropdownNav.tsx
  frontend-react/src/pages/admin/AdminReceiverDashPage.tsx
  frontend-react/src/resources/AdmConnStatusResource.ts
  frontend-react/src/styles/_reportstream.scss
  prime-router/docs/api/admin.yml
  prime-router/src/main/kotlin/azure/AdminApiFunctions.kt
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/test/kotlin/azure/AdminApiFunctionsTests.kt
Labels: pipeline, experience

#6260 fix: remove unreliable time zone dependent test case [unticketed]
  frontend-react/src/utils/DateTimeUtils.test.ts
Labels: experience
