Repository CDCgov/prime-reportstream, pull requests merged in 2022-08, with the labels that each got.

#6266 Experience/6169 file handler component tests
  frontend-react/src/components/FileHandlers/FileHandler.test.tsx
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/components/FileHandlers/FileHandlerButton.test.tsx
  frontend-react/src/components/FileHandlers/FileHandlerButton.tsx
  frontend-react/src/components/FileHandlers/FileHandlerForm.test.tsx
  frontend-react/src/components/FileHandlers/FileHandlerForm.tsx
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.test.tsx
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx
  frontend-react/src/hooks/UseFileHandler.ts
  frontend-react/src/hooks/UseOrgName.ts
  frontend-react/src/hooks/UseOrganizationResource.ts
Labels: experience

#6280 Monkeypox demographics schema updates
  prime-router/docs/schema_documentation/dcipher-dcipher-monkeypox.md
  prime-router/docs/schema_documentation/monkeypox.md
  prime-router/metadata/schemas/dcipher/dcipher-monkeypox.schema
  prime-router/metadata/schemas/monkeypox.schema
Labels: monkeypox

#6269 Update AdminLastMileFailuresTable.tsx
  frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx
Labels: frontend

#6277 multiple content updates, product nav update
  frontend-react/package.json
  frontend-react/public/assets/reportstream-works.png
  frontend-react/src/components/Content/MarkdownContent.tsx
  frontend-react/src/content/content.json
  frontend-react/src/content/product/product-index.md
  frontend-react/src/content/resources/referral-guide.md
  frontend-react/src/pages/product/ProductIndex.tsx
  frontend-react/src/pages/resources/ResourcesIndex.tsx
  frontend-react/src/pages/resources/programmers-guide/ProgrammersGuide.tsx
  frontend-react/src/pages/support/Contact.tsx
  frontend-react/src/pages/support/Faq.tsx
  frontend-react/src/pages/support/SupportIndex.tsx
  frontend-react/yarn.lock
Labels: experience

#6268 Dashboard Fixes
  frontend-react/src/components/Admin/AdminReceiverDashboard.test.tsx
  frontend-react/src/components/Admin/AdminReceiverDashboard.tsx
  frontend-react/src/pages/admin/AdminReceiverDashPage.tsx
  frontend-react/src/styles/_reportstream.scss
Labels: frontend

#6287 Convert details page to new API tools (Fix admin 401)
  frontend-react/src/__mocks__/HistoryMockServer.ts
  frontend-react/src/hooks/network/History/ReportsHooks.test.ts
  frontend-react/src/hooks/network/History/ReportsHooks.ts
  frontend-react/src/network/api/History/Reports.ts
  frontend-react/src/pages/daily/Table/ReportLink.tsx
  frontend-react/src/pages/details/Details.tsx
  frontend-react/src/pages/details/ReportDetails.tsx
  frontend-react/src/pages/details/Summary.tsx
Labels: bug, frontend, experience, tech-debt

#6283 Create zipCodeToState Mapper for RADx
  prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
  prime-router/docs/schema_documentation/direct-hca-covid-19.md
  prime-router/docs/schema_documentation/hl7-detect-covid-19.md
  prime-router/docs/schema_documentation/hl7-hcintegrations-covid-19.md
  prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19-prod.md
  prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19-training.md
  prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19.md
  prime-router/docs/schema_documentation/hl7-lifepoint-covid-19.md
  prime-router/docs/schema_documentation/hl7-mns-covid-19.md
  prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
  prime-router/docs/schema_documentation/hl7-primary-covid-19.md
  prime-router/docs/schema_documentation/hl7-signetic-covid-19.md
  prime-router/docs/schema_documentation/hl7-test-covid-19.md
  prime-router/metadata/schemas/HL7/hl7-ingest-covid-19-training.schema
  prime-router/metadata/schemas/HL7/hl7-ingest-covid-19.schema
  prime-router/metadata/schemas/NM/nm-covid-19-csv.schema
  prime-router/metadata/schemas/covid-19.schema
  prime-router/metadata/schemas/csv-otc-covid-19.schema
  prime-router/metadata/schemas/direct/direct-otc-covid-19.schema
  prime-router/metadata/schemas/monkeypox.schema
  prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema
  prime-router/metadata/schemas/upload-covid-19.schema
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/metadata/Mappers.kt
  prime-router/src/test/kotlin/metadata/MapperTests.kt
Labels: onboarding-ops

#6256 5746 Generate HL7 SFT segment from FHIR
  prime-router/metadata/hl7_mapping/ORU_R01/ORU_R01-base.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/message-header.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/patient.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/software.yml
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
  prime-router/src/main/resources/log4j2.xml
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/ConstantResolverTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/FhirPathUtilsTests.kt
Labels: pipeline

#6282 Experience/validation mvp content fixes
  frontend-react/src/components/FileHandlers/FileHandler.test.tsx
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx
  frontend-react/src/hooks/UseSenderResource.test.ts
  frontend-react/src/hooks/UseSenderResource.ts
  frontend-react/src/network/api/OrganizationsApi.ts
  frontend-react/src/pages/UploadToPipeline.tsx
  frontend-react/src/pages/Validate.tsx
  frontend-react/src/styles/_reportstream.scss
  frontend-react/src/utils/misc.test.ts
  frontend-react/src/utils/misc.ts
Labels: experience

#6322 experience/5713-fix-auth-level: change auth type from FUNCTION to ANONYMOUS
  prime-router/src/main/kotlin/azure/ValidateFunction.kt
Labels: experience

#6295 feat: link upload success confirmation code to submission detail [experience-6286]
  frontend-react/src/components/FileHandlers/FileHandler.test.tsx
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.test.tsx
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx
Labels: experience

#6321 Fixed MO Validation Error ORC-2 and OBR-2 by replacing the value give…
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0127-Mo-Fixed-ORC-2_OBR-2.yml
  prime-router/settings/staging/0127-Mo-Fixed-ORC-2_OBR-2.yml
Labels: onboarding-ops

#6279 Bump com.okta.jwt:okta-jwt-verifier-impl:0.5.1 to 0.5.3 in /prime-router
  prime-router/build.gradle.kts
Labels: security, dependencies

#6335 experience/6285: Hookup /validate page with new /validate endpoint
  frontend-react/src/components/FileHandlers/FileHandler.test.tsx
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/hooks/UseFileHandler.test.ts
  frontend-react/src/hooks/UseFileHandler.ts
  frontend-react/src/network/api/WatersApi.ts
  frontend-react/src/network/api/WatersApiFunctions.test.ts
  frontend-react/src/network/api/WatersApiFunctions.ts
  frontend-react/src/pages/UploadToPipeline.tsx
  frontend-react/src/pages/Validate.tsx
Labels: experience

#6320 6233 Fix submissions list returning multiple entries for one submission
  prime-router/docs/api/waters-submissions.yml
  prime-router/src/main/kotlin/Sender.kt
  prime-router/src/main/kotlin/history/SubmissionHistory.kt
  prime-router/src/main/kotlin/history/azure/DatabaseSubmissionsAccess.kt
  prime-router/src/main/kotlin/history/azure/HistoryDatabaseAccess.kt
  prime-router/src/main/kotlin/history/azure/SubmissionsFacade.kt
  prime-router/src/test/kotlin/history/SubmissionHistoryTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionFunctionTests.kt
Labels: pipeline

#6302 Adds a patient age mapper for outbound calculation of age for a patient
  prime-router/docs/schema_documentation/dcipher-dcipher-monkeypox.md
  prime-router/docs/schema_documentation/monkeypox.md
  prime-router/metadata/schemas/dcipher/dcipher-monkeypox.schema
  prime-router/metadata/schemas/monkeypox.schema
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/common/DateUtilities.kt
  prime-router/src/main/kotlin/metadata/Mappers.kt
  prime-router/src/test/kotlin/common/DateUtilitiesTests.kt
  prime-router/src/test/kotlin/metadata/MapperTests.kt
Labels: monkeypox

#6315 Dashboard optimizations
  frontend-react/src/components/Admin/AdminReceiverDashboard.test.tsx
  frontend-react/src/components/Admin/AdminReceiverDashboard.tsx
  frontend-react/src/pages/admin/AdminReceiverDashPage.tsx
  frontend-react/src/styles/_reportstream.scss
Labels: frontend

#6305 Add `.limit()` to queries to bound them
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
Labels: pipeline, API

#6353 FHIR to HL7 library allows use of primitives in resource schema property
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
Labels: pipeline

#6350 Experience/6341: return Valid status if warnings but no errors are submitted
  prime-router/src/main/kotlin/SubmissionReceiver.kt
  prime-router/src/main/kotlin/azure/ValidateFunction.kt
  prime-router/src/test/kotlin/SubmissionReceiverTests.kt
Labels: experience

#6346 Adds additional metadata columns for ELR and fixes bug with test performed fields
  prime-router/docs/schema_documentation/dcipher-dcipher-monkeypox.md
  prime-router/docs/schema_documentation/monkeypox.md
  prime-router/metadata/schemas/dcipher/dcipher-monkeypox.schema
  prime-router/metadata/schemas/monkeypox.schema
  prime-router/metadata/valuesets/monkeypox.valuesets
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/resources/db/migration/V55__add_normalized_code_values_elr_metadata.sql
Labels: monkeypox

#6376 fix: remove unused variables in admin receiver dashbaord test
  frontend-react/src/components/Admin/AdminReceiverDashboard.test.tsx
Labels: experience

#6369 Bump postgresql 42.4.1
  prime-router/build.gradle.kts
Labels: backend, security, dependencies

#6389 Experience/5909: valueset backend refactor
  prime-router/metadata/tables/local/ethnicity.csv
  prime-router/metadata/tables/local/gender.csv
  prime-router/metadata/tables/local/patient_preferred_language.csv
  prime-router/metadata/tables/local/pregnant.csv
  prime-router/metadata/tables/local/race.csv
  prime-router/metadata/tables/local/residence_type.csv
  prime-router/metadata/tables/local/specimen_source_site_code.csv
  prime-router/metadata/tables/local/specimen_type.csv
  prime-router/metadata/tables/local/state.csv
  prime-router/metadata/tables/local/test_result.csv
  prime-router/metadata/tables/local/yesno.csv
  prime-router/src/main/kotlin/cli/ConvertValuesetsYamlToCSV.kt
  prime-router/src/main/kotlin/metadata/Mappers.kt
  prime-router/src/test/kotlin/metadata/MapperTests.kt
  prime-router/src/test/resources/metadata/tables/gender.csv
  prime-router/src/test/resources/metadata/tables/test_result.csv
Labels: backend, pipeline, experience

#6398 Update loading indicator to match RS branding
  frontend-react/src/components/Spinner.tsx
Labels: experience

#6387 Add deep link to settings for org
  frontend-react/src/components/Admin/AdminReceiverDashboard.test.tsx
  frontend-react/src/components/Admin/AdminReceiverDashboard.tsx
Labels: experience

#6333 Replace `History` reports API with `Delivery` API
  frontend-react/src/__mocks__/DeliveriesMockServer.ts
  frontend-react/src/__mocks__/OrganizationMockServer.ts
  frontend-react/src/hooks/network/History/DeliveryHooks.test.ts
  frontend-react/src/hooks/network/History/DeliveryHooks.ts
  frontend-react/src/hooks/network/History/ReportsHooks.ts
  frontend-react/src/hooks/network/History/__mocks__/DeliveryHooks.ts
  frontend-react/src/hooks/network/Organizations/ReceiversHooks.test.ts
  frontend-react/src/hooks/network/Organizations/ReceiversHooks.ts
  frontend-react/src/hooks/network/Organizations/__mocks__/ReceiversHooks.ts
  frontend-react/src/hooks/network/UseMemoizedConfig.ts
  frontend-react/src/hooks/network/UseRequestConfig.ts
  frontend-react/src/network/api/History/Reports.ts
  frontend-react/src/network/api/NewApi.ts
  frontend-react/src/network/api/Organizations/Receivers.ts
  frontend-react/src/network/api/OrganizationsApi.ts
  frontend-react/src/pages/daily/Table/ReportLink.tsx
  frontend-react/src/pages/daily/Table/ReportsTable.test.tsx
  frontend-react/src/pages/daily/Table/ReportsTable.tsx
  frontend-react/src/pages/daily/Table/ServicesDropdown.tsx
  frontend-react/src/pages/daily/Table/TableButtonGroup.tsx
  frontend-react/src/pages/details/Details.tsx
  frontend-react/src/pages/details/ReportDetails.tsx
  frontend-react/src/pages/details/Summary.tsx
  frontend-react/src/utils/ReportUtils.ts
Labels: frontend, experience

#6414 fix: correctly store org override on member type change [unticketed]
  frontend-react/src/hooks/UseOktaMemberships.test.ts
  frontend-react/src/hooks/UseOktaMemberships.ts
Labels: experience

#6416 fix: do not crash daily data if data comes back undefined
  frontend-react/src/pages/daily/Table/ReportsTable.test.tsx
  frontend-react/src/pages/daily/Table/ReportsTable.tsx
Labels: experience

#6415 Clean-up and separation of IA concerns
  frontend-react/src/App.tsx
  frontend-react/src/components/Content/PageGenerationTools.test.tsx
  frontend-react/src/components/Content/PageGenerationTools.tsx
  frontend-react/src/components/Content/Templates/IACardGridTemplate.tsx
  frontend-react/src/components/Content/Templates/IAMetaAndRouter.tsx
  frontend-react/src/content/product/index.ts
  frontend-react/src/content/resources/index.ts
  frontend-react/src/content/support/contact.md
  frontend-react/src/content/support/faq.md
  frontend-react/src/content/support/index.ts
  frontend-react/src/pages/product/ProductIndex.tsx
  frontend-react/src/pages/product/ReleaseNotes.tsx
  frontend-react/src/pages/product/legacy-page-content/WhereWereLive.tsx
  frontend-react/src/pages/resources/ResourcesCardGrid.tsx
  frontend-react/src/pages/resources/ResourcesIndex.tsx
  frontend-react/src/pages/resources/__snapshots__/CsvSchemaDocumentation.test.tsx.snap
  frontend-react/src/pages/resources/index-legacy.ts
  frontend-react/src/pages/resources/legacy-page-content/AccountRegistrationGuide.tsx
  frontend-react/src/pages/resources/legacy-page-content/CsvSchemaDocumentation.test.tsx
  frontend-react/src/pages/resources/legacy-page-content/CsvSchemaDocumentation.tsx
  frontend-react/src/pages/resources/legacy-page-content/CsvUploadGuide.tsx
  frontend-react/src/pages/resources/legacy-page-content/DataDownloadGuide.tsx
  frontend-react/src/pages/resources/legacy-page-content/ElrChecklist.tsx
  frontend-react/src/pages/resources/legacy-page-content/GettingStartedPhd.tsx
  frontend-react/src/pages/resources/legacy-page-content/ProgrammersGuide.tsx
  frontend-react/src/pages/resources/legacy-page-content/SecurityPractices.tsx
  frontend-react/src/pages/resources/legacy-page-content/SystemAndSettings.tsx
  frontend-react/src/pages/resources/markdown-adapters.tsx
  frontend-react/src/pages/support/SupportCardGrid.tsx
  frontend-react/src/pages/support/SupportIndex.tsx
  frontend-react/src/pages/support/index-legacy.ts
  frontend-react/src/pages/support/legacy-page-content/Contact.tsx
  frontend-react/src/pages/support/legacy-page-content/Faq.tsx
Labels: frontend, content, experience

#6424 fix: route to product sub-pages
  frontend-react/src/pages/product/ProductIndex.tsx
Labels: experience

#6430 `<IACardGridTemplate>` now optionally configurable with sections
  frontend-react/src/components/Content/PageGenerationTools.tsx
  frontend-react/src/components/Content/Templates/IACardGridTemplate.test.tsx
  frontend-react/src/components/Content/Templates/IACardGridTemplate.tsx
  frontend-react/src/content/resources/index.ts
  frontend-react/src/content/support/index.ts
  frontend-react/src/pages/resources/legacy-page-content/__snapshots__/CsvSchemaDocumentation.test.tsx.snap
Labels: frontend, experience

#6426 Update AZ filtering
  prime-router/settings/organizations.yml
Labels: onboarding-ops, Arizona

#6362 Combine authorization for Okta and Server2server
  prime-router/docs/proposals/0016-authorization.md
  prime-router/src/main/kotlin/azure/EmailEngineFunction.kt
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/azure/TokenFunction.kt
  prime-router/src/main/kotlin/azure/ValidateFunction.kt
  prime-router/src/main/kotlin/cli/tests/WatersAuthTests.kt
  prime-router/src/main/kotlin/history/azure/ReportFileFacade.kt
  prime-router/src/main/kotlin/history/azure/ReportFileFunction.kt
  prime-router/src/main/kotlin/tokens/AuthenticatedClaims.kt
  prime-router/src/main/kotlin/tokens/AuthenticationStrategy.kt
  prime-router/src/main/kotlin/tokens/OktaAuthentication.kt
  prime-router/src/main/kotlin/tokens/Scope.kt
  prime-router/src/main/kotlin/tokens/Server2ServerAuthentication.kt
  prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
  prime-router/src/test/kotlin/azure/TokenFunctionTests.kt
  prime-router/src/test/kotlin/azure/ValidateFunctionTests.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFunctionTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionFunctionTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionsFacadeTests.kt
  prime-router/src/test/kotlin/tokens/AuthenticatedClaimsTests.kt
  prime-router/src/test/kotlin/tokens/AuthenticationStrategyTests.kt
  prime-router/src/test/kotlin/tokens/OktaAuthenticationTests.kt
  prime-router/src/test/kotlin/tokens/ScopeTests.kt
  prime-router/src/test/kotlin/tokens/Server2ServerAuthenticationTests.kt
Labels: tech-debt

#6402 Experience/follow up for user state management refactors
  frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx
  frontend-react/src/components/Admin/EditReceiverSettings.tsx
  frontend-react/src/components/Admin/EditSenderSettings.tsx
  frontend-react/src/components/Admin/OrgsTable.tsx
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/components/SenderModeBanner.test.tsx
  frontend-react/src/components/SenderModeBanner.tsx
  frontend-react/src/components/header/ReportStreamHeader.test.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/contexts/SessionContext.test.tsx
  frontend-react/src/contexts/SessionContext.tsx
  frontend-react/src/hooks/UseOktaMemberships.test.ts
  frontend-react/src/hooks/UseOktaMemberships.ts
  frontend-react/src/hooks/UseOrganizationResource.ts
  frontend-react/src/hooks/UseSenderResource.test.ts
  frontend-react/src/hooks/UseSenderResource.ts
  frontend-react/src/hooks/network/History/DeliveryHooks.test.ts
  frontend-react/src/hooks/network/Organizations/ReceiversHooks.test.ts
  frontend-react/src/hooks/network/UseMemoizedConfig.ts
  frontend-react/src/network/Apis.ts
  frontend-react/src/network/api/readme.md
  frontend-react/src/pages/Login.tsx
  frontend-react/src/pages/admin/AdminOrgEdit.tsx
  frontend-react/src/pages/daily/Table/ReportLink.tsx
  frontend-react/src/pages/daily/Table/ReportsTable.test.tsx
  frontend-react/src/pages/daily/Table/ReportsTable.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.tsx
  frontend-react/src/pages/submissions/SubmissionTable.test.tsx
  frontend-react/src/pages/submissions/SubmissionTable.tsx
  frontend-react/src/resources/AuthResource.ts
  frontend-react/src/resources/SenderAuthResource.ts
  frontend-react/src/utils/OrganizationUtils.test.ts
  frontend-react/src/utils/OrganizationUtils.ts
  frontend-react/src/utils/SessionStorageTools.ts
Labels: experience

#5914 Adds logic to deidentify patient DOB according to HIPAA Safe Harbor Rules
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/common/DateUtilities.kt
  prime-router/src/test/kotlin/ReportTests.kt
Labels: onboarding-ops

#6472 Revert Delivery endpoint implementation
  frontend-react/src/network/api/History/Reports.ts
  frontend-react/src/pages/daily/Table/ReportsTable.test.tsx
  frontend-react/src/pages/daily/Table/ReportsTable.tsx
  frontend-react/src/pages/daily/Table/ServicesDropdown.tsx
  frontend-react/src/pages/details/Details.tsx
  frontend-react/src/pages/details/ReportDetails.tsx
  frontend-react/src/pages/details/Summary.tsx
  frontend-react/src/utils/ReportUtils.ts
Labels: bug, frontend, experience

#6488 Fix css layout for Last Mile failures dialog
  frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx
Labels: experience

#6476 refactor: move value sets gets to react-query
  frontend-react/package.json
  frontend-react/src/App.tsx
  frontend-react/src/__mocks__/LookupTableMockServer.ts
  frontend-react/src/hooks/UseLookupTable.test.ts
  frontend-react/src/hooks/UseLookupTable.ts
  frontend-react/src/hooks/UseValueSets.test.ts
  frontend-react/src/hooks/UseValueSets.ts
  frontend-react/src/network/api/LookupTableApi.ts
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.test.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.test.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.tsx
  frontend-react/src/utils/CustomRenderUtils.tsx
  frontend-react/yarn.lock
Labels: experience

#6474 5753 Generate HL7 TQ1 segment from FHIR
  prime-router/metadata/hl7_mapping/ORU_R01/ORU_R01-base.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/order-observation.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/timing-quantity.yml
Labels: pipeline

#6477 Experience/6392 react query mutate value sets
  frontend-react/src/__mocks__/LookupTableMockServer.ts
  frontend-react/src/hooks/UseValueSets.test.ts
  frontend-react/src/hooks/UseValueSets.ts
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.test.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
Labels: experience

#6511 Update programmers guide pdf to v2.3 (updated version)
  frontend-react/public/assets/pdf/ReportStream-Programmers-Guide-v2.2.pdf
  frontend-react/public/assets/pdf/ReportStream-Programmers-Guide-v2.3-updated.pdf
  frontend-react/src/content/site.json
  frontend-react/src/pages/resources/legacy-page-content/ProgrammersGuide.tsx
Labels: frontend, experience, documentation

#6498 New receivers for Nevada
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0131-new-receivers-NV.yml
  prime-router/settings/staging/0131-new-receivers-NV.yml
Labels: onboarding-ops

#6433 Bump com.azure:azure-storage-blob@12.17.1 to 12.19.0 in /prime-router
  prime-router/build.gradle.kts
Labels: security, dependencies

#6554 Remove tabs from CompareFhirDataTests.kt to keep linter happy
  prime-router/src/test/kotlin/fhirengine/utils/CompareFhirDataTests.kt
Labels: pipeline

#6515 Bump jsoup from 1.14.2 to 1.15.3 in /prime-router
  prime-router/build.gradle.kts
Labels: security, dependencies

#6510 5754 Generate HL7 ORC segment from FHIR
  prime-router/metadata/hl7_mapping/ORU_R01/base/entity-identifier.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/order-observation.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/order.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/patient-contact.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/patient-visit.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/patient.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/timing-quantity.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/xcn-contact.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/xon-organization.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/xtn-telecom.yml
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
Labels: pipeline

#6455 Bump ca.uhn.hapi.fhir:hapi-fhir-structures-r4@6.0.3 to 6.1.0 in /prime-router
  prime-router/build.gradle.kts
Labels: security, dependencies

#5913 Adds logic to deidentify the patient age if over the age of 89
  prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
  prime-router/docs/schema_documentation/covid-19.md
  prime-router/docs/schema_documentation/direct-abbott-covid-19.md
  prime-router/docs/schema_documentation/direct-anavasidx-covid-19.md
  prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
  prime-router/docs/schema_documentation/direct-cue-covid-19.md
  prime-router/docs/schema_documentation/direct-direct-covid-19.md
  prime-router/docs/schema_documentation/direct-directlite-covid-19.md
  prime-router/docs/schema_documentation/direct-hca-covid-19.md
  prime-router/docs/schema_documentation/direct-ihealthlabs-covid-19.md
  prime-router/docs/schema_documentation/direct-imagemover-covid-19.md
  prime-router/docs/schema_documentation/direct-inbios-covid-19.md
  prime-router/docs/schema_documentation/direct-pmg-covid-19.md
  prime-router/docs/schema_documentation/direct-safehealth-covid-19.md
  prime-router/docs/schema_documentation/fl-fl-covid-19.md
  prime-router/docs/schema_documentation/gu-gu-covid-19.md
  prime-router/docs/schema_documentation/hhsprotect-hhsprotect-covid-19.md
  prime-router/docs/schema_documentation/hl7-detect-covid-19.md
  prime-router/docs/schema_documentation/hl7-hcintegrations-covid-19.md
  prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19-prod.md
  prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19-training.md
  prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19.md
  prime-router/docs/schema_documentation/hl7-lifepoint-covid-19.md
  prime-router/docs/schema_documentation/hl7-mns-covid-19.md
  prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
  prime-router/docs/schema_documentation/hl7-primary-covid-19.md
  prime-router/docs/schema_documentation/hl7-signetic-covid-19.md
  prime-router/docs/schema_documentation/hl7-test-covid-19.md
  prime-router/docs/schema_documentation/la-la-covid-19.md
  prime-router/docs/schema_documentation/mt-mt-covid-19.md
  prime-router/docs/schema_documentation/nd-nd-covid-19.md
  prime-router/docs/schema_documentation/nm-nm-covid-19.md
  prime-router/docs/schema_documentation/oh-oh-covid-19.md
  prime-router/docs/schema_documentation/or-or-covid-19-hl7.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
  prime-router/docs/schema_documentation/standard-standard-covid-19.md
  prime-router/docs/schema_documentation/tpca-tpca-covid-19.md
  prime-router/docs/schema_documentation/tx-tx-covid-19.md
  prime-router/docs/schema_documentation/vt-vt-covid-19.md
  prime-router/docs/schema_documentation/waters-waters-covid-19.md
  prime-router/metadata/schemas/covid-19.schema
  prime-router/src/main/kotlin/Report.kt
Labels: onboarding-ops

#6517 Implements table name into LookupTableApi calls
  frontend-react/src/hooks/UseLookupTable.ts
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
Labels: frontend, experience

#6596 update limasabc-nova to prod
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0132-limsabc-nova-to-prod.yml
  prime-router/settings/staging/0132-limsabc-nova-to-prod.yml
Labels: onboarding-ops

#6603 experience/fix-activate-call: send valueSet name to activate API call
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
Labels: experience
