Repository CDCgov/prime-reportstream, pull requests merged in 2022-12, with the labels that each got.

#7517 7277 Codified Error Messages
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.test.tsx
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx
  frontend-react/src/config/endpoints/waters.ts
  frontend-react/src/hooks/UseFileHandler.test.ts
  frontend-react/src/resources/ActionDetailsResource.ts
  frontend-react/src/resources/TestResponse.ts
  prime-router/src/main/kotlin/ActionLog.kt
  prime-router/src/main/kotlin/ActionMessages.kt
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/history/ReportHistory.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
Labels: frontend, experience

#7512 Fixed RI ELR messages failure
  prime-router/.swn
  prime-router/metadata/tables/livd/LIVD-Supplemental.csv
Labels: onboarding-ops, receiver

#7521 Fetch Refactor: Replace NewApi: Cleanup
  frontend-react/src/hooks/UseAdminSafeOrganizationName.test.ts
  frontend-react/src/hooks/UseAdminSafeOrganizationName.ts
  frontend-react/src/hooks/UseOrgName.ts
  frontend-react/src/hooks/UseOrganizationResource.ts
  frontend-react/src/hooks/network/History/DeliveryHooks.ts
  frontend-react/src/hooks/network/Organizations/ReceiversHooks.test.ts
  frontend-react/src/hooks/network/Organizations/ReceiversHooks.ts
  frontend-react/src/hooks/network/Organizations/__mocks__/ReceiversHooks.ts
  frontend-react/src/hooks/network/UseMemoizedConfig.ts
  frontend-react/src/hooks/network/UseRequestConfig.test.ts
  frontend-react/src/hooks/network/UseRequestConfig.ts
  frontend-react/src/network/api/NewApi.test.ts
  frontend-react/src/network/api/NewApi.ts
  frontend-react/src/network/api/Organizations/Receivers.ts
  frontend-react/src/network/api/OrganizationsApi.ts
  frontend-react/src/network/api/mocks/MockApi.ts
Labels: experience

#7477 Cle/7049 fhirpath resolver
  prime-router/metadata/tables/local/fhirpath_filter_shorthand.csv
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/metadata/LookupTable.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/DefaultFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/GetFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
  prime-router/src/test/resources/fhirengine/engine/routing/no_patient_state.fhir
  prime-router/src/test/resources/fhirengine/engine/routing/no_performer_state.fhir
Labels: pipeline

#7520 Turn React client errors into warnings for insights
  frontend-react/src/components/Table/TableFilters.tsx
  frontend-react/src/hooks/UseFileHandler.ts
  frontend-react/src/utils/DiffCompare/JsonSourceMap.ts
  frontend-react/src/utils/DiffCompare/TextDiffer.ts
  frontend-react/src/utils/SessionStorageTools.ts
  frontend-react/src/utils/misc.test.ts
  frontend-react/src/utils/misc.ts
Labels: experience

#7555 7301-Permissions/FeatureFlags at organization level.
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/Permission.kt
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/PermissionsFunctions.kt
  prime-router/src/main/resources/db/migration/V58__create_permissions_tables.sql
  prime-router/src/test/kotlin/azure/HttpTestUtils.kt
  prime-router/src/test/kotlin/azure/PermissionsFunctionsTests.kt
Labels: backend, experience

#7435 Convert @v* to @hash
  .github/actions/deploy-backend/action.yml
  .github/workflows/build_hub.yml
  .github/workflows/codeql.yml
Labels: github_actions

#7633 7301-Permissions/FeatureFlags at organization level. (Re-open)
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/Permission.kt
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/PermissionsFunctions.kt
  prime-router/src/main/resources/db/migration/V58__create_permissions_tables.sql
  prime-router/src/test/kotlin/azure/HttpTestUtils.kt
  prime-router/src/test/kotlin/azure/PermissionsFunctionsTests.kt
Labels: backend, experience

#7621 Add returns response error message to GAENTransport
  prime-router/src/main/kotlin/transport/GAENTransport.kt
  prime-router/src/testIntegration/kotlin/transport/GAENTransportIntegrationTests.kt
Labels: onboarding-ops

#7711 Send user to the correct details page
  frontend-react/src/components/MessageTracker/MessageTracker.tsx
Labels: experience

#7714 Attribution for SVG creative commons Map resource
  frontend-react/src/pages/home/Sections/LiveMapSection.tsx
  frontend-react/src/pages/product/legacy-page-content/WhereWereLive.tsx
Labels: experience

#7713 Experience 7448: Fix highlighting UX
  frontend-react/src/components/Admin/CompareJsonModal.test.tsx
  frontend-react/src/components/Admin/CompareJsonModal.tsx
  frontend-react/src/components/EditableCompare.tsx
Labels: experience

#7756 7561 Updates to HL7 to FHIR mappings for MSH segment
  prime-router/metadata/fhir_mapping/hl7/codesystem/CodingSystemMapping.yml
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Identifier_Gen.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Identifier_var.yml
  prime-router/metadata/fhir_mapping/hl7/extension/ExtensionMeta.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Device.yml
  prime-router/metadata/fhir_mapping/hl7/resource/MessageHeader.yml
  prime-router/metadata/fhir_mapping/hl7/resource/MessageSender.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Organization.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/Destination.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/Source.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/message-header.yml
  prime-router/metadata/hl7_mapping/STLTs/CO/CO.yml
  prime-router/metadata/tables/local/fhirpath_filter_shorthand.csv
  prime-router/src/main/kotlin/fhirengine/translation/HL7toFhirTranslator.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctions.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/ConstantResolverTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctionsTests.kt
  prime-router/src/test/resources/fhirengine/engine/valid_data.fhir
  prime-router/src/test/resources/fhirengine/engine/valid_data_testing_sender.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0006.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0014.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_2_20220803-0001.fhir
Labels: pipeline

#7777 Update release-notes.md
  frontend-react/src/content/product/release-notes.md
Labels: experience

#7768 Update bug template to use markdown headings
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: experience, documentation

#7780 Add new `USLink` components
  frontend-react/src/components/USLink.test.tsx
  frontend-react/src/components/USLink.tsx
Labels: experience, enhancement
