Repository CDCgov/prime-reportstream, pull requests merged in 2022-04, with the labels that each got.

#4984 Add Nevada to where we're live
  frontend-react/src/content/live.json
  frontend-react/src/content/usa_w_territories.svg
Labels: frontend, experience

#4978 Setting's meta data display support
  frontend-react/src/components/Admin/DisplayMeta.test.tsx
  frontend-react/src/components/Admin/DisplayMeta.tsx
  frontend-react/src/components/Admin/OrgReceiverTable.tsx
  frontend-react/src/components/Admin/OrgSenderTable.tsx
  frontend-react/src/pages/admin/AdminOrgEdit.tsx
  frontend-react/src/resources/OrgSettingsBaseResource.ts
  frontend-react/src/resources/TestResponse.ts
Labels: experience

#4991 Fixes the sender settings call on login
  frontend-react/src/App.tsx
  frontend-react/src/index.tsx
Labels: bug, frontend, experience

#4896 Removing reportingFacility from direct schema
  prime-router/docs/schema_documentation/direct-anavasidx-covid-19.md
  prime-router/docs/schema_documentation/direct-cue-covid-19.md
  prime-router/docs/schema_documentation/direct-direct-covid-19.md
  prime-router/docs/schema_documentation/direct-ihealthlabs-covid-19.md
  prime-router/docs/schema_documentation/direct-imagemover-covid-19.md
  prime-router/docs/schema_documentation/direct-inbios-covid-19.md
  prime-router/docs/schema_documentation/direct-pmg-covid-19.md
  prime-router/docs/schema_documentation/direct-safehealth-covid-19.md
  prime-router/docs/schema_documentation/direct-xtrava-covid-19.md
  prime-router/docs/schema_documentation/hhsprotect-hhsprotect-covid-19.md
  prime-router/metadata/schemas/direct/direct-covid-19.schema
Labels: onboarding-ops

#4902 Hide large tables on lookup table creation
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/cli/LivdTableDownload.kt
  prime-router/src/main/kotlin/cli/LookupTableCommands.kt
  prime-router/src/main/kotlin/metadata/LivdMappers.kt
Labels: pipeline

#4996 4990: Fix Fake Date Generator to generate correct HL7 value_type ID
  prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
  prime-router/docs/schema_documentation/covid-19.md
  prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
  prime-router/docs/schema_documentation/direct-hca-covid-19.md
  prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19.md
  prime-router/docs/schema_documentation/hl7-lifepoint-covid-19.md
  prime-router/docs/schema_documentation/hl7-mns-covid-19.md
  prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
  prime-router/docs/schema_documentation/hl7-primary-covid-19.md
  prime-router/docs/schema_documentation/hl7-test-covid-19.md
  prime-router/docs/schema_documentation/la-la-covid-19.md
  prime-router/docs/schema_documentation/mt-mt-covid-19.md
  prime-router/docs/schema_documentation/nm-nm-covid-19.md
  prime-router/docs/schema_documentation/or-or-covid-19-hl7.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
  prime-router/docs/schema_documentation/standard-standard-covid-19.md
  prime-router/docs/schema_documentation/tx-tx-covid-19.md
  prime-router/docs/schema_documentation/vt-vt-covid-19.md
  prime-router/metadata/schemas/covid-19.schema
  prime-router/src/main/kotlin/FakeReport.kt
Labels: onboarding-ops

#4892 Remove craco from build system
  frontend-react/.env.dev.csp
  frontend-react/.env.development
  frontend-react/.env.production
  frontend-react/.env.staging
  frontend-react/.env.test
  frontend-react/.gitignore
  frontend-react/README.md
  frontend-react/craco.config.js
  frontend-react/package.json
  frontend-react/public/index.html
  frontend-react/src/components/Admin/CompareJsonModal.tsx
  frontend-react/src/components/Admin/EditSenderSettings.test.tsx
  frontend-react/src/components/SenderModeBanner.test.tsx
  frontend-react/src/contexts/FilterContext.tsx
  frontend-react/src/contexts/SessionStorageContext.tsx
  frontend-react/src/global.scss
  frontend-react/src/index.tsx
  frontend-react/src/pages/error/ErrorPage.test.tsx
  frontend-react/src/pages/home/Home.test.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.test.tsx
  frontend-react/src/pages/submissions/SubmissionFilters.test.tsx
  frontend-react/src/pages/tos-sign/TermsOfServiceForm.test.tsx
  frontend-react/src/resources/AuthResource.ts
  frontend-react/src/resources/OrgSettingsResource.ts
  frontend-react/src/resources/SenderAuthResource.ts
  frontend-react/src/styles/_uswds_overrides.scss
  frontend-react/src/styles/_uswds_settings.scss
  frontend-react/yarn.lock
Labels: experience, tech-debt

#5036 OO/4786/Add new CSV for OTC Data Schema
  prime-router/docs/schema_documentation/csv-otc-covid-19.md
  prime-router/metadata/schemas/csv-otc-covid-19.schema
Labels: onboarding-ops

#5030 Onboarding Detect sender
  prime-router/docs/schema_documentation/hl7-detect-covid-19.md
  prime-router/metadata/schemas/HL7/detect-covid-19.schema
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0102-detect.yml
  prime-router/settings/staging/0102-detect.yml
Labels: onboarding-ops, HL7, sender

#5033 Latest updates and fix some backwards compatibility issues
  frontend-react/package.json
  frontend-react/src/components/OktaSignInWidget.jsx
  frontend-react/yarn.lock
Labels: experience, tech-debt

#5085 Provide delivery statistics before filtering, after filtering, and after sending.
  prime-router/docs/release-notes.md
  prime-router/examples/submission/README.md
  prime-router/examples/submission/example1-async-response.json
  prime-router/examples/submission/example2-sync-response.json
  prime-router/examples/submission/example3-complete-response.json
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/Submission.kt
  prime-router/src/main/kotlin/Translator.kt
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/DatabaseSubmissionsAccess.kt
  prime-router/src/main/kotlin/azure/SubmissionsFacade.kt
  prime-router/src/main/resources/db/migration/V44__more_delivery_statistics.sql
  prime-router/src/test/kotlin/SubmissionTests.kt
  prime-router/src/test/kotlin/TranslatorTests.kt
  prime-router/src/test/kotlin/azure/SendFunctionTests.kt
  prime-router/src/test/kotlin/azure/SenderFilesFunctionTests.kt
  prime-router/src/testIntegration/kotlin/transport/AS2TransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/TransportIntegrationTests.kt
Labels: pipeline, feature, release_notes

#5097 OO/rhood/5066/Add new Senders
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0106-desertoasishealthcare-ca.yml
  prime-router/settings/prod/0107-toprankdx-ca.yml
  prime-router/settings/prod/0108-bi2technologies.yml
  prime-router/settings/staging/0106-desertoasishealthcare-ca.yml
  prime-router/settings/staging/0107-toprankdx-ca.yml
  prime-router/settings/staging/0108-bi2technologies.yml
Labels: onboarding-ops

#5061 Remove unused packages as per depcheck
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: experience, tech-debt

#5019 Pre-release generator
  .github/actions/build-vars/action.yml
  .github/changelog_config.json
  .github/workflows/github_release.yaml
  DEPLOYMENTS.md
Labels: DevOps

#5046 Configurable Table component added
  frontend-react/src/__mocks__/OrganizationMockServer.ts
  frontend-react/src/components/Table/Table.test.tsx
  frontend-react/src/components/Table/Table.tsx
  frontend-react/src/components/Table/TestTable.tsx
  frontend-react/src/contexts/FilterContext.tsx
  frontend-react/src/hooks/UsePaginator.tsx
  frontend-react/src/hooks/filters/UseCursorManager.test.ts
  frontend-react/src/hooks/filters/UseCursorManager.ts
  frontend-react/src/hooks/filters/UseDateRange.test.ts
  frontend-react/src/hooks/filters/UseDateRange.ts
  frontend-react/src/hooks/filters/UseFilterManager.test.ts
  frontend-react/src/hooks/filters/UseFilterManager.ts
  frontend-react/src/hooks/filters/UsePageSize.test.ts
  frontend-react/src/hooks/filters/UsePageSize.ts
  frontend-react/src/hooks/filters/UseSortOrder.test.ts
  frontend-react/src/hooks/filters/UseSortOrder.ts
  frontend-react/src/pages/submissions/SubmissionFilters.test.tsx
  frontend-react/src/pages/submissions/SubmissionFilters.tsx
  frontend-react/src/pages/submissions/SubmissionTable.tsx
  frontend-react/src/pages/submissions/Submissions.tsx
Labels: frontend, experience

#5114 OO/rhood/5098/Add residence_type for COVID-19 results
  prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
  prime-router/docs/schema_documentation/covid-19.md
  prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
  prime-router/docs/schema_documentation/direct-hca-covid-19.md
  prime-router/docs/schema_documentation/hl7-detect-covid-19.md
  prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19.md
  prime-router/docs/schema_documentation/hl7-lifepoint-covid-19.md
  prime-router/docs/schema_documentation/hl7-mns-covid-19.md
  prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
  prime-router/docs/schema_documentation/hl7-primary-covid-19.md
  prime-router/docs/schema_documentation/hl7-test-covid-19.md
  prime-router/docs/schema_documentation/la-la-covid-19.md
  prime-router/docs/schema_documentation/mt-mt-covid-19.md
  prime-router/docs/schema_documentation/nm-nm-covid-19.md
  prime-router/docs/schema_documentation/or-or-covid-19-hl7.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
  prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
  prime-router/docs/schema_documentation/standard-standard-covid-19.md
  prime-router/docs/schema_documentation/tx-tx-covid-19.md
  prime-router/docs/schema_documentation/upload-covid-19.md
  prime-router/docs/schema_documentation/vt-vt-covid-19.md
  prime-router/docs/schema_documentation/waters-waters-covid-19.md
  prime-router/metadata/schemas/covid-19.schema
  prime-router/metadata/schemas/upload-covid-19.schema
  prime-router/metadata/valuesets/covid-19.valuesets
  prime-router/metadata/valuesets/sender-automation.valuesets
Labels: onboarding-ops

#4742 Cle/2024 dupe item hash
  prime-router/docs/openapi.yml
  prime-router/docs/proposals/0004-settings-api/openapi.yml
  prime-router/examples/submission/README.md
  prime-router/examples/submission/duplicate.csv
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/ActionLog.kt
  prime-router/src/main/kotlin/ActionMessages.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/Submission.kt
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/resources/db/migration/V46__item_hash.sql
  prime-router/src/main/resources/db/migration/V47__item_hash_index.sql
  prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
  prime-router/src/test/kotlin/azure/WorkflowEngineTests.kt
Labels: sender, feature, release_notes

#5149 update deploy doc
  DEPLOYMENTS.md
Labels: documentation

#5170 Add crumb component and implement on SubmissionDetails
  frontend-react/src/components/Crumbs.test.tsx
  frontend-react/src/components/Crumbs.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.test.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.tsx
  frontend-react/src/pages/submissions/SubmissionTable.tsx
Labels: frontend, experience

#5095 experience/4313: return more detailed error messages from the API, if available
  frontend-react/src/components/Admin/EditReceiverSettings.tsx
  frontend-react/src/components/Admin/EditSenderSettings.tsx
  frontend-react/src/components/Admin/NewSetting.tsx
  frontend-react/src/components/Table/Table.tsx
  frontend-react/src/pages/admin/AdminOrgEdit.tsx
  frontend-react/src/utils/TestUtils.ts
  frontend-react/src/utils/misc.test.ts
  frontend-react/src/utils/misc.ts
Labels: frontend, experience

#5163 4879: Need ability to override hl7 field with a hardcode value
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
Labels: onboarding-ops

#5151 Submission History QA fixes
  frontend-react/src/components/Table/Table.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.test.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.tsx
  frontend-react/src/pages/submissions/SubmissionFilters.tsx
  frontend-react/src/pages/submissions/SubmissionPages.css
Labels: frontend, experience

#5201 OO/rhood/5166 - Add new CSV Sender (Navus Health)
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0109-navushealth.yml
  prime-router/settings/staging/0109-navushealth.yml
Labels: onboarding-ops

#5203 5200 Allow processing of reports after a schema change
  prime-router/src/main/kotlin/azure/CovidResultMetaDataFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/cli/ProcessDataCommands.kt
  prime-router/src/main/kotlin/serializers/CsvSerializer.kt
  prime-router/src/test/kotlin/serializers/CsvSerializerTests.kt
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
Labels: pipeline

#5214 Experience/4325: guard against simultaneous setting edits
  frontend-react/src/components/Admin/CompareJsonModal.tsx
  frontend-react/src/components/Admin/EditReceiverSettings.tsx
  frontend-react/src/components/Admin/EditSenderSettings.tsx
  frontend-react/src/components/EditableCompare.tsx
  frontend-react/src/hooks/UseOrgName.ts
  frontend-react/src/pages/admin/AdminOrgEdit.tsx
  frontend-react/src/styles/_reportstream.scss
  frontend-react/src/utils/misc.test.ts
  frontend-react/src/utils/misc.ts
Labels: frontend, experience, javascript

#5204 Ascending Pagination on Table Component
  frontend-react/src/components/Table/Table.tsx
  frontend-react/src/components/Table/TableFilters.test.tsx
  frontend-react/src/components/Table/TableFilters.tsx
  frontend-react/src/components/Table/TestTable.tsx
  frontend-react/src/hooks/filters/UseCursorManager.test.ts
  frontend-react/src/hooks/filters/UseCursorManager.ts
  frontend-react/src/hooks/filters/UseDateRange.test.ts
  frontend-react/src/hooks/filters/UseDateRange.ts
  frontend-react/src/hooks/filters/UseFilterManager.test.ts
  frontend-react/src/hooks/filters/UseFilterManager.ts
  frontend-react/src/hooks/filters/UsePageSize.test.ts
  frontend-react/src/hooks/filters/UsePageSize.ts
  frontend-react/src/hooks/filters/UsePages.test.ts
  frontend-react/src/hooks/filters/UsePages.ts
  frontend-react/src/hooks/filters/UseSortOrder.test.ts
  frontend-react/src/hooks/filters/UseSortOrder.ts
  frontend-react/src/hooks/filters/mocks/MockCursorManager.ts
  frontend-react/src/hooks/filters/mocks/MockFilterManager.ts
  frontend-react/src/pages/submissions/SubmissionFilters.test.tsx
  frontend-react/src/pages/submissions/SubmissionTable.tsx
Labels: frontend, experience

#5228 Table readme with basic and advanced implementations
  frontend-react/src/components/Table/readme.md
Labels: frontend, experience, documentation

#5224 5067 Specify fields to ignore in HL7 compare
  prime-router/src/main/kotlin/cli/tests/CompareData.kt
  prime-router/src/test/kotlin/cli/tests/CompareDataTests.kt
Labels: pipeline

#5238 sync staging terraform with prod/test
  operations/app/terraform/modules/common/private_endpoint/data.tf
  operations/app/terraform/vars/prod/main.tf
  operations/app/terraform/vars/staging/data.tf
  operations/app/terraform/vars/staging/main.tf
  operations/app/terraform/vars/staging/secrets.tf
  operations/app/terraform/vars/staging/variables.tf
Labels: DevOps

#5241 Onboarding Healthcare Integrations
  prime-router/docs/schema_documentation/hl7-hcintegrations-covid-19.md
  prime-router/metadata/schemas/HL7/hcintegrations-covid-19.schema
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0109-hcintegrations.yml
  prime-router/settings/staging/0109-hcintegrations.yml
Labels: onboarding-ops, HL7, sender

#5247 Update terraform validation to work with overhaul
  .github/workflows/validate_terraform.yml
Labels: DevOps

#5057 Onbaording ops/oslynn/4016/fake data generator doesn not output facility names that match nces
  prime-router/src/main/kotlin/FakeReport.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/cli/ProcessDataCommands.kt
  prime-router/src/main/kotlin/common/Hl7Utilities.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/FakeReportTests.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
  prime-router/src/testIntegration/kotlin/FakeReportIntegrationTests.kt
Labels: onboarding-ops

#5291 Ensure the storage retention time is 60 days in prod/staging
  operations/README.md
  operations/app/terraform/modules/storage/candidate_slot.tf
  operations/app/terraform/modules/storage/main.tf
  operations/app/terraform/modules/storage/~inputs.tf
  operations/app/terraform/vars/prod/main.tf
  operations/app/terraform/vars/prod/variables.tf
  operations/app/terraform/vars/staging/main.tf
  operations/app/terraform/vars/staging/variables.tf
  operations/app/terraform/vars/test/main.tf
  operations/app/terraform/vars/test/variables.tf
Labels: DevOps

#5302 5301 Readded version metadata to settings API
  prime-router/src/main/kotlin/Organization.kt
  prime-router/src/main/kotlin/Sender.kt
  prime-router/src/main/kotlin/azure/SettingsFacade.kt
Labels: pipeline

#5320 TF sticky settings and hook
  .environment/terraform-fmt/run-terraform-fmt.sh
  .github/workflows/validate_terraform.yml
  .vscode/settings.json
  operations/app/terraform/modules/application_insights/main.tf
  operations/app/terraform/modules/application_insights/metabase.tf
  operations/app/terraform/modules/function_app/candidate_slot.tf
  operations/app/terraform/modules/function_app/main.tf
  operations/app/terraform/vars/dev/azure.tf
  operations/app/terraform/vars/prod/azure.tf
  operations/app/terraform/vars/prod/main.tf
  operations/app/terraform/vars/staging/azure.tf
  operations/app/terraform/vars/test/azure.tf
  prime-router/docs/getting-started/getting-started.md
Labels: DevOps

#5325 Updated rule alert to match prod. metric_column required
  .environment/terraform-fmt/run-terraform-fmt.sh
  operations/app/terraform/modules/application_insights/alert_response_time.tf
Labels: DevOps
