Repository CDCgov/prime-reportstream, pull requests merged in 2022-02, with the labels that each got.

#4072 4064 History function token validation errors not log exceptions
  prime-router/src/main/kotlin/azure/HistoryFunctions.kt
Labels: pipeline

#4048 4045 Order mappers based on their dependencies
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/Schema.kt
  prime-router/src/main/kotlin/serializers/CsvSerializer.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/SchemaTests.kt
Labels: pipeline

#4116 4113 Merged release notes into one file
  prime-router/README.md
  prime-router/docs/release-notes.md
  prime-router/docs/releases/2020-12-29-release-notes.md
  prime-router/docs/releases/2021-01-07-release-notes.md
  prime-router/docs/releases/2021-01-12-release-notes.md
  prime-router/docs/releases/2021-02-04-release-notes.md
  prime-router/docs/releases/2021-02-12-release-notes.md
  prime-router/docs/releases/2021-03-15-release-notes.md
  prime-router/docs/releases/2021-04-26-release-notes.md
  prime-router/docs/releases/2021-05-12-release-notes.md
  prime-router/docs/releases/2021-05-27-release-notes.md
  prime-router/docs/releases/2021-06-01-release-notes.md
  prime-router/docs/releases/2021-06-07-release-notes.md
  prime-router/docs/releases/2021-06-14-release-notes.md
  prime-router/docs/releases/2021-06-25-release-notes.md
  prime-router/docs/releases/2021-07-07-release-notes.md
  prime-router/docs/releases/2021-07-26-release-notes.md
  prime-router/docs/releases/2021-08-03-release-notes.md
  prime-router/docs/releases/2021-08-10-release-notes.md
  prime-router/docs/releases/2021-08-17-release-notes.md
  prime-router/docs/releases/2021-08-24-release-notes.md
  prime-router/docs/releases/2021-09-08-release-notes.md
  prime-router/docs/releases/2021-10-19-release-notes.md
  prime-router/docs/releases/2021-11-04-release-notes.md
  prime-router/docs/releases/2021-11-18-release-notes.md
  prime-router/docs/releases/2021-12-12-release-notes.md
  prime-router/docs/releases/2022-01-10-release-notes.md
  prime-router/docs/releases/2022-01-28-release-notes.md
Labels: pipeline

#4141 OO/rhood/4106/CSV Uploader - Set processing mode from settings table AND added DATETIME
  prime-router/docs/schema_documentation/upload-covid-19.md
  prime-router/metadata/schemas/upload-covid-19.schema
Labels: onboarding-ops

#4188 Fix batch decider unit test
  prime-router/src/main/kotlin/azure/BatchDeciderFunction.kt
  prime-router/src/test/kotlin/azure/BatchDeciderTests.kt
Labels: pipeline

#4164 Addition to 2054: Added unit tests to cover more of the LIVD mapper apply logic
  prime-router/src/main/kotlin/metadata/LivdMappers.kt
  prime-router/src/test/kotlin/metadata/LivdMapperTests.kt
Labels: pipeline

#4176 OC Rapid Test in CA - Add as a new CSV Sender
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0073-ocrapidtest-ca.yml
  prime-router/settings/staging/0073-ocrapidtest-ca.yml
Labels: onboarding-ops

#4168 OO/rhood/4166/Core Bio Labs as a CSV Sender
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0072-corebiolabs-oh.yml
  prime-router/settings/staging/0072-corebiolabs-oh.yml
Labels: onboarding-ops

#4203 3974: Fixed Bug-Qualityfilter Smoke Test Fails when runs in async mode
  prime-router/src/main/kotlin/cli/tests/BasicTests.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
Labels: pipeline

#4207 OO/rhood/4205 - Warrior Diagnostics - Add as new CSV User
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0074-warrior-dx-co.yml
  prime-router/settings/staging/0074-warrior-dx-co.yml
Labels: onboarding-ops

#4036 4009: Added unit test cases for Element checkForError and toNormalize…
  prime-router/src/test/kotlin/ElementTests.kt
Labels: pipeline

#4172 4003: Testing uses CLI not work with the new CSV uploader schema
  prime-router/src/main/kotlin/cli/ProcessDataCommands.kt
  prime-router/src/main/kotlin/serializers/CsvSerializer.kt
Labels: pipeline

#4221 Bugfix: Show topnav even if there's a network error or server is down.
  frontend-react/src/components/header/ReportStreamHeader.tsx
Labels: frontend, experience

#4237 OO/rhood/4219-Update CSV Schema with Reporting Facility and Patient Primary Language.
  prime-router/docs/schema_documentation/upload-covid-19.md
  prime-router/metadata/schemas/upload-covid-19.schema
Labels: onboarding-ops

#4239 Add link to RS programmers guide .doc
  frontend-react/src/pages/getting-started/testing-facilities/Overview.tsx
Labels: frontend, content

#4187 4186 Perform validation of elements in metadata catalog
  prime-router/docs/schema_documentation/az-az-ihs-covid-19.md
  prime-router/docs/schema_documentation/co-co-covid-19-redox.md
  prime-router/docs/schema_documentation/covid-19-redox.md
  prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
  prime-router/docs/schema_documentation/experity-experity-covid-19.md
  prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
  prime-router/docs/schema_documentation/nm-nm-covid-19-csv.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-redox.md
  prime-router/docs/schema_documentation/sample-fed1-sample.md
  prime-router/docs/schema_documentation/sample-phd1-sample.md
  prime-router/docs/schema_documentation/sample-phd2-sample.md
  prime-router/docs/schema_documentation/strac-strac-covid-19.md
  prime-router/docs/schema_documentation/tpca-tpca-covid-19.md
  prime-router/metadata/schemas/AZ/az-ihs-covid-19.schema
  prime-router/metadata/schemas/Experity/experity-covid-19.schema
  prime-router/metadata/schemas/NM/nm-covid-19-csv.schema
  prime-router/metadata/schemas/STRAC/strac-covid-19.schema
  prime-router/metadata/schemas/TPCA/tpca-covid-19.schema
  prime-router/metadata/schemas/covid-19-redox.schema
  prime-router/metadata/schemas/sample/fed1-sample.schema
  prime-router/metadata/schemas/sample/phd1-sample.schema
  prime-router/metadata/schemas/sample/phd2-sample.schema
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/Schema.kt
  prime-router/src/test/kotlin/ElementTests.kt
  prime-router/src/test/kotlin/MetadataTests.kt
  prime-router/src/test/kotlin/serializers/CsvSerializerTests.kt
Labels: pipeline

#4254 Add logic to strip the special char for PA
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0076-add-invalid-char-stripping-for-pa.yml
  prime-router/settings/staging/0076-add-invalid-char-stripping-for-pa.yml
  prime-router/src/main/kotlin/TranslatorConfiguration.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/unit_test_files/bad-character-replacements.csv
  prime-router/src/testIntegration/kotlin/serializers/Hl7SerializerIntegrationTests.kt
Labels: onboarding-ops

#4253 lint/prettier tool wasn't really working on all files
  frontend-react/package.json
Labels: bug, experience, tech-debt

#4229 4013: Fixed Fake Data Generator does not output valid site_of_care va…
  prime-router/src/main/kotlin/FakeReport.kt
Labels: onboarding-ops

#4278 OO/rhood/4277-Add Covid Clinic and Stemexpress as New CSV Senders
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0077-covidclinic-org.yml
  prime-router/settings/prod/0078-stemexpress-ca.yml
  prime-router/settings/prod/0079-hollywoodsmiles-ca.yml
  prime-router/settings/staging/0077-covidclinic-org.yml
  prime-router/settings/staging/0078-stemexpress-ca.yml
  prime-router/settings/staging/0079-hollywoodsmiles-ca.yml
Labels: backend

#4289 replaced LAW data sources with resource wiring where possible
  .vscode/settings.json
  operations/app/terraform/modules/container_registry/~outputs.tf
  operations/app/terraform/modules/front_door/~outputs.tf
  operations/app/terraform/modules/function_app/~inputs.tf
  operations/app/terraform/modules/function_app/~outputs.tf
  operations/app/terraform/modules/key_vault/main.tf
  operations/app/terraform/modules/key_vault/~inputs.tf
  operations/app/terraform/modules/key_vault/~outputs.tf
  operations/app/terraform/modules/log_analytics_workspace/data.tf
  operations/app/terraform/modules/log_analytics_workspace/main.tf
  operations/app/terraform/modules/log_analytics_workspace/~inputs.tf
  operations/app/terraform/modules/log_analytics_workspace/~outputs.tf
  operations/app/terraform/modules/nat_gateway/~outputs.tf
  operations/app/terraform/modules/storage/candidate_slot.tf
  operations/app/terraform/modules/storage/main.tf
  operations/app/terraform/modules/storage/~inputs.tf
  operations/app/terraform/modules/storage/~outputs.tf
  operations/app/terraform/modules/vnet/data.tf
  operations/app/terraform/modules/vnet/~outputs.tf
  operations/app/terraform/vars/test/main.tf
  operations/app/terraform/vars/test/variables.tf
Labels: DevOps

#4235 Kevinhaube/submissions details
  frontend-react/src/App.tsx
  frontend-react/src/pages/daily/Table/ReportLink.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.test.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.tsx
  frontend-react/src/pages/submissions/SubmissionsTable.tsx
  frontend-react/src/resources/ActionDetailsResource.ts
  frontend-react/src/resources/TestResponse.ts
  frontend-react/src/utils/CustomRenderUtils.tsx
  frontend-react/src/utils/DateTimeUtils.test.ts
  frontend-react/src/utils/DateTimeUtils.ts
  frontend-react/yarn.lock
Labels: frontend, experience

#4274 Onboarding ops/3520/redox be gone
  .github/workflows/build_hub.yml
  prime-router/build.gradle.kts
  prime-router/cleanslate.sh
  prime-router/devenv-infrastructure.sh
  prime-router/docker-compose.yml
  prime-router/docs/getting-started/Using-an-apple-silicon-mac.md
  prime-router/docs/getting_started.md
  prime-router/docs/openapi.yml
  prime-router/docs/playbooks/how-retry-mechanisms-work.md
  prime-router/docs/proposals/0003-lineage/README.md
  prime-router/docs/proposals/0003-lineage/additional-notes.md
  prime-router/docs/proposals/0004-settings-api/openapi.yml
  prime-router/docs/proposals/0005-api-hardening.md
  prime-router/docs/proposals/0010-translations-and-schemas/0010-translations-and-schemas.md
  prime-router/docs/schema_documentation/co-co-covid-19-redox.md
  prime-router/docs/schema_documentation/covid-19-redox.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-redox.md
  prime-router/end-to-end-test.sh
  prime-router/metadata/schemas/CO/co-covid-19-redox.schema
  prime-router/metadata/schemas/PA/pa-covid-19-redox.schema
  prime-router/metadata/schemas/STRAC/strac-covid-19.schema
  prime-router/metadata/schemas/covid-19-redox.schema
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0000-organizations.yml
  prime-router/settings/prod/0002-pa-philadelphia.yml
  prime-router/settings/prod/0006-pa-phd-add-batch-timings.yml
  prime-router/settings/prod/0013-co-phd.yml
  prime-router/settings/prod/0025-update-pa-allegheny.yml
  prime-router/settings/staging/0000-organizations.yml
  prime-router/settings/staging/0015-update-pa-allegheny.yml
  prime-router/settings/staging/0024-ignore.yml
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/TranslatorConfiguration.kt
  prime-router/src/main/kotlin/TransportType.kt
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/main/kotlin/azure/RequeueFunction.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/cli/FileUtilities.kt
  prime-router/src/main/kotlin/cli/ProcessDataCommands.kt
  prime-router/src/main/kotlin/cli/tests/BasicTests.kt
  prime-router/src/main/kotlin/cli/tests/Hl7Tests.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/serializers/RedoxSerializer.kt
  prime-router/src/main/kotlin/transport/RedoxTransport.kt
  prime-router/src/main/resources/clitests/compare-test-files/test-0001-input-covid-19.hl7
  prime-router/src/main/resources/db/migration/V35__remove_redox_transport.sql
  prime-router/src/main/resources/log4j2.xml
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/tokens/JwkTests.kt
  prime-router/src/test/kotlin/transport/RedoxTransportTests.kt
  prime-router/src/test/redox/initializerJson.json
  prime-router/src/test/redox/mockserver.properties
  prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-batch-pdi-20210608-0001.csv
Labels: pipeline

#4297 update release note categories to account for common commit titles
  .github/changelog_config.json
Labels: DevOps

#4285 O Canada
  prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
  prime-router/docs/schema_documentation/covid-19.md
  prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
  prime-router/docs/schema_documentation/direct-hca-covid-19.md
  prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19.md
  prime-router/docs/schema_documentation/hl7-lifepoint-covid-19.md
  prime-router/docs/schema_documentation/hl7-mns-covid-19.md
  prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
  prime-router/docs/schema_documentation/hl7-primary-covid-19.md
  prime-router/docs/schema_documentation/hl7-test-covid-19.md
  prime-router/docs/schema_documentation/la-la-covid-19.md
  prime-router/docs/schema_documentation/mt-mt-covid-19.md
  prime-router/docs/schema_documentation/nm-nm-covid-19.md
  prime-router/docs/schema_documentation/or-or-covid-19-hl7.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
  prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
  prime-router/docs/schema_documentation/standard-standard-covid-19.md
  prime-router/docs/schema_documentation/tx-tx-covid-19.md
  prime-router/docs/schema_documentation/vt-vt-covid-19.md
  prime-router/metadata/schemas/PrimeDataInput/pdi-covid-19.schema
  prime-router/metadata/schemas/covid-19.schema
  prime-router/metadata/valuesets/iso.valuesets
  prime-router/src/main/kotlin/FakeReport.kt
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/ValueSet.kt
  prime-router/src/main/kotlin/metadata/Mappers.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/metadata/MapperTests.kt
Labels: onboarding-ops

#3625 Updates our local dev SFTP server to include public key auth clients so we can verify any errors when updating SSHJ
  .environment/gitleaks/gitleaks-config.toml
  .environment/sftp-conf/README.md
  .environment/sftp-conf/ignore-putty-file-old
  .environment/sftp-conf/ignore-putty-file-old-openssh.pub
  .environment/sftp-conf/ssh_dev_rsa_key
  .environment/sftp-conf/ssh_dev_rsa_key.pem
  .environment/sftp-conf/ssh_dev_rsa_key.pem.pub
  .environment/sftp-conf/ssh_host_ed25519_key
  .environment/sftp-conf/ssh_host_ed25519_key.pub
  .environment/sftp-conf/ssh_host_rsa_key
  .environment/sftp-conf/ssh_host_rsa_key.pub
  .environment/sftp-conf/users.conf
  prime-router/docker-compose.yml
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/transport/SftpTransport.kt
Labels: onboarding-ops, security, dependencies

#4331 Replace `spinners-react` with `react-loader-spinner`
  frontend-react/package.json
  frontend-react/src/components/Spinner.tsx
  frontend-react/yarn.lock
Labels: bug, frontend

#4319 Expose Submissions pages to Senders
  frontend-react/src/App.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
Labels: frontend, experience

#3410 Adds organization name to metadata table
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/resources/db/migration/V38__add_organization_name_to_metadata_table.sql
Labels: onboarding-ops

#3442 3160 Ack proposal
  prime-router/docs/proposals/0013-Ack/0013-ack-continued.md
  prime-router/docs/proposals/0013-Ack/ack_data_flow.png
  prime-router/docs/proposals/0013-Ack/db_changes.png
Labels: onboarding-ops, HL7, pipeline

#4370 fixes #4369 increase release retention
  .github/workflows/github_release.yaml
Labels: DevOps

#4290 #4210 Notify FHIREngine of incoming HL7 messages for testing
  prime-router/docker-compose.yml
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/main/kotlin/azure/CovidResultMetaDataFunction.kt
  prime-router/src/main/kotlin/azure/FHIRFlowFunctions.kt
  prime-router/src/main/kotlin/azure/ProcessFunction.kt
  prime-router/src/main/kotlin/azure/QueueAccess.kt
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/azure/SenderFilesFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/cli/tests/CompareData.kt
  prime-router/src/main/kotlin/common/Environment.kt
  prime-router/src/main/kotlin/engine/Message.kt
  prime-router/src/main/kotlin/transport/BlobStoreTransport.kt
  prime-router/src/main/resources/log4j2.xml
  prime-router/src/test/kotlin/azure/FHIRFlowFunctionsTests.kt
  prime-router/src/test/kotlin/azure/SenderFilesFunctionTests.kt
  prime-router/src/test/kotlin/azure/WorkflowEngineTests.kt
Labels: pipeline, fhir

#4389 Fixes language error for SimpleReport
  prime-router/docs/release-notes.md
  prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
  prime-router/metadata/schemas/PrimeDataInput/pdi-covid-19.schema
Labels: onboarding-ops

#4394 OO/rhood/4374 - Change ocrapidtest-ca to newport-childrens-hospital-ca. Add 2 new Senders
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0080-newport-childrens-hospital-ca.yml
  prime-router/settings/prod/0081-elitemedlabs-co.yml
  prime-router/settings/prod/0082-youthclinic-co.yml
  prime-router/settings/staging/0080-newport-childrens-hospital-ca.yml
  prime-router/settings/staging/0081-elitemedlabs-co.yml
  prime-router/settings/staging/0082-youthclinic-co.yml
Labels: onboarding-ops

#4379 update `follow-redirect`
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: experience, tech-debt

#4388 Quick and dirty combining Org picking
  frontend-react/src/components/Admin/OrgSettingsTable.tsx
  frontend-react/src/components/Admin/OrgsTable.tsx
  frontend-react/src/components/header/OrgDropdown.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/pages/admin/AdminMain.tsx
Labels: experience

#4400 Updating receivers to smaller batch size
  prime-router/settings/prod/0080-max-batch-size-100.yml
  prime-router/settings/staging/0080-max-batch-size-100.yml
  prime-router/src/main/kotlin/Receiver.kt
Labels: onboarding-ops

#4276 oktapreview migration
  frontend-react/.env.development
  frontend-react/.env.production
  frontend-react/.env.staging
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/components/header/SignInOrUser.tsx
  frontend-react/src/oktaConfig.ts
  frontend-react/src/styles/_reportstream.scss
  prime-router/docker-compose.yml
  prime-router/docs/getting-started/Using-an-apple-silicon-mac.md
  prime-router/src/main/kotlin/cli/OktaCommands.kt
  prime-router/src/main/kotlin/common/Environment.kt
Labels: backend, DevOps, frontend

#4423 Prime admin bug fix.
  frontend-react/src/components/Admin/OrgsTable.tsx
Labels: bug, experience

#4412 4193: Setting API update org validation treats empty string as potent…
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/azure/SettingsFacade.kt
  prime-router/src/main/kotlin/common/StringUtilities.kt
Labels: onboarding-ops

#4418 Support single digit hour in date times
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/test/kotlin/ElementTests.kt
Labels: pipeline

#4416 Adds higher precision header date time values for HL7 in the FHS and BHS segments
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0083-update-il-batch-header-precision.yml
  prime-router/settings/staging/0083-update-il-batch-header-precision.yml
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/TranslatorConfiguration.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
Labels: onboarding-ops

#4441 OO/rhood/4439 - Add cardinality: ONE to multiple fields in the A1H schema
  prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
  prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema
Labels: onboarding-ops

#4363 Adds a materialized view for LIVD table and functionality to keep it fresh
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/DatabaseLookupTableAccess.kt
  prime-router/src/main/resources/db/migration/V39__add_livd_materialized_view.sql
Labels: onboarding-ops

#4446 Onboarding ops/4445/add additional languages to iso639
  prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
  prime-router/docs/schema_documentation/covid-19.md
  prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
  prime-router/docs/schema_documentation/direct-hca-covid-19.md
  prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19.md
  prime-router/docs/schema_documentation/hl7-lifepoint-covid-19.md
  prime-router/docs/schema_documentation/hl7-mns-covid-19.md
  prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
  prime-router/docs/schema_documentation/hl7-primary-covid-19.md
  prime-router/docs/schema_documentation/hl7-test-covid-19.md
  prime-router/docs/schema_documentation/la-la-covid-19.md
  prime-router/docs/schema_documentation/mt-mt-covid-19.md
  prime-router/docs/schema_documentation/nm-nm-covid-19.md
  prime-router/docs/schema_documentation/or-or-covid-19-hl7.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
  prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
  prime-router/docs/schema_documentation/standard-standard-covid-19.md
  prime-router/docs/schema_documentation/tx-tx-covid-19.md
  prime-router/docs/schema_documentation/vt-vt-covid-19.md
  prime-router/metadata/valuesets/iso.valuesets
Labels: onboarding-ops, Enhancement

#4473 experience/4293: workaround inconsistencies in API for writing blank JSON settings
  frontend-react/src/components/Admin/AdminFormEdit.tsx
  frontend-react/src/components/Admin/EditReceiverSettings.tsx
  frontend-react/src/components/Admin/NewSetting.tsx
  frontend-react/src/pages/admin/AdminOrgEdit.tsx
Labels: bug, frontend, experience

#4481 OO/rhood/4467/Add the latest ISO639 updates to sender-automation.valuesets
  prime-router/docs/schema_documentation/upload-covid-19.md
  prime-router/metadata/valuesets/sender-automation.valuesets
Labels: good-first-issue

#4430 React Network Layer: Hooks and APIs
  frontend-react/docs/rs-react-networking.md
  frontend-react/docs/rs-react-testing-network-calls.md
  frontend-react/package.json
  frontend-react/src/__mocks__/HistoryMockServer.ts
  frontend-react/src/components/__mocks__/GlobalContextProvider.tsx
  frontend-react/src/network/api/Api.test.ts
  frontend-react/src/network/api/Api.ts
  frontend-react/src/network/api/History.test.ts
  frontend-react/src/network/api/History.ts
  frontend-react/src/network/hooks/useNetwork.test.ts
  frontend-react/src/network/hooks/useNetwork.ts
  frontend-react/yarn.lock
Labels: experience

#4398 Conditionally show filename in title of details page
  frontend-react/src/pages/submissions/SubmissionDetails.test.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.tsx
  frontend-react/src/utils/DateTimeUtils.test.ts
  frontend-react/src/utils/DateTimeUtils.ts
Labels: frontend, experience

#4493 OO/rhood/4490 - Move CSV Sender SDI Labs to PROD
  prime-router/settings/prod/0070-sdilabs-ca.yml
Labels: onboarding-ops

#4475 4241 Update Submissions API response to match reports API
  .environment/ktlint/run-ktlintCheck.sh
  prime-router/src/main/kotlin/Submission.kt
Labels: pipeline

#4526 Fixing date parsing for Submissions pages
  frontend-react/package.json
  frontend-react/src/pages/submissions/SubmissionDetails.test.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.tsx
  frontend-react/src/utils/DateTimeUtils.test.ts
  frontend-react/src/utils/DateTimeUtils.ts
  frontend-react/yarn.lock
Labels: bug, frontend, experience

#4543 Updated LIVD table with the latest from production
  prime-router/metadata/tables/local/LIVD-SARS-CoV-2.csv
Labels: pipeline

#4545 Update url-parse
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: experience, tech-debt

#4530 Submissions API: sortCol query param
  prime-router/src/main/kotlin/azure/DatabaseSubmissionsAccess.kt
  prime-router/src/main/kotlin/azure/SubmissionFunction.kt
  prime-router/src/main/kotlin/azure/SubmissionsFacade.kt
  prime-router/src/test/kotlin/azure/SubmissionFunctionTests.kt
Labels: backend, experience

#4558 Updating Cue schema for Eurofins data
  prime-router/docs/schema_documentation/direct-cue-covid-19.md
  prime-router/metadata/schemas/direct/cue-covid-19.schema
Labels: onboarding-ops, sender

#4556 OO/rhood/4468/Sync LIVD specimen types to our valuesets
  prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
  prime-router/docs/schema_documentation/az-az-covid-19.md
  prime-router/docs/schema_documentation/az-az-ihs-covid-19.md
  prime-router/docs/schema_documentation/az-pima-az-covid-19.md
  prime-router/docs/schema_documentation/ca-ca-scc-covid-19.md
  prime-router/docs/schema_documentation/covid-19.md
  prime-router/docs/schema_documentation/direct-abbott-covid-19.md
  prime-router/docs/schema_documentation/direct-anavasidx-covid-19.md
  prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
  prime-router/docs/schema_documentation/direct-cue-covid-19.md
  prime-router/docs/schema_documentation/direct-direct-covid-19.md
  prime-router/docs/schema_documentation/direct-directlite-covid-19.md
  prime-router/docs/schema_documentation/direct-hca-covid-19.md
  prime-router/docs/schema_documentation/direct-ihealthlabs-covid-19.md
  prime-router/docs/schema_documentation/direct-imagemover-covid-19.md
  prime-router/docs/schema_documentation/direct-inbios-covid-19.md
  prime-router/docs/schema_documentation/direct-pmg-covid-19.md
  prime-router/docs/schema_documentation/direct-safehealth-covid-19.md
  prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
  prime-router/docs/schema_documentation/experity-experity-covid-19.md
  prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
  prime-router/docs/schema_documentation/fl-fl-covid-19.md
  prime-router/docs/schema_documentation/fl-fl-hillsborough-covid-19-csv.md
  prime-router/docs/schema_documentation/gu-gu-covid-19.md
  prime-router/docs/schema_documentation/hhsprotect-hhsprotect-covid-19.md
  prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19.md
  prime-router/docs/schema_documentation/hl7-lifepoint-covid-19.md
  prime-router/docs/schema_documentation/hl7-mns-covid-19.md
  prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
  prime-router/docs/schema_documentation/hl7-primary-covid-19.md
  prime-router/docs/schema_documentation/hl7-test-covid-19.md
  prime-router/docs/schema_documentation/ipatientcare-ipatientcare-covid-19.md
  prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
  prime-router/docs/schema_documentation/la-la-covid-19.md
  prime-router/docs/schema_documentation/mt-mt-covid-19-csv.md
  prime-router/docs/schema_documentation/mt-mt-covid-19.md
  prime-router/docs/schema_documentation/nd-nd-covid-19.md
  prime-router/docs/schema_documentation/nm-nm-covid-19-csv.md
  prime-router/docs/schema_documentation/nm-nm-covid-19.md
  prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
  prime-router/docs/schema_documentation/oh-oh-clark-covid-19-csv.md
  prime-router/docs/schema_documentation/oh-oh-covid-19.md
  prime-router/docs/schema_documentation/or-or-covid-19-hl7.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
  prime-router/docs/schema_documentation/pa-pa-covid-19.md
  prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
  prime-router/docs/schema_documentation/standard-standard-covid-19.md
  prime-router/docs/schema_documentation/strac-strac-covid-19.md
  prime-router/docs/schema_documentation/tx-tx-covid-19.md
  prime-router/docs/schema_documentation/upload-covid-19.md
  prime-router/docs/schema_documentation/vt-vt-covid-19.md
  prime-router/docs/schema_documentation/waters-waters-covid-19.md
  prime-router/metadata/valuesets/covid-19.valuesets
  prime-router/metadata/valuesets/sender-automation.valuesets
  prime-router/settings/prod/0068-cadph-csvuploadertest.yml
  prime-router/settings/prod/0071-cdphe-csvuploader.yml
  prime-router/settings/staging/0068-cadph-csvuploadertest.yml
  prime-router/settings/staging/0071-cdphe-csvuploader.yml
Labels: onboarding-ops

#4529 Global truncation for OBR-16.3 and ORC-12.3 to 30 characters
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0085-update-ca-dph-truncate-obr-16-3-orc-12-3.yml
  prime-router/settings/staging/0085-update-ca-dph-truncate-obr-16-3-orc-12-3.yml
Labels: onboarding-ops

#4537 4309 Submission History API always shows external name property
  prime-router/build.gradle.kts
  prime-router/docs/getting-started/Using-an-apple-silicon-mac.md
  prime-router/docs/getting-started/faster-development.md
  prime-router/src/main/kotlin/Submission.kt
Labels: pipeline

#4479 4019: IL - ORC-21-1 truncate org name to 50 chars
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0084-update-il-phd.yml
  prime-router/settings/staging/0084-update-il-phd.yml
Labels: onboarding-ops

#4535 Adding onboarding doc for county receivers
  prime-router/docs/assets/playbook-add-county-receiver/Screen Shot 2022-02-24 at 10.47.49 AM.png
  prime-router/docs/assets/playbook-add-county-receiver/Screen Shot 2022-02-24 at 10.47.57 AM.png
  prime-router/docs/assets/playbook-add-county-receiver/Screen Shot 2022-02-24 at 10.48.34 AM.png
  prime-router/docs/playbooks/how-to-onboard-county-receiver.md
Labels: onboarding-ops, documentation

#4561 Updates IL delivery cadence
  prime-router/settings/prod/0085-update-il-delivery-cadence.yml
Labels: onboarding-ops

#4521 Add Routt County and San Juan Basin PHDs
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0084-add-routt-county-phd.yml
  prime-router/settings/prod/0085-add-san-juan-basin-phd.yml
  prime-router/settings/staging/0084-add-routt-county-phd.yml
  prime-router/settings/staging/0085-add-san-juan-basin-phd.yml
Labels: onboarding-ops
