Repository CDCgov/prime-reportstream, pull requests merged in 2022-01, with the labels that each got.

#3626 OO/3508 Build standard csv schema
  prime-router/docs/schema_documentation/upload-covid-19.md
  prime-router/metadata/schemas/upload-covid-19.schema
  prime-router/metadata/valuesets/sender-automation.valuesets
  prime-router/settings/organizations.yml
  prime-router/settings/staging/0059-manualupload.yml
Labels: onboarding-ops, High Priority, experience

#3651 OO/3645-A1H All Date Fields - Set cardinality and nullifyValue
  prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
  prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema
Labels: onboarding-ops, experience

#3464 Mapper and table added for npi lookups
  prime-router/src/main/kotlin/Mappers.kt
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/test/kotlin/MapperTests.kt
  prime-router/src/test/resources/metadata/tables/npi-lookup.csv
Labels: experience

#3655 Adds trimming to the formatting and normalizing methods
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/serializers/CsvSerializer.kt
  prime-router/src/test/kotlin/ElementTests.kt
Labels: onboarding-ops

#3704 fixes #1048 replace release body
  .github/workflows/github_release.yaml
Labels: DevOps

#3659 Proposal draft for React app permissions
  frontend-react/docs/proposals/permissions_layer_proposal.md
Labels: experience, tech-debt

#3699 3579 & 3580 Allow mapper to provide errors and warnings
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/ElementErrors.kt
  prime-router/src/main/kotlin/FakeReport.kt
  prime-router/src/main/kotlin/Mappers.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/ResponseMessage.kt
  prime-router/src/main/kotlin/cli/SettingCommands.kt
  prime-router/src/main/kotlin/cli/tests/BasicTests.kt
  prime-router/src/main/kotlin/cli/tests/HistoryApiTest.kt
  prime-router/src/main/kotlin/serializers/CsvSerializer.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/ElementTests.kt
  prime-router/src/test/kotlin/MapperTests.kt
  prime-router/src/testIntegration/kotlin/SimpleReportIntegrationTests.kt
  prime-router/start_func.sh
Labels: pipeline

#3697 Add flag to swap positive offset to negative offset for UTC date time
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/TranslatorConfiguration.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/ElementTests.kt
Labels: onboarding-ops

#3741 3728 Allow fields that can be blank to have mappers
  prime-router/src/main/kotlin/Metadata.kt
Labels: pipeline

#3683 3383: PRIME CLI Updates changed lookup tables
  prime-router/src/main/kotlin/azure/DatabaseLookupTableAccess.kt
  prime-router/src/main/kotlin/azure/HttpUtilities.kt
  prime-router/src/main/kotlin/azure/LookupTableFunctions.kt
  prime-router/src/main/kotlin/cli/LivdTableDownload.kt
  prime-router/src/main/kotlin/cli/LookupTableCommands.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/main/resources/db/migration/V30__add_sha256_to_lookup_table.sql
  prime-router/src/test/kotlin/azure/LookupTableFunctionsTests.kt
  prime-router/src/test/kotlin/cli/LookupTableCommandsTest.kt
Labels: pipeline

#3767 fix #1048 body content length exception
  .github/workflows/github_release.yaml
Labels: DevOps

#3769 3325: Fixed Bug NET.1 is blank
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
Labels: pipeline

#3759 OO/rhood/3740 - A1H - Errors Generating Fake Test
  prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
  prime-router/docs/schema_documentation/experity-experity-covid-19.md
  prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
  prime-router/docs/schema_documentation/ipatientcare-ipatientcare-covid-19.md
  prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
  prime-router/docs/schema_documentation/manualupload-csvuploadertest-covid-19.md
  prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
  prime-router/docs/schema_documentation/upload-covid-19.md
  prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema
  prime-router/metadata/valuesets/sender-automation.valuesets
Labels: bug, onboarding-ops

#3749 Adds PID-20 suppression for MA
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0062-suppress-pid-20-ma.yml
  prime-router/settings/staging/0062-suppress-pid-20.yml
Labels: onboarding-ops

#3755 Adds new name format for TX
  prime-router/metadata/file_name_templates/file-name-templates.yml
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0063-change-tx-name-format.yml
  prime-router/settings/staging/0063-change-tx-name-format.yml
Labels: onboarding-ops

#3773 OO/rhood/3764-ReddyFMC and Experity Error Generating Fake Data
  prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
  prime-router/docs/schema_documentation/experity-experity-covid-19.md
  prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
  prime-router/docs/schema_documentation/ipatientcare-ipatientcare-covid-19.md
  prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
  prime-router/metadata/schemas/Experity/CUC-AL-covid-19.schema
  prime-router/metadata/schemas/Experity/GUC-LA-covid-19.schema
  prime-router/metadata/schemas/Experity/experity-covid-19.schema
  prime-router/metadata/schemas/iPatientCare/ReddyFMC-LA-covid-19.schema
  prime-router/metadata/schemas/iPatientCare/iPatientCare-covid-19.schema
Labels: bug, onboarding-ops

#3785 OO/rhood/3780 Std CSV - Fix Fake Data Error
  prime-router/docs/schema_documentation/manualupload-csvuploadertest-covid-19.md
  prime-router/docs/schema_documentation/upload-covid-19.md
  prime-router/metadata/schemas/manualupload/csvuploadertest-covid-19.schema
  prime-router/metadata/schemas/upload-covid-19.schema
Labels: bug, onboarding-ops

#3789 Upgrade postcss
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: tech-debt

#3735 Josiahsiegel/#1674 docker content trust
  .github/actions/deploy-backend/action.yml
  .github/actions/deploy-frontend/action.yml
  .github/actions/vpn-azure/action.yml
  .github/workflows/release.yml
Labels: DevOps, security

#3808 Removed JCenter from dependency repo list
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/azure/EmailEngineFunction.kt
Labels: pipeline

#3816 Remove jcenter from gradle plugin manager
  prime-router/settings.gradle.kts
Labels: pipeline

#3727 Updated to fix org name checking and admin all-org access
  prime-router/src/main/kotlin/azure/HistoryFunctions.kt
Labels: bug, backend, experience

#3746 3745 Reduce log messages from batchDecider
  prime-router/src/main/kotlin/azure/BatchDeciderFunction.kt
Labels: pipeline

#3851 Fix production issues when going to Upload as Admin
  frontend-react/.env.production
  frontend-react/src/components/GlobalContextProvider.tsx
  frontend-react/src/pages/Upload.tsx
  frontend-react/src/resources/SenderAuthResource.ts
  frontend-react/src/utils/UserUtils.ts
  frontend-react/src/webreceiver-utils.ts
Labels: bug, experience

#3853 OO/rhood/3847 Source BioScience sub-schema for CSV Uploader Pilot
  prime-router/docs/schema_documentation/manualupload-sourcebioscience_ca-covid-19.md
  prime-router/metadata/schemas/manualupload/sourcebioscience_ca-covid-19.schema
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0064-sourcebioscience_ca.yml
  prime-router/settings/staging/0064-sourcebioscience_ca.yml
Labels: onboarding-ops

#3826 Sets Admin default when not a member of other orgs
  frontend-react/src/pages/Login.tsx
Labels: bug, frontend, experience

#3859 Updated svg to match PHD onboarding tracker
  frontend-react/src/content/live.json
  frontend-react/src/content/usa_w_territories.svg
Labels: onboarding-ops, frontend, experience

#3858 2887 Fixed diff working with the LIVD table
  prime-router/local.settings.json
  prime-router/src/main/kotlin/azure/DatabaseLookupTableAccess.kt
  prime-router/src/main/kotlin/cli/LookupTableCommands.kt
Labels: pipeline

#3838 close #1048 build release notes after creating tag
  .github/actions/build-frontend/action.yml
  .github/actions/deploy-frontend/action.yml
  .github/changelog_config.json
  .github/workflows/github_release.yaml
Labels: DevOps

#3806 Exposing Submissions component and nav item to Senders
  frontend-react/src/App.tsx
  frontend-react/src/components/AuthorizedRoute.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/webreceiver-utils.ts
Labels: frontend, experience

#3831 Josiahsiegel/#3775 deploy frontend efficiency
  .github/actions/build-backend/action.yml
  .github/actions/build-frontend/action.yml
  .github/actions/build-vars/action.yml
  .github/actions/deploy-backend/action.yml
  .github/actions/deploy-frontend/action.yml
  .github/workflows/build_frontend.yaml
  .github/workflows/github_release.yaml
  .github/workflows/release.yml
Labels: DevOps

#3881 removed hardcoded version tag set for testing
  .github/actions/build-vars/action.yml
Labels: bug

#3855 Jeremy/gitleaks cleanup
  .environment/gitleaks/gitleaks-config.toml
Labels: security

#3928 force change trigger if prod deploy
  .github/actions/build-vars/action.yml
Labels: DevOps

#3932 Josiahsiegel/ignore change trigger prod deploy
  .github/actions/build-vars/action.yml
Labels: DevOps

#3931 postcss fix part2
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: security, frontend, tech-debt

#3850 3381: PRIME CLI command to store the extracted LIVD lookup table data…
  prime-router/src/main/kotlin/cli/LivdTableDownload.kt
  prime-router/src/main/kotlin/cli/LookupTableCommands.kt
Labels: pipeline

#3742 Adds logic to suppress OBX-18 for NJ
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0061-nj-suppress-obx-18.yml
  prime-router/settings/staging/0061-nj-suppress-obx-18.yml
Labels: onboarding-ops

#3936 Adds dokka to Gradle and adds JavaDoc from our files
  prime-router/build.gradle.kts
Labels: onboarding-ops

#3726 OBX-23-1 with ampersand fails
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
Labels: bug, backend, onboarding-ops

#3624 Add support for Admin settings
  frontend-react/package.json
  frontend-react/src/App.tsx
  frontend-react/src/components/Admin/AdminFormEdit.tsx
  frontend-react/src/components/Admin/AdminModal.tsx
  frontend-react/src/components/Admin/EditReceiverSettings.tsx
  frontend-react/src/components/Admin/EditSenderSettings.tsx
  frontend-react/src/components/Admin/OrgReceiverTable.tsx
  frontend-react/src/components/Admin/OrgSenderTable.tsx
  frontend-react/src/components/Admin/OrgSettingsTable.tsx
  frontend-react/src/components/AlertNotifications.tsx
  frontend-react/src/components/header/AdminDropdownNav.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/pages/admin/AdminMain.tsx
  frontend-react/src/pages/admin/AdminOrgEdit.tsx
  frontend-react/src/resources/OrgReceiverSettingsResource.ts
  frontend-react/src/resources/OrgSenderSettingsResource.ts
  frontend-react/src/resources/OrgSettingsBaseResource.ts
  frontend-react/src/resources/OrgSettingsResource.ts
  frontend-react/yarn.lock
Labels: experience

#3715 Onboarding Iowa
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0059-onboarding-iowa.yml
  prime-router/settings/staging/0060-onboarding-iowa.yml
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
Labels: onboarding-ops

#3952 Onboarding Medical Network Solutions
  prime-router/docs/schema_documentation/hl7-mns-covid-19.md
  prime-router/metadata/schemas/HL7/mns-covid-19.schema
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0066-mns.yml
  prime-router/settings/staging/0066-mns.yml
Labels: onboarding-ops, sender

#3983 Add Lemoore Naval Clinic as a Sender
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0068-add-lemoore-naval-clinic.yml
  prime-router/settings/staging/0068-add-lemoore-naval-clinic.yml
Labels: onboarding-ops

#4000 Onboarding SafeHealth into full production
  prime-router/docs/schema_documentation/direct-safehealth-covid-19.md
  prime-router/metadata/schemas/direct/safehealth-covid-19.schema
Labels: onboarding-ops, sender

#3981 Turns on NCES for New Mexico
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0067-nm-nces-flag.yml
  prime-router/settings/staging/0067-nm-nces-flag.yml
Labels: onboarding-ops

#4006 3765: Bug, Process Blobstorage should have folder sender
  prime-router/src/main/kotlin/azure/ReportFunction.kt
Labels: pipeline

#3942 3860: Make CSV Uploader to accept multiple DATETIME format.
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/test/kotlin/serializers/CsvSerializerTests.kt
Labels: pipeline

#4010 Fixes issue with MSH-3 not truncating
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
Labels: onboarding-ops

#4034 OO/rhood/4025 Add vivature-tx as a CSV Sender
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0067-sourcebioscience_ca.yml
  prime-router/settings/prod/0068-cadph-csvuploadertest.yml
  prime-router/settings/prod/0069-vivature-tx.yml
  prime-router/settings/staging/0069-vivature-tx.yml
Labels: onboarding-ops, sender

#3978 Update Okta dependencies
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: experience, tech-debt

#4040 Moved LIVD mappers to their own file
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/FakeReport.kt
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/Translator.kt
  prime-router/src/main/kotlin/cli/LivdTableDownload.kt
  prime-router/src/main/kotlin/metadata/LivdMappers.kt
  prime-router/src/main/kotlin/metadata/Mappers.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/ElementTests.kt
  prime-router/src/test/kotlin/metadata/LivdMapperTests.kt
  prime-router/src/test/kotlin/metadata/MapperTests.kt
Labels: pipeline

#4050 OO/rhood/4049/Bug Fix: CSV Uploader - processing_mode_code
  prime-router/metadata/schemas/upload-covid-19.schema
Labels: bug, onboarding-ops

#4083 OO/rhood/4082 CSV Uploader - Temporarily Set Processing Mode to T
  prime-router/docs/schema_documentation/upload-covid-19.md
  prime-router/metadata/schemas/upload-covid-19.schema
Labels: onboarding-ops

#4095 OO/rhood/4088 Add CSV Sender - CDPHE (CO)
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0071-cdphe-csvuploader.yml
  prime-router/settings/staging/0071-cdphe-csvuploader.yml
Labels: onboarding-ops

#4084 OO/rhood/4056 YML for SDI Labs
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0068-cadph-csvuploadertest.yml
  prime-router/settings/prod/0070-sdilabs-ca.yml
  prime-router/settings/staging/0068-cadph-csvuploadertest.yml
  prime-router/settings/staging/0070-sdilabs-ca.yml
Labels: onboarding-ops

#4093 Updated field name to represent back-end change
  frontend-react/src/pages/Upload.tsx
Labels: bug, experience

#4080 Fixes issue with LOINC multiplex look up logic
  prime-router/src/main/kotlin/metadata/LivdMappers.kt
Labels: onboarding-ops
