Repository CDCgov/prime-reportstream, pull requests merged in 2022-09, with the labels that each got.

#6567 Router Refactor 1: Install `react-router-dom` v6 and refactor main app router
  frontend-react/package.json
  frontend-react/src/App.tsx
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/Admin/EditReceiverSettings.tsx
  frontend-react/src/components/Admin/EditSenderSettings.test.tsx
  frontend-react/src/components/Admin/EditSenderSettings.tsx
  frontend-react/src/components/Admin/NewSetting.tsx
  frontend-react/src/components/Admin/OrgsTable.tsx
  frontend-react/src/components/AuthElement.tsx
  frontend-react/src/components/AuthorizedRoute.tsx
  frontend-react/src/components/Content/GeneratedSideNav.tsx
  frontend-react/src/components/Content/MarkdownDirectory.tsx
  frontend-react/src/components/Content/StaticPageFromDirectories.test.tsx
  frontend-react/src/components/Content/StaticPagesFromDirectories.tsx
  frontend-react/src/components/Content/Templates/IAMetaAndRouter.tsx
  frontend-react/src/pages/Login.tsx
  frontend-react/src/pages/Upload.tsx
  frontend-react/src/pages/UploadToPipeline.tsx
  frontend-react/src/pages/Validate.tsx
  frontend-react/src/pages/admin/AdminLastMileFailures.tsx
  frontend-react/src/pages/admin/AdminMain.tsx
  frontend-react/src/pages/admin/AdminOrgEdit.tsx
  frontend-react/src/pages/admin/AdminOrgNew.tsx
  frontend-react/src/pages/admin/AdminReceiverDashPage.tsx
  frontend-react/src/pages/admin/InternalUserGuides.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.tsx
  frontend-react/src/pages/daily/Daily.tsx
  frontend-react/src/pages/details/Details.tsx
  frontend-react/src/pages/misc/FeatureFlags.tsx
  frontend-react/src/pages/product/ProductIndex.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.tsx
  frontend-react/src/pages/submissions/Submissions.tsx
  frontend-react/src/utils/PermissionsUtils.ts
  frontend-react/yarn.lock
Labels: frontend, experience, tech-debt

#6600 6299 Use FHIR to HL7 base schema in translation process
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/test/resources/fhirengine/engine/valid_data.fhir
Labels: pipeline

#6610 fix: correctly save value sets by adding back idea of value set row ids
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
Labels: experience

#6607 Oo/oslynn/6605/hot fix livd table download
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/cli/LivdTableDownload.kt
Labels: onboarding-ops

#6572 Improve Lastmile tracking
  frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx
  frontend-react/src/pages/admin/AdminLastMileFailures.tsx
  frontend-react/src/pages/resources/legacy-page-content/CsvSchemaDocumentation.tsx
  frontend-react/src/resources/AdmActionResource.ts
  frontend-react/src/styles/_reportstream.scss
  prime-router/docs/api/admin.yml
  prime-router/src/main/kotlin/azure/AdminApiFunctions.kt
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/RequeueFunction.kt
Labels: onboarding-ops, experience, API

#6655 Lastmile fix layout
  frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx
  frontend-react/src/resources/AdmActionResource.ts
  frontend-react/src/styles/_reportstream.scss
Labels: frontend

#6648 docs: new request patterns [experience-6392]
  frontend-react/docs/data-fetching-patterns.md
  frontend-react/docs/rs-react-networking.md
  frontend-react/docs/rs-react-testing-network-calls.md
  frontend-react/src/config/endpoints/RSEndpoint.test.ts
  frontend-react/src/contexts/AuthorizedFetchContext.tsx
Labels: experience

#6647 Experience/shadow master react query
  frontend-react/docs/data-fetching-patterns.md
  frontend-react/docs/rs-react-networking.md
  frontend-react/docs/rs-react-testing-network-calls.md
  frontend-react/package.json
  frontend-react/src/App.tsx
  frontend-react/src/__mocks__/LookupTableMockServer.ts
  frontend-react/src/components/AppWrapper.tsx
  frontend-react/src/config/endpoints/RSEndpoint.test.ts
  frontend-react/src/config/endpoints/index.ts
  frontend-react/src/config/endpoints/lookupTables.ts
  frontend-react/src/contexts/AuthorizedFetchContext.tsx
  frontend-react/src/hooks/UseCreateFetch.test.ts
  frontend-react/src/hooks/UseCreateFetch.ts
  frontend-react/src/hooks/UseLookupTable.test.ts
  frontend-react/src/hooks/UseLookupTable.ts
  frontend-react/src/hooks/UseValueSets.test.ts
  frontend-react/src/hooks/UseValueSets.ts
  frontend-react/src/index.tsx
  frontend-react/src/network/api/Api.test.ts
  frontend-react/src/network/api/Api.ts
  frontend-react/src/network/api/LookupTableApi.test.ts
  frontend-react/src/network/api/LookupTableApi.ts
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.test.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.test.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.tsx
  frontend-react/src/utils/CustomRenderUtils.tsx
  frontend-react/yarn.lock
Labels: experience

#6627 Oo/jgilmore/6417/onboard bzd labs
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0134-bzlabs.yml
  prime-router/settings/staging/0134-bzdlabs.yml
Labels: onboarding-ops

#5933 Add Hl7 field repettion separation (~) handling to replaceValueAwithB
  prime-router/src/main/kotlin/cli/ProcessDataCommands.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
  prime-router/src/testIntegration/kotlin/serializers/Hl7SerializerIntegrationTests.kt
  prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-pdi-covid-19-nh.csv
  prime-router/src/testIntegration/resources/settings/organizations.yml
Labels: onboarding-ops

#6643 6310 Support CLIA IDs in full-ELR pipeline
  prime-router/metadata/fhir_mapping/hl7/datatype/Identifier_var.yml
  prime-router/metadata/fhir_mapping/hl7/resource/DiagnosticReport.yml
  prime-router/metadata/fhir_mapping/hl7/resource/MessageSender.yml
  prime-router/metadata/fhir_mapping/hl7/resource/ServiceRequest.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/Destination.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/Source.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/entity-identifier.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/hd-hierarchic-designator.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/message-header.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/xon-organization.yml
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/ConstantResolverTests.kt
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_2_20220803-0001.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_2_20220803-0001.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: pipeline

#6661 refactor: new lookup table endpoint [experience-5708]
  frontend-react/src/__mocks__/LookupTableMockServer.ts
  frontend-react/src/config/endpoints/lookupTables.ts
  frontend-react/src/hooks/UseValueSets.test.ts
  frontend-react/src/hooks/UseValueSets.ts
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.test.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.tsx
Labels: experience

#6668 6469 Fixed time zone in HL7 conversion
  prime-router/metadata/hl7_mapping/ORU_R01/base/message-header.yml
Labels: pipeline

#6677 Adds NY to the "where we're live" map and list
  frontend-react/src/content/live.json
  frontend-react/src/content/usa_w_territories.svg
Labels: frontend, experience

#6658 6579 Allow for FHIR to HL7 schema extensions
  prime-router/metadata/hl7_mapping/ORU_R01/base/message-header.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/order.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/patient-visit.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/patient.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/specimen.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/xcn-contact.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/xon-organization.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/xtn-telecom.yml
  prime-router/metadata/hl7_mapping/STLTs/CO/CO.yml
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReader.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReaderTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/FhirPathUtilsTests.kt
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01-extended.yml
Labels: pipeline

#6685 update tx hostname
  prime-router/settings/prod/0135-update-tx-hostname.yml
  prime-router/settings/staging/0135-update-tx-hostname.yml
Labels: onboarding-ops, Texas

#6676 Onboarding ops/6674/providence onboard
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0135-providence.yml
  prime-router/settings/staging/0135-providence.yml
Labels: onboarding-ops, HL7, sender

#6679 Allow FHIR to HL7 library schema constants to support FHIR Path expressions
  prime-router/metadata/hl7_mapping/ORU_R01/ORU_R01-base.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/cx-extended-composite-id.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/note.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/observation-result.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/observation.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/order-observation.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/order.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/patient.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/software.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/timing-quantity.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/xcn-contact.yml
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/ConstantResolverTests.kt
Labels: pipeline

#6671 Experience/5912 value sets meta
  frontend-react/src/components/Table/Table.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.test.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
  frontend-react/src/styles/_reportstream.scss
Labels: experience

#6721 Oo/jgilmore/6592/american samoa new receiver
  prime-router/docs/schema_documentation/as-as-download-csv.md
  prime-router/metadata/schemas/AS/as-download-csv.schema
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0136-American-Samoa-Onboarding.yml
  prime-router/settings/staging/0136-American-Samoa-Onboarding.yml
Labels: onboarding-ops, American Samoa

#6701 Add service request from
  frontend-react/src/content/support/index.ts
  frontend-react/src/pages/support/index-legacy.ts
  frontend-react/src/pages/support/legacy-page-content/Contact.tsx
  frontend-react/src/pages/support/legacy-page-content/ServiceRequest.tsx
  frontend-react/src/styles/_reportstream.scss
Labels: experience

#6742 Fetch Refactor: New RSErrorBoundary and RSNetworkError
  frontend-react/docs/rs-error-boundary-and-suspense.md
  frontend-react/src/components/RSErrorBoundary.test.tsx
  frontend-react/src/components/RSErrorBoundary.tsx
  frontend-react/src/hooks/UseCreateFetch.ts
  frontend-react/src/pages/error/ErrorPage.tsx
  frontend-react/src/utils/RSNetworkError.ts
Labels: frontend, experience

#6750 Fetch Refactor: ErrorPage modifications
  frontend-react/src/App.tsx
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/Admin/NewSetting.tsx
  frontend-react/src/components/RSErrorBoundary.test.tsx
  frontend-react/src/content/error/ErrorMessages.ts
  frontend-react/src/pages/error/ErrorPage.test.tsx
  frontend-react/src/pages/error/ErrorPage.tsx
  frontend-react/src/pages/error/Generic.tsx
  frontend-react/src/pages/error/NotFound.tsx
  frontend-react/src/pages/error/legacy-content/ErrorNoPage.tsx
  frontend-react/src/pages/error/legacy-content/ErrorUnsupportedBrowser.tsx
Labels: frontend, experience

#6736 Experience/6309: return quality filter results from the /validate endpoint
  prime-router/src/main/kotlin/SubmissionReceiver.kt
  prime-router/src/main/kotlin/ValidationReceiver.kt
  prime-router/src/main/kotlin/azure/ValidateFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/test/kotlin/SubmissionReceiverTests.kt
Labels: experience

#6739 Experience/env var config
  frontend-react/package.json
  frontend-react/src/App.tsx
  frontend-react/src/__mocks__/WatersMockServer.ts
  frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx
  frontend-react/src/components/Admin/EditReceiverSettings.tsx
  frontend-react/src/components/Admin/EditSenderSettings.tsx
  frontend-react/src/components/Content/Templates/IAMeta.tsx
  frontend-react/src/components/header/BasicHelmet.test.tsx
  frontend-react/src/components/header/BasicHelmet.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/components/header/SignInOrUser.tsx
  frontend-react/src/config/endpoints/index.ts
  frontend-react/src/config/index.ts
  frontend-react/src/network/api/NewApi.ts
  frontend-react/src/network/api/WatersApi.test.ts
  frontend-react/src/oktaConfig.ts
  frontend-react/src/pages/About.tsx
  frontend-react/src/pages/admin/AdminLastMileFailures.tsx
  frontend-react/src/pages/admin/AdminMain.tsx
  frontend-react/src/pages/admin/AdminOrgEdit.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.tsx
  frontend-react/src/pages/daily/Daily.tsx
  frontend-react/src/pages/daily/Table/ReportLink.tsx
  frontend-react/src/pages/daily/Table/ReportsUtils.ts
  frontend-react/src/pages/error/ErrorPage.tsx
  frontend-react/src/pages/error/Generic.tsx
  frontend-react/src/pages/misc/FeatureFlags.tsx
  frontend-react/src/pages/product/legacy-page-content/WhereWereLive.tsx
  frontend-react/src/pages/resources/legacy-page-content/AccountRegistrationGuide.tsx
  frontend-react/src/pages/resources/legacy-page-content/CsvSchemaDocumentation.tsx
  frontend-react/src/pages/resources/legacy-page-content/CsvUploadGuide.tsx
  frontend-react/src/pages/resources/legacy-page-content/DataDownloadGuide.tsx
  frontend-react/src/pages/resources/legacy-page-content/ElrChecklist.tsx
  frontend-react/src/pages/resources/legacy-page-content/GettingStartedPhd.tsx
  frontend-react/src/pages/resources/legacy-page-content/ProgrammersGuide.tsx
  frontend-react/src/pages/resources/legacy-page-content/SecurityPractices.tsx
  frontend-react/src/pages/resources/legacy-page-content/SystemAndSettings.tsx
  frontend-react/src/pages/submissions/Submissions.tsx
  frontend-react/src/pages/support/legacy-page-content/Contact.tsx
  frontend-react/src/pages/support/legacy-page-content/Faq.tsx
  frontend-react/src/pages/tos-sign/SuccessPage.tsx
  frontend-react/src/pages/tos-sign/TermsOfServiceForm.tsx
  frontend-react/src/resources/ActionDetailsResource.ts
  frontend-react/src/resources/AdmActionResource.ts
  frontend-react/src/resources/AdmConnStatusResource.ts
  frontend-react/src/resources/AdmSendFailuresResource.ts
  frontend-react/src/resources/CardResource.ts
  frontend-react/src/resources/FacilityResource.ts
  frontend-react/src/resources/OrgReceiverSettingsResource.ts
  frontend-react/src/resources/OrgSenderSettingsResource.ts
  frontend-react/src/resources/OrgSettingsResource.ts
  frontend-react/src/resources/OrganizationResource.ts
  frontend-react/src/resources/ReportResource.ts
  frontend-react/src/resources/SenderOrganizationResource.ts
  frontend-react/src/resources/SubmissionsResource.ts
Labels: experience

#6664 Staging changes for genabio
  prime-router/docs/schema_documentation/direct-genabio-covid-19.md
  prime-router/metadata/schemas/direct/genabio-covid-19.schema
  prime-router/settings/staging/0138-add-genabio.yml
Labels: onboarding-ops

#6756 Adding handling for monkeypox AOE ages
  prime-router/docs/schema_documentation/dcipher-dcipher-monkeypox.md
  prime-router/docs/schema_documentation/monkeypox.md
  prime-router/metadata/schemas/dcipher/dcipher-monkeypox.schema
  prime-router/metadata/schemas/monkeypox.schema
Labels: onboarding-ops, HL7, monkeypox

#6788 Better AOE Processing
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
  prime-router/src/testIntegration/kotlin/FileNameTemplateIntegrationTests.kt
Labels: onboarding-ops, monkeypox

#6785 Fetch Refactor: Hook up RSErrorBoundary and Suspense to ValueSetsIndex and ValueSetsDetail
  frontend-react/docs/data-fetching-patterns.md
  frontend-react/src/components/AppWrapper.tsx
  frontend-react/src/hooks/UseValueSets.test.ts
  frontend-react/src/hooks/UseValueSets.ts
  frontend-react/src/network/QueryClients.ts
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.test.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.test.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.tsx
  frontend-react/src/utils/CustomRenderUtils.tsx
Labels: frontend, experience

#6811 fix: do not make useQuery requests with uninitialized okta [experience-unticketed]
  frontend-react/src/components/AuthElement.test.tsx
  frontend-react/src/components/SenderModeBanner.test.tsx
  frontend-react/src/components/header/ReportStreamHeader.test.tsx
  frontend-react/src/contexts/AuthorizedFetchContext.test.tsx
  frontend-react/src/contexts/AuthorizedFetchContext.tsx
  frontend-react/src/contexts/SessionContext.test.tsx
  frontend-react/src/contexts/SessionContext.tsx
  frontend-react/src/hooks/UseValueSets.ts
  frontend-react/src/hooks/network/History/DeliveryHooks.test.ts
  frontend-react/src/hooks/network/Organizations/ReceiversHooks.test.ts
  frontend-react/src/pages/submissions/SubmissionTable.test.tsx
  frontend-react/src/utils/CustomRenderUtils.tsx
Labels: experience

#6770 Experience/feature flag env vars
  frontend-react/package.json
  frontend-react/src/components/AppWrapper.tsx
  frontend-react/src/components/AuthElement.test.tsx
  frontend-react/src/components/AuthElement.tsx
  frontend-react/src/components/header/DropdownNav.test.tsx
  frontend-react/src/components/header/DropdownNav.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/config/index.ts
  frontend-react/src/contexts/FeatureFlagContext.test.tsx
  frontend-react/src/contexts/FeatureFlagContext.tsx
  frontend-react/src/contexts/__mocks__/FeatureFlagContext.tsx
  frontend-react/src/pages/misc/FeatureFlags.test.tsx
  frontend-react/src/pages/misc/FeatureFlags.tsx
  frontend-react/src/pages/submissions/SubmissionTable.test.tsx
  frontend-react/src/pages/submissions/SubmissionTable.tsx
  frontend-react/src/utils/CustomRenderUtils.tsx
  frontend-react/src/utils/SessionStorageTools.ts
  frontend-react/src/utils/__mocks__/SessionStorageTools.ts
  frontend-react/yarn.lock
Labels: experience

#6814 Experience/9 23 docs refresh
  frontend-react/docs/data-fetching-patterns.md
  frontend-react/docs/feature-flags.md
Labels: experience

#6746 6573 FHIR conversion updates from HCA samples
  prime-router/metadata/fhir_mapping/hl7/codesystem/CodingSystemMapping.yml
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/CodeableConcept.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Entity_Identifier_Pair_1.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Entity_Identifier_Pair_2.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Identifier.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Identifier_SystemID.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Quantity.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Encounter.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Observation.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Patient.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Practitioner.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Specimen.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/Collection.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/PatientContact.yml
  prime-router/metadata/hl7_mapping/ORU_R01/ORU_R01-base.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/datatype/ce-coded-element.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/datatype/ce-coded-with-exceptions.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/datatype/cnn-composite-number-name.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/datatype/cx-extended-composite-id.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/datatype/ei-entity-identifier.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/datatype/hd-hierarchic-designator.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/datatype/sn-structured-numeric.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/datatype/xad-extended-address.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/datatype/xcn-contact.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/datatype/xon-organization.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/datatype/xpn-person-name.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/datatype/xtn-telecom.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/message-header.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/observation-request.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/observation-result.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/observation.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/order.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/patient-contact.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/patient-visit.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/patient.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/software.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/specimen.yml
  prime-router/metadata/hl7_mapping/STLTs/CO/CO.yml
  prime-router/metadata/hl7_mapping/STLTs/CO/co-order-observation.yml
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReader.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
  prime-router/src/main/resources/log4j2.xml
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0006.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0006.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0014.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0014.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_2_20220803-0001.fhir
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: pipeline

#6826 Experience/membership hook init
  frontend-react/src/components/AuthElement.test.tsx
  frontend-react/src/components/AuthElement.tsx
  frontend-react/src/components/Spinner.tsx
  frontend-react/src/contexts/SessionContext.tsx
  frontend-react/src/hooks/UseOktaMemberships.test.ts
  frontend-react/src/hooks/UseOktaMemberships.ts
Labels: experience

#6841 Fixed LIVD API no longer appears to work
  prime-router/src/main/kotlin/azure/MetaDataFunction.kt
Labels: onboarding-ops

#6858 Adds a hard check for admin auth in memberships map
  frontend-react/src/components/AuthElement.test.tsx
  frontend-react/src/components/AuthElement.tsx
  frontend-react/src/contexts/SessionContext.test.tsx
  frontend-react/src/contexts/SessionContext.tsx
  frontend-react/src/hooks/__mocks__/UseOktaMemberships.ts
Labels: bug, frontend, experience

#6769 Add support for Settings Revision History
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/Admin/AdminReceiverDashboard.tsx
  frontend-react/src/components/Admin/OrgReceiverTable.tsx
  frontend-react/src/components/Admin/OrgSenderTable.tsx
  frontend-react/src/components/StaticCompare.tsx
  frontend-react/src/hooks/UseCreateFetch.ts
  frontend-react/src/hooks/UseOktaMemberships.ts
  frontend-react/src/network/api/Organizations/SettingRevisions.ts
  frontend-react/src/pages/admin/AdminOrgEdit.tsx
  frontend-react/src/pages/admin/AdminRevHistory.test.tsx
  frontend-react/src/pages/admin/AdminRevHistory.tsx
  frontend-react/src/styles/_reportstream.scss
  frontend-react/src/utils/misc.test.ts
  frontend-react/src/utils/misc.ts
  prime-router/docs/api/settings.yml
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/SettingsFacade.kt
  prime-router/src/main/kotlin/azure/SettingsFunctions.kt
Labels: experience, release_notes, API

#6854 Adding fields to DCIPHER schema
  prime-router/docs/schema_documentation/dcipher-dcipher-monkeypox.md
  prime-router/metadata/schemas/dcipher/dcipher-monkeypox.schema
Labels: onboarding-ops, monkeypox

#6874 add camel case rule
  frontend-react/package.json
  frontend-react/src/__mocks__/LookupTableMockServer.ts
  frontend-react/src/components/Admin/AdminReceiverDashboard.tsx
  frontend-react/src/components/EditableCompare.tsx
  frontend-react/src/utils/diff.ts
Labels: experience
