Repository CDCgov/prime-reportstream, pull requests merged in 2022-05, with the labels that each got.

#5352 Update reportstream-team-member-offboarding.md
  .github/ISSUE_TEMPLATE/reportstream-team-member-offboarding.md
Labels: chore

#5294 Update TranslatorConfiguration.kt
  prime-router/src/main/kotlin/TranslatorConfiguration.kt
Labels: onboarding-ops

#5384 OpenAPI (Report) Delivery Detail. Jh765/5333
  prime-router/docs/api/waters-delivery-detail.yml
  prime-router/src/main/kotlin/TranslatorConfiguration.kt
Labels: pipeline

#5360 Admin Settings: add dropdowns and valid json field value tooltips (4353/4354)
  frontend-react/src/components/Admin/AdminFormEdit.test.tsx
  frontend-react/src/components/Admin/AdminFormEdit.tsx
  frontend-react/src/components/Admin/EditReceiverSettings.tsx
  frontend-react/src/components/Admin/EditSenderSettings.tsx
  frontend-react/src/components/tooltips/ObjectTooltip.test.tsx
  frontend-react/src/components/tooltips/ObjectTooltip.tsx
  frontend-react/src/pages/admin/AdminOrgEdit.tsx
  frontend-react/src/styles/_reportstream.scss
  frontend-react/src/utils/TemporarySettingsAPITypes.test.ts
  frontend-react/src/utils/TemporarySettingsAPITypes.ts
Labels: frontend, experience

#5408 Experience/3163: Add DAP to public-facing pages
  frontend-react/src/App.tsx
  frontend-react/src/components/header/DAPHeader.test.tsx
  frontend-react/src/components/header/DAPHeader.tsx
Labels: frontend

#5434 Fix date range filter pickers to use range instead of individual dates
  frontend-react/src/components/Table/Table.test.tsx
  frontend-react/src/components/Table/Table.tsx
  frontend-react/src/components/Table/TableFilters.test.tsx
  frontend-react/src/components/Table/TableFilters.tsx
  frontend-react/src/components/Table/TestTable.tsx
  frontend-react/src/hooks/filters/UseDateRange.test.ts
  frontend-react/src/hooks/filters/UseDateRange.ts
  frontend-react/src/hooks/filters/UseFilterManager.test.ts
  frontend-react/src/hooks/filters/UseFilterManager.ts
  frontend-react/src/hooks/filters/mocks/MockFilterManager.ts
  frontend-react/src/pages/submissions/SubmissionPages.css
  frontend-react/src/pages/submissions/SubmissionTable.tsx
Labels: bug, frontend, experience

#5266 5068 Improved error output for CLI data command
  prime-router/src/main/kotlin/cli/ProcessDataCommands.kt
Labels: pipeline

#5254 3869: New Accept International Phone number
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/csv_test_files/expected/simplereport-az.csv
  prime-router/src/test/csv_test_files/expected/simplereport-pima.csv
  prime-router/src/test/csv_test_files/input/simplereport.csv
  prime-router/src/test/kotlin/ElementTests.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
Labels: onboarding-ops

#5453 Identify pending Terraform changes
  .github/workflows/alert_terraform_changes.yml
Labels: DevOps

#5422 add workflow to scan action logs for unexpected output
  .github/runleaks/exclusions.txt
  .github/runleaks/patterns.txt
  .github/workflows/scan_action_logs.yml
Labels: DevOps

#5451 5111 Convert HL7 MSH segment to FHIR resources
  prime-router/metadata/fhir_mapping/config.properties
  prime-router/metadata/fhir_mapping/fhir/resourcemapping.yml
  prime-router/metadata/fhir_mapping/hl7/codesystem/CodingSystemMapping.yml
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Address.yml
  prime-router/metadata/fhir_mapping/hl7/extension/ExtensionMeta.yml
  prime-router/metadata/fhir_mapping/hl7/message/.gitkeep
  prime-router/metadata/fhir_mapping/hl7/message/ORU_R01.yml
  prime-router/metadata/fhir_mapping/hl7/resource/.gitkeep
  prime-router/metadata/fhir_mapping/hl7/resource/Device.yml
  prime-router/metadata/fhir_mapping/hl7/resource/MessageHeader.yml
  prime-router/metadata/fhir_mapping/hl7/resource/MessageSender.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Provenance.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/ProvenanceAgent.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/ProvenanceEntity.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/Source.yml
  prime-router/src/main/kotlin/azure/HttpUtilities.kt
  prime-router/src/main/kotlin/azure/MetaDataFunction.kt
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/azure/SubmissionsFacade.kt
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/main/kotlin/common/JacksonMapperUtilities.kt
  prime-router/src/main/kotlin/fhirengine/azure/FHIRFlowFunctions.kt
  prime-router/src/main/kotlin/fhirengine/azure/FHIRProcessFunctions.kt
  prime-router/src/main/kotlin/fhirengine/encoding/FHIR.kt
  prime-router/src/main/kotlin/fhirengine/encoding/HL7.kt
  prime-router/src/main/kotlin/fhirengine/engine/Message.kt
  prime-router/src/main/kotlin/fhirengine/translation/HL7toFHIR.kt
  prime-router/src/main/kotlin/fhirengine/translation/HL7toFhirTranslator.kt
  prime-router/src/main/kotlin/fhirengine/utils/FhirTranscoder.kt
  prime-router/src/main/kotlin/fhirengine/utils/HL7Reader.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRFlowFunctionsTests.kt
  prime-router/src/test/kotlin/fhirengine/translator/HL7toFhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/utils/HL7ReaderTests.kt
Labels: pipeline

#5477 Fixes sort order issue on submissions table
  frontend-react/src/components/Table/Table.tsx
Labels: bug, High Priority, experience

#5486 20220516 Update to local LIVD table
  prime-router/metadata/tables/local/LIVD-SARS-CoV-2.csv
Labels: pipeline

#5475 History table swapped to reusable table component
  frontend-react/src/__mocks__/HistoryMockServer.ts
  frontend-react/src/components/Table/Table.test.tsx
  frontend-react/src/components/Table/Table.tsx
  frontend-react/src/components/Table/TestTable.tsx
  frontend-react/src/components/__mocks__/SessionStorageTools.ts
  frontend-react/src/pages/daily/Daily.tsx
  frontend-react/src/pages/daily/Table/ReportsTable.test.tsx
  frontend-react/src/pages/daily/Table/ReportsTable.tsx
  frontend-react/src/pages/daily/Table/ReportsUtils.test.ts
  frontend-react/src/pages/daily/Table/ReportsUtils.ts
  frontend-react/src/pages/daily/Table/TableButtonGroup.tsx
  frontend-react/src/pages/daily/Table/TableReports.tsx
  frontend-react/src/pages/daily/Table/TableReportsData.tsx
  frontend-react/src/pages/submissions/SubmissionTable.tsx
  frontend-react/src/resources/ReportResource.ts
Labels: experience, tech-debt

#4671 Add time zone conversion flag for receivers
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/Element.kt
  prime-router/src/main/kotlin/FakeReport.kt
  prime-router/src/main/kotlin/Organization.kt
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/ReportStreamFilterDefinition.kt
  prime-router/src/main/kotlin/Sender.kt
  prime-router/src/main/kotlin/TranslatorConfiguration.kt
  prime-router/src/main/kotlin/USTimeZone.kt
  prime-router/src/main/kotlin/azure/SettingsFacade.kt
  prime-router/src/main/kotlin/cli/tests/CompareData.kt
  prime-router/src/main/kotlin/common/DateUtilities.kt
  prime-router/src/main/kotlin/common/StringUtilities.kt
  prime-router/src/main/kotlin/metadata/Mappers.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/csv_test_files/expected/federal-test-receiver-happy-path.csv
  prime-router/src/test/csv_test_files/input/federal-test-schema.schema
  prime-router/src/test/kotlin/ElementTests.kt
  prime-router/src/test/kotlin/ReportTests.kt
  prime-router/src/test/kotlin/common/DateUtilitiesTests.kt
  prime-router/src/test/kotlin/metadata/MapperTests.kt
  prime-router/src/test/kotlin/serializers/CsvSerializerTests.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
  prime-router/src/test/kotlin/unittest/UnitTestUtils.kt
  prime-router/src/testIntegration/kotlin/SimpleReportIntegrationTests.kt
  prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-batch-pdi-20210608-0001.csv
  prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-batch-pdi-20210608-0001.hl7
  prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-single-pdi-20210608-0002.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_INTERNAL/CA-20211001-sully.internal.csv
  prime-router/src/testIntegration/resources/datatests/HL7_to_INTERNAL/CA-20211018-sully.internal.csv
  prime-router/src/testIntegration/resources/datatests/HL7_to_INTERNAL/CE-20200415-0001.internal.csv
Labels: onboarding-ops

#5483 5267 Translate full-ELR HL7 SFT segment to FHIR
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/extension/ExtensionMeta.yml
  prime-router/metadata/fhir_mapping/hl7/message/ORU_R01.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Organization.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/Source.yml
Labels: pipeline

#5502 only tf alert if changes gt 0
  .github/workflows/alert_terraform_changes.yml
Labels: DevOps

#5495 Extend table component
  frontend-react/src/App.tsx
  frontend-react/src/components/Table/Table.test.tsx
  frontend-react/src/components/Table/Table.tsx
  frontend-react/src/components/Table/TestTable.tsx
  frontend-react/src/components/header/AdminDropdownNav.test.tsx
  frontend-react/src/components/header/AdminDropdownNav.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.test.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.tsx
  frontend-react/src/pages/daily/Table/ReportsTable.tsx
  frontend-react/src/pages/misc/FeatureFlags.tsx
  frontend-react/src/pages/submissions/SubmissionTable.tsx
  frontend-react/src/styles/_reportstream.scss
Labels: frontend, experience

#5473 Update offboarding to include SendGrid
  .github/ISSUE_TEMPLATE/reportstream-team-member-offboarding.md
Labels: chore

#5541 Fixes config for SubmissionsTable
  frontend-react/src/pages/submissions/SubmissionTable.tsx
Labels: bug, frontend

#5524 5355 Compare FHIR data for integration testing
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/main/kotlin/cli/FileUtilities.kt
  prime-router/src/main/kotlin/cli/ProcessDataCommands.kt
  prime-router/src/main/kotlin/cli/tests/CompareData.kt
  prime-router/src/main/kotlin/fhirengine/azure/FHIRProcessFunctions.kt
  prime-router/src/main/kotlin/fhirengine/translation/HL7toFhirTranslator.kt
  prime-router/src/main/kotlin/fhirengine/utils/CompareFhirData.kt
  prime-router/src/main/kotlin/fhirengine/utils/FhirTranscoder.kt
  prime-router/src/test/kotlin/fhirengine/translator/HL7toFhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/utils/CompareFhirDataTests.kt
  prime-router/src/test/kotlin/fhirengine/utils/FhirTranscoderTests.kt
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_INTERNAL/CA-20201129-0001.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_INTERNAL/CA-20201129-0001.internal.csv
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: pipeline

#5536 infrastructure administration function app
  .github/workflows/alert_terraform_changes.yml
  .gitignore
  .vscode/settings.json
  operations/app/functions/admin/.funcignore
  operations/app/functions/admin/.gitignore
  operations/app/functions/admin/ConfirmDBAccess/__init__.py
  operations/app/functions/admin/ConfirmDBAccess/confirm_db_access.py
  operations/app/functions/admin/ConfirmDBAccess/function.json
  operations/app/functions/admin/ConfirmStorageAccess/__init__.py
  operations/app/functions/admin/ConfirmStorageAccess/confirm_storage_access.py
  operations/app/functions/admin/ConfirmStorageAccess/function.json
  operations/app/functions/admin/ConfirmVaultAccess/__init__.py
  operations/app/functions/admin/ConfirmVaultAccess/confirm_vault_access.py
  operations/app/functions/admin/ConfirmVaultAccess/function.json
  operations/app/functions/admin/GetIP/__init__.py
  operations/app/functions/admin/GetIP/function.json
  operations/app/functions/admin/PingAddress/__init__.py
  operations/app/functions/admin/PingAddress/function.json
  operations/app/functions/admin/PingAddress/ping_address.py
  operations/app/functions/admin/QueryDurations/__init__.py
  operations/app/functions/admin/QueryDurations/function.json
  operations/app/functions/admin/QueryDurations/query_durations.py
  operations/app/functions/admin/host.json
  operations/app/functions/admin/requirements.txt
  operations/app/functions/functions-workspace.code-workspace
  operations/app/terraform/modules/function_app/admin_app.tf
  operations/app/terraform/modules/function_app/~inputs.tf
  operations/app/terraform/modules/function_app/~outputs.tf
  operations/app/terraform/modules/key_vault/main.tf
  operations/app/terraform/modules/key_vault/~inputs.tf
  operations/app/terraform/modules/key_vault/~outputs.tf
  operations/app/terraform/vars/prod/main.tf
  operations/app/terraform/vars/staging/main.tf
  operations/app/terraform/vars/test/main.tf
Labels: DevOps

#5556 Update MP Biomedicals for production
  prime-router/docs/schema_documentation/csv-otc-covid-19.md
  prime-router/metadata/schemas/csv-otc-covid-19.schema
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0113-mpbiomedicals.yml
  prime-router/settings/staging/0113-mpbiomedicals.yml
Labels: onboarding-ops, sender

#5561 5268 Translate HL7 full-ELR PID segment to FHIR
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Identifier_SystemID.yml
  prime-router/metadata/fhir_mapping/hl7/extension/ExtensionMeta.yml
  prime-router/metadata/fhir_mapping/hl7/message/ORU_R01.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Observation.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Patient.yml
  prime-router/src/main/kotlin/fhirengine/utils/CompareFhirData.kt
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir
Labels: pipeline

#5573 add blob level diag and permit lifecycle management access
  operations/app/terraform/modules/log_analytics_workspace/data.tf
  operations/app/terraform/modules/storage/main.tf
Labels: DevOps

#5251 New ifThenElse mapper
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/metadata/Mappers.kt
  prime-router/src/test/kotlin/metadata/MapperTests.kt
Labels: pipeline

#5542 Experience/3329 add cypress tests
  .gitignore
  frontend-react/cypress.json
  frontend-react/cypress/integration/live.test.tsx
  frontend-react/cypress/plugins/index.js
  frontend-react/cypress/support/commands.js
  frontend-react/cypress/support/index.js
  frontend-react/package.json
  frontend-react/tsconfig.json
  frontend-react/yarn.lock
Labels: frontend, experience

#5586 Tomn usds/fix empty table bug
  frontend-react/src/components/Table/Table.tsx
  frontend-react/src/resources/AuthResource.ts
Labels: bug, experience

#5567 Healthcare Integrations onboarding
  prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
  prime-router/docs/schema_documentation/covid-19.md
  prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
  prime-router/docs/schema_documentation/direct-hca-covid-19.md
  prime-router/docs/schema_documentation/fl-fl-covid-19.md
  prime-router/docs/schema_documentation/gu-gu-covid-19.md
  prime-router/docs/schema_documentation/hl7-detect-covid-19.md
  prime-router/docs/schema_documentation/hl7-hcintegrations-covid-19.md
  prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19.md
  prime-router/docs/schema_documentation/hl7-lifepoint-covid-19.md
  prime-router/docs/schema_documentation/hl7-mns-covid-19.md
  prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
  prime-router/docs/schema_documentation/hl7-primary-covid-19.md
  prime-router/docs/schema_documentation/hl7-signetic-covid-19.md
  prime-router/docs/schema_documentation/hl7-test-covid-19.md
  prime-router/docs/schema_documentation/la-la-covid-19.md
  prime-router/docs/schema_documentation/mt-mt-covid-19.md
  prime-router/docs/schema_documentation/nd-nd-covid-19.md
  prime-router/docs/schema_documentation/nm-nm-covid-19.md
  prime-router/docs/schema_documentation/oh-oh-covid-19.md
  prime-router/docs/schema_documentation/or-or-covid-19-hl7.md
  prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
  prime-router/docs/schema_documentation/standard-standard-covid-19.md
  prime-router/docs/schema_documentation/tpca-tpca-covid-19.md
  prime-router/docs/schema_documentation/tx-tx-covid-19.md
  prime-router/docs/schema_documentation/vt-vt-covid-19.md
  prime-router/metadata/schemas/FL/fl-covid-19.schema
  prime-router/metadata/schemas/HL7/hcintegrations-covid-19.schema
  prime-router/metadata/schemas/covid-19.schema
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0114-hcintegrations-ca.yml
  prime-router/settings/staging/0114-hcintegrations-ca.yml
Labels: onboarding-ops, HL7, sender

#5603 Deploy Terraform workflow
  .github/workflows/deploy_terraform.yml
Labels: DevOps

#5622 Exclude FE tests from duplication check
  .github/workflows/run_sonarcloud_scan.yaml
Labels: experience

#5633 Clear cache before test CI
  frontend-react/package.json
Labels: DevOps, experience
