Repository CDCgov/prime-reportstream, pull requests merged in 2023-04, with the labels that each got.

#8803 Experience 8346: Add configuration for local instance of Storybook
  frontend-react/.eslintrc.js
  frontend-react/.storybook/main.js
  frontend-react/.storybook/preview.js
  frontend-react/package.json
  frontend-react/src/components/StaticAlert.stories.tsx
  frontend-react/src/components/USLink.stories.tsx
  frontend-react/yarn.lock
Labels: experience

#8922 MDX support
  frontend-react/config/webpack.config.js
  frontend-react/package.json
  frontend-react/tsconfig.json
  frontend-react/yarn.lock
Labels: experience, engineering

#8904 Added additional receiver transforms
  prime-router/metadata/hl7_mapping/ORU_R01/base/observation-result.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/order.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/CA.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/ca-order-observation.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/ca-specimen.yml
  prime-router/metadata/hl7_mapping/common/datatype/ce-coded-with-exceptions.yml
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SR_1_20230302-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SR_1_20230302-0001.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0001-expected-CO.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0001-expected-base.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/test_playground_20220930-0001-expected-CO.hl7
Labels: pipeline, platform

#8983 Bump jacoco from 0.8.8 to 0.8.9
  prime-router/build.gradle.kts
Labels: pipeline, dependencies, java, platform

#9001 Update MDX loader to ignore md files
  frontend-react/config/webpack.config.js
Labels: experience

#8699 Bump hapi-fhir-structures-r4:6.2.5 to hapi-fhir-structures-r4:6.4.0 in /prime-router
  prime-router/build.gradle.kts
Labels: security, dependencies, java

#8989 Jessica/8862 default sender transform
  prime-router/metadata/fhir_transforms/default-sender-transform.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/CA.yml
  prime-router/metadata/hl7_mapping/common/message-header.yml
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: pipeline, platform

#9024 Address storybook npm audit vulnerabilities
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: security, experience

#8801 8587 Full ELR California Receiver
  prime-router/settings/prod/0150-CA-Add-FullELR-SaphireStage-Receiver.yml
  prime-router/settings/staging/0150-CA-Add-FullELR-SaphireStage-Receiver.yml
Labels: pipeline, platform

#8930 Bump org.jetbrains.dokka:dokka-*@1.7.20 to org.jetbrains.dokka-*@1.8.10 in /prime-router
  prime-router/build.gradle.kts
Labels: security, dependencies, java

#9029 Deduplicate @bable* dependencies
  frontend-react/yarn.lock
Labels: security, dependencies, javascript

#8954 Experience/8943/mdx general layout
  frontend-react/jest.config.ts
  frontend-react/src/__mocks__/mdxjsReactMock.tsx
  frontend-react/src/components/Content/MarkdownLayout.test.tsx
  frontend-react/src/components/Content/MarkdownLayout.tsx
  frontend-react/src/components/Content/MarkdownRSLink.test.tsx
  frontend-react/src/components/Content/MarkdownRSLink.tsx
  frontend-react/src/components/Content/MarkdownRenderer.tsx
  frontend-react/src/components/USLink.test.tsx
  frontend-react/src/components/USLink.tsx
  frontend-react/src/shared/SideNav.test.tsx
  frontend-react/src/shared/SideNav.tsx
Labels: experience

#9012 8752 Added CA receiver transforms to truncate fields needed for CA
  prime-router/metadata/hl7_mapping/STLTs/CA/CA.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/ca-observation-request.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/ca-observation-result.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/ca-order-observation.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/ca-order.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/ca-patient.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/ca-specimen.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_truncate_CA_20230406-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_truncate_CA_20230406-0001.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: pipeline, platform

#9059 Add h4 font size, small body size styles
  frontend-react/src/styles/_typography.scss
  frontend-react/src/styles/_uswds_settings.scss
  frontend-react/src/styles/styles.stories.tsx
Labels: frontend, experience

#9028 9009 Moved NTE (AOE notes) between the OBX and SPM segments
  prime-router/metadata/hl7_mapping/ORU_R01/base/specimen.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/CA.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/ca-aoe-note.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/ca-observation-result.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/ca-order-note.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/ca-specimen.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SR_1_20230302-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_truncate_CA_20230406-0001.hl7
Labels: pipeline, platform

#9033 Experience/8939/remove-react-dev-utils-dependency
  frontend-react/.babelrc.js
  frontend-react/.eslintrc.js
  frontend-react/.storybook/main.js
  frontend-react/config/babel/create.js
  frontend-react/config/babel/dependencies.js
  frontend-react/config/babel/dev.js
  frontend-react/config/babel/index.js
  frontend-react/config/babel/prod.js
  frontend-react/config/babel/test.js
  frontend-react/config/babel/webpack-overrides.js
  frontend-react/config/getHttpsConfig.js
  frontend-react/config/jest/babelTransform.js
  frontend-react/config/modules.js
  frontend-react/config/paths.js
  frontend-react/config/webpack.config.js
  frontend-react/config/webpackDevServer.config.js
  frontend-react/react-dev-utils/FileSizeReporter.js
  frontend-react/react-dev-utils/ForkTsCheckerWarningWebpackPlugin.js
  frontend-react/react-dev-utils/InlineChunkHtmlPlugin.js
  frontend-react/react-dev-utils/InterpolateHtmlPlugin.js
  frontend-react/react-dev-utils/ModuleNotFoundPlugin.js
  frontend-react/react-dev-utils/ModuleScopePlugin.js
  frontend-react/react-dev-utils/WebpackDevServerUtils.js
  frontend-react/react-dev-utils/browsersHelper.js
  frontend-react/react-dev-utils/checkRequiredFiles.js
  frontend-react/react-dev-utils/clearConsole.js
  frontend-react/react-dev-utils/errorOverlayMiddleware.js
  frontend-react/react-dev-utils/eslintFormatter.js
  frontend-react/react-dev-utils/evalSourceMapMiddleware.js
  frontend-react/react-dev-utils/formatWebpackMessages.js
  frontend-react/react-dev-utils/getCSSModuleLocalIdent.js
  frontend-react/react-dev-utils/getCacheIdentifier.js
  frontend-react/react-dev-utils/getProcessForPort.js
  frontend-react/react-dev-utils/getPublicUrlOrPath.js
  frontend-react/react-dev-utils/ignoredFiles.js
  frontend-react/react-dev-utils/launchEditor.js
  frontend-react/react-dev-utils/launchEditorEndpoint.js
  frontend-react/react-dev-utils/noopServiceWorkerMiddleware.js
  frontend-react/react-dev-utils/openBrowser.js
  frontend-react/react-dev-utils/openChrome.applescript
  frontend-react/react-dev-utils/printBuildError.js
  frontend-react/react-dev-utils/printHostingInstructions.js
  frontend-react/react-dev-utils/redirectServedPathMiddleware.js
  frontend-react/react-dev-utils/webpackHotDevClient.js
  frontend-react/scripts/build.js
  frontend-react/scripts/start.js
  frontend-react/yarn.lock
Labels: experience

#9043 Universal Pipeline filter logging improvements
  prime-router/docs/features/0001-universal-pipeline-filter-reporting.md
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/DefaultFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/GetFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
Labels: platform

#9116 cert exp notification
  .github/actions/notifications/action.yml
  .github/workflows/keyvault-certificates.yaml
  .github/workflows/keyvault_cert.txt
Labels: DevOps

#8900 8670: check all JwkSets when resolving a signing key
  prime-router/examples/generate-jwt-python/.gitignore
  prime-router/examples/generate-jwt-python/generate-jwt.py
  prime-router/src/main/kotlin/azure/ApiKeysFunctions.kt
  prime-router/src/main/kotlin/azure/TokenFunction.kt
  prime-router/src/main/kotlin/cli/SenderUtilsCommand.kt
  prime-router/src/main/kotlin/tokens/AuthenticatedClaims.kt
  prime-router/src/main/kotlin/tokens/Jwk.kt
  prime-router/src/main/kotlin/tokens/SenderUtils.kt
  prime-router/src/main/kotlin/tokens/Server2ServerAuthentication.kt
  prime-router/src/test/kotlin/azure/ApiKeysFunctionsTest.kt
  prime-router/src/test/kotlin/azure/MessagesFunctionsTests.kt
  prime-router/src/test/kotlin/azure/TokenFunctionTests.kt
  prime-router/src/test/kotlin/tokens/AuthenticatedClaimsTests.kt
  prime-router/src/test/kotlin/tokens/JwkTests.kt
  prime-router/src/test/kotlin/tokens/Server2ServerAuthenticationTests.kt
Labels: platform

#8993 Experience-8202: Add proposal for website-API communication
  prime-router/docs/proposals/0019-website-api-payload-structure.md
Labels: experience

#9056 8918: update server 2 server auth docs
  prime-router/docs/ReportStream-Programmers-Guide-v2.4.docx
  prime-router/docs/features/0002-authentication.md
  prime-router/docs/playbooks/how-to-use-token-auth.md
  prime-router/examples/generate-jwt-python/generate-jwt.py
  prime-router/src/main/kotlin/cli/SenderUtilsCommand.kt
Labels: platform

#9019 Experience-8928: Add Chromatic GHA
  .github/workflows/chromatic-master.yml
  .github/workflows/chromatic-pr.yml
  .gitignore
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: experience, chromatic

#9206 Feature/staleitems report
  .github/scripts/stale_items_report/StaleIssues.ps1
  .github/scripts/stale_items_report/StalePullRequests.ps1
  .github/scripts/stale_items_report/Stale_Branches.ps1
  .github/scripts/stale_items_report/excludebrancheslist.txt
  .github/workflows/StaleItemsReport.yml
Labels: DevOps, reportstream

#9108 8490: delete API key endpoint
  prime-router/docs/api/api-keys.yml
  prime-router/src/main/kotlin/azure/ApiKeysFunctions.kt
  prime-router/src/main/kotlin/azure/HttpUtilities.kt
  prime-router/src/main/kotlin/cli/SenderUtilsCommand.kt
  prime-router/src/main/kotlin/cli/SettingCommands.kt
  prime-router/src/main/kotlin/cli/tests/AuthTests.kt
  prime-router/src/main/kotlin/tokens/Jwk.kt
  prime-router/src/test/kotlin/azure/ApiKeysFunctionsTest.kt
  prime-router/src/test/kotlin/tokens/JwkTests.kt
Labels: platform

#9099 item_lineage_descendants stored function
  prime-router/src/main/resources/db/migration/V63__item_lineage_descendants.sql
Labels: platform

#9236 Experience-9235: Fix storybook command
  frontend-react/package.json
Labels: experience

#9228 Add user story issue template
  .github/ISSUE_TEMPLATE/platform-user-story.md
Labels: platform

#9247 MDX plugin support
  frontend-react/.storybook/main.js
  frontend-react/config/webpack.config.js
  frontend-react/scripts/build.js
  frontend-react/scripts/start.js
Labels: experience, engineering

#9182 Reorganize transform schemas for the Universal Pipeline
  prime-router/docs/features/0002-universal-pipeline-sender-transforms.md
  prime-router/metadata/fhir_transforms/fhir-transform-sample.yml
  prime-router/metadata/fhir_transforms/senders/Flexion/TrustedIntermediaryLabOrder.yml
  prime-router/metadata/fhir_transforms/senders/default-sender-transform.yml
  prime-router/metadata/hl7_mapping/receivers/Flexion/TrustedIntermediaryLabOrder.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/CA.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-aoe-note.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-observation-request.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-observation-result.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-order-note.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-order-observation.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-order.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-patient-note.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-patient.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-specimen.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CO/CO.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CO/co-observation-result.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CO/co-order-observation.yml
  prime-router/settings/organizations.yml
  prime-router/settings/prod/0150-CA-Add-FullELR-SaphireStage-Receiver.yml
  prime-router/settings/staging/0149-etor.yml
  prime-router/settings/staging/0150-CA-Add-FullELR-SaphireStage-Receiver.yml
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: platform

#9252 9217 - removed button to Upload a new public key
  frontend-react/src/components/ManagePublicKey/ManagePublicKey.test.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKey.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKeyConfigured.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKeyUploadError.tsx
Labels: frontend, experience, trialfrontend02

#9308 Update Resources Page
  frontend-react/src/content/resources/ResourcesIndex.mdx
Labels: experience

#9234 8955 - FAQ Website Content Update
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/Content/MarkdownLayout.tsx
  frontend-react/src/content/resources/ResourcesIndex.mdx
  frontend-react/src/content/support/faq/FaqIndex.mdx
  frontend-react/src/content/support/index.ts
  frontend-react/src/pages/support/faq/FaqPage.stories.tsx
  frontend-react/src/pages/support/faq/FaqPage.tsx
  frontend-react/src/pages/support/index-legacy.ts
  frontend-react/src/pages/support/legacy-page-content/Faq.tsx
  frontend-react/src/styles/_reportstream.scss
Labels: frontend, experience, trialfrontend03

#9040 Update release-notes.md
  frontend-react/src/content/product/release-notes.md
Labels: experience

#9147 Remaining deduplication of dependencies in /frontend-react
  .github/actions/build-frontend/action.yml
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: security, dependencies, javascript

#9307 9224 correct database entries when UP routing sends to no receivers
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
Labels: pipeline, platform
