Repository CDCgov/prime-reportstream, pull requests merged in 2023-02, with the labels that each got.

#8171 Update TOS on site
  frontend-react/src/pages/TermsOfService.tsx
Labels: experience

#8117 Oo/oslynn/8062/add batch header replace value awith b
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
  prime-router/src/testIntegration/kotlin/serializers/Hl7SerializerIntegrationTests.kt
  prime-router/src/testIntegration/resources/settings/organizations.yml
Labels: onboarding-ops

#8192 8129 Turn Utah Blue on the public map
  frontend-react/src/content/live.json
  frontend-react/src/content/usa_w_territories.svg
Labels: frontend, experience

#8206 Updated Jacoco version to support JDK 17 and 18
  prime-router/build.gradle.kts
Labels: pipeline

#8140 Victor/7932 UP accepts bulk FHIR bundles
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/Sender.kt
  prime-router/src/main/kotlin/SubmissionReceiver.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/utils/FhirTranscoder.kt
  prime-router/src/main/kotlin/history/SubmissionHistory.kt
  prime-router/src/test/kotlin/SubmissionReceiverTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/utils/FhirTranscoderTests.kt
  prime-router/src/test/kotlin/history/SubmissionHistoryTests.kt
  prime-router/src/test/resources/fhirengine/engine/bulk_valid_data.fhir
  prime-router/src/test/resources/fhirengine/engine/routing/valid.fhir
  prime-router/src/test/resources/fhirengine/engine/valid_data.fhir
Labels: pipeline, platform

#8181 Read up sender transform config
  prime-router/src/main/kotlin/azure/CheckFunction.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReader.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/converter/ConverterSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/converter/ConverterSchemaReader.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/fhirTransform/FHIRTransformSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/fhirTransform/FHIRTransformSchemaReader.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/ExceptionTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReaderTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/converter/ConverterSchemaTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/fhirTransform/FHIRTransformSchemaTests.kt
  prime-router/src/test/resources/fhir_sender_transforms/circular_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/extends_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/incomplete_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/invalid_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/observation.yml
  prime-router/src/test/resources/fhir_sender_transforms/sample_schema.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-06/ORU_R01.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-06/ORU_R01/header.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-06/ORU_R01/observation.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-06/ORU_R01/order-observation.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-06/ORU_R01/patient-identification.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-06/ORU_R01/patient.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-06/ORU_R01_circular.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-06/ORU_R01_extends.yml
Labels: platform

#8239 7932 Added missing unit test for bulk FHIR bundles
  prime-router/src/test/kotlin/fhirengine/utils/FhirTranscoderTests.kt
  prime-router/src/test/resources/fhirengine/engine/bulk_valid_data.fhir
Labels: platform

#8201 Experience-7773: Add schema dropdown on validator page
  frontend-react/src/components/FileHandlers/FileHandler.test.tsx
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/components/FileHandlers/FileHandlerForm.test.tsx
  frontend-react/src/components/FileHandlers/FileHandlerForm.tsx
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx
  frontend-react/src/hooks/UseCreateFetch.ts
  frontend-react/src/hooks/UseFileHandler.test.ts
  frontend-react/src/hooks/UseFileHandler.ts
  frontend-react/src/hooks/UseSenderResource.ts
  frontend-react/src/hooks/network/WatersHooks.test.ts
  frontend-react/src/hooks/network/WatersHooks.ts
  frontend-react/src/pages/Validate.tsx
  frontend-react/src/senders/hooks/UseSenderSchemaOptions/UseSenderSchemaOptions.test.ts
  frontend-react/src/senders/hooks/UseSenderSchemaOptions/index.ts
Labels: experience, engineering

#8261 7933 Submission history API supports bulk FHIR submissions
  prime-router/src/main/kotlin/azure/ValidateFunction.kt
  prime-router/src/main/kotlin/history/SubmissionHistory.kt
  prime-router/src/test/kotlin/history/SubmissionHistoryTests.kt
Labels: pipeline, platform

#8268 8180 Convert SR FHIR samples
  prime-router/metadata/hl7_mapping/ORU_R01/base/datatype/xpn-person-name.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/datatype/xtn-telecom.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/message-header.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/patient.yml
  prime-router/metadata/hl7_mapping/Senders/SimpleReport.yml
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/FhirPathUtilsTests.kt
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0001-expected-CO.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0001-expected-base.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0004-expected-base.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0014-expected-base.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0019-expected-CO.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0019-expected-base.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/test_playground_20220930-0001-expected-CO.hl7
Labels: platform

#8190 7754 - Redesign Message Tracker Sender Details
  frontend-react/src/components/DetailItem/DetailItem.tsx
  frontend-react/src/components/MessageTracker/MessageDetails.test.tsx
  frontend-react/src/components/MessageTracker/MessageDetails.tsx
  frontend-react/src/components/MessageTracker/MessageReceivers.tsx
  frontend-react/src/components/MessageTracker/MessageTracker.tsx
  frontend-react/src/components/MessageTracker/WarningsErrors.tsx
  frontend-react/src/styles/_components.scss
  frontend-react/src/styles/_uswds_overrides.scss
  frontend-react/src/utils/misc.test.ts
  frontend-react/src/utils/misc.ts
Labels: frontend, experience

#8070 Bump org.hl7.fhir.utilities from 5.6.36 to 5.6.92 in /prime-router
  prime-router/build.gradle.kts
Labels: security, dependencies, java

#8253 Remove extra <hr>s wrapping breadcrumb component, fixes #8252
  frontend-react/src/components/Crumbs.tsx
Labels: bug, experience

#8323 Experience-8161: Remove makeOktaHook logic
  frontend-react/src/App.tsx
  frontend-react/src/components/AppWrapper.tsx
  frontend-react/src/components/SenderModeBanner.test.tsx
  frontend-react/src/contexts/SessionContext.tsx
  frontend-react/src/utils/CustomRenderUtils.tsx
Labels: experience, engineering

#8324 Update release-notes.md
  frontend-react/src/content/product/release-notes.md
Labels: experience

#8334 Upgrade to Cypress v12
  frontend-react/cypress.config.ts
  frontend-react/cypress/support/commands/auth.ts
  frontend-react/cypress/support/pages/Base.ts
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: experience, engineering

#8326 8241 Update email address in Terms of Service
  frontend-react/src/pages/TermsOfService.tsx
  frontend-react/src/pages/resources/legacy-page-content/AccountRegistrationGuide.tsx
Labels: frontend, experience

#8350 Update dompurify to 3.0.X
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: experience

#8351 Upgrade react-idle-timer to 5.5.x
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: experience

#8389 Fixed Hl7Serializer to produce PID-13 correctly
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/hl7_test_files/batch_message.hl7
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
Labels: onboarding-ops

#8392 Non-breaking visual hiccups from USWDS 3.0 upgrade
  frontend-react/package.json
  frontend-react/src/global.scss
  frontend-react/src/styles/_color.scss
  frontend-react/src/styles/_components.scss
  frontend-react/src/styles/_reportstream.scss
  frontend-react/src/styles/_uswds_custom_theme.scss
  frontend-react/src/styles/_uswds_overrides.scss
  frontend-react/src/styles/_uswds_settings.scss
  frontend-react/yarn.lock
Labels: experience

#8349 Upgrade to msw 1.0.x
  frontend-react/.env.test
  frontend-react/package.json
  frontend-react/src/__mocks__/DeliveriesMockServer.ts
  frontend-react/src/__mocks__/OrganizationMockServer.ts
  frontend-react/src/__mocks__/WatersMockServer.ts
  frontend-react/src/components/Admin/AdminReceiverDashboard.tsx
  frontend-react/src/components/Admin/EditReceiverSettings.test.tsx
  frontend-react/src/components/Admin/EditSenderSettings.test.tsx
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.test.tsx
  frontend-react/src/components/RSErrorBoundary.test.tsx
  frontend-react/src/components/Table/Table.test.tsx
  frontend-react/src/config/endpoints/RSEndpoint.test.ts
  frontend-react/src/hooks/UseCreateFetch.test.ts
  frontend-react/src/hooks/UseCreateFetch.ts
  frontend-react/src/hooks/UseOrganizationReceiversFeed.test.ts
  frontend-react/src/hooks/UseValueSetActivation.test.ts
  frontend-react/src/hooks/UseValueSetUpdate.test.ts
  frontend-react/src/hooks/UseValueSets.test.ts
  frontend-react/src/hooks/UseValueSetsMeta.test.ts
  frontend-react/src/hooks/UseValueSetsTable.test.ts
  frontend-react/src/hooks/filters/mocks/MockFilterManager.ts
  frontend-react/src/hooks/network/History/DeliveryHooks.test.ts
  frontend-react/src/hooks/network/History/UseOrgDeliveries.test.ts
  frontend-react/src/hooks/network/History/UseReportDetail.test.ts
  frontend-react/src/hooks/network/History/UseReportFacilities.test.ts
  frontend-react/src/hooks/network/History/UseReportsList.test.ts
  frontend-react/src/hooks/network/WatersHooks.test.ts
  frontend-react/src/network/QueryClients.ts
  frontend-react/src/pages/Validate.test.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.test.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.test.tsx
  frontend-react/src/pages/deliveries/Table/ReportsUtils.test.ts
  frontend-react/src/utils/CustomRenderUtils.tsx
  frontend-react/src/utils/DiffCompare/JsonSourceMap.test.ts
  frontend-react/src/utils/TestUtils.ts
  frontend-react/yarn.lock
Labels: experience

#8422 Bump node.js from 16.19.0 to 16.19.1 in /frontend-react
  .github/actions/build-frontend/action.yml
  frontend-react/.nvmrc
  frontend-react/package.json
Labels: security, frontend, dependencies, javascript

#8452 chore: update yarn.lock
  frontend-react/yarn.lock
Labels: experience

#8267 [SPIKE] Migrate frontend to manual Webpack 5 config
  frontend-react/.babelrc.js
  frontend-react/.eslintrc.js
  frontend-react/config/env.js
  frontend-react/config/getHttpsConfig.js
  frontend-react/config/jest/babelTransform.js
  frontend-react/config/jest/cssTransform.js
  frontend-react/config/jest/fileTransform.js
  frontend-react/config/modules.js
  frontend-react/config/paths.js
  frontend-react/config/webpack.config.js
  frontend-react/config/webpack/persistentCache/createEnvironmentHash.js
  frontend-react/config/webpackDevServer.config.js
  frontend-react/jest.config.ts
  frontend-react/package.json
  frontend-react/scripts/build.js
  frontend-react/scripts/start.js
  frontend-react/scripts/test.js
  frontend-react/src/react-app-env.d.ts
  frontend-react/tsconfig.json
  frontend-react/yarn.lock
Labels: experience

#8160 Created a method that allows you to look up the LOINC code for a FHIR…
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctions.kt
  prime-router/src/main/kotlin/metadata/LivdLookup.kt
  prime-router/src/main/kotlin/metadata/LivdMappers.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctionsTests.kt
  prime-router/src/test/kotlin/metadata/LivdLookupTests.kt
  prime-router/src/test/kotlin/metadata/LivdMapperTests.kt
Labels: pipeline, platform

#8295 Experience/8157/redesign message tracker table
  frontend-react/src/components/MessageTracker/MessageDetails.test.tsx
  frontend-react/src/components/MessageTracker/MessageDetails.tsx
  frontend-react/src/components/MessageTracker/MessageReceivers.test.tsx
  frontend-react/src/components/MessageTracker/MessageReceivers.tsx
  frontend-react/src/config/endpoints/RSEndpoint.test.ts
  frontend-react/src/styles/_components.scss
  frontend-react/src/styles/_uswds_settings.scss
Labels: experience

#8381 FHIR Transcoder test cleanup
  prime-router/src/test/kotlin/fhirengine/utils/FhirTranscoderTests.kt
Labels: pipeline, platform

#8348 7998 date range filter bug fix
  frontend-react/src/components/Table/TableFilters.test.tsx
  frontend-react/src/components/Table/TableFilters.tsx
  frontend-react/src/hooks/filters/UseDateRange.test.ts
  frontend-react/src/hooks/filters/UseDateRange.ts
  frontend-react/src/hooks/filters/mocks/MockFilterManager.ts
Labels: frontend, experience

#8441 Victor/8096 remove FHIR resources
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/BundleUpdateTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/FHIRBundleHelpersTests.kt
  prime-router/src/test/resources/fhirengine/engine/bundle_diagnostic_report_no_observations.fhir
  prime-router/src/test/resources/fhirengine/engine/bundle_multiple_observations.fhir
Labels: pipeline, platform

#8484 CA Adds SaphireStaging receiver
  prime-router/settings/prod/0148-CA-Add-SaphireStage-Receiver.yml
  prime-router/settings/staging/0148-CA-Add-SaphireStage-Receiver.yml
Labels: onboarding-ops
