Repository CDCgov/prime-reportstream, pull requests merged in 2023-10, with the labels that each got.

#11556 11460 - Added NoServicesBanner to table component.
  frontend-react/src/components/DataDashboard/DataDashboardTable/DataDashboardTable.test.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsTable.test.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKey.tsx
  frontend-react/src/components/Table/Table.tsx
  frontend-react/src/components/alerts/NoServicesAlert.tsx
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.tsx
  frontend-react/src/shared/Table/Table.tsx
Labels: frontend, experience, trialfrontend01

#11215 Cleaning of Settings Functions and addition of tests
  prime-router/src/main/kotlin/azure/SettingsFunctions.kt
  prime-router/src/test/kotlin/azure/SettingFacadeTests.kt
Labels: platform

#11597 Bump node.js to 18.18 in /frontend-react
  frontend-react/.nvmrc
  frontend-react/package.json
Labels: security, dependencies, javascript

#11558 10484 BlobAccess can access alternate environments
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/main/kotlin/common/Environment.kt
  prime-router/src/main/kotlin/transport/BlobStoreTransport.kt
  prime-router/src/test/kotlin/azure/BatchFunctionTests.kt
  prime-router/src/test/kotlin/azure/BlobAccessTests.kt
  prime-router/src/test/kotlin/azure/HistoryFunctionsTests.kt
  prime-router/src/test/kotlin/azure/SenderFilesFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReaderTests.kt
Labels: platform

#11638 Update precommit hook script to bypass klint if nothing has changed under /prime-router (#6842)
  .environment/ktlint/run-ktlintCheck.sh
Labels: DevOps, enhancement

#11605 11512 - About landing page: Update Recommended resources card descriptions
  frontend-react/src/content/about/index.mdx
Labels: frontend, experience

#11645 Added missing OKTA variable references in function_app module in DEMO env
  operations/app/terraform/vars/demo/main.tf
Labels: bug, DevOps

#11606 11592 - Getting Started updates
  frontend-react/src/content/getting-started/index.mdx
Labels: frontend, experience, trialfrontend02

#11571 Add codeowners for backend
  .github/CODEOWNERS
Labels: platform

#11600 11549: NTE HL7 -> FHIR -> HL7
  prime-router/metadata/fhir_mapping/hl7/datatype/Annotation.yml
  prime-router/metadata/hl7_mapping/common/note.yml
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/nte_note/NTETests.kt
  prime-router/src/testIntegration/resources/datatests/mappinginventory/NTE/NTE-to-Annotation.csv
  prime-router/src/testIntegration/resources/datatests/mappinginventory/NTE/annotation_author_string_resource_test_file.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/NTE/annotation_resource_test_file.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/NTE/nte_segment_author_string_test_file.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/NTE/nte_segment_test_file.hl7
Labels: platform

#11617 Webx sprint 77 feature branch
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/header/ReportStreamNavbar.tsx
  frontend-react/src/content/about/case-studies.mdx
  frontend-react/src/content/about/index.mdx
  frontend-react/src/content/about/release-notes.mdx
  frontend-react/src/content/about/security.mdx
  frontend-react/src/content/about/sidenav.mdx
  frontend-react/src/content/developer-resources/index-page.mdx
  frontend-react/src/content/getting-started/sending-data.mdx
  frontend-react/src/content/home/index.mdx
  frontend-react/src/content/product/release-notes.mdx
  frontend-react/src/content/product/sidenav.mdx
  frontend-react/src/content/resources/ResourcesIndex.mdx
  frontend-react/src/content/resources/index.ts
  frontend-react/src/content/support/index.mdx
  frontend-react/src/pages/resources/index-legacy.ts
  frontend-react/src/pages/resources/legacy-page-content/SecurityPractices.tsx
  frontend-react/src/shared/ReleaseNote/ReleaseNote.module.scss
  frontend-react/src/shared/ReleaseNote/ReleaseNote.stories.tsx
  frontend-react/src/shared/ReleaseNote/ReleaseNote.tsx
  frontend-react/src/shared/index.ts
  frontend-react/src/styles/_components.scss
Labels: frontend, experience, trialfrontend01

#11622 Experience/11553/news
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/header/ReportStreamNavbar.tsx
  frontend-react/src/content/about/case-studies.mdx
  frontend-react/src/content/about/index.mdx
  frontend-react/src/content/about/news.mdx
  frontend-react/src/content/about/sidenav.mdx
Labels: frontend, experience, trialfrontend02

#11566 Simplify OBX2 string mapping
  prime-router/metadata/hl7_mapping/common/observation-result.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001-custom-datetime.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_2_20230220-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_RADx_MARS_20230406-0002.hl7
Labels: pipeline, platform

#11726 Massive Dependabot PR Closure
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: experience

#11463 HL7 NK1 Mapping for OML
  prime-router/metadata/hl7_mapping/common/patient-contact.yml
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctions.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_OML_20230831-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_OML_20230831-0001.hl7
Labels: platform

#11742 postcss lock
  frontend-react/yarn.lock
Labels: security, dependencies, javascript

#11743 dedupe to eliminate vulnerable/obsolete versions
  frontend-react/yarn.lock
Labels: security, dependencies, javascript

#11483 Fix repeated download in Batch step
  prime-router/src/main/kotlin/azure/BatchFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/test/kotlin/azure/BatchFunctionTests.kt
Labels: pipeline, platform

#11506 Cleaned up the bundle enhancing methods by moving them out into their…
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/translation/HL7toFhirTranslator.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/BundleUpdateTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/FHIRBundleHelpersTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
  prime-router/src/test/resources/fhirengine/engine/fhir_without_birth_time.fhir
  prime-router/src/test/resources/fhirengine/engine/fhir_without_patient.fhir
  prime-router/src/test/resources/fhirengine/engine/hl7_2.6.hl7
  prime-router/src/test/resources/fhirengine/engine/hl7_2.7.hl7
  prime-router/src/test/resources/fhirengine/engine/hl7_with_birth_time.hl7
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
Labels: pipeline, platform

#11728 Bump jooq from 3.15.4 to 3.18.6 in /prime-router
  prime-router/build.gradle.kts
Labels: security, dependencies, java

#11729 Change node spec to match only major version
  frontend-react/package.json
Labels: security, dependencies, javascript

#11820 Fixing the Build Frontend workflow to fail if any of the tests fail
  .github/actions/build-frontend/action.yml
  .github/workflows/build_frontend.yaml
Labels: bug, DevOps

#11787 11472 add mapping schema organization document
  prime-router/docs/design/design/mapping-schemas.md
Labels: platform

#11783 Dependency grab bag + Fix test suite
  frontend-react/package.json
  frontend-react/patches/@trussworks+react-uswds+5.3.0.patch
  frontend-react/src/components/Admin/EditReceiverSettings.test.tsx
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilitiesProvidersTable.test.tsx
  frontend-react/src/components/FileHandlers/FileHandler.test.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKey.test.tsx
  frontend-react/src/components/MessageTracker/MessageReceivers.test.tsx
  frontend-react/src/global.scss
  frontend-react/src/styles/react-uswds-fixed.css
  frontend-react/yarn.lock
Labels: experience

#11846 Bump @babel/traverse from 7.23.0 to 7.23.2 in /frontend-react
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: security, dependencies, javascript

#11851 11829: cleanup hd xon mappings
  prime-router/metadata/fhir_mapping/hl7/resource/MessageHeader.yml
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_orm_20230809-001.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/NTE/annotation_resource_test_file.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/hd/HD-to-Location-iso.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/hd/HD-to-Location-uuid.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/hd/HD-to-Organization-clia.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/hd/HD-to-Organization-empty-hd3.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/hd/HD-to-Organization-iso.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/hd/HD-to-Organization-uuid.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/hd/HD-to-extensionAssigningAuthority-iso.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/hd/HD-to-extensionAssigningAuthority-uuid.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xtn/xtn_2_use_code_home.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xtn/xtn_2_use_code_mobile.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xtn/xtn_2_use_code_work.fhir
Labels: platform

#11785 11557 - Homepage updates
  frontend-react/public/assets/img/home/network.png
  frontend-react/src/content/home/index.mdx
  frontend-react/src/pages/tos-sign/TermsOfServiceForm.test.tsx
  frontend-react/src/shared/LiveMap/LiveMap.tsx
Labels: frontend, experience, trialfrontend02

#11831 LA-PHL sender and receiver onboarding
  prime-router/settings/staging/0156-LA-PHL-Sender-And-Receiver-Onboarding.yml
Labels: onboarding-ops, etor

#11858 revert checksum to "v1" since chromatic does not support versioning
  .github/workflows/chromatic-master.yml
  .github/workflows/chromatic-pr.yml
Labels: DevOps, dependencies, github_actions

#11860 11472 reorganize HD->Organization->HD mappings
  prime-router/metadata/fhir_mapping/hl7/datatype/deprecated.md
  prime-router/metadata/fhir_mapping/hl7/datatypes/HD/ExtensionAssigningAuthority.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/HD/Location.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/HD/Organization.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/XON/Organization.yml
  prime-router/metadata/fhir_mapping/hl7/message/ORM_O01.yml
  prime-router/metadata/fhir_mapping/hl7/message/ORU_R01.yml
  prime-router/metadata/fhir_mapping/hl7/message/deprecated.md
  prime-router/metadata/fhir_mapping/hl7/resource/deprecated.md
  prime-router/metadata/fhir_mapping/hl7/segments/MSH/MessageHeader.yml
  prime-router/metadata/hl7_mapping/ADT_A01/ADT_A01-base.yml
  prime-router/metadata/hl7_mapping/ADT_A01/deprecated.md
  prime-router/metadata/hl7_mapping/OML_O21/OML_O21-base.yml
  prime-router/metadata/hl7_mapping/OML_O21/deprecated.md
  prime-router/metadata/hl7_mapping/ORU_R01/ORU_R01-base.yml
  prime-router/metadata/hl7_mapping/ORU_R01/deprecated.md
  prime-router/metadata/hl7_mapping/common/datatype/xon-organization.yml
  prime-router/metadata/hl7_mapping/common/deprecated.md
  prime-router/metadata/hl7_mapping/datatypes/extensionAssigningAuthority/HD.yml
  prime-router/metadata/hl7_mapping/resources/Location/HD.yml
  prime-router/metadata/hl7_mapping/resources/MessageHeader/MSH.yml
  prime-router/metadata/hl7_mapping/resources/Organization/HD.yml
  prime-router/metadata/hl7_mapping/resources/Organization/XON.yml
Labels: platform

#11744 Added support to convert timestamps to date times in the UP
  frontend-react/src/shared/ReleaseNote/ReleaseNote.module.scss
  prime-router/src/main/kotlin/fhirengine/engine/CustomTranslationFunctions.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/ConfigSchemaProcessor.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/TranslationFunctions.kt
  prime-router/src/test/kotlin/fhirengine/engine/CustomTranslationFunctionsTest.kt
  prime-router/src/test/kotlin/unittest/UnitTestUtils.kt
Labels: onboarding-ops

#11745 11650: update CompareFhirData to handle all entries
  prime-router/metadata/fhir_mapping/hl7/datatype/ContactPoint.yml
  prime-router/src/main/kotlin/fhirengine/utils/CompareFhirData.kt
Labels: platform

#11641 platform/jimfuqian/10488 - Add functions listing blobs used by the pipeline
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/test/kotlin/azure/BlobAccessTests.kt
Labels: platform

#11849 11611 strict fhir comparison
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/fhirengine/utils/CompareFhirData.kt
  prime-router/src/test/kotlin/fhirengine/utils/CompareFhirDataTests.kt
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_orm_20230809-001.fhir
Labels: platform

#11857 10489: implement function to copy dir
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/test/kotlin/azure/BlobAccessTests.kt
Labels: platform

#11856 Experience/11724/receiving data
  frontend-react/src/AppRouter.tsx
  frontend-react/src/content/getting-started/index.mdx
  frontend-react/src/content/getting-started/receiving-data.mdx
  frontend-react/src/content/getting-started/sending-data.mdx
  frontend-react/src/content/getting-started/sidenav.mdx
  frontend-react/src/content/managing-your-connection/index.mdx
  frontend-react/src/content/managing-your-connection/sidenav.mdx
  frontend-react/src/pages/GettingStartedPhd.tsx
Labels: frontend, experience, trialfrontend01

#11932 Reformat yml files in `metadata`
  prime-router/metadata/fhir_mapping/hl7/datatype/Address.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Annotation.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/ContactPoint.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Entity_Identifier_Pair_1.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Entity_Identifier_Pair_2.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/HumanName.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Quantity.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Encounter.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/Contact.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/Hospitalization.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/timing-quantity.yml
  prime-router/metadata/hl7_mapping/common/datatype/ce-coded-with-exceptions.yml
  prime-router/metadata/hl7_mapping/common/datatype/xcn-contact.yml
  prime-router/metadata/hl7_mapping/common/patient.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/CA-receiver-transform.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-aoe-note.yml
Labels: platform

#11947 add db replica endpoint to staging terraform
  operations/app/terraform/vars/staging/locals.tf
Labels: DevOps, reportstream

#11927 Experience/11751/dashboard updates
  frontend-react/public/assets/img/DailyData.png
  frontend-react/public/assets/img/DataDashboard.png
  frontend-react/src/AppRouter.tsx
  frontend-react/src/content/home/index.mdx
  frontend-react/src/content/managing-your-connection/index.mdx
  frontend-react/src/pages/DataDownloadGuide.tsx
  frontend-react/src/pages/tos-sign/SuccessPage.test.tsx
  frontend-react/src/pages/tos-sign/SuccessPage.tsx
  frontend-react/src/pages/tos-sign/TermsOfServiceForm.test.tsx
  frontend-react/src/pages/tos-sign/TermsOfServiceForm.tsx
  frontend-react/src/shared/Tile/Tile.test.tsx
Labels: frontend, experience, trialfrontend02

#11974 Fixed get_ssh_list.sh to work on Bash versions prior to v4.
  .environment/sftp/get_ssh_list.sh
Labels: bug, DevOps, enhancement

#11929 Added DR datatype mappinng
  prime-router/metadata/fhir_mapping/hl7/datatypes/DR/Period.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/XAD/Address.yml
  prime-router/metadata/hl7_mapping/common/datatype/xad-extended-address.yml
  prime-router/metadata/hl7_mapping/datatypes/Address/XAD.yml
  prime-router/metadata/hl7_mapping/resources/Patient/DR.yml
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/dr/DrToPeriodTests.kt
  prime-router/src/testIntegration/resources/datatests/mappinginventory/dr/dr-to-period.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/dr/dr-to-period.hl7
Labels: pipeline, platform

#11931 11674: XAD[Address] mapping
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/DR/Period.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/XAD/Address.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/XON/Organization.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Patient.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/PatientContact.yml
  prime-router/metadata/hl7_mapping/ORU_R01/ORU_R01-test.yml
  prime-router/metadata/hl7_mapping/common/datatype/xad-extended-address.yml
  prime-router/metadata/hl7_mapping/common/patient-contact.yml
  prime-router/metadata/hl7_mapping/datatypes/Address/XAD.yml
  prime-router/metadata/hl7_mapping/resources/Patient/DR.yml
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/dr/DrToPeriodTests.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/xad/XADToAddress.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_2_20230220-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_RADx_MARS_20230406-0002.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/dr/dr-to-period.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/dr/dr-to-period.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-ignores-xad12-for-xad13.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-ignores-xad12-for-xad13.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-ignores-xad12-for-xad14.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-ignores-xad12-for-xad14.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-type-b.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-type-b.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-type-ba.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-type-ba.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-type-bi.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-type-bi.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-type-c.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-type-c.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-type-h.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-type-h.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-type-hv.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-type-hv.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-type-m.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-type-m.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-type-o.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-type-o.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-type-sh.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-type-sh.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-uses-xad12.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xad/xad-to-address-uses-xad12.hl7
Labels: platform

#11975 add new user type on FE
  frontend-react/src/components/AuthElement.test.tsx
  frontend-react/src/components/DataDashboard/DataDashboardTable/DataDashboardTable.test.tsx
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilitiesProvidersTable.test.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsSummary.test.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKey.test.tsx
  frontend-react/src/components/SenderModeBanner.test.tsx
  frontend-react/src/components/header/ReportStreamNavbar.stories.tsx
  frontend-react/src/components/header/ReportStreamNavbar.test.tsx
  frontend-react/src/components/header/ReportStreamNavbar.tsx
  frontend-react/src/contexts/SessionContext.tsx
  frontend-react/src/hooks/UseOrganizationReceivers.test.ts
  frontend-react/src/hooks/UseOrganizationReceiversFeed.test.ts
  frontend-react/src/hooks/UseOrganizationSenders.test.ts
  frontend-react/src/hooks/UseOrganizationSettings.test.ts
  frontend-react/src/hooks/UseSenderResource.test.ts
  frontend-react/src/hooks/network/DataDashboard/useReceiverDeliveries.test.ts
  frontend-react/src/hooks/network/DataDashboard/useReceiverSubmitters.test.ts
  frontend-react/src/hooks/network/History/UseOrgDeliveries.test.ts
  frontend-react/src/hooks/network/History/UseReportDetail.test.ts
  frontend-react/src/hooks/network/History/UseReportFacilities.test.ts
  frontend-react/src/hooks/network/History/UseReportsList.test.ts
  frontend-react/src/hooks/network/MessageTracker/MessageTrackerHooks.test.ts
  frontend-react/src/hooks/network/Organizations/PublicKeys/UseCreateOrganizationPublicKey.test.ts
  frontend-react/src/hooks/network/Organizations/PublicKeys/UseOrganizationPublicKeys.test.ts
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.test.tsx
  frontend-react/src/pages/submissions/SubmissionTable.test.tsx
  frontend-react/src/utils/PermissionsUtils.ts
Labels: blocked, experience, trialfrontend02
