Repository CDCgov/prime-reportstream, pull requests merged in 2023-07, with the labels that each got.

#10068 Updated the convertDateToAge function to take an another optional par…
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/helpers/ConvertDateToAge.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctionsTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/helpers/ConvertDateToAgeTests.kt
Labels: platform

#9929 Further updates to Submission History status logic
  prime-router/docs/features/0004-submission-status.md
  prime-router/src/main/kotlin/history/SubmissionHistory.kt
  prime-router/src/test/kotlin/history/SubmissionHistoryTests.kt
Labels: platform

#10171 #10148 Copy Update For Homepage
  frontend-react/public/assets/img/ReportStreamDiagram_2022.png
  frontend-react/src/content/content.json
  frontend-react/src/pages/home/Features/DeliveryMethodsFeature.tsx
  frontend-react/src/pages/home/Features/Feature.test.tsx
  frontend-react/src/pages/home/Hero.test.tsx
  frontend-react/src/pages/home/Hero.tsx
  frontend-react/src/pages/home/Home.test.tsx
  frontend-react/src/pages/home/Home.tsx
  frontend-react/src/pages/home/Sections/CtaSection.tsx
  frontend-react/src/pages/home/Sections/Section.test.tsx
  frontend-react/src/pages/home/Sections/Section.tsx
  frontend-react/src/styles/_reportstream.scss
Labels: experience, trialfrontend02

#10276 Experience/9986/common storybook components
  frontend-react/.storybook/UtilizedUSWDSComponents/Accordian.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/Alert.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/Banner.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/Breadcrumb.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/Button.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/ButtonGroup.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/Card.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/Datepicker.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/Dropdown.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/FileInput.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/ProcessList.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/SideNav.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/Tooltip.stories.tsx
  frontend-react/.storybook/main.ts
  frontend-react/.storybook/preview.tsx
  frontend-react/.storybook/react-uswds.stories.json
  frontend-react/src/components/ReportStreamFooter.stories.tsx
  frontend-react/src/components/StaticAlert.stories.tsx
  frontend-react/src/components/Table/Pagination.stories.tsx
  frontend-react/src/components/USLink.stories.tsx
  frontend-react/src/shared/Table/Table.stories.tsx
  frontend-react/src/styles/styles.stories.tsx
Labels: experience, chromatic

#9935 9395: deliveries v1 api
  prime-router/docs/api/delivery.yml
  prime-router/src/main/kotlin/history/azure/DeliveryFunction.kt
  prime-router/src/main/kotlin/history/db/DeliveryDatabaseAccess.kt
  prime-router/src/main/kotlin/history/db/ReportGraph.kt
  prime-router/src/test/kotlin/db/DeliveryDatabaseAccessTest.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFunctionTests.kt
Labels: platform

#10293 Experience/9722/programmers guide style updates
  frontend-react/src/pages/Login.tsx
Labels: frontend, experience

#10277 10167 - Fix bug where downloading a sample HL7 file requires a Google login
  frontend-react/public/assets/hl7/Example-hl7-file.hl7
  frontend-react/src/content/resources/reportstream-api/documentation/SamplePayloadsAndOutput.mdx
  frontend-react/src/content/site.json
Labels: frontend, experience

#9720 9397: search for providers, facilities, senders via new submitters API
  prime-router/docs/api/delivery.yml
  prime-router/src/main/kotlin/azure/ApiSearch.kt
  prime-router/src/main/kotlin/db/ReportFileDatabaseAccess.kt
  prime-router/src/main/kotlin/history/azure/DeliveryFunction.kt
  prime-router/src/main/kotlin/history/db/DeliveryDatabaseAccess.kt
  prime-router/src/main/kotlin/history/db/ReportGraph.kt
  prime-router/src/main/kotlin/history/db/SubmitterDatabaseAccess.kt
  prime-router/src/main/resources/db/migration/V65__action_sender_receiver.sql
  prime-router/src/test/kotlin/azure/ApiSearchTest.kt
  prime-router/src/test/kotlin/db/DeliveryDatabaseAccessTest.kt
  prime-router/src/test/kotlin/db/SubmitterDatabaseAccessTest.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFunctionTests.kt
Labels: API, platform

#9948 Add ETOR support to RESTTransport
  prime-router/settings/staging/0149-etor.yml
  prime-router/src/main/kotlin/TransportType.kt
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/main/kotlin/transport/TokenInfo.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
Labels: onboarding-ops

#10137 9362 add SFTP transport integration tests
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/transport/SftpTransport.kt
  prime-router/src/testIntegration/kotlin/transport/SftpTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/TransportIntegrationTests.kt
Labels: onboarding-ops

#10070 9411: Performance improvements for the STLT dashboard apis
  prime-router/src/main/kotlin/azure/ApiSearch.kt
  prime-router/src/main/kotlin/history/db/DeliveryDatabaseAccess.kt
  prime-router/src/main/kotlin/history/db/SubmitterDatabaseAccess.kt
Labels: platform

#10076 Add metadata design brief to tech proposal
  prime-router/docs/proposals/0020-universal-metadata-search/0020-universal-metadata-search.md
Labels: platform

#10314 Updating Staging URL for ETOR
  prime-router/settings/staging/0149-etor.yml
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
Labels: onboarding-ops

#10316 10315: return delivery details for a report_id for the send action
  prime-router/src/main/kotlin/history/azure/DeliveryFunction.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFunctionTests.kt
Labels: platform

#10117 jimfuqian/9285 Add OpenAPI spec generation task and generate spec for ApiKeysFunction.kt
  .gitignore
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/azure/ApiKeysFunctions.kt
  prime-router/src/test/kotlin/azure/ApiKeysFunctionsTest.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
Labels: platform

#10196 Bump gradle to 7.6.1 in /prime-router
  prime-router/Dockerfile.build
  prime-router/gradle/wrapper/gradle-wrapper.jar
  prime-router/gradle/wrapper/gradle-wrapper.properties
Labels: dependencies, java

#10369 10367: increase timeout for step polling and confirm batch results were found
  prime-router/src/main/kotlin/cli/tests/BasicTests.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
Labels: platform

#10362 Fixed Simple Report sender transform and timezone offsets
  prime-router/metadata/fhir_transforms/senders/SimpleReport/simple-report-sender-transform.yml
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_2_20230220-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SR_1_20230302-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_truncate_CA_20230406-0001.hl7
Labels: onboarding-ops

#10424 Increase smoketest timeout and update generate-jwt example print out
  prime-router/examples/generate-jwt-python/generate-jwt.py
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
Labels: platform

#10078 7275: manage translation schemas proposal
  prime-router/docs/features/0005-managing-translation-schemas.md
Labels: platform

#9736 Replace alerts with Tip Callout Component
  frontend-react/package.json
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/components/FileHandlers/FileHandlerProgrammersGuideTip.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKey.tsx
  frontend-react/src/content/resources/reportstream-api/ReportStreamApi.mdx
  frontend-react/src/content/resources/reportstream-api/documentation/Documentation.mdx
  frontend-react/src/content/resources/reportstream-api/documentation/ResponsesFromReportStream.mdx
  frontend-react/src/content/resources/reportstream-api/documentation/data-model/DataModel.mdx
  frontend-react/src/content/resources/reportstream-api/documentation/data-model/OrderingProviderDataElementsTable.mdx
  frontend-react/src/content/resources/reportstream-api/getting-started/GettingStarted.mdx
  frontend-react/src/content/resources/reportstream-api/getting-started/Method1.mdx
  frontend-react/src/shared/Alert/Alert.module.scss
  frontend-react/src/shared/Alert/Alert.stories.tsx
  frontend-react/src/shared/Alert/Alert.test.tsx
  frontend-react/src/shared/Alert/Alert.tsx
  frontend-react/src/shared/Icon/Icon.stories.tsx
  frontend-react/src/shared/Icon/Icon.test.tsx
  frontend-react/src/shared/Icon/Icon.tsx
  frontend-react/src/styles/_reportstream.scss
  frontend-react/src/styles/_uswds_overrides.scss
Labels: experience, trialfrontend03, chromatic

#10426 Add elr-elims topic for UP
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/Sender.kt
  prime-router/src/main/kotlin/SettingsProvider.kt
  prime-router/src/main/kotlin/cli/tests/BasicTests.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/GetFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
Labels: platform

#10431 feat: convert legacy markdown files into MDX
  frontend-react/src/content/resources/getting-started-submitting-data.mdx
  frontend-react/src/content/resources/referral-guide.mdx
  frontend-react/src/pages/resources/markdown-adapters.tsx
Labels: experience

#10443 Experience/10387/sender bug
  frontend-react/src/__mocks__/OrganizationMockServer.ts
  frontend-react/src/components/FileHandlers/FileHandlerFileUploadStep.test.tsx
  frontend-react/src/components/FileHandlers/FileHandlerFileUploadStep.tsx
  frontend-react/src/components/SenderModeBanner.tsx
  frontend-react/src/hooks/UseSenderResource.test.ts
  frontend-react/src/hooks/UseSenderResource.ts
  frontend-react/src/hooks/__mocks__/UseSenderResource.ts
  frontend-react/src/senders/hooks/UseSenderSchemaOptions/UseSenderSchemaOptions.test.ts
  frontend-react/src/senders/hooks/UseSenderSchemaOptions/index.ts
  frontend-react/yarn.lock
Labels: frontend, experience

#10425 Setup connection to Trusted-Intermediary using OAuth2
  prime-router/settings/staging/0149-etor.yml
  prime-router/src/main/kotlin/TransportType.kt
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
Labels: onboarding-ops

#10386 Added tests to test sender transform extensions
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirTransformerTests.kt
  prime-router/src/test/resources/fhir_sender_transforms/observation.yml
  prime-router/src/test/resources/fhir_sender_transforms/test_base_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/test_extension_schema.yml
Labels: pipeline, platform

#10523 add AutoUpdateFileChromatic to files that affect storybook stories
  .github/workflows/chromatic-pr.yml
  frontend-react/src/shared/Alert/Alert.module.scss
  frontend-react/src/shared/Alert/Alert.stories.tsx
  frontend-react/src/shared/Alert/Alert.tsx
  frontend-react/src/shared/Icon/Icon.stories.tsx
  frontend-react/src/shared/Icon/Icon.tsx
  frontend-react/src/shared/Table/Table.module.scss
  frontend-react/src/shared/Table/Table.stories.tsx
  frontend-react/src/styles/_components.scss
  frontend-react/src/styles/_reportstream.scss
  frontend-react/src/styles/_typography.scss
  frontend-react/src/styles/_uswds_overrides.scss
Labels: experience

#10519 10207: add CDC elims metabase queries to source control
  prime-router/examples/cdc-elims-metabase-queries/README.md
  prime-router/examples/cdc-elims-metabase-queries/active-stlts.sql
  prime-router/examples/cdc-elims-metabase-queries/find-delivered-reports.sql
  prime-router/examples/cdc-elims-metabase-queries/find-delivered-rows.sql
  prime-router/examples/cdc-elims-metabase-queries/find-original-report.sql
  prime-router/examples/cdc-elims-metabase-queries/find-row-in-original-report.sql
  prime-router/examples/cdc-elims-metabase-queries/undelivered-reports.sql
Labels: platform

#10522 Experience/9400/stlt dashboard api integration
  frontend-react/src/__mocks__/DataDashboardMockServer.ts
  frontend-react/src/__mocks__/DeliveriesMockServer.ts
  frontend-react/src/__mocks__/OrganizationMockServer.ts
  frontend-react/src/components/DataDashboard/DataDashboardTable/DataDashboardTable.test.tsx
  frontend-react/src/components/DataDashboard/DataDashboardTable/DataDashboardTable.tsx
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilitiesProvidersTable.test.tsx
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilitiesProvidersTable.tsx
  frontend-react/src/components/DataDashboard/ReceiverServices/ReceiverServices.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetails.test.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetails.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsSummary.test.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsSummary.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsTable.test.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsTable.tsx
  frontend-react/src/config/endpoints/dataDashboard.ts
  frontend-react/src/hooks/UseOrganizationReceiversFeed.ts
  frontend-react/src/hooks/filters/UsePages.ts
  frontend-react/src/hooks/network/DataDashboard/DataDashboardHooks.ts
  frontend-react/src/hooks/network/DataDashboard/UseReceiverDeliveries.ts
  frontend-react/src/hooks/network/DataDashboard/__mocks__/UseReceiverDeliveries.ts
  frontend-react/src/hooks/network/DataDashboard/useReceiverDeliveries.test.ts
  frontend-react/src/shared/Table/Table.module.scss
  frontend-react/src/shared/Table/Table.tsx
Labels: frontend, experience, trialfrontend03

#10581 Dependabot Updates
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: experience

#10512 9455: use test containers to test reportfile database access
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/db/ReportFileDatabaseAccess.kt
  prime-router/src/test/kotlin/db/ReportFileDatabaseAccessTest.kt
  prime-router/src/test/kotlin/db/ReportStreamTestDatabaseContainer.kt
  prime-router/src/test/kotlin/db/ReportStreamTestDatabaseSetupExtension.kt
Labels: platform

#10600 10213: document batch step
  prime-router/docs/universal-pipeline/batch.md
Labels: platform

#10597 Experience/9403/facilities providers
  frontend-react/src/__mocks__/DataDashboardMockServer.ts
  frontend-react/src/components/DataDashboard/DataDashboardTable/DataDashboardTable.test.tsx
  frontend-react/src/components/DataDashboard/DataDashboardTable/DataDashboardTable.tsx
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilitiesProviders.module.scss
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilitiesProviders.test.tsx
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilitiesProviders.tsx
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilitiesProvidersTable.test.tsx
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilitiesProvidersTable.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetails.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsSummary.module.scss
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsSummary.test.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsSummary.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsTable.module.scss
  frontend-react/src/config/endpoints/dataDashboard.ts
  frontend-react/src/hooks/UseOrganizationReceivers.test.ts
  frontend-react/src/hooks/UseOrganizationReceiversFeed.test.ts
  frontend-react/src/hooks/UseOrganizationReceiversFeed.ts
  frontend-react/src/hooks/network/DataDashboard/UseReceiverSubmitters.ts
  frontend-react/src/hooks/network/DataDashboard/__mocks__/UseReceiverSubmitter.ts
  frontend-react/src/hooks/network/DataDashboard/useReceiverSubmitters.test.ts
  frontend-react/src/pages/data-dashboard/DataDashboard.module.scss
  frontend-react/src/pages/data-dashboard/DataDashboard.tsx
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.test.tsx
  frontend-react/src/utils/DataDashboardUtils.test.ts
  frontend-react/src/utils/DataDashboardUtils.ts
  prime-router/docs/api/delivery.yml
Labels: frontend, experience, trialfrontend03

#10534 Migrate to azure functions 4
  prime-router/Dockerfile
  prime-router/Dockerfile.build
  prime-router/Dockerfile.dev
  prime-router/host.json
  prime-router/local.settings.json
  prime-router/src/main/kotlin/cli/tests/BasicTests.kt
Labels: platform

#10656 9778: add a five minute for processing UP route and translate tasks
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIREngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
Labels: platform

#10620 Add initial overview of universal pipeline
  prime-router/docs/assets/azure-queues.png
  prime-router/docs/assets/item-lineage.png
  prime-router/docs/assets/rs-architecture.png
  prime-router/docs/design/metadata.md
  prime-router/docs/design/swagger.md
  prime-router/docs/universal-pipeline/README.md
  prime-router/docs/universal-pipeline/batch.md
Labels: platform

#10639 Fixed bug to allow custom FHIR path functions in filters
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
Labels: onboarding-ops, pipeline, platform
