Repository CDCgov/prime-reportstream, pull requests merged in 2023-01, with the labels that each got.

#7814 [Bug]: Site Wide: Navigating through the application buttons does not…
  frontend-react/src/App.tsx
  frontend-react/src/hooks/UseScrollToTop.tsx
Labels: experience

#7796 Refactor: One `Link` to rule them all
  frontend-react/src/App.tsx
  frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx
  frontend-react/src/components/Admin/AdminReceiverDashboard.tsx
  frontend-react/src/components/Admin/OrgReceiverTable.tsx
  frontend-react/src/components/Admin/OrgSenderTable.tsx
  frontend-react/src/components/Admin/OrgsTable.tsx
  frontend-react/src/components/Content/Templates/GeneratedSideNav.tsx
  frontend-react/src/components/Content/Templates/IACard.tsx
  frontend-react/src/components/Crumbs.tsx
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx
  frontend-react/src/components/ReportStreamFooter.tsx
  frontend-react/src/components/SenderModeBanner.tsx
  frontend-react/src/components/Table/ColumnData.tsx
  frontend-react/src/components/USLink.test.tsx
  frontend-react/src/components/USLink.tsx
  frontend-react/src/components/header/DropdownNav.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/components/header/SignInOrUser.tsx
  frontend-react/src/pages/About.tsx
  frontend-react/src/pages/Login.tsx
  frontend-react/src/pages/TermsOfService.tsx
  frontend-react/src/pages/Upload.tsx
  frontend-react/src/pages/admin/AdminOrgEdit.tsx
  frontend-react/src/pages/deliveries/Table/ReportLink.tsx
  frontend-react/src/pages/deliveries/Table/TableReportsData.tsx
  frontend-react/src/pages/error/ErrorPage.test.tsx
  frontend-react/src/pages/error/Generic.tsx
  frontend-react/src/pages/error/legacy-content/ErrorNoPage.tsx
  frontend-react/src/pages/error/legacy-content/ErrorUnsupportedBrowser.tsx
  frontend-react/src/pages/home/Home.test.tsx
  frontend-react/src/pages/home/Sections/CtaSection.tsx
  frontend-react/src/pages/home/Sections/LiveMapSection.tsx
  frontend-react/src/pages/home/Sections/Section.test.tsx
  frontend-react/src/pages/product/legacy-page-content/WhereWereLive.tsx
  frontend-react/src/pages/resources/legacy-page-content/AccountRegistrationGuide.tsx
  frontend-react/src/pages/resources/legacy-page-content/CsvSchemaDocumentation.tsx
  frontend-react/src/pages/resources/legacy-page-content/CsvUploadGuide.tsx
  frontend-react/src/pages/resources/legacy-page-content/DataDownloadGuide.tsx
  frontend-react/src/pages/resources/legacy-page-content/ElrChecklist.tsx
  frontend-react/src/pages/resources/legacy-page-content/GettingStartedPhd.tsx
  frontend-react/src/pages/resources/legacy-page-content/ProgrammersGuide.tsx
  frontend-react/src/pages/resources/legacy-page-content/SecurityPractices.tsx
  frontend-react/src/pages/resources/legacy-page-content/SystemAndSettings.tsx
  frontend-react/src/pages/support/legacy-page-content/Contact.tsx
  frontend-react/src/pages/support/legacy-page-content/Faq.tsx
  frontend-react/src/pages/support/legacy-page-content/ServiceRequest.tsx
  frontend-react/src/pages/tos-sign/TermsOfServiceForm.tsx
  frontend-react/src/styles/_reportstream.scss
Labels: experience, enhancement

#7833 Update release-notes.md
  frontend-react/src/content/product/release-notes.md
Labels: experience

#7834 Include URL in thrown RSNetworkErrors
  frontend-react/src/components/RSErrorBoundary.test.tsx
  frontend-react/src/hooks/UseCreateFetch.ts
  frontend-react/src/hooks/network/WatersHooks.ts
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.test.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.test.tsx
  frontend-react/src/utils/RSNetworkError.test.ts
  frontend-react/src/utils/RSNetworkError.ts
Labels: experience

#7844 Remove Mimic UserType dropdown and functions
  frontend-react/src/components/Admin/OrgsTable.tsx
Labels: experience

#7881 Fix `PageGenerationTools` to render in a way React prefers
  frontend-react/src/components/Content/PageGenerationTools.tsx
Labels: bug, experience

#7830 Remove the GAEN Error From Last Mile Failure
  prime-router/src/main/kotlin/transport/GAENTransport.kt
  prime-router/src/testIntegration/kotlin/transport/GAENTransportIntegrationTests.kt
Labels: onboarding-ops

#7805 7629 Added Analytics service to TrackAppInsightEvent
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/Table/Table.test.tsx
  frontend-react/src/components/Table/TableFilters.test.tsx
  frontend-react/src/components/Table/TableFilters.tsx
  frontend-react/src/components/header/DropdownNav.tsx
  frontend-react/src/components/header/ReportStreamHeader.test.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/pages/admin/AdminLastMileFailures.tsx
  frontend-react/src/pages/admin/AdminMain.tsx
  frontend-react/src/pages/deliveries/Deliveries.tsx
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.test.tsx
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.tsx
  frontend-react/src/pages/deliveries/details/Summary.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.test.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.tsx
  frontend-react/src/pages/submissions/SubmissionTable.tsx
  frontend-react/src/pages/submissions/Submissions.tsx
  frontend-react/src/utils/Analytics.test.ts
  frontend-react/src/utils/Analytics.ts
  frontend-react/src/utils/__mocks__/ApplicationInsights.ts
Labels: frontend, experience

#7806 Bump json5 from 1.0.1 to 1.0.2 and 2.2.1 to 2.2.2 in /frontend-react
  frontend-react/yarn.lock
Labels: security, experience, dependencies, javascript

#7817 Bump Node.js from 16.18.1 to 16.19.0
  .github/actions/build-frontend/action.yml
  frontend-react/.nvmrc
  frontend-react/README.md
  frontend-react/package.json
  prime-router/docs/getting-started/Using-an-apple-silicon-mac.md
Labels: experience, dependencies, javascript

#7918 Fix empty line lint complaint
  frontend-react/src/utils/Analytics.test.ts
Labels: experience, engineering

#7912 Trim message_id search field value
  frontend-react/src/components/MessageTracker/MessageTracker.test.tsx
  frontend-react/src/components/MessageTracker/MessageTracker.tsx
Labels: bug, experience

#7827 Breadcrumbs on Submissions Detail don't link back to previous URL
  frontend-react/.env.development
  frontend-react/src/components/Crumbs.tsx
  frontend-react/src/components/IconButton.tsx
  frontend-react/src/components/MessageTracker/MessageTracker.tsx
  frontend-react/src/components/Table/ColumnData.tsx
  frontend-react/src/components/Table/Table.tsx
  frontend-react/src/components/USLink.tsx
  frontend-react/src/global.scss
  frontend-react/src/pages/submissions/SubmissionDetails.tsx
  frontend-react/src/styles/_components.scss
Labels: experience

#7914 Replace File column value with fileName
  frontend-react/src/components/Table/ColumnData.tsx
  frontend-react/src/hooks/network/History/DeliveryHooks.ts
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.tsx
Labels: experience

#7906 Bump azure-core-http-netty from 1.12.5 to 1.12.8 in /prime-router
  prime-router/build.gradle.kts
Labels: onboarding-ops, security, dependencies, java

#7720 Bump commons-net from 3.8.0 to 3.9.0 in /prime-router
  prime-router/build.gradle.kts
Labels: onboarding-ops, security, dependencies, java

#7930 Remove unused `memberships` Map and pattern
  frontend-react/src/contexts/SessionContext.test.tsx
  frontend-react/src/contexts/SessionContext.tsx
  frontend-react/src/hooks/UseOktaMemberships.test.ts
  frontend-react/src/hooks/UseOktaMemberships.ts
Labels: experience

#7953 Prioritize active receivers on Daily Data
  frontend-react/src/hooks/UseOrganizationReceiversFeed.ts
Labels: experience

#7940 7628 - Pagination usage with feature info and membership data
  frontend-react/src/hooks/UsePagination.test.ts
  frontend-react/src/hooks/UsePagination.ts
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.tsx
  frontend-react/src/pages/submissions/SubmissionTable.tsx
  frontend-react/src/utils/Analytics.ts
Labels: frontend, experience, insights

#7983 Experience: add proposal for domain-driven directory structure
  frontend-react/docs/proposals/0001-permissions-layer-proposal.md
  frontend-react/docs/proposals/0002-domain-driven-directory-structure.md
  frontend-react/docs/proposals/xxxx-template.md
Labels: experience, engineering

#8068 Allow Duplicates checkbox for Sender Settings
  frontend-react/src/components/Admin/AdminFormEdit.tsx
  frontend-react/src/components/Admin/EditSenderSettings.test.tsx
  frontend-react/src/components/Admin/EditSenderSettings.tsx
  frontend-react/src/resources/OrgSenderSettingsResource.ts
  frontend-react/src/resources/TestResponse.ts
Labels: experience

#7913 Experience-7867: Add local Cypress UX checks
  frontend-react/.gitignore
  frontend-react/cypress.config.ts
  frontend-react/cypress/README.md
  frontend-react/cypress/cypress.sample.json
  frontend-react/cypress/e2e/specs/daily-data-page.cy.ts
  frontend-react/cypress/e2e/specs/home-page.cy.ts
  frontend-react/cypress/e2e/specs/product-pages.cy.ts
  frontend-react/cypress/e2e/specs/resources-pages.cy.ts
  frontend-react/cypress/e2e/specs/submissions-page.cy.ts
  frontend-react/cypress/integration/pages/AdminMain.test.js
  frontend-react/cypress/integration/pages/Validate.test.js
  frontend-react/cypress/integration/pages/ValueSetsIndex.test.js
  frontend-react/cypress/integration/pages/WhereWereLive.test.js
  frontend-react/cypress/plugins/index.js
  frontend-react/cypress/plugins/index.ts
  frontend-react/cypress/support/commands.js
  frontend-react/cypress/support/commands.ts
  frontend-react/cypress/support/commands/api.ts
  frontend-react/cypress/support/commands/auth.ts
  frontend-react/cypress/support/commands/organizations.ts
  frontend-react/cypress/support/e2e.ts
  frontend-react/cypress/support/index.js
  frontend-react/cypress/support/pageComponents/Base.ts
  frontend-react/cypress/support/pageComponents/DateRangeFilter.ts
  frontend-react/cypress/support/pageComponents/PaginatedTable.ts
  frontend-react/cypress/support/pages/Base.ts
  frontend-react/cypress/support/pages/DailyData.ts
  frontend-react/cypress/support/pages/Home.ts
  frontend-react/cypress/support/pages/Submissions.ts
  frontend-react/cypress/support/pages/admin/Base.ts
  frontend-react/cypress/support/pages/admin/OrganizationSettings.ts
  frontend-react/cypress/support/pages/admin/ValueSets.ts
  frontend-react/cypress/support/pages/product/About.ts
  frontend-react/cypress/support/pages/product/Base.ts
  frontend-react/cypress/support/pages/product/Overview.ts
  frontend-react/cypress/support/pages/product/ReleaseNotes.ts
  frontend-react/cypress/support/pages/product/WhereWereLive.ts
  frontend-react/cypress/support/pages/resources/Base.ts
  frontend-react/cypress/support/pages/resources/Index.ts
  frontend-react/cypress/support/pages/resources/Show.ts
  frontend-react/package.json
  frontend-react/tsconfig.json
  frontend-react/yarn.lock
Labels: experience, engineering

#7928 Experience-7891: Disable organization-specific fetches as admin
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx
  frontend-react/src/components/StaticAlert.test.tsx
  frontend-react/src/components/StaticAlert.tsx
  frontend-react/src/components/alerts/AdminFetchAlert.tsx
  frontend-react/src/components/alerts/NoServicesAlert.tsx
  frontend-react/src/hooks/UseOrganizationReceivers.ts
  frontend-react/src/hooks/UseOrganizationReceiversFeed.test.ts
  frontend-react/src/hooks/UseOrganizationReceiversFeed.ts
  frontend-react/src/hooks/UseOrganizationSettings.test.ts
  frontend-react/src/hooks/UseOrganizationSettings.ts
  frontend-react/src/hooks/network/History/DeliveryHooks.test.ts
  frontend-react/src/hooks/network/History/DeliveryHooks.ts
  frontend-react/src/network/QueryClients.ts
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.test.tsx
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.tsx
  frontend-react/src/pages/submissions/SubmissionTable.test.tsx
  frontend-react/src/pages/submissions/SubmissionTable.tsx
Labels: experience, engineering

#8056 Update validation endpoint and remove authentication
  prime-router/docs/api/validate.yml
  prime-router/docs/release-notes.md
  prime-router/src/main/kotlin/azure/RequestFunction.kt
  prime-router/src/main/kotlin/azure/ValidateFunction.kt
  prime-router/src/test/kotlin/azure/ValidateFunctionTests.kt
Labels: API, platform

#8072 Add fields to receiver settings
  frontend-react/src/components/Admin/EditReceiverSettings.tsx
  frontend-react/src/resources/OrgReceiverSettingsResource.ts
  frontend-react/src/utils/TemporarySettingsAPITypes.ts
Labels: experience

#8057 7776 - Create Events to track success of Public File Validation
  frontend-react/src/components/FileHandlers/FileHandler.test.tsx
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/utils/Analytics.ts
Labels: frontend, experience
