Repository CDCgov/prime-reportstream, pull requests merged in 2023-09, with the labels that each got.

#11023 Website Redesign - Getting started
  frontend-react/src/AppRouter.tsx
  frontend-react/src/content/getting-started/index.mdx
  frontend-react/src/content/home/home-index.mdx
  frontend-react/src/content/product/release-notes.md
  frontend-react/src/layouts/Main/MainLayout.tsx
  frontend-react/src/layouts/Markdown/MarkdownLayout.tsx
  frontend-react/src/shared/HeroWrapper/HeroWrapper.module.scss
  frontend-react/src/shared/Icon/Icon.tsx
  frontend-react/src/shared/Icon/reportstream-sprite.svg
  frontend-react/src/shared/LiveMap/LiveMap.tsx
  frontend-react/src/shared/PageHeader/PageHeader.tsx
  frontend-react/src/shared/Tile/Tile.module.scss
  frontend-react/src/shared/Tile/Tile.tsx
  frontend-react/src/styles/_reportstream.scss
  frontend-react/src/styles/_uswds_overrides.scss
Labels: frontend, experience

#11020 Website Redesign - Sending Data
  frontend-react/public/assets/pdf/ReportStream_Onepager_20230621.pdf
  frontend-react/src/AppRouter.tsx
  frontend-react/src/content/getting-started/sending-data.mdx
  frontend-react/src/content/getting-started/sidenav.mdx
  frontend-react/src/layouts/Markdown/MarkdownLayout.tsx
  frontend-react/src/shared/Blockquote/Blockquote.stories.tsx
  frontend-react/src/shared/Blockquote/Blockquote.tsx
  frontend-react/src/shared/index.ts
  frontend-react/src/styles/_uswds_overrides.scss
  frontend-react/src/styles/hr.stories.tsx
Labels: frontend, experience, trialfrontend03

#10942 Website Redesign - Refer health care organizations
  frontend-react/.storybook/main.ts
  frontend-react/package.json
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/Content/MarkdownRenderer.tsx
  frontend-react/src/components/MessageTracker/MessageDetails.tsx
  frontend-react/src/content/managing-your-connection/refer-healthcare-organizations.mdx
  frontend-react/src/content/managing-your-connection/sidenav.mdx
  frontend-react/src/pages/support/Support.tsx
  frontend-react/src/styles/_components.scss
  frontend-react/vite.config.ts
  frontend-react/yarn.lock
Labels: experience, trialfrontend03

#11007 Experience/10910-Website-Redesign---Developer-Resources
  frontend-react/src/AppRouter.tsx
  frontend-react/src/content/developer-resources/index-page.mdx
  frontend-react/src/styles/_uswds_overrides.scss
Labels: design, experience, trialfrontend03

#11213 react-uswds 5.3 patch fix
  frontend-react/patches/@trussworks+react-uswds+5.2.0.patch
  frontend-react/patches/@trussworks+react-uswds+5.3.0.patch
Labels: experience

#10837 Experience/10709/navbar redesign
  frontend-react/src/components/OktaSignInWidget.tsx
  frontend-react/src/components/USLink.test.tsx
  frontend-react/src/components/USLink.tsx
  frontend-react/src/components/header/ReportStreamHeader.test.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/components/header/ReportStreamNavbar.module.scss
  frontend-react/src/components/header/ReportStreamNavbar.stories.tsx
  frontend-react/src/components/header/ReportStreamNavbar.tsx
  frontend-react/src/content/internal-user-guides/make-markdown-pages.md
  frontend-react/src/layouts/Main/MainLayout.tsx
  frontend-react/src/layouts/Markdown/CallToAction.test.tsx
  frontend-react/src/layouts/Markdown/CallToAction.tsx
  frontend-react/src/layouts/Markdown/MarkdownLayout.tsx
  frontend-react/src/pages/Login.tsx
  frontend-react/src/pages/TermsOfService.tsx
  frontend-react/src/shared/PageHeader/PageHeader.tsx
  frontend-react/src/styles/_reportstream.scss
Labels: experience

#11220 BUG: Width on app pages broken
  frontend-react/src/components/header/ReportStreamNavbar.module.scss
  frontend-react/src/content/internal-user-guides/make-markdown-pages.md
  frontend-react/src/layouts/Main/MainLayout.tsx
Labels: experience

#11036 platform/jimfuqian/10262 Deploy Report Stream API Docs swagger UI to Staging
  .github/actions/deploy-frontend/action.yml
Labels: deployment, platform

#11203 Outbound OML Message - PID Segment
  prime-router/metadata/hl7_mapping/common/patient.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_OML_20230831-0001.hl7
Labels: platform

#11226 Bump chromaui action to 7.0.0
  .github/workflows/chromatic-master.yml
  .github/workflows/chromatic-pr.yml
Labels: dependencies, github_actions

#11139 Convert Step Documentation
  prime-router/docs/design/design/transformations.md
  prime-router/docs/universal-pipeline/convert.md
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/fhirTransform/FhirTransformSchema.kt
Labels: platform

#11238 fix link
  frontend-react/src/components/header/ReportStreamNavbar.tsx
Labels: experience

#11156 Experience/10911/manage connection 2
  frontend-react/src/content/home/home-index.mdx
  frontend-react/src/content/manage-connection/manage-connection-index.mdx
  frontend-react/src/shared/Card/Card.module.scss
  frontend-react/src/shared/HeroWrapper/HeroWrapper.module.scss
  frontend-react/src/shared/Tile/Tile.tsx
  frontend-react/src/styles/_uswds_overrides.scss
Labels: frontend, experience, trialfrontend02

#11261 Experience/11257/navbar updates
  frontend-react/src/components/USLink.test.tsx
  frontend-react/src/components/USLink.tsx
  frontend-react/src/components/header/ReportStreamNavbar.module.scss
  frontend-react/src/components/header/ReportStreamNavbar.tsx
  frontend-react/src/shared/PageHeader/PageHeader.tsx
Labels: experience

#11204 HL7 OBR Mapping for OML messages
  prime-router/metadata/hl7_mapping/OML_O21/OML_O21-base.yml
  prime-router/metadata/hl7_mapping/OML_O21/base/service-request-order-observation.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/observation-request.yml
  prime-router/metadata/hl7_mapping/common/observation-request.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_OML_20230831-0001.hl7
Labels: platform

#11231 NY UP Onboarding
  prime-router/metadata/fhir_transforms/senders/default-sender-transform.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/NY/NY-receiver-transform.yml
  prime-router/settings/organizations.yml
  prime-router/settings/staging/0155-NY-up-onboarding.yml
Labels: onboarding-ops

#11021 10921 extract HL7 truncation logic into UP
  prime-router/src/main/kotlin/TranslatorConfiguration.kt
  prime-router/src/main/kotlin/common/StringUtilities.kt
  prime-router/src/main/kotlin/fhirengine/config/HL7TranslationConfig.kt
  prime-router/src/main/kotlin/fhirengine/engine/CustomTranslationFunctions.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/HL7Truncator.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/config/ContextConfig.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/config/TruncationConfig.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/HL7Constants.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/HL7Utils.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/TranslationFunctions.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
  prime-router/src/test/kotlin/fhirengine/engine/CustomTranslationFunctionsTest.kt
  prime-router/src/test/kotlin/fhirengine/engine/HL7TranslationFunctionsTest.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/HL7TrucatorTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/FhirPathUtilsTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/Hl7UtilsTests.kt
  prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
  prime-router/src/test/kotlin/unittest/UnitTestUtils.kt
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
Labels: onboarding-ops, reportstream

#11279 Filter submitters with null names from submitter API
  prime-router/src/main/kotlin/history/db/SubmitterDatabaseAccess.kt
Labels: platform

#11304 11297 - [BUG] Fix link for Refer healthcare organizations
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/header/ReportStreamNavbar.tsx
  frontend-react/src/content/managing-your-connection/index.mdx
Labels: bug, frontend, experience

#11216 10486: support multiple file schemes when loading schemas
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReader.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReaderTests.kt
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-07/ORU_R01-extended.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-07/ORU_R01.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-07/ORU_R01/header.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-07/ORU_R01/observation.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-07/ORU_R01/order-observation.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-07/ORU_R01/patient-identification.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-07/ORU_R01/patient.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-08/ORU_R01.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-08/ORU_R01/header.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-08/ORU_R01/observation.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-08/ORU_R01/order-observation.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-08/ORU_R01/patient-identification.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-08/ORU_R01/patient.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-08/ORU_R01_circular.yml
Labels: platform

#11217 #11221: Create and upload a blob in the send step and support downloading it
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/HistoryFunctions.kt
  prime-router/src/main/kotlin/transport/AS2Transport.kt
  prime-router/src/main/kotlin/transport/BlobStoreTransport.kt
  prime-router/src/main/kotlin/transport/GAENTransport.kt
  prime-router/src/main/kotlin/transport/NullTransport.kt
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/main/kotlin/transport/SftpTransport.kt
  prime-router/src/main/kotlin/transport/SoapTransport.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/azure/HistoryFunctionsTests.kt
  prime-router/src/testIntegration/kotlin/transport/GAENTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/SftpTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/SoapTransportIntegrationTests.kt
Labels: platform

#11302 bump chromaui to 7.1.0
  .github/workflows/chromatic-master.yml
  .github/workflows/chromatic-pr.yml
Labels: dependencies, github_actions

#11266 Remove debug from snyk.yml
  .github/workflows/snyk.yml
Labels: DevOps

#11218 Website Redesign - Our Network
  frontend-react/src/AppRouter.tsx
  frontend-react/src/content/about/our-network.mdx
  frontend-react/src/content/about/sidenav.mdx
  frontend-react/src/styles/_reportstream.scss
  frontend-react/src/styles/_uswds_overrides.scss
Labels: experience

#11234 Website Redesign - Support Page
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/USLink.test.tsx
  frontend-react/src/components/header/ReportStreamNavbar.module.scss
  frontend-react/src/content/support/index.mdx
  frontend-react/src/layouts/Markdown/LayoutComponents.tsx
  frontend-react/src/layouts/Markdown/MarkdownLayout.tsx
  frontend-react/src/shared/Accordion/Accordian.stories.tsx
  frontend-react/src/shared/Accordion/Accordion.tsx
  frontend-react/src/shared/Card/Card.module.scss
  frontend-react/src/shared/index.ts
  frontend-react/src/styles/_components.scss
  frontend-react/src/styles/_reportstream.scss
  frontend-react/src/styles/_uswds_overrides.scss
Labels: experience, trialfrontend03

#11187 Experience/11133/homepage
  frontend-react/public/assets/img/ReportStreamDiagram_2023.png
  frontend-react/public/assets/img/home/grid.png
  frontend-react/public/assets/img/home/how-we-help-1.png
  frontend-react/public/assets/img/home/how-we-help-2.png
  frontend-react/public/assets/img/home/how-we-help-3.png
  frontend-react/src/AppRouter.tsx
  frontend-react/src/content/home/home-index.mdx
  frontend-react/src/content/home/index.mdx
  frontend-react/src/shared/Card/Card.module.scss
  frontend-react/src/shared/HeroWrapper/HeroWrapper.module.scss
  frontend-react/src/shared/LiveMap/LiveMap.tsx
  frontend-react/src/styles/_alternate.scss
  frontend-react/src/styles/_uswds_overrides.scss
Labels: frontend, experience

#11227 platform/jimfuqian/11161-Bug: updating kotlin jvm plugin version to 1.9.10 causes a test to fail
  prime-router/build.gradle.kts
  prime-router/src/test/kotlin/azure/TokenFunctionTests.kt
Labels: platform

#11312 Experience/11137/redesign footer
  frontend-react/src/layouts/Main/MainLayout.tsx
  frontend-react/src/shared/ReportStreamFooter/ReportStreamFooter.module.scss
  frontend-react/src/shared/ReportStreamFooter/ReportStreamFooter.stories.tsx
  frontend-react/src/shared/ReportStreamFooter/ReportStreamFooter.tsx
Labels: experience, trialfrontend01

#11058 Kalish/platform/hl7 diff prototype
  prime-router/src/main/kotlin/cli/ProcessHl7Commands.kt
  prime-router/src/main/kotlin/cli/helpers/HL7DiffHelper.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/test/kotlin/cli/helpers/HL7DiffHelperTests.kt
Labels: pipeline, platform

#11310 11298 - [BUG] Remove Breadcrumbs from Pages
  frontend-react/cypress/e2e/specs/resources-pages.cy.ts
  frontend-react/src/content/resources/index.ts
  frontend-react/src/pages/resources/legacy-page-content/DataDownloadGuide.tsx
  frontend-react/src/pages/resources/legacy-page-content/GettingStartedPhd.tsx
Labels: bug, frontend, experience

#11228 Experience/11135/about
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/header/ReportStreamNavbar.tsx
  frontend-react/src/content/about/index.mdx
  frontend-react/src/content/resources/index.ts
  frontend-react/src/pages/admin/AdminRevHistory.test.tsx
  frontend-react/src/pages/resources/legacy-page-content/SecurityPractices.tsx
  frontend-react/src/shared/Accordion/Accordian.stories.tsx
  frontend-react/src/shared/Accordion/Accordion.module.scss
  frontend-react/src/shared/Accordion/Accordion.stories.tsx
  frontend-react/src/shared/Accordion/Accordion.tsx
  frontend-react/src/styles/_reportstream.scss
Labels: frontend, experience, trialfrontend02

#11087 Implemented parallel downloads in batch step
  prime-router/src/main/kotlin/azure/BatchFunction.kt
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
Labels: platform

#11349 Cleanup translation tests
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001-xxx.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0006-xxx.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0006.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0006.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0014-xxx.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0014.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0014.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_2_20220803-0001-xxx.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_2_20220803-0001.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_2_20220803-0001.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0001-expected-CO.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0001-expected-base.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0001.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0004-expected-base.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0004.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0014-expected-base.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0014.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0019-expected-CO.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0019-expected-base.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0019.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/test_playground_20220930-0001-expected-CO.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/test_playground_20220930-0001.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: pipeline, platform

#11365 Experience/11013/dashboard improvements
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilitiesProviders.module.scss
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilitiesProviders.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsSummary.tsx
  frontend-react/src/hooks/UseOrganizationReceiversFeed.ts
  frontend-react/src/hooks/network/DataDashboard/UseReceiverDeliveries.ts
  frontend-react/src/hooks/network/DataDashboard/UseReceiverSubmitters.ts
  frontend-react/src/pages/data-dashboard/DataDashboard.tsx
Labels: frontend, experience, trialfrontend03

#11372 11181 - Add Dashboard to nav
  frontend-react/src/components/header/ReportStreamNavbar.tsx
  frontend-react/src/hooks/UseOrganizationSettings.ts
Labels: frontend, experience, trialfrontend01

#11318 8910 Add integration tests for removing Observations from a bundle
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/FHIRBundleHelpersTests.kt
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_multiple_observations.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_multiple_observations.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_multiple_observations_keepall.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_multiple_observations_keepall.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_some_filtered_observations.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_some_filtered_observations.hl7
  prime-router/src/testIntegration/resources/datatests/README.md
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: pipeline, platform

#11411 Update dependabot.yml for swagger group
  .github/dependabot.yml
Labels: DevOps, dependencies, java

#11362 Unify Kotlin version for the various pieces of Kotlin.
  prime-router/build.gradle.kts
  prime-router/gradle.properties
Labels: dependencies, java

#11357 11012: add documentation for the translation step
  prime-router/docs/universal-pipeline/README.md
  prime-router/docs/universal-pipeline/convert.md
  prime-router/docs/universal-pipeline/receive.md
  prime-router/docs/universal-pipeline/route.md
  prime-router/docs/universal-pipeline/translate.md
Labels: platform

#11363 11280: add more tests to document how overriding schemas work
  prime-router/docs/design/design/transformations.md
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-test-overrides/ORU_R01.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-test-overrides/ORU_R01/sft.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-test-overrides/ORU_R01/sft2.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-test-overrides/ORU_R01/xon.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-test-overrides/ORU_R01/xon2.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-test-overrides/ORU_R01/xon_extended.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-test-overrides/ORU_R01_extended.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-test-overrides/ORU_R01_extended_extended.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-test-overrides/ORU_R01_extended_overrides_software.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-test-overrides/ORU_R01_extended_overrides_xon.yml
Labels: platform

#11374 10477: document topic
  prime-router/docs/design/design/topic.md
Labels: platform

#11396 Remove pipeline label from Platform User Story template
  .github/ISSUE_TEMPLATE/platform-user-story.md
Labels: platform

#11433 11299 - Remove inactive receivers
  frontend-react/public/assets/folder-search.svg
  frontend-react/src/__mocks__/OrganizationMockServer.ts
  frontend-react/src/components/DataDashboard/DataDashboardTable/DataDashboardTable.test.tsx
  frontend-react/src/components/DataDashboard/DataDashboardTable/DataDashboardTable.tsx
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilitiesProviders.test.tsx
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilitiesProvidersTable.test.tsx
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilitiesProvidersTable.tsx
  frontend-react/src/components/alerts/NoServicesAlert.test.tsx
  frontend-react/src/components/alerts/NoServicesAlert.tsx
  frontend-react/src/components/header/ReportStreamNavbar.tsx
  frontend-react/src/content/managing-your-connection/index.mdx
  frontend-react/src/content/site.json
  frontend-react/src/content/support/index.mdx
  frontend-react/src/hooks/UseOrganizationReceiversFeed.test.ts
  frontend-react/src/hooks/UseOrganizationReceiversFeed.ts
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.test.tsx
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.tsx
  frontend-react/src/utils/DataDashboardUtils.ts
Labels: frontend, experience, trialfrontend01

#11368 10210 UP transform documentation
  prime-router/docs/design/design/transformations.md
  prime-router/docs/getting-started/standard-operating-procedures/changing-transforms.md
  prime-router/docs/getting-started/universal-pipeline-configuration.md
Labels: platform

#11369 Updated java version
  prime-router/.java-version
Labels: pipeline, platform

#11390 11088: upgrade to gradle 8.3
  prime-router/Dockerfile.build
  prime-router/build.gradle.kts
  prime-router/gradle/wrapper/gradle-wrapper.jar
  prime-router/gradle/wrapper/gradle-wrapper.properties
  prime-router/gradlew
  prime-router/gradlew.bat
Labels: platform

#11502 Gradle 8.3 doc update
  prime-router/Dockerfile.build
  prime-router/docs/docs-deprecated/getting-started/install-gradle.md
Labels: java

#11485 Fix NPE and message in DiffHelper, add option to diff when converting HL7->FHIR->HL7
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/cli/helpers/HL7DiffHelper.kt
Labels: platform

#11174 gap analysis hci
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Identifier.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Identifier_SystemID.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Identifier_XON.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Identifier_var.yml
  prime-router/metadata/fhir_mapping/hl7/extension/ExtensionHierarchicDesignator.yml
  prime-router/metadata/fhir_mapping/hl7/resource/DiagnosticReport.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Location.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Observation.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Organization.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Practitioner.yml
  prime-router/metadata/fhir_mapping/hl7/resource/PractitionerRole.yml
  prime-router/metadata/fhir_mapping/hl7/resource/ServiceRequest.yml
  prime-router/metadata/hl7_mapping/ORU_R01/RADx_MARS/RADx_MARS-base.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/note.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/observation-request.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/order.yml
  prime-router/metadata/hl7_mapping/common/datatype/ei-entity-identifier.yml
  prime-router/metadata/hl7_mapping/common/datatype/hd-hierarchic-designator.yml
  prime-router/metadata/hl7_mapping/common/datatype/hd-location.yml
  prime-router/metadata/hl7_mapping/common/datatype/pl-location.yml
  prime-router/metadata/hl7_mapping/common/datatype/xon-organization.yml
  prime-router/metadata/hl7_mapping/common/datatype/xpn-person-name.yml
  prime-router/metadata/hl7_mapping/common/datatype/xtn-telecom.yml
  prime-router/metadata/hl7_mapping/common/observation-result.yml
  prime-router/metadata/hl7_mapping/common/patient-visit.yml
  prime-router/metadata/hl7_mapping/common/patient.yml
  prime-router/metadata/hl7_mapping/common/software.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/CA-receiver-transform.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/CA.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-patient.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CO/co-order-observation.yml
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctions.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_FHIR/sample_AOE_1_20230220-0001-expected.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_FHIR/sample_AOE_1_20230220-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_2_20230220-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_OML_20230831-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_OML_20230831-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_RADx_MARS_20230406-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_RADx_MARS_20230406-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_RADx_MARS_20230406-0002.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_multiple_observations.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_multiple_observations.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_multiple_observations_keepall.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_multiple_observations_keepall.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_some_filtered_observations.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_some_filtered_observations.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_SR_1_20230119-0001.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_SR_1_20230119-0001.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/hci-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/hci.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: platform

#11438 11347 - Remove New Jersey and update programmers guide pdf
  frontend-react/public/assets/pdf/ReportStream-Programmers-Guide-v4.0.pdf
  frontend-react/public/assets/pdf/ReportStream-Programmers-Guide-v4.1.pdf
  frontend-react/src/content/resources/reportstream-api/ReportStreamApi.mdx
  frontend-react/src/content/resources/reportstream-api/getting-started/GettingStarted.mdx
  frontend-react/src/content/site.json
Labels: frontend, experience, trialfrontend01

#11149 Initial proposal for a test plan for translations
  prime-router/docs/design/proposals/mapping-inventory-test-plan.md
Labels: pipeline, platform

#11529 Removed outOfStateClia logic for CA and updated integration tests
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/CA-receiver-transform.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/CA.yml
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001-custom-datetime.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_2_20230220-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_multiple_observations.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_multiple_observations_keepall.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_some_filtered_observations.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: onboarding-ops

#11147 Only default xtn.2 to email when use is not set
  prime-router/metadata/hl7_mapping/ORU_R01/ORU_R01-test.yml
  prime-router/metadata/hl7_mapping/ORU_R01/RADx_MARS/RADx_MARS-base.yml
  prime-router/metadata/hl7_mapping/common/datatype/xtn-telecom.yml
  prime-router/metadata/hl7_mapping/common/patient.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/CA-receiver-transform.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/CA.yml
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/TranslateAndCompareFile.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/xtn/XTNTests.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_RADx_MARS_20230406-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SR_1_20230302-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_truncate_CA_20230406-0001.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_1_72_3029202646_5532_NoPII-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_29_5065302_35227_NoPII_CANCELED-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_2_40_05059364_34872_MIN-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_2_52_5068110_35230_NoPII-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_2_72_3029198209_5121_NoPII-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_40_4988249_33033-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_40_4988249_33033-with-truncation-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_47_1_32361_04608646_11034_mega_case-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_47_2_04608646_11024_mega_specimen-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_47_3_04608717_11184_mega_specimen-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/hci-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/hci.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xtn/XTN-to-ContactPoint.csv
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xtn/xtn_2_3_use_code_no_use_system_email.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xtn/xtn_2_3_use_code_no_use_system_email.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xtn/xtn_2_3_use_code_no_use_system_pager.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xtn/xtn_2_3_use_code_no_use_system_pager.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xtn/xtn_2_use_code_home.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xtn/xtn_2_use_code_home.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xtn/xtn_2_use_code_mobile.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xtn/xtn_2_use_code_mobile.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xtn/xtn_2_use_code_temp.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xtn/xtn_2_use_code_temp.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xtn/xtn_2_use_code_work.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xtn/xtn_2_use_code_work.hl7
Labels: platform

#11436 First draft of outer resource design
  prime-router/docs/design/design/schema-resource-design.md
Labels: pipeline, platform

#11406 11345: upgrade hapi fhir library
  prime-router/build.gradle.kts
  prime-router/metadata/hl7_mapping/ORU_R01/ORU_R01-base.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/observation-request.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/observation-result.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/order-observation.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/specimen.yml
  prime-router/metadata/hl7_mapping/common/datatype/ce-coded-element.yml
  prime-router/metadata/hl7_mapping/common/datatype/ce-coded-with-exceptions.yml
  prime-router/metadata/hl7_mapping/common/note.yml
  prime-router/metadata/hl7_mapping/common/observation-result.yml
  prime-router/metadata/hl7_mapping/common/patient.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-aoe-note.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-order-note.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-patient-note.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-specimen.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CO/co-observation-result.yml
  prime-router/src/main/kotlin/fhirengine/translation/hl7/ConfigSchemaProcessor.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/ConstantResolverTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/FhirPathUtilsTests.kt
Labels: platform

#11440 CSS norms
  frontend-react/README.md
Labels: experience

#11551 11333 - new Security page
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKey.tsx
  frontend-react/src/content/about/index.mdx
  frontend-react/src/content/about/security.mdx
  frontend-react/src/content/getting-started/sending-data.mdx
  frontend-react/src/content/home/index.mdx
  frontend-react/src/content/resources/ResourcesIndex.mdx
  frontend-react/src/content/resources/index.ts
  frontend-react/src/content/support/index.mdx
  frontend-react/src/pages/resources/index-legacy.ts
  frontend-react/src/pages/resources/legacy-page-content/SecurityPractices.tsx
Labels: frontend, experience

#11475 Added function to download Blobs as binary data + retry mechanism to Blob downloads
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/azure/BatchFunction.kt
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/main/kotlin/azure/CovidResultMetaDataFunction.kt
  prime-router/src/main/kotlin/azure/HistoryFunctions.kt
  prime-router/src/main/kotlin/azure/SenderFilesFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/Message.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReader.kt
  prime-router/src/test/kotlin/azure/BatchFunctionTests.kt
  prime-router/src/test/kotlin/azure/BlobAccessTests.kt
  prime-router/src/test/kotlin/azure/HistoryFunctionsTests.kt
  prime-router/src/test/kotlin/azure/SenderFilesFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReaderTests.kt
Labels: pipeline, platform

#11313 10262 Add APIDocs Swagger UI upload as part of back end deploy (Staging)
  .github/actions/deploy-backend/action.yml
Labels: deployment, platform

#11570 case studies page
  frontend-react/src/AppRouter.tsx
  frontend-react/src/content/about/case-studies.mdx
  frontend-react/src/content/about/index.mdx
  frontend-react/src/content/about/sidenav.mdx
  frontend-react/src/styles/_components.scss
Labels: experience, trialfrontend02

#11582 11543: set %context to the resource available before getting the focus resource
  prime-router/docs/design/design/context-resource-design.md
  prime-router/docs/design/design/transformations.md
  prime-router/docs/getting-started/standard-operating-procedures/changing-transforms.md
  prime-router/metadata/hl7_mapping/OML_O21/base/service-request-order-observation.yml
  prime-router/metadata/hl7_mapping/common/observation-result.yml
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/ConfigSchemaProcessor.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirTransformer.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/ConstantResolverTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/FhirPathUtilsTests.kt
Labels: platform
