Repository CDCgov/prime-reportstream, pull requests merged in 2023-12, with the labels that each got.

#12410 Remove topic from translator
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
Labels: platform

#12422 Add sender transform for hci
  prime-router/metadata/fhir_transforms/senders/HCI/hci-sender-transform.yml
  prime-router/metadata/fhir_transforms/senders/baseline-sender-transform.yml
  prime-router/settings/organizations.yml
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
  prime-router/src/testIntegration/resources/settings/organizations.yml
Labels: platform

#12441 11443: split batch function into universal and covid
  prime-router/src/main/kotlin/azure/QueueAccess.kt
  prime-router/src/main/kotlin/azure/batch/BatchConstants.kt
  prime-router/src/main/kotlin/azure/batch/BatchDeciderFunction.kt
  prime-router/src/main/kotlin/azure/batch/CovidBatchFunction.kt
  prime-router/src/main/kotlin/azure/batch/DeprecatedBatchFunction.kt
  prime-router/src/main/kotlin/azure/batch/UniversalBatchFunction.kt
  prime-router/src/test/kotlin/azure/batch/BatchDeciderTests.kt
  prime-router/src/test/kotlin/azure/batch/CovidBatchFunctionTests.kt
  prime-router/src/test/kotlin/azure/batch/UniversalBatchFunctionTests.kt
Labels: platform

#12338 Merge a bunch of dependabots at once again
  prime-router/build.gradle.kts
Labels: security, dependencies, platform

#12448 Experience/12403/sitemap
  frontend-react/.husky/pre-commit
  frontend-react/public/sitemap.xml
  frontend-react/scripts/approuter-check.sh
Labels: experience

#12465 update homepage content
  frontend-react/src/content/home/index.mdx
  frontend-react/yarn.lock
Labels: experience, trialfrontend03

#12434 Updated the logging to only log an error if all message types fail to…
  prime-router/src/main/kotlin/fhirengine/utils/HL7Reader.kt
Labels: pipeline, platform

#12463 12153 - Added File download on Message Details
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsSummary.tsx
  frontend-react/src/components/MessageTracker/MessageReceivers.tsx
  frontend-react/src/pages/deliveries/Table/ReportLink.tsx
  frontend-react/src/pages/deliveries/Table/ReportsUtils.ts
  frontend-react/src/pages/deliveries/Table/TableReportsData.tsx
  frontend-react/src/pages/deliveries/details/Summary.tsx
  prime-router/src/main/kotlin/azure/HistoryFunctions.kt
  prime-router/src/test/kotlin/azure/HistoryFunctionsTests.kt
Labels: frontend, experience

#12527 Add availability testing for the SFTP container
  operations/app/functions/admin/ConfirmSFTPAccess/confirm_sftp_access.py
  operations/app/terraform/modules/application_insights/alert_availability.tf
  operations/app/terraform/modules/function_app/admin_app.tf
Labels: DevOps, enhancement

#12076 platform/jimfuqian/11928-Refactor-code-to-remove-old-and-unsupported-libs
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/azure/EmailEngineFunction.kt
  prime-router/src/main/kotlin/cli/CommandUtilities.kt
  prime-router/src/main/kotlin/cli/LookupTableCommands.kt
  prime-router/src/main/kotlin/cli/OktaCommands.kt
  prime-router/src/main/kotlin/cli/SenderFilesCommand.kt
  prime-router/src/main/kotlin/cli/SettingCommands.kt
  prime-router/src/main/kotlin/cli/SettingsUtilities.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/main/kotlin/cli/tests/AuthTests.kt
  prime-router/src/main/kotlin/cli/tests/HistoryApiTest.kt
  prime-router/src/main/kotlin/cli/tests/LivdApiTest.kt
  prime-router/src/main/kotlin/cli/tests/SettingsTest.kt
  prime-router/src/main/kotlin/cli/tests/SftpcheckTest.kt
  prime-router/src/main/kotlin/common/HttpClientUtils.kt
  prime-router/src/main/kotlin/credentials/AzureCredentialService.kt
  prime-router/src/main/kotlin/credentials/CredentialService.kt
  prime-router/src/main/kotlin/credentials/HashicorpVaultCredentialService.kt
  prime-router/src/main/kotlin/credentials/MemoryCredentialService.kt
  prime-router/src/main/kotlin/transport/GAENTransport.kt
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/test/kotlin/cli/ApiMockEngine.kt
  prime-router/src/test/kotlin/cli/LookupTableCommandsTest.kt
  prime-router/src/test/kotlin/cli/MainCmdTests.kt
  prime-router/src/test/kotlin/common/HttpClientUtilsTests.kt
  prime-router/src/test/kotlin/credentials/HashicorpVaultCredentialServiceTests.kt
  prime-router/src/test/kotlin/tokens/JwkTests.kt
  prime-router/src/test/kotlin/tokens/Server2ServerAuthenticationTests.kt
  prime-router/src/testIntegration/kotlin/transport/ApiMockEngineForIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/GAENTransportIntegrationTests.kt
Labels: pipeline, platform

#12334 Migrate to modular flyway (v10) + add postgres module
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
Labels: platform

#12327 Implement CLI update utility for observation mapping table
  prime-router/build.gradle.kts
  prime-router/docs/getting-started/standard-operating-procedures/observation-mapping-table.md
  prime-router/src/main/kotlin/cli/LookupTableCommands.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/test/kotlin/cli/LookupTableCommandsTest.kt
Labels: release_notes, demoable, platform

#12508 Experience/12330/page metadata
  frontend-react/.env.demo1
  frontend-react/.env.demo2
  frontend-react/.env.demo3
  frontend-react/.env.dev.csp
  frontend-react/.env.development
  frontend-react/.env.preview
  frontend-react/.env.production
  frontend-react/.env.staging
  frontend-react/.env.test
  frontend-react/.env.trialfrontend01
  frontend-react/.env.trialfrontend02
  frontend-react/.env.trialfrontend03
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKey.tsx
  frontend-react/src/content/about/case-studies.mdx
  frontend-react/src/content/about/index.mdx
  frontend-react/src/content/about/news.mdx
  frontend-react/src/content/about/our-network.mdx
  frontend-react/src/content/about/release-notes.mdx
  frontend-react/src/content/about/security.mdx
  frontend-react/src/content/developer-resources/index-page.mdx
  frontend-react/src/content/developer-resources/reportstream-api/ReportStreamApi.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/Documentation.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/ResponsesFromReportStream.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/SamplePayloadsAndOutput.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/data-model/DataModel.mdx
  frontend-react/src/content/developer-resources/reportstream-api/getting-started/GettingStarted.mdx
  frontend-react/src/content/getting-started/index.mdx
  frontend-react/src/content/getting-started/receiving-data.mdx
  frontend-react/src/content/getting-started/sending-data.mdx
  frontend-react/src/content/managing-your-connection/index.mdx
  frontend-react/src/content/managing-your-connection/refer-healthcare-organizations.mdx
  frontend-react/src/content/support/index.mdx
  frontend-react/src/layouts/Markdown/MarkdownLayout.tsx
  frontend-react/src/pages/Login.tsx
  frontend-react/src/pages/TermsOfService.tsx
  frontend-react/src/pages/admin/AdminLastMileFailures.tsx
  frontend-react/src/pages/admin/AdminMain.tsx
  frontend-react/src/pages/admin/AdminMessageTracker.tsx
  frontend-react/src/pages/admin/AdminOrgEdit.tsx
  frontend-react/src/pages/admin/AdminOrgNew.tsx
  frontend-react/src/pages/admin/AdminReceiverDashPage.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.tsx
  frontend-react/src/pages/data-dashboard/DataDashboard.tsx
  frontend-react/src/pages/deliveries/Deliveries.tsx
  frontend-react/src/pages/misc/FeatureFlags.tsx
  frontend-react/src/pages/submissions/Submissions.tsx
  frontend-react/src/utils/SupportedBrowsers.ts
  frontend-react/src/vite-env.d.ts
  frontend-react/yarn.lock
Labels: experience, trialfrontend03

#12540 12130: remove integration tests no longer in use
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: platform

#12546 Fix HCI sender transform
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_transforms/senders/baseline-sender-transform.yml
Labels: platform

#12561 12130: more test coverage of ORC/OBR to ServiceRequestDiagnosticReport
  prime-router/metadata/fhir_mapping/hl7/segments/ORC/OBRExtension.yml
  prime-router/metadata/hl7_mapping/resources/ServiceRequest/OBR.yml
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirTransformer.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirTransformerTests.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/orcobr/ORCOBRToServiceRequestDiagnosticReportTests.kt
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-obr11-a.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-obr11-a.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-obr11-g.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-obr11-g.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-obr11-l.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-obr11-l.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-obr8-not-populated.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-obr8-not-populated.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-orc-obr-populated.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-orc-obr-populated.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-prefers-orc-12-for-requester.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-prefers-orc-12-for-requester.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-prefers-orc-for-identifiers.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-prefers-orc-for-identifiers.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-requester-practitioner-missing-orc212223.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-requester-practitioner-missing-orc212223.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-requester-practitionerrole-orc21-populated.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-requester-practitionerrole-orc21-populated.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-requester-practitionerrole-orc22-populated.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-requester-practitionerrole-orc22-populated.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-requester-practitionerrole-orc23-populated.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-requester-practitionerrole-orc23-populated.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-sets-authored-on.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/orcobr/orc_obr-to-servicerequest_diagnosticreport-sets-authored-on.hl7
Labels: platform

#12596 11723 - Nov release notes
  frontend-react/src/content/about/release-notes.mdx
  frontend-react/yarn.lock
Labels: frontend, experience, trialfrontend01

#12539 Removed old RawSubmission code
  prime-router/src/main/kotlin/SubmissionReceiver.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIREngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
Labels: pipeline, platform

#12618 Revert "platform/jimfuqian/11928-Refactor-code-to-remove-old-and-unsu…
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/azure/EmailEngineFunction.kt
  prime-router/src/main/kotlin/cli/CommandUtilities.kt
  prime-router/src/main/kotlin/cli/LookupTableCommands.kt
  prime-router/src/main/kotlin/cli/OktaCommands.kt
  prime-router/src/main/kotlin/cli/SenderFilesCommand.kt
  prime-router/src/main/kotlin/cli/SettingCommands.kt
  prime-router/src/main/kotlin/cli/SettingsUtilities.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/main/kotlin/cli/tests/AuthTests.kt
  prime-router/src/main/kotlin/cli/tests/HistoryApiTest.kt
  prime-router/src/main/kotlin/cli/tests/LivdApiTest.kt
  prime-router/src/main/kotlin/cli/tests/SettingsTest.kt
  prime-router/src/main/kotlin/cli/tests/SftpcheckTest.kt
  prime-router/src/main/kotlin/common/HttpClientUtils.kt
  prime-router/src/main/kotlin/credentials/AzureCredentialService.kt
  prime-router/src/main/kotlin/credentials/CredentialService.kt
  prime-router/src/main/kotlin/credentials/HashicorpVaultCredentialService.kt
  prime-router/src/main/kotlin/credentials/MemoryCredentialService.kt
  prime-router/src/main/kotlin/transport/GAENTransport.kt
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/test/kotlin/cli/ApiMockEngine.kt
  prime-router/src/test/kotlin/cli/LookupTableCommandsTest.kt
  prime-router/src/test/kotlin/cli/MainCmdTests.kt
  prime-router/src/test/kotlin/common/HttpClientUtilsTests.kt
  prime-router/src/test/kotlin/credentials/HashicorpVaultCredentialServiceTests.kt
  prime-router/src/test/kotlin/tokens/JwkTests.kt
  prime-router/src/test/kotlin/tokens/Server2ServerAuthenticationTests.kt
  prime-router/src/testIntegration/kotlin/transport/ApiMockEngineForIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/GAENTransportIntegrationTests.kt
Labels: platform

#12621 Removed extra <Helmet> wrapper causing error and not allowing Daily data to load.
  frontend-react/src/pages/deliveries/Deliveries.tsx
Labels: frontend, experience

#12619 12349 - Updates to API guide
  frontend-react/public/assets/pdf/ReportStream-Programmers-Guide-v4.2.pdf
  frontend-react/src/content/developer-resources/reportstream-api/getting-started/GettingStarted.mdx
  frontend-react/src/content/developer-resources/reportstream-api/getting-started/Method1.mdx
  frontend-react/src/content/developer-resources/reportstream-api/getting-started/Method2.mdx
  frontend-react/src/content/developer-resources/reportstream-api/getting-started/Step1.mdx
  frontend-react/src/content/developer-resources/reportstream-api/getting-started/Step2.mdx
  frontend-react/src/content/developer-resources/reportstream-api/getting-started/Step3.mdx
  frontend-react/src/content/developer-resources/reportstream-api/getting-started/Step4.mdx
  frontend-react/src/content/site.json
Labels: frontend, experience, trialfrontend01

#12622 Fix overflow during integer parse of constants
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/ConstantResolverTests.kt
Labels: platform

#12632 Add AKDOH value to AK-DOH message
  prime-router/metadata/hl7_mapping/receivers/STLTs/AK/AK-receiver-transform.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SR_2_20231106-0003.hl7
Labels: onboarding-ops

#12514 12427: refactor delete resource to avoid OOM
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/test/kotlin/fhirengine/utils/FHIRBundleHelpersTests.kt
Labels: platform

#12623 Experience/12254/sender doc
  prime-router/docs/onboarding-users/senders.md
Labels: experience

#12571 Experience/12307/e2e homepage
  frontend-react/.eslintrc.cjs
  frontend-react/.gitignore
  frontend-react/cypress.config.ts
  frontend-react/cypress/README.md
  frontend-react/cypress/cypress.sample.json
  frontend-react/cypress/e2e/specs/daily-data-page.cy.ts
  frontend-react/cypress/e2e/specs/home-page.cy.ts
  frontend-react/cypress/e2e/specs/submissions-page.cy.ts
  frontend-react/cypress/fixtures/example.json
  frontend-react/cypress/plugins/index.ts
  frontend-react/cypress/support/commands.ts
  frontend-react/cypress/support/commands/api.ts
  frontend-react/cypress/support/commands/auth.ts
  frontend-react/cypress/support/commands/organizations.ts
  frontend-react/cypress/support/e2e.ts
  frontend-react/cypress/support/pageComponents/Base.ts
  frontend-react/cypress/support/pageComponents/DateRangeFilter.ts
  frontend-react/cypress/support/pageComponents/PaginatedTable.ts
  frontend-react/cypress/support/pages/Base.ts
  frontend-react/cypress/support/pages/DailyData.ts
  frontend-react/cypress/support/pages/Home.ts
  frontend-react/cypress/support/pages/Submissions.ts
  frontend-react/cypress/support/pages/admin/Base.ts
  frontend-react/cypress/support/pages/admin/OrganizationSettings.ts
  frontend-react/cypress/support/pages/admin/ValueSets.ts
  frontend-react/cypress/support/pages/resources/Base.ts
  frontend-react/cypress/support/pages/resources/Index.ts
  frontend-react/cypress/support/pages/resources/Show.ts
  frontend-react/e2e/fixtures/homepage.spec.ts
  frontend-react/e2e/fixtures/organization-settings-page.spec.ts
  frontend-react/e2e/fixtures/product-page.spec.ts
  frontend-react/e2e/fixtures/resources-page.spec.ts
  frontend-react/e2e/fixtures/support-page.spec.ts
  frontend-react/e2e/helpers/auth.setup.ts
  frontend-react/e2e/helpers/external-links.ts
  frontend-react/e2e/helpers/rs-test.ts
  frontend-react/e2e/helpers/utils.ts
  frontend-react/e2e/pages/getting-started.ts
  frontend-react/e2e/pages/header.ts
  frontend-react/e2e/pages/managing-your-connection.ts
  frontend-react/e2e/pages/our-network.ts
  frontend-react/e2e/pages/security.ts
  frontend-react/e2e/pages/support.ts
  frontend-react/package.json
  frontend-react/playwright.config.ts
  frontend-react/src/content/generated/global.out.css
  frontend-react/tsconfig.json
  frontend-react/yarn.lock
Labels: frontend, experience

#11923 Cleanup the Receiver-ssh-key directory
  prime-router/receiver-ssh-key/1-SelectAllSubscriptions.png
  prime-router/receiver-ssh-key/2-CreateSSHKeyScreen.png
  prime-router/receiver-ssh-key/3-SelectResourceGroup.png
  prime-router/receiver-ssh-key/4-NameSSHKey.png
  prime-router/receiver-ssh-key/5-AddStateTag.png
  prime-router/receiver-ssh-key/6-ReviewOptions.png
  prime-router/receiver-ssh-key/7-DownloadConfirmation.png
  prime-router/receiver-ssh-key/8-CreationConfirmation.png
Labels: onboarding-ops

#12641 Add REST for LA-PHL and Refactor
  prime-router/settings/prod/0160-ok-phd-prod-new-rest-setting.yml
  prime-router/settings/prod/0161-wa-prod-new-rest-setting.yml
  prime-router/settings/prod/0162-ny-prod-new-rest-setting.yml
  prime-router/settings/staging/0160-nbs-staging-new-rest-setting.yml
  prime-router/settings/staging/0161-flexion-staging-new-rest-setting.yml
  prime-router/settings/staging/0162-la-phl-staging-new-rest-setting.yml
  prime-router/settings/staging/0163-ok-phd-staging-new-rest-setting.yml
  prime-router/settings/staging/0164-ny-staging-new-rest-setting.yml
  prime-router/settings/staging/0165-wa-staging-new-rest-setting.yml
  prime-router/src/main/kotlin/TransportType.kt
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
Labels: onboarding-ops, etor

#12684 Experience/12309/e2e updates
  frontend-react/e2e/fixtures/homepage.spec.ts
  frontend-react/e2e/fixtures/our-network-page.spec.ts
  frontend-react/e2e/fixtures/product-page.spec.ts
  frontend-react/e2e/fixtures/resources-page.spec.ts
  frontend-react/e2e/fixtures/support-page.spec.ts
  frontend-react/e2e/helpers/utils.ts
  frontend-react/package.json
Labels: frontend, experience

#12629 Removing remaining RawSubmission code
  prime-router/docs/universal-pipeline/README.md
  prime-router/src/main/kotlin/fhirengine/azure/FHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/Message.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirRouterTests.kt
Labels: pipeline, platform

#12573 Platform/jessica/12461 json message serialization
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/SubmissionReceiver.kt
  prime-router/src/main/kotlin/azure/Event.kt
  prime-router/src/main/kotlin/fhirengine/azure/FHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIREngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/engine/QueueMessage.kt
  prime-router/src/test/kotlin/azure/EventTest.kt
  prime-router/src/test/kotlin/azure/batch/CovidBatchFunctionTests.kt
  prime-router/src/test/kotlin/azure/batch/UniversalBatchFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirRouterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/utils/HL7QueueMessageHelpersTests.kt
Labels: pipeline, platform

#12721 Experience/12446/date string bug
  frontend-react/src/components/DataDashboard/DataDashboardTable/DataDashboardTable.tsx
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilitiesProvidersTable.tsx
  frontend-react/src/components/DataDashboard/FacilityProviderSubmitterDetails/FacilityProviderSubmitterTable.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsTable.tsx
  prime-router/docs/onboarding-users/senders.md
Labels: frontend, experience

#12708 Fixed the issue where it could not handle Piped targetTypes
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirBundleUtils.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/FhirBundleUtilsTests.kt
Labels: pipeline, platform

#12500 Implement code to condition mapping and remerge CLI update tool
  prime-router/src/main/kotlin/ActionMessages.kt
  prime-router/src/main/kotlin/cli/LookupTableCommands.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/main/kotlin/metadata/LookupTable.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/utils/FHIRBundleHelpersTests.kt
Labels: platform
