Repository CDCgov/prime-reportstream, pull requests merged in 2023-05, with the labels that each got.

#9320 Add header info to platform user story template
  .github/ISSUE_TEMPLATE/platform-user-story.md
Labels: platform

#9306 Injecting the provenance resource when it is missing
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/FHIRBundleHelpersTests.kt
  prime-router/src/test/resources/fhirengine/engine/valid_data_no_provenance.fhir
Labels: platform

#9334 9076 - Added routes and empty pages for STLT dashboard
  frontend-react/src/AppRouter.tsx
  frontend-react/src/pages/dashboard/Dashboard.tsx
  frontend-react/src/pages/dashboard/facilities-providers/FacilitiesProviders.tsx
  frontend-react/src/pages/dashboard/facilities-providers/FacilityProviderSubmitterDetails.tsx
  frontend-react/src/pages/dashboard/report-details/ReportDetails.tsx
Labels: frontend, experience

#9233 8434 Extract LIVD Lookup FHIR custom function outside the conversion library
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/fhirengine/engine/CustomFhirPathFunctions.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathFunctions.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
  prime-router/src/test/kotlin/fhirengine/engine/CustomFhirPathFunctionTest.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/ConstantResolverTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctionsTests.kt
Labels: pipeline, platform

#9204 8659: clean auth code up now that organization store keys
  prime-router/docs/api/api-keys.yml
  prime-router/src/main/kotlin/Sender.kt
  prime-router/src/main/kotlin/SettingsProvider.kt
  prime-router/src/main/kotlin/azure/ApiKeysFunctions.kt
  prime-router/src/main/kotlin/azure/HttpUtilities.kt
  prime-router/src/main/kotlin/cli/OrganizationUtilsCommand.kt
  prime-router/src/main/kotlin/cli/SettingCommands.kt
  prime-router/src/main/kotlin/cli/tests/AuthTests.kt
  prime-router/src/main/kotlin/cli/tests/HistoryApiTest.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/tokens/AuthUtils.kt
  prime-router/src/main/kotlin/tokens/Server2ServerAuthentication.kt
  prime-router/src/test/kotlin/SettingsProviderTest.kt
  prime-router/src/test/kotlin/azure/TokenFunctionTests.kt
  prime-router/src/test/kotlin/metadata/MapperTests.kt
  prime-router/src/test/kotlin/tokens/AuthenticatedClaimsTests.kt
  prime-router/src/test/kotlin/tokens/Server2ServerAuthenticationTests.kt
Labels: platform

#9261 Support FHIR receivers and receiver transforms
  prime-router/metadata/fhir_transforms/receivers/fhir-transform-sample.yml
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/TranslatorConfiguration.kt
  prime-router/src/main/kotlin/azure/BatchFunction.kt
  prime-router/src/main/kotlin/cli/tests/BasicTests.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/main/kotlin/fhirengine/utils/HL7MessageHelpers.kt
  prime-router/src/test/kotlin/ReportTests.kt
  prime-router/src/test/kotlin/azure/BatchFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/FHIRBundleHelpersTests.kt
  prime-router/src/test/kotlin/fhirengine/utils/HL7MessageHelpersTests.kt
  prime-router/src/test/resources/fhirengine/engine/bundle_multiple_bundles.fhir
  prime-router/src/test/resources/fhirengine/engine/valid_data_multiple_targets.fhir
Labels: platform

#9389 Feature/7746 investigate alert tf changes action
  .github/workflows/alert_terraform_changes.yml
Labels: DevOps, reportstream

#9387 9077 - Implement main dashboard page
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/Admin/AdminReceiverDashboard.tsx
  frontend-react/src/components/DataDashboard/DataDashboardTable/DataDashboardTable.tsx
  frontend-react/src/components/DataDashboard/DataDashboardTable/ReceiverServices.tsx
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilitiesProviders.tsx
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilityProviderSubmitterDetails.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetails.tsx
  frontend-react/src/components/Table/TableFilters.css
  frontend-react/src/components/Table/TableFilters.test.tsx
  frontend-react/src/components/Table/TableFilters.tsx
  frontend-react/src/components/Table/TestTable.tsx
  frontend-react/src/config/endpoints/dataDashboard.ts
  frontend-react/src/hooks/network/DataDashboard/DataDashboardHooks.ts
  frontend-react/src/pages/dashboard/facilities-providers/FacilityProviderSubmitterDetails.tsx
  frontend-react/src/pages/data-dashboard/DataDashboard.tsx
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.tsx
  frontend-react/src/pages/submissions/SubmissionTable.tsx
  frontend-react/src/styles/_components.scss
  frontend-react/src/styles/_reportstream.scss
Labels: frontend, experience

#9393 Update tests to unmockk objects to fix inconsistent test failures
  prime-router/src/test/kotlin/fhirengine/engine/CustomFhirPathFunctionTest.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
Labels: pipeline, platform

#9357 Update release-notes.md
  frontend-react/src/content/product/release-notes.md
Labels: experience

#9418 Experience/8959/replace organizations table
  frontend-react/src/components/Admin/OrgsTable.tsx
  frontend-react/src/shared/Table/Table.module.scss
  frontend-react/src/shared/Table/Table.tsx
Labels: experience, trialfrontend01

#9438 9008 NPI sender transform
  prime-router/metadata/fhir_transforms/senders/default-sender-transform.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/CA-receiver-transform.yml
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirTransformer.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirTransformerTests.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_2_20230220-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_2_20230220-0001.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: pipeline, platform

#9465 Etor topic design
  prime-router/docs/proposals/0020-univeral-pipeline-topics.md
Labels: pipeline, platform

#9473 9080 - STLT Report Details Design
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/DataDashboard/DataDashboardTable/DataDashboardTable.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetails.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsSummary.module.scss
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsSummary.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsTable.module.scss
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsTable.tsx
  frontend-react/src/components/Table/TableFilters.test.tsx
  frontend-react/src/config/endpoints/dataDashboard.ts
  frontend-react/src/hooks/network/DataDashboard/DataDashboardHooks.ts
  frontend-react/src/pages/data-dashboard/DataDashboard.module.scss
  frontend-react/src/pages/data-dashboard/DataDashboard.tsx
  frontend-react/src/pages/deliveries/Table/ReportLink.tsx
  frontend-react/src/styles/_components.scss
  frontend-react/src/utils/DateTimeUtils.test.ts
  frontend-react/src/utils/DateTimeUtils.ts
Labels: frontend, experience

#9324 8519: universal search design proposals
  prime-router/docs/proposals/0018-universal-search.md
  prime-router/docs/proposals/0020-universal-metadata-search/0020-universal-metadata-search.md
  prime-router/docs/proposals/0020-universal-metadata-search/example-queries.md
  prime-router/docs/proposals/0020-universal-metadata-search/resource-in-db.png
  prime-router/docs/proposals/0020-universal-metadata-search/search-patient.png
  prime-router/docs/proposals/0020-universal-metadata-search/search-results.png
Labels: platform

#9527 change quality filter to block the negative Antigen Test results
  prime-router/settings/prod/0152-CA-update-antigen-qualityfilter.yml
  prime-router/settings/staging/0152-CA-update-antigen-qualityfilter.yml
Labels: onboarding-ops

#9472 Update Condition Filter to use OR instead of AND
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/DefaultFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
Labels: platform

#9462 Implement wider grid container site-wide
  frontend-react/package.json
  frontend-react/src/App.tsx
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/AuthElement.test.tsx
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilityProviderSubmitterDetails.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKey.test.tsx
  frontend-react/src/components/MessageTracker/MessageDetails.tsx
  frontend-react/src/components/SenderModeBanner.test.tsx
  frontend-react/src/components/header/ReportStreamHeader.test.tsx
  frontend-react/src/contexts/SessionContext.tsx
  frontend-react/src/global.scss
  frontend-react/src/hooks/UseOrganizationReceivers.test.ts
  frontend-react/src/hooks/UseOrganizationReceiversFeed.test.ts
  frontend-react/src/hooks/UseOrganizationSenders.test.ts
  frontend-react/src/hooks/UseOrganizationSettings.test.ts
  frontend-react/src/hooks/UseSenderResource.test.ts
  frontend-react/src/hooks/network/History/UseOrgDeliveries.test.ts
  frontend-react/src/hooks/network/History/UseReportDetail.test.ts
  frontend-react/src/hooks/network/History/UseReportFacilities.test.ts
  frontend-react/src/hooks/network/History/UseReportsList.test.ts
  frontend-react/src/hooks/network/MessageTracker/MessageTrackerHooks.test.ts
  frontend-react/src/hooks/network/Organizations/PublicKeys/UseCreateOrganizationPublicKey.test.ts
  frontend-react/src/hooks/network/Organizations/PublicKeys/UseOrganizationPublicKeys.test.ts
  frontend-react/src/index.tsx
  frontend-react/src/layouts/MainLayout.tsx
  frontend-react/src/pages/admin/AdminLastMileFailures.tsx
  frontend-react/src/pages/admin/AdminMessageTracker.tsx
  frontend-react/src/pages/admin/AdminReceiverDashPage.tsx
  frontend-react/src/pages/deliveries/Deliveries.tsx
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.test.tsx
  frontend-react/src/pages/deliveries/details/DeliveryDetail.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.tsx
  frontend-react/src/pages/submissions/SubmissionTable.test.tsx
  frontend-react/src/pages/submissions/Submissions.tsx
  frontend-react/src/styles/_reportstream.scss
  frontend-react/src/styles/_uswds_settings.scss
  frontend-react/src/types.d.ts
  frontend-react/src/utils/CustomRenderUtils.tsx
  frontend-react/yarn.lock
Labels: experience, trialfrontend03

#9526 9471 - Remove hyperlink on file download where date has expired.
  frontend-react/src/components/Table/ColumnData.tsx
  frontend-react/src/components/Table/Table.test.tsx
  frontend-react/src/components/Table/Table.tsx
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.tsx
Labels: frontend, experience

#9590 BUG: Errors bubbling to react-router
  frontend-react/src/layouts/MainLayout.test.tsx
  frontend-react/src/layouts/MainLayout.tsx
  frontend-react/src/pages/error/Generic.tsx
Labels: experience

#9061 Experience/8946/apiguide-documentation
  frontend-react/public/assets/xlsx/ReportStream CSV and HL7 Field Requirements (version 3.0).xlsx
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/Content/MarkdownLayout.tsx
  frontend-react/src/content/resources/api-programmers-guide/Sidenav.mdx
  frontend-react/src/content/resources/api-programmers-guide/documentation/Documentation.mdx
  frontend-react/src/content/resources/api-programmers-guide/documentation/ResponsesFromReportStream.mdx
  frontend-react/src/content/resources/api-programmers-guide/documentation/SamplePayloadsAndOutput.mdx
  frontend-react/src/content/resources/api-programmers-guide/documentation/data-model/AskOnEntryTable.mdx
  frontend-react/src/content/resources/api-programmers-guide/documentation/data-model/DataModel.mdx
  frontend-react/src/content/resources/api-programmers-guide/documentation/data-model/OrderAndResultDataElementsTable.mdx
  frontend-react/src/content/resources/api-programmers-guide/documentation/data-model/OrderingProviderDataElementsTable.mdx
  frontend-react/src/content/resources/api-programmers-guide/documentation/data-model/PatientDataElementsTable.mdx
  frontend-react/src/content/resources/api-programmers-guide/documentation/data-model/ReportingAndOrderingFacilityDataElementsTable.mdx
  frontend-react/src/content/resources/api-programmers-guide/documentation/data-model/SpecimenDataElementsTable.mdx
  frontend-react/src/content/resources/api-programmers-guide/documentation/data-model/TestingFacilityDataElementsTable.mdx
  frontend-react/src/pages/resources/api-programmers-guide/documentation/DataModel.stories.tsx
  frontend-react/src/pages/resources/api-programmers-guide/documentation/DataModel.tsx
  frontend-react/src/pages/resources/api-programmers-guide/documentation/Documentation.stories.tsx
  frontend-react/src/pages/resources/api-programmers-guide/documentation/Documentation.tsx
  frontend-react/src/pages/resources/api-programmers-guide/documentation/ResponsesFromReportStream.stories.tsx
  frontend-react/src/pages/resources/api-programmers-guide/documentation/ResponsesFromReportStream.tsx
  frontend-react/src/pages/resources/api-programmers-guide/documentation/SamplePayloadsAndOutput.stories.tsx
  frontend-react/src/pages/resources/api-programmers-guide/documentation/SamplePayloadsAndOutput.tsx
  frontend-react/src/shared/SideNavItem.test.tsx
  frontend-react/src/shared/SideNavItem.tsx
  frontend-react/src/styles/_components.scss
  frontend-react/src/styles/_uswds_overrides.scss
Labels: experience, chromatic

#9060 Experience/8945/apiguide-getting-started
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/Content/MarkdownLayout.tsx
  frontend-react/src/content/resources/api-programmers-guide/getting-started/GettingStarted.mdx
  frontend-react/src/content/resources/api-programmers-guide/getting-started/Method1.mdx
  frontend-react/src/content/resources/api-programmers-guide/getting-started/Method2.mdx
  frontend-react/src/pages/resources/api-programmers-guide/GettingStarted.stories.tsx
  frontend-react/src/pages/resources/api-programmers-guide/GettingStarted.tsx
  frontend-react/src/styles/_components.scss
  frontend-react/src/styles/_reportstream.scss
  frontend-react/src/styles/_uswds_overrides.scss
Labels: experience, chromatic

#8966 Experience/8944/apiguide reportstream api page
  frontend-react/src/AppRouter.tsx
  frontend-react/src/content/resources/ResourcesIndex.mdx
  frontend-react/src/content/resources/api-programmers-guide/ReportStreamApi.mdx
  frontend-react/src/pages/resources/api-programmers-guide/ReportStreamApi.stories.tsx
  frontend-react/src/pages/resources/api-programmers-guide/ReportStreamApi.tsx
Labels: experience, chromatic

#9591 Fixed mapping for specimen collected and received dates
  prime-router/metadata/hl7_mapping/ORU_R01/base/specimen.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SR_1_20230302-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SR_1_20230302-0001.hl7
Labels: pipeline, platform

#9534 8696 RADx MARS conditional receiver transforms
  prime-router/metadata/hl7_mapping/ORU_R01/RADx_MARS/RADx_MARS-base.yml
  prime-router/metadata/hl7_mapping/ORU_R01/RADx_MARS/RADx_MARS-observation-request.yml
  prime-router/metadata/hl7_mapping/ORU_R01/RADx_MARS/RADx_MARS-observation-result.yml
  prime-router/metadata/hl7_mapping/ORU_R01/RADx_MARS/RADx_MARS-order-observation.yml
  prime-router/metadata/hl7_mapping/ORU_R01/RADx_MARS/RADx_MARS-order.yml
  prime-router/settings/organizations.yml
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_RADx_MARS_20230406-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_RADx_MARS_20230406-0001.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: pipeline, platform

#9535 Introduce `etor-ti` topic to Universal Pipeline
  prime-router/build.gradle.kts
  prime-router/docs/proposals/0020-univeral-pipeline-topics.md
  prime-router/metadata/fhir_transforms/senders/Flexion/TILabOrder.yml
  prime-router/metadata/hl7_mapping/receivers/Flexion/TILabOrder.yml
  prime-router/settings/staging/0149-etor.yml
  prime-router/src/main/kotlin/JOOQBindings.kt
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/Sender.kt
  prime-router/src/main/kotlin/SettingsProvider.kt
  prime-router/src/main/kotlin/SubmissionReceiver.kt
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/BatchFunction.kt
  prime-router/src/main/kotlin/azure/SettingsFacade.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/docgenerators/MarkdownDocumentationFactory.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/engine/Message.kt
  prime-router/src/main/kotlin/history/DeliveryHistory.kt
  prime-router/src/main/kotlin/history/ReportHistory.kt
  prime-router/src/main/kotlin/history/SubmissionHistory.kt
  prime-router/src/main/kotlin/messages/ReportFileMessage.kt
  prime-router/src/test/kotlin/ReceiverTests.kt
  prime-router/src/test/kotlin/ReportTests.kt
  prime-router/src/test/kotlin/SettingsProviderTest.kt
  prime-router/src/test/kotlin/SubmissionReceiverTests.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/azure/BatchFunctionTests.kt
  prime-router/src/test/kotlin/azure/MessagesFunctionsTests.kt
  prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
  prime-router/src/test/kotlin/azure/SenderFilesFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/BundleUpdateTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/FHIRBundleHelpersTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
  prime-router/src/test/kotlin/history/DeliveryHistoryTests.kt
  prime-router/src/test/kotlin/history/SubmissionHistoryTests.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFacadeTests.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFunctionTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionFunctionTests.kt
Labels: platform

#9646 Route Resource Page Link to the new API Programmer's Guide
  frontend-react/src/AppRouter.tsx
  frontend-react/src/content/resources/api-programmers-guide/Sidenav.mdx
  frontend-react/src/content/resources/api-programmers-guide/getting-started/GettingStarted.mdx
  frontend-react/src/pages/resources/api-programmers-guide/documentation/DataModel.stories.tsx
  frontend-react/src/pages/resources/api-programmers-guide/documentation/Documentation.stories.tsx
  frontend-react/src/pages/resources/api-programmers-guide/documentation/ResponsesFromReportStream.stories.tsx
  frontend-react/src/pages/resources/api-programmers-guide/documentation/SamplePayloadsAndOutput.stories.tsx
Labels: experience

#9635 Cleaned up the calls to the LIVD lookup find function
  prime-router/src/main/kotlin/fhirengine/engine/CustomFhirPathFunctions.kt
  prime-router/src/main/kotlin/metadata/LivdLookup.kt
  prime-router/src/main/kotlin/metadata/LivdMappers.kt
  prime-router/src/test/kotlin/metadata/LivdLookupTests.kt
Labels: pipeline, platform
