Repository CDCgov/prime-reportstream, pull requests merged in 2023-06, with the labels that each got.

#9621 Correct Submission History to display "Received" and "Not Received" correctly
  prime-router/src/main/kotlin/history/SubmissionHistory.kt
  prime-router/src/test/kotlin/history/SubmissionHistoryTests.kt
Labels: platform

#9559 Log the element type and UUID for FHIR elements filtered out by Condition Filters
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
Labels: platform

#9667 Consider topics when routing in Universal Pipeline
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/cli/tests/BasicTests.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
Labels: platform

#9662 9331 - Added Web Analytics tracking to API Programmer's Guide download link
  frontend-react/src/content/resources/api-programmers-guide/ReportStreamApi.mdx
  frontend-react/src/pages/resources/api-programmers-guide/GettingStarted.stories.tsx
Labels: frontend, experience

#9698 Action update
  .github/workflows/alert_terraform_changes.yml
  .github/workflows/deploy_terraform.yml
Labels: github_actions

#9668 Checksum versioning
  .github/workflows/StaleItemsReport.yml
Labels: github_actions

#9691 Let analyzer choose skipUnchanged
  .github/workflows/build_hub.yml
  .github/workflows/sonarcloud_master.yml
Labels: github_actions

#9714 SonarCloud update
  .github/workflows/build_hub.yml
  .github/workflows/sonarcloud_master.yml
Labels: github_actions

#9656 Final API Programmer's Guide Engineering Changes Pre-launch
  frontend-react/src/App.tsx
  frontend-react/src/components/Content/MarkdownLayout.tsx
  frontend-react/src/components/ScrollRestoration.tsx
  frontend-react/src/components/USLink.test.tsx
  frontend-react/src/components/USLink.tsx
  frontend-react/src/content/resources/api-programmers-guide/Sidenav.mdx
  frontend-react/src/content/resources/api-programmers-guide/documentation/Documentation.mdx
  frontend-react/src/content/resources/api-programmers-guide/getting-started/GettingStarted.mdx
  frontend-react/src/content/resources/api-programmers-guide/getting-started/Method1.mdx
Labels: experience, trialfrontend03

#9715 Update the downloadable PDF file of the API Programmer's Guide
  frontend-react/public/assets/pdf/ReportStream-Programmers-Guide-v3.0.pdf
  frontend-react/public/assets/pdf/ReportStream-Programmers-Guide-v4.0.pdf
  frontend-react/src/content/site.json
Labels: experience, trialfrontend03

#9660 Experience/9212/file validator 404
  frontend-react/src/components/FileHandlers/FileHandlerSchemaSelectionStep.tsx
  frontend-react/src/hooks/UseSenderResource.ts
  frontend-react/src/network/QueryClients.ts
  frontend-react/src/senders/hooks/UseSenderSchemaOptions/index.ts
  frontend-react/src/utils/PermissionsUtils.ts
Labels: experience

#9784 Attempt to fix failing smoke test
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
Labels: pipeline, platform

#9756 9706 - Added more add more exception logging when calling trackException
  frontend-react/src/TelemetryService.test.ts
  frontend-react/src/TelemetryService.ts
Labels: frontend, experience

#9788 Fix the File Validator Statistics chart in App Insights Prod Dashboard
  templates/az_dashboard_json.tpl
Labels: DevOps, reportstream

#9732 Added the receiving_org and receiving_org_svc to the translate action
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
Labels: pipeline, platform

#9792 BUG: Chromatic Github Workflow Broken
  .github/workflows/chromatic-master.yml
  .github/workflows/chromatic-pr.yml
Labels: experience

#9924 CA receiver transforms
  prime-router/metadata/fhir_transforms/senders/SimpleReport/simple-report-sender-transform.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/CA-receiver-transform.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/CA.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-observation-request.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-observation-result.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-order.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-specimen.yml
  prime-router/settings/organizations.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_2_20230220-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SR_1_20230302-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_truncate_CA_20230406-0001.hl7
Labels: pipeline, platform

#9608 Enable soft deletion for Azure Storage Account
  operations/app/terraform/modules/sftp/storage.tf
  operations/app/terraform/modules/storage/candidate_slot.tf
  operations/app/terraform/modules/storage/main.tf
  operations/app/terraform/modules/storage/trial_frontends.tf
Labels: DevOps, reportstream

#9951 Feature/65 add check fa for monitoring tasktable
  .github/workflows/az_function_check.yml
  operations/app/terraform/modules/function_app/admin_app.tf
  requirements.txt
Labels: reportstream

#9911 Experience/dependabot-roundup
  frontend-react/package.json
  frontend-react/src/pages/admin/AdminRevHistory.test.tsx
  frontend-react/yarn.lock
Labels: security, experience, dependencies, javascript

#9693 Remove references to CsvFileTests
  prime-router/src/main/kotlin/ReportStreamFilter.kt
  prime-router/src/main/kotlin/SettingsProvider.kt
  prime-router/src/test/csv_test_files/input/federal-test-schema.schema
  prime-router/src/test/csv_test_files/input/test-organizations.yml
  prime-router/src/test/csv_test_files/input/test-schema.schema
  prime-router/src/test/kotlin/CsvFileTests.kt
Labels: platform

#9958 Add default etor filters to UP
  prime-router/src/main/kotlin/cli/tests/BasicTests.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/DefaultFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/GetFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
Labels: platform

#9666 9480 RADx MARS de-identification
  prime-router/metadata/hl7_mapping/ORU_R01/RADx_MARS/RADx_MARS-base-deidentified.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/observation-request.yml
  prime-router/metadata/hl7_mapping/common/datatype/cx-extended-composite-id.yml
  prime-router/metadata/hl7_mapping/common/datatype/ei-entity-identifier.yml
  prime-router/metadata/hl7_mapping/common/datatype/xad-extended-address.yml
  prime-router/metadata/hl7_mapping/common/datatype/xcn-contact.yml
  prime-router/metadata/hl7_mapping/common/datatype/xpn-person-name.yml
  prime-router/metadata/hl7_mapping/common/datatype/xtn-telecom.yml
  prime-router/settings/organizations.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_RADx_MARS_20230406-0002.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_RADx_MARS_20230406-0002.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SR_1_20230302-0001.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: pipeline, platform

#9165 Created the design docs for FHIR & HL7 validation
  prime-router/docs/design/validation/annotated-architecture-diagram.png
  prime-router/docs/design/validation/design.md
  prime-router/docs/design/validation/fhir-validator.png
Labels: platform

#10043 9397: verify the expected receiver got the report in UP smoketest
  prime-router/src/main/kotlin/cli/tests/BasicTests.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
Labels: platform

#10052 Out Of Memory Error on Chromatic Builds
  frontend-react/.storybook/main.ts
Labels: experience, chromatic

#10065 Remove remaining unused devDependencies
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: experience

#10067 BUG: Custom environment variables not loaded
  frontend-react/vite.config.ts
Labels: bug, experience

#9964 9778: add route message after all conversion is done
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
Labels: platform

#10014 Add more details to metadata proposal for condition mapping
  prime-router/docs/proposals/0020-universal-metadata-search/0020-universal-metadata-search.md
Labels: platform

#9390 8642: return more informative error messages on authenticate errors
  prime-router/docs/proposals/0021-authenticate-end-user-messaging.md
  prime-router/src/main/kotlin/azure/HttpUtilities.kt
  prime-router/src/main/kotlin/azure/TokenFunction.kt
  prime-router/src/main/kotlin/tokens/Server2ServerAuthentication.kt
  prime-router/src/main/kotlin/tokens/Server2ServerAuthenticationException.kt
  prime-router/src/test/kotlin/azure/TokenFunctionTests.kt
  prime-router/src/test/kotlin/tokens/Server2ServerAuthenticationTests.kt
Labels: pipeline, platform

#10109 Dependabot Dev Dependency Roundup
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: experience

#10077 update last mile table
  frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx
Labels: experience

#10110 Dependabot Non-Dev Dependency Roundup
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: experience

#10074 Bump semver from 7.5.* to 7.5.3 in /frontend-react
  frontend-react/yarn.lock
Labels: security, dependencies, javascript

#10113 BUG: USWDS Image/Font Paths Regression
  frontend-react/src/styles/_uswds_settings.scss
Labels: experience

#9928 Adds a utility function to remove PHI from a bundle
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/FHIRBundleHelpersTests.kt
Labels: pipeline, platform

#10123 9735 force using TLS 1.3 for NY-PHD
  prime-router/src/main/kotlin/transport/RESTTransport.kt
Labels: onboarding-ops, security

#10048 Cleaned up SonarCloud code smells as well as IntelliJ warnings in the…
  prime-router/src/main/kotlin/fhirengine/engine/CustomFhirPathFunctions.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIREngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/engine/Message.kt
  prime-router/src/test/kotlin/fhirengine/engine/CustomFhirPathFunctionTest.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/BundleUpdateTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/DefaultFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/FHIRBundleHelpersTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/GetFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
Labels: platform

#10143 override to forked/patched version in /frontend-react
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: security, dependencies, javascript

#10174 Deduplicate and update dependencies
  frontend-react/yarn.lock
Labels: security, dependencies, javascript
