Repository CDCgov/prime-reportstream, pull requests merged in 2023-03, with the labels that each got.

#8332 Fix delivery & submission history filtering inconsistencies
  prime-router/docs/api/waters-delivery.yml
  prime-router/docs/api/waters-submissions.yml
  prime-router/src/main/kotlin/cli/tests/HistoryApiTest.kt
  prime-router/src/main/kotlin/history/azure/DeliveryFunction.kt
  prime-router/src/main/kotlin/history/azure/ReportFileFunction.kt
  prime-router/src/main/kotlin/history/azure/SubmissionFunction.kt
  prime-router/src/test/kotlin/history/azure/SubmissionFunctionTests.kt
Labels: release_notes, platform

#8551 Update Jest to run in UTC
  frontend-react/package.json
Labels: experience

#8444 8426 Created simple ADT A01 and OML O21 FHIR to HL7 v2 schema
  prime-router/metadata/hl7_mapping/ADT_A01/ADT_A01-base.yml
  prime-router/metadata/hl7_mapping/OML_O21/OML_O21-base.yml
  prime-router/metadata/hl7_mapping/ORU_R01/ORU_R01-base.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/patient-contact.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/patient-visit.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/patient.yml
  prime-router/metadata/hl7_mapping/STLTs/CO/CO.yml
  prime-router/metadata/hl7_mapping/Senders/SimpleReport.yml
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/converter/ConverterSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/HL7Utils.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/FHIRBundleHelpersTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReaderTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/converter/ConverterSchemaTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/fhirTransform/FhirTransformSchemaTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/Hl7UtilsTests.kt
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01-extended.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-02/ORU_R01_incomplete.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-03/ORU_R01_bad.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-04/ORU_R01.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-05/ORU_R01.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-06/ORU_R01.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-06/ORU_R01_circular.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-06/ORU_R01_extends.yml
Labels: platform

#8536 Victor/8320 AOE questions FHIR to HL7 translation
  prime-router/metadata/hl7_mapping/ORU_R01/base/order-observation.yml
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctions.kt
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: pipeline, platform

#8556 8453 ELR intake url update
  frontend-react/src/content/site.json
Labels: frontend, experience

#8567 Experience-8565: Fix incorrect HL7 schema for validator options
  frontend-react/src/senders/hooks/UseSenderSchemaOptions/index.ts
Labels: experience

#8498 Experience-7945: Update additional validation error messages
  frontend-react/src/components/FileHandlers/FileHandler.test.tsx
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.test.tsx
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx
  frontend-react/src/config/endpoints/waters.ts
  frontend-react/src/hooks/UseFileHandler.test.ts
  prime-router/src/main/kotlin/ActionMessages.kt
  prime-router/src/main/kotlin/azure/RequestFunction.kt
  prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
Labels: frontend, experience

#8561 8552 Gracefully Handle Routing Filters when a property isn't present in the FHIR Bundle
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/ActionLog.kt
  prime-router/src/main/kotlin/ActionMessages.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
Labels: pipeline, platform

#8529 update to latest commit of OVPN
  .github/actions/vpn-azure/action.yml
Labels: DevOps, security, github_actions

#8430 Experience-6693: Add doc for front-end test patterns
  frontend-react/docs/test-conventions.md
Labels: experience

#8315 Jessica/8095 implement condition filter
  prime-router/metadata/tables/local/fhirpath_filter_shorthand.csv
  prime-router/src/main/kotlin/Metadata.kt
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/Translator.kt
  prime-router/src/main/kotlin/cli/tests/BasicTests.kt
  prime-router/src/main/kotlin/cli/tests/CompareData.kt
  prime-router/src/main/kotlin/cli/tests/Hl7Tests.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/test/kotlin/ReceiverTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/BundleUpdateTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/FHIRBundleHelpersTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/GetFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
  prime-router/src/test/resources/fhirengine/engine/bundle_multiple_observations.fhir
  prime-router/yarn.lock
Labels: pipeline, platform

#8572 7785 Remove feature flag for Message Tracker
  frontend-react/src/components/header/DropdownNav.test.tsx
  frontend-react/src/components/header/DropdownNav.tsx
  frontend-react/src/pages/misc/FeatureFlags.tsx
Labels: frontend, experience

#8576 Bump org.json:json@20220924 to org.json:json:20230227 in /prime-router
  prime-router/build.gradle.kts
Labels: security, dependencies, java

#8582 Victor/8320 FHIR translation AOE questions
  prime-router/metadata/hl7_mapping/ORU_R01/base/observation-result.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SR_1_20230302-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SR_1_20230302-0001.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: pipeline, platform

#8604 Experience-8602: Add FHIR format to list of options
  frontend-react/src/hooks/UseFileHandler.ts
  frontend-react/src/utils/TemporarySettingsAPITypes.test.ts
  frontend-react/src/utils/TemporarySettingsAPITypes.ts
Labels: experience

#8535 8093 UP FHIR bundles should reference Diagnostic Reports in Provenance target property
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/translation/HL7toFhirTranslator.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/FHIRBundleHelpersTests.kt
Labels: pipeline, platform

#8601 fixes single long string modal issue
  frontend-react/src/styles/_uswds_overrides.scss
Labels: frontend, experience

#8632 8288 Send Okta user email with all App Insights events
  frontend-react/src/TelemetryService.ts
  frontend-react/src/utils/SessionStorageTools.ts
Labels: frontend, experience, insights

#8550 Experience-8549: Fix incorrect setting type history
  frontend-react/src/network/api/Organizations/SettingRevisions.ts
Labels: experience

#8600 8098 generate condition filtered FHIR bundle
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/test/resources/fhirengine/engine/bundle_all_filtered_observations.fhir
  prime-router/src/test/resources/fhirengine/engine/bundle_some_filtered_observations.fhir
  prime-router/src/test/resources/fhirengine/engine/valid_data_with_extensions.fhir
Labels: pipeline, platform

#8665 8395 [Manage Public Key] Add new route, and basic page
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKey.tsx
Labels: frontend, experience

#7185 Send retries over longer period of time.
  prime-router/src/main/kotlin/azure/Event.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
Labels: pipeline, platform

#8681 Trusted Intermediary: Lab Order Base
  prime-router/metadata/hl7_mapping/ORU_R01/base/message-header.yml
  prime-router/metadata/hl7_mapping/Senders/TrustedIntermediaryLabOrder.yml
Labels: etor

#8715 Upload latest API Programmers Guide PDF to RS Website
  frontend-react/public/assets/pdf/ReportStream-Programmers-Guide-v2.3-updated.pdf
  frontend-react/public/assets/pdf/ReportStream-Programmers-Guide-v3.0.pdf
  frontend-react/src/content/site.json
Labels: experience

#8635 Experience-8026: Widen grid container
  frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx
  frontend-react/src/components/Admin/AdminReceiverDashboard.tsx
  frontend-react/src/components/Admin/OrgsTable.tsx
  frontend-react/src/components/Content/PageGenerationTools.tsx
  frontend-react/src/components/Content/Templates/IACardGridTemplate.tsx
  frontend-react/src/components/Crumbs.tsx
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/components/HipaaNotice.tsx
  frontend-react/src/components/MessageTracker/MessageDetails.tsx
  frontend-react/src/components/MessageTracker/MessageTracker.tsx
  frontend-react/src/components/Table/Table.tsx
  frontend-react/src/components/Table/TableFilters.tsx
  frontend-react/src/pages/admin/AdminLastMileFailures.tsx
  frontend-react/src/pages/admin/AdminMain.tsx
  frontend-react/src/pages/admin/AdminMessageTracker.tsx
  frontend-react/src/pages/admin/AdminReceiverDashPage.tsx
  frontend-react/src/pages/deliveries/Deliveries.tsx
  frontend-react/src/pages/deliveries/Table/DeliveriesTable.tsx
  frontend-react/src/pages/deliveries/details/DeliveryDetail.tsx
  frontend-react/src/pages/deliveries/details/DeliveryFacilitiesTable.tsx
  frontend-react/src/pages/deliveries/details/DeliveryInfo.tsx
  frontend-react/src/pages/deliveries/details/Summary.tsx
  frontend-react/src/pages/resources/Resources.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.tsx
  frontend-react/src/pages/submissions/Submissions.tsx
  frontend-react/src/pages/support/Support.tsx
  frontend-react/src/styles/_uswds_overrides.scss
Labels: experience

#8726 US Core Race Extension for FHIR -> HL7v2 Conversion
  prime-router/metadata/hl7_mapping/ORU_R01/base/patient.yml
Labels: etor, etor-mvp

#8707 Update release-notes.md
  frontend-react/src/content/product/release-notes.md
Labels: experience

#8735 Remove scripts/test.js in favor of config
  frontend-react/jest.config.ts
  frontend-react/package.json
  frontend-react/scripts/test.js
Labels: experience

#8743 Add new issue template for design tickets
  .github/ISSUE_TEMPLATE/design-issue-template.md
Labels: design

#8760 Experience 8616: Relax Organization/service name validation
  frontend-react/src/components/Admin/EditSenderSettings.test.tsx
  frontend-react/src/components/Admin/EditSenderSettings.tsx
  frontend-react/src/components/Admin/NewSetting.tsx
  frontend-react/src/utils/misc.test.ts
  frontend-react/src/utils/misc.ts
Labels: bug, experience

#8754 8212 Moved phone utilities class to library folders
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/PhoneUtilities.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/PhoneUtilitiesTests.kt
Labels: platform

#8759 Trusted Intermediary: Added birth time to FHIR to HL7v2 conversion
  prime-router/metadata/hl7_mapping/common/patient.yml
Labels: etor, etor-mvp

#8809 Trusted Intermediary: FHIR ServiceRequest -> OML Order and Order Observation
  prime-router/metadata/hl7_mapping/OML_O21/OML_O21-base.yml
  prime-router/metadata/hl7_mapping/OML_O21/base/service-request-order-observation.yml
  prime-router/metadata/hl7_mapping/OML_O21/base/service-request-order.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/TrustedIntermediaryLabOrder.yml
Labels: etor, etor-mvp

#8786 Trusted Intermediary: Added birth order to FHIR to HL7v2 conversion
  prime-router/metadata/hl7_mapping/STLTs/CA/TrustedIntermediaryLabOrder.yml
  prime-router/metadata/hl7_mapping/common/patient.yml
Labels: etor, etor-mvp

#8829 Remove Unsupported test type gaen from last mile failure
  prime-router/src/main/kotlin/transport/GAENTransport.kt
Labels: onboarding-ops

#8785 Add Telecom to FHIR path
  prime-router/metadata/hl7_mapping/common/patient-contact.yml
Labels: etor, etor-mvp

#8800 8587 Added additional CA receiver transforms
  prime-router/metadata/hl7_mapping/ORU_R01/base/order.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/CA.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/ca-order-observation.yml
  prime-router/metadata/hl7_mapping/STLTs/CA/ca-order.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SR_1_20230302-0001.hl7
Labels: pipeline, platform

#8856 Engagement/bgreen/check default time before conversion
  prime-router/src/main/kotlin/common/DateUtilities.kt
Labels: onboarding-ops

#8858 Documented copy process for conversion library
  prime-router/src/main/kotlin/fhirengine/translation/hl7/notes on migration.md
Labels: platform

#8833 Initial integration of fhir transforms into universal pipeline
  prime-router/metadata/fhir_transforms/fhir-transform-sample.yml
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/Sender.kt
  prime-router/src/main/kotlin/SubmissionReceiver.kt
  prime-router/src/main/kotlin/azure/RequestFunction.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/Message.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirTransformer.kt
  prime-router/src/test/kotlin/SubmissionReceiverTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
Labels: platform

#8820 CA Flu Condition Filters Proposal
  prime-router/metadata/tables/local/fhirpath_filter_shorthand.csv
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
Labels: platform

#8731 8396- Public key tool select sender and upload key component
  frontend-react/src/__mocks__/OrganizationMockServer.ts
  frontend-react/src/components/ManagePublicKey/ManagePublicKey.test.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKey.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKeyChooseSender.test.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKeyChooseSender.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKeyUpload.test.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKeyUpload.tsx
  frontend-react/src/components/Spinner.test.tsx
  frontend-react/src/components/Spinner.tsx
  frontend-react/src/hooks/UseOrganizationSenders.test.ts
  frontend-react/src/hooks/UseOrganizationSenders.ts
  frontend-react/src/hooks/UseValueSets.ts
  frontend-react/src/styles/_components.scss
  frontend-react/src/utils/FileUtils.ts
Labels: frontend, experience

#8745 Platform/mkalish/8669
  prime-router/src/main/kotlin/cli/SenderUtilsCommand.kt
  prime-router/src/main/kotlin/cli/SettingCommands.kt
Labels: platform

#8895 Update release-notes.md
  frontend-react/src/content/product/release-notes.md
Labels: experience

#8893 Experience-8170: Update validate endpoint to return 200 for strictly validation errors
  prime-router/docs/api/validate.yml
  prime-router/src/main/kotlin/azure/ValidateFunction.kt
  prime-router/src/test/kotlin/azure/ValidateFunctionTests.kt
Labels: experience

#8714 Experience/8531/file validator redesign
  frontend-react/package.json
  frontend-react/src/__mocks__/validation.ts
  frontend-react/src/components/FileHandlers/FileHandler.test.tsx
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/components/FileHandlers/FileHandlerButton.test.tsx
  frontend-react/src/components/FileHandlers/FileHandlerButton.tsx
  frontend-react/src/components/FileHandlers/FileHandlerErrorsWarningsStep.test.tsx
  frontend-react/src/components/FileHandlers/FileHandlerErrorsWarningsStep.tsx
  frontend-react/src/components/FileHandlers/FileHandlerFileUploadStep.test.tsx
  frontend-react/src/components/FileHandlers/FileHandlerFileUploadStep.tsx
  frontend-react/src/components/FileHandlers/FileHandlerForm.test.tsx
  frontend-react/src/components/FileHandlers/FileHandlerForm.tsx
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.test.tsx
  frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx
  frontend-react/src/components/FileHandlers/FileHandlerPiiWarning.tsx
  frontend-react/src/components/FileHandlers/FileHandlerProgrammersGuideTip.tsx
  frontend-react/src/components/FileHandlers/FileHandlerSchemaSelectionStep.test.tsx
  frontend-react/src/components/FileHandlers/FileHandlerSchemaSelectionStep.tsx
  frontend-react/src/components/FileHandlers/FileHandlerSuccessStep.tsx
  frontend-react/src/hooks/UseFileHandler.test.ts
  frontend-react/src/hooks/UseFileHandler.ts
  frontend-react/src/hooks/network/WatersHooks.test.ts
  frontend-react/src/hooks/network/WatersHooks.ts
  frontend-react/src/pages/resources/legacy-page-content/ElrChecklist.tsx
  frontend-react/src/senders/hooks/UseSenderSchemaOptions/UseSenderSchemaOptions.test.ts
  frontend-react/src/senders/hooks/UseSenderSchemaOptions/index.ts
  frontend-react/src/setupTests.ts
  frontend-react/src/styles/_components.scss
  frontend-react/src/utils/FileUtils.ts
  frontend-react/src/utils/TemporarySettingsAPITypes.ts
  frontend-react/yarn.lock
Labels: experience
