Repository CDCgov/prime-reportstream, pull requests merged in 2023-11, with the labels that each got.

#12030 Revert "Update github/codeql-action requirement to 4fddc51e4f3b5e5e9022f35c3464736cc10e1e98"
  .github/workflows/sonarcloud.yml
Labels: DevOps, dependencies, github_actions

#12032 Experience/11414/legacy pages
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKeyConfigured.tsx
  frontend-react/src/content/about/release-notes.mdx
  frontend-react/src/content/developer-resources/getting-started-submitting-data.md
  frontend-react/src/content/developer-resources/getting-started-submitting-data.mdx
  frontend-react/src/content/developer-resources/referral-guide.md
  frontend-react/src/content/developer-resources/referral-guide.mdx
  frontend-react/src/content/developer-resources/reportstream-api/ReportStreamApi.mdx
Labels: frontend, experience

#12057 fix-metabase-health-check-dns-value-prod
  .github/workflows/validate_terraform.yml
  operations/app/terraform/modules/application_insights/alert_availability.tf
Labels: DevOps, reportstream

#12053 Remove duplicate okta settings in function app
  operations/app/terraform/modules/function_app/candidate_slot.tf
  operations/app/terraform/modules/function_app/locals.tf
  operations/app/terraform/modules/function_app/main.tf
  operations/app/terraform/vars/staging/locals.tf
  operations/app/terraform/vars/test/locals.tf
Labels: DevOps, reportstream

#12042 Experience/12006 receiving updates
  frontend-react/src/content/getting-started/receiving-data.mdx
Labels: frontend, experience, trialfrontend01

#12002 11672: NDL mappings
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/CNN/Practitioner.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/NDL/HD/Location.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/NDL/IS/Location.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/NDL/PractitionerRole.yml
  prime-router/metadata/fhir_mapping/hl7/resource/DiagnosticReport.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/observation-request.yml
  prime-router/metadata/hl7_mapping/common/datatype/cnn-composite-number-name.yml
  prime-router/metadata/hl7_mapping/common/observation-request.yml
  prime-router/metadata/hl7_mapping/resources/Practitioner/CNN.yml
  prime-router/metadata/hl7_mapping/resources/PractitionerRole/Location/HD.yml
  prime-router/metadata/hl7_mapping/resources/PractitionerRole/NDL.yml
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/cnn/CNNTests.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/ndl/NDLToPractitionerRoleTests.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/nte/NTETests.kt
  prime-router/src/testIntegration/resources/datatests/mappinginventory/CNN/CNN-to-Practitioner.csv
  prime-router/src/testIntegration/resources/datatests/mappinginventory/CNN/CNN-to-Practitioner.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/CNN/CNN-to-Practitioner.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/ndl/NDL-to-PractitionerRole.csv
  prime-router/src/testIntegration/resources/datatests/mappinginventory/ndl/NDL-to-PractitionerRole.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/ndl/NDL-to-PractitionerRole.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/nte/NTE-to-Annotation.csv
  prime-router/src/testIntegration/resources/datatests/mappinginventory/nte/NTE-to-annotation.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/nte/NTE-to-annotation.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/nte/annotation_author_string_resource_test_file.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/nte/nte_segment_author_string_test_file.hl7
Labels: platform

#12040 Implemented sender compendium comparison tool / obx mapping tool
  prime-router/src/main/kotlin/cli/FileUtilities.kt
  prime-router/src/main/kotlin/cli/LookupTableCommands.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/test/kotlin/cli/CommonUtilitiesTests.kt
  prime-router/src/test/kotlin/cli/LookupTableCommandsTest.kt
Labels: pipeline, platform

#12072 CWE[Quantity] and CWE[Coding] mapping inventory
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/CWE/Coding.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/CWE/Quantity.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/XON/Organization.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Observation.yml
  prime-router/metadata/hl7_mapping/common/observation-result.yml
  prime-router/metadata/hl7_mapping/resources/Organization/XON.yml
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/cwe/CWEtoQuantityTests.kt
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cwe/quantity/CWEtoQuantity.csv
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cwe/quantity/cwe-quantity.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cwe/quantity/cwe-quantity.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xon/xon-to-organization-xon10-populated-xon3-empty.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xon/xon-to-organization-xon10-populated.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xon/xon-to-organization.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xon/xon-to-organization.hl7
Labels: platform

#12041 Add availability testing for the SFTP container
  operations/app/functions/admin/ConfirmSFTPAccess/__init__.py
  operations/app/functions/admin/ConfirmSFTPAccess/confirm_sftp_access.py
  operations/app/functions/admin/ConfirmSFTPAccess/function.json
  operations/app/functions/admin/requirements.txt
  operations/app/terraform/modules/application_insights/alert_availability.tf
  operations/app/terraform/modules/function_app/admin_app.tf
Labels: DevOps, enhancement

#12075 Bump azurite in tests
  .environment/docker/docker-compose/Dockerfile.azurite
  prime-router/build.gradle.kts
  prime-router/src/test/kotlin/azure/BlobAccessTests.kt
Labels: platform

#12014 11673 11812 add XPN and FN mappings
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/FN/ExtensionHumanName-family.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/XPN/HumanName.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/PatientContact.yml
  prime-router/metadata/hl7_mapping/common/patient-contact.yml
  prime-router/metadata/hl7_mapping/datatypes/HumanName/FN.yml
  prime-router/metadata/hl7_mapping/datatypes/HumanName/XPN.yml
  prime-router/src/test/kotlin/azure/BlobAccessTests.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/xpn/XPNtoHumanNameTests.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_2_20230220-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_OML_20230831-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_RADx_MARS_20230406-0002.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xpn/xpn-to-humanname-xpn10-populated-xpn12-13-empty.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xpn/xpn-to-humanname-xpn10-populated-xpn12-13-empty.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xpn/xpn-to-humanname-xpn12-13-populated-xpn10-empty.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xpn/xpn-to-humanname-xpn12-13-populated-xpn10-empty.hl7
Labels: platform

#12062 Restore backend stats
  .github/workflows/sonarcloud.yml
Labels: DevOps, security

#12161 Removing app insights availability check for the sftp container
  operations/app/terraform/modules/application_insights/alert_availability.tf
Labels: bug, DevOps

#12117 11670: PL and DLD to location mapping inventory
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/DLD/Location.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/EI/Identifier-DefaultAssigner.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/EI/Identifier-Organization.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/EI/Organization.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/HD/Identifier/IdentifierNamespaceId.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/HD/Identifier/IdentifierUniversalId.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/ID/CodeableConcept.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/NDL/HD/Location.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/PL/Location.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/PL/LocationBranch1.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/PL/LocationBranch2.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/PL/LocationBranch3.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/PL/LocationBranch4.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/PL/LocationBranch5.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Encounter.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/EncounterLocation.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/Hospitalization.yml
  prime-router/metadata/hl7_mapping/common/patient-visit.yml
  prime-router/metadata/hl7_mapping/datatypes/identifier/EI.yml
  prime-router/metadata/hl7_mapping/datatypes/identifier/HD.yml
  prime-router/metadata/hl7_mapping/resources/Location/DLD.yml
  prime-router/metadata/hl7_mapping/resources/Location/PL/PL.yml
  prime-router/metadata/hl7_mapping/resources/Location/PL/PLBranch.yml
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/cwe/CWEtoAnnotation.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/cwe/CWEtoCodeableConcept.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/dld/DLDToLocationTests.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/ei/EIToIdentifierTests.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/pl/PLToLocationTests.kt
  prime-router/src/testIntegration/resources/datatests/mappinginventory/dld/DLD-to-Location.csv
  prime-router/src/testIntegration/resources/datatests/mappinginventory/dld/DLD-to-Location.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/dld/DLD-to-Location.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/ei/EI-to-Identifier-default-assigner.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/ei/EI-to-Identifier-default-assigner.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/ei/EI-to-Identifier-organization-assigner.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/ei/EI-to-Identifier-organization-assigner.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/ei/EI-to-IdentifierDefaultAssigner.csv
  prime-router/src/testIntegration/resources/datatests/mappinginventory/ei/EI-to-IdentifierOrganization.csv
  prime-router/src/testIntegration/resources/datatests/mappinginventory/ndl/NDL-to-PractitionerRole.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-all-leaves.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-all-leaves.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-missing-pl1-pl3.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-missing-pl1-pl3.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-missing-pl1.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-missing-pl1.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-missing-pl7.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-missing-pl7.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-only-pl3-pl1-pl4.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-only-pl3-pl1-pl4.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-only-pl3-pl4.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-only-pl3-pl4.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-only-pl4.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-only-pl4.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location.csv
Labels: platform

#12146 add DAP script to all public pages
  frontend-react/src/shared/DAPScript/DAPScript.tsx
Labels: experience

#12129 Onboarding AK setting
  prime-router/metadata/hl7_mapping/receivers/STLTs/AK/AK-receiver-transform.yml
  prime-router/settings/prod/0157-AK-up-onboarding.yml
  prime-router/settings/staging/0157-AK-up-onboarding.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SR_2_20231106-0003.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SR_2_20231106-0003.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: onboarding-ops

#11938 Limit jitpack use
  prime-router/build.gradle.kts
Labels: security, dependencies, java

#12221 12154 - Homepage updates
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/content/home/index.mdx
  frontend-react/src/shared/HeroWrapper/HeroWrapper.stories.tsx
Labels: frontend, experience, trialfrontend02

#12240 remove env block, add better safety
  frontend-react/src/App.tsx
  frontend-react/src/shared/DAPScript/DAPScript.tsx
Labels: experience

#12181 Added a document with background/howtos on condition mapping table
  prime-router/docs/getting-started/standard-operating-procedures/observation-mapping-table.md
Labels: platform

#12167 11659: EI to Identifier and Device-udiCarrier
  prime-router/metadata/fhir_mapping/hl7/datatypes/EI/Device-udiCarrier.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/EI/Identifier.yml
  prime-router/metadata/fhir_mapping/hl7/message/ORU_R01.yml
  prime-router/metadata/fhir_mapping/hl7/resource/DiagnosticReport.yml
  prime-router/metadata/fhir_mapping/hl7/segments/PRT/Device.yml
  prime-router/metadata/fhir_transforms/senders/SimpleReport/simple-report-sender-transform.yml
  prime-router/metadata/hl7_mapping/ORU_R01/ORU_R01-base.yml
  prime-router/metadata/hl7_mapping/common/observation-request.yml
  prime-router/metadata/hl7_mapping/datatypes/device-udiCarrier/EI.yml
  prime-router/metadata/hl7_mapping/datatypes/identifier-extension/EI.yml
  prime-router/metadata/hl7_mapping/resources/Device/PRT.yml
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/ei/EIToDeviceUDICarrierTests.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/ei/EIToIdentifierExtensionTests.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_2_20230220-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_OML_20230831-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_RADx_MARS_20230406-0002.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_multiple_observations.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_multiple_observations_keepall.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_some_filtered_observations.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/ei/EI-to-Device-UDI-Carrier.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/ei/EI-to-Device-UDI-Carrier.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/ei/EI-to-Identifier-Extension.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/ei/EI-to-Identifier-Extension.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/nte/NTE-to-annotation.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/nte/annotation_author_string_resource_test_file.fhir
Labels: platform

#12259 Remove dummy action from build_hub
  .github/actions/build-vars/action.yml
  .github/workflows/build_hub.yml
  .github/workflows/build_hub_dummy.yml
Labels: DevOps, enhancement

#11532 Okta Migration Changes
  frontend-react/.env.demo1
  frontend-react/.env.demo2
  frontend-react/.env.demo3
  frontend-react/.env.dev.csp
  frontend-react/.env.development
  frontend-react/.env.preview
  frontend-react/.env.production
  frontend-react/.env.staging
  frontend-react/.env.test
  frontend-react/.env.trialfrontend01
  frontend-react/.env.trialfrontend02
  frontend-react/.env.trialfrontend03
  frontend-react/404.html
  frontend-react/index.html
  prime-router/build.gradle.kts
  prime-router/docker-compose.yml
  prime-router/docs/api/components/security_schemes.yml
  prime-router/docs/design/proposals/0004-settings-api/openapi.yml
  prime-router/docs/docs-deprecated/environment-provisioning.md
  prime-router/docs/docs-deprecated/getting-started/Using-an-apple-silicon-mac.md
  prime-router/docs/docs-deprecated/getting-started/getting-started.md
  prime-router/src/main/kotlin/azure/ApiKeysFunctions.kt
  prime-router/src/main/kotlin/azure/EmailEngineFunction.kt
  prime-router/src/main/kotlin/azure/HistoryFunctions.kt
  prime-router/src/main/kotlin/cli/OktaCommands.kt
  prime-router/src/main/kotlin/tokens/OktaAuthentication.kt
Labels: backend, DevOps, frontend, platform

#12162 Experience/8941/code snippet
  frontend-react/src/content/developer-resources/reportstream-api/getting-started/Method1.mdx
  frontend-react/src/content/developer-resources/reportstream-api/getting-started/Method2.mdx
  frontend-react/src/shared/CodeSnippet/CodeSnippet.module.scss
  frontend-react/src/shared/CodeSnippet/CodeSnippet.stories.tsx
  frontend-react/src/shared/CodeSnippet/CodeSnippet.tsx
  frontend-react/src/shared/index.ts
  frontend-react/src/utils/SupportedBrowsers.ts
  frontend-react/yarn.lock
Labels: frontend, experience, trialfrontend01

#12266 Use test organizations.yml file in translation tests
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SR_1_20230302-0001.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
  prime-router/src/testIntegration/resources/settings/organizations.yml
Labels: platform

#12281 Adjust sender transforms to prevent exceptions
  prime-router/metadata/fhir_transforms/senders/SimpleReport/simple-report-sender-transform.yml
  prime-router/metadata/fhir_transforms/senders/default-sender-transform.yml
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirTransformer.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SR_1_20230302-0001-missing-data.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SR_1_20230302-0001-missing-data.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: platform

#12282 Use OutputStream instead of File in csv write utility and related tests
  prime-router/src/main/kotlin/cli/FileUtilities.kt
  prime-router/src/main/kotlin/cli/LookupTableCommands.kt
  prime-router/src/test/kotlin/azure/BatchFunctionTests.kt
  prime-router/src/test/kotlin/cli/CommonUtilitiesTests.kt
Labels: platform

#12256 Bump com.squareup.okio:okio@3.0.0 to com.squareup.okio:okio@3.4.0 in /prime-router
  prime-router/build.gradle.kts
Labels: security, dependencies, java

#12267 Bump io.projectreactor.netty:reactor-netty-http@1.0.38 to io.projectreactor.netty:reactor-netty-http:1.0.39 in /prime-router
  prime-router/build.gradle.kts
Labels: security, dependencies, java

#12166 11665 XCN mappings
  prime-router/docs/design/design/HL7v2-FHIR-Inventory.md
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/XCN/Practitioner.yml
  prime-router/metadata/fhir_mapping/hl7/resource/ServiceRequest.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/observation-request.yml
  prime-router/metadata/hl7_mapping/resources/Practitioner/XCN.yml
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/xcn/XCNtoPractitionerTests.kt
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xcn/xcn-to-practitioner-dns-assigning-authority.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xcn/xcn-to-practitioner-dns-assigning-authority.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xcn/xcn-to-practitioner-iso-assigning-authority-no-namespace.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xcn/xcn-to-practitioner-iso-assigning-authority-no-namespace.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xcn/xcn-to-practitioner-uuid-assigning-authority-no-namespace.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xcn/xcn-to-practitioner-uuid-assigning-authority-no-namespace.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xcn/xcn-to-practitioner-uuid-assigning-authority.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xcn/xcn-to-practitioner-uuid-assigning-authority.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xcn/xcn-to-practitioner-xcn17-populated-xcn19-20-empty.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xcn/xcn-to-practitioner-xcn17-populated-xcn19-20-empty.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xcn/xcn-to-practitioner-xcn19-20-populated-xcn17-empty.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/xcn/xcn-to-practitioner-xcn19-20-populated-xcn17-empty.hl7
Labels: platform

#12248 Fixes usages of deprecated assertThat{} and bump assertk
  prime-router/build.gradle.kts
  prime-router/src/test/kotlin/ActionLogTests.kt
  prime-router/src/test/kotlin/ElementTests.kt
  prime-router/src/test/kotlin/FileSettingsTests.kt
  prime-router/src/test/kotlin/MetadataTests.kt
  prime-router/src/test/kotlin/ReportStreamFilterDefinitionTests.kt
  prime-router/src/test/kotlin/ReportTests.kt
  prime-router/src/test/kotlin/SubmissionReceiverTests.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/azure/BatchFunctionTests.kt
  prime-router/src/test/kotlin/azure/ReportWriterTests.kt
  prime-router/src/test/kotlin/azure/SenderFilesFunctionTests.kt
  prime-router/src/test/kotlin/common/CsvUtilitiesTests.kt
  prime-router/src/test/kotlin/common/Hl7UtilitiesTests.kt
  prime-router/src/test/kotlin/common/JacksonMapperUtilitiesTests.kt
  prime-router/src/test/kotlin/credentials/CredentialTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/CustomFhirPathFunctionTest.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/LookupTableValueSetTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/HL7toFhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirTransformerTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReaderTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/converter/ConverterSchemaTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/fhirTransform/FhirTransformSchemaTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/ConstantResolverTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctionsTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/FhirBundleUtilsTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/FhirPathUtilsTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/Hl7UtilsTests.kt
  prime-router/src/test/kotlin/history/SubmissionHistoryTests.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFacadeTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionsFacadeTests.kt
  prime-router/src/test/kotlin/metadata/MapperTests.kt
  prime-router/src/test/kotlin/tokens/AuthenticatedClaimsTests.kt
  prime-router/src/test/kotlin/tokens/Server2ServerAuthenticationTests.kt
  prime-router/src/testIntegration/kotlin/FileNameTemplateIntegrationTests.kt
Labels: platform

#11906 Oo/engagement/jgilmore/10151 code to condition tables
  prime-router/docs/design/proposals/0023-condition-to-code-mapping/0023-condition-to-code-mapping.md
  prime-router/docs/design/proposals/0023-condition-to-code-mapping/HL7-condition-information.png
  prime-router/docs/design/proposals/0023-condition-to-code-mapping/New-helper-function-location.png
  prime-router/docs/design/proposals/0023-condition-to-code-mapping/New-helper-function-logic.png
  prime-router/docs/design/proposals/0023-condition-to-code-mapping/code-to-condtion-overview.png
  prime-router/docs/design/proposals/0023-condition-to-code-mapping/exampleinput.fhir
  prime-router/docs/design/proposals/0023-condition-to-code-mapping/exampleoutput1.hl7
  prime-router/docs/design/proposals/0023-condition-to-code-mapping/fhir-condition-information.png
Labels: platform

#12326 Modified REST Transport to connect to new NBS server
  prime-router/settings/staging/0158-nbs-cdc-staging.yml
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
Labels: onboarding-ops

#12258 11660: add EIP datatype mappings
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/EIP/EI/ExtensionEI.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/EIP/Identifier-FillerAssignedIdentifier.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/EIP/Identifier-PlacerAssignedIdentifier.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Specimen.yml
  prime-router/metadata/fhir_transforms/senders/SimpleReport/simple-report-sender-transform.yml
  prime-router/metadata/hl7_mapping/common/specimen.yml
  prime-router/metadata/hl7_mapping/datatypes/extensionEI/EI.yml
  prime-router/metadata/hl7_mapping/datatypes/identifier-fillerAssignedIdentifier/EIP.yml
  prime-router/metadata/hl7_mapping/datatypes/identifier-placerAssignedIdentifier/EIP.yml
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/eip/EIPToIdentifierTests.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_2_20230220-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_RADx_MARS_20230406-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_RADx_MARS_20230406-0002.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_multiple_observations.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_multiple_observations_keepall.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_bundle_some_filtered_observations.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/eip/EIP-to-Identifier-Both.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/eip/EIP-to-Identifier-Both.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/eip/EIP-to-Identifier-FillerAssignedIdentifier.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/eip/EIP-to-Identifier-FillerAssignedIdentifier.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/eip/EIP-to-Identifier-PlacerAssignedIdentifier.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/eip/EIP-to-Identifier-PlacerAssignedIdentifier.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/nte/annotation_author_string_resource_test_file.fhir
Labels: platform

#12173 CX Identifier mapping created and tested
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/CX/Identifier.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/EI/Identifier.yml
  prime-router/metadata/fhir_mapping/hl7/resource/ServiceRequest.yml
  prime-router/metadata/hl7_mapping/common/observation-request.yml
  prime-router/metadata/hl7_mapping/datatypes/URI/HD.yml
  prime-router/metadata/hl7_mapping/datatypes/identifier/CX.yml
  prime-router/metadata/hl7_mapping/resources/MessageHeader/Destination/HD.yml
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/cx/CxToIdentifierTests.kt
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cx/cx-5.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cx/cx-5.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cx/cx-identifier-organization-null-org-type.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cx/cx-identifier-organization-null-org-type.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cx/cx-identifier-organization.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cx/cx-identifier-organization.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cx/cx-identifier-system-iso-no-cx-4-1.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cx/cx-identifier-system-iso-no-cx-4-1.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cx/cx-identifier-system-iso-no-cx-4-2.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cx/cx-identifier-system-iso-no-cx-4-2.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cx/cx-identifier-system-iso.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cx/cx-identifier-system-iso.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cx/cx-identifier-system-uuid-no-cx-4-1.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cx/cx-identifier-system-uuid-no-cx-4-1.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cx/cx-identifier-system-uuid-no-cx-4-2.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cx/cx-identifier-system-uuid-no-cx-4-2.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cx/cx-identifier-system-uuid.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cx/cx-identifier-system-uuid.hl7
Labels: pipeline, platform

#12353 12352 - removed activeMembership.service check since not all receiver have a service defined i.e."default"
  frontend-react/src/hooks/network/DataDashboard/UseReceiverDeliveries.ts
  frontend-react/yarn.lock
Labels: frontend, experience

#12342 Engagement/jgilmore/9083 ar onboarding
  .environment/soap_service/soap/operation/v2/I3hfFO.opr
  .environment/soap_service/soap/port/v2/qBIz6q.port
  .environment/soap_service/soap/resource/v2/InzRhE.rsc
  .environment/soap_service/soap/resource/v2/wsdl/InzRhE.rsc
  .environment/soap_service/tmpFiles/Upload-2023-11-08-11-27-36
  prime-router/settings/prod/0159-AR-onboarding.yml
  prime-router/settings/staging/0159-AR-onboarding.yml
  prime-router/src/main/kotlin/TransportType.kt
  prime-router/src/main/kotlin/credentials/Credential.kt
  prime-router/src/main/kotlin/serializers/SoapSerializer.kt
  prime-router/src/main/kotlin/serializers/soapimpl/Soap12Message.kt
  prime-router/src/main/kotlin/transport/SoapTransport.kt
  prime-router/src/test/kotlin/serializers/SoapSerializerTests.kt
Labels: onboarding-ops, Arkansas

#12325 12238: capture schema/element when an error is thrown during a transform
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirTransformer.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/converter/ConverterSchema.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirTransformerTests.kt
Labels: platform

#12418 12361 - removed activeMembership.service check where applicable since not all receivers have a service defined i.e."default"
  frontend-react/src/hooks/UseOrganizationSenders.ts
  frontend-react/src/hooks/network/DataDashboard/UseReceiverSubmitters.ts
  frontend-react/src/hooks/network/DataDashboard/useReceiverSubmitters.test.ts
  frontend-react/src/hooks/network/Organizations/PublicKeys/UseOrganizationPublicKeys.ts
Labels: frontend, experience

#12350 CQ and NM Mapping Inventory
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/CQ/Quantity.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/NM/Quantity-LengthOfStay.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Encounter.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/Collection.yml
  prime-router/metadata/hl7_mapping/common/patient-visit.yml
  prime-router/metadata/hl7_mapping/common/specimen.yml
  prime-router/metadata/hl7_mapping/datatypes/Quantity/CQ.yml
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/cq/CQTests.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/nm/NMTests.kt
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cq/quantity/cq_29_null.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cq/quantity/cq_29_null.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cq/quantity/cq_all_fields.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cq/quantity/cq_all_fields.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/nm/nm-to-quantity.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/nm/nm-to-quantity.hl7
Labels: platform

#12401 11051: route a message per receiver
  prime-router/build.gradle.kts
  prime-router/docs/universal-pipeline/route.md
  prime-router/docs/universal-pipeline/translate.md
  prime-router/src/main/kotlin/cli/tests/BasicTests.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/fhirengine/azure/FHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIREngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/engine/Message.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirRouterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/BundleUpdateTests.kt
  prime-router/src/test/kotlin/fhirengine/utils/FHIRBundleHelpersTests.kt
Labels: platform
