Repository CDCgov/prime-reportstream, pull requests merged in 2023-08, with the labels that each got.

#10657 10359 - Add App Insights Tracking for Public Key Tool
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKey.tsx
  frontend-react/src/hooks/network/Organizations/PublicKeys/UseCreateOrganizationPublicKey.ts
Labels: frontend, experience

#10625 Bump bouncycastle from 15@1.70 to 18@1.75 in /prime-router
  prime-router/build.gradle.kts
Labels: security, dependencies, java

#10716 Experience: vite preview
  frontend-react/.env.preview
  frontend-react/package.json
  frontend-react/vite.config.ts
Labels: experience

#10718 Missing autoprefixer
  frontend-react/package.json
  frontend-react/postcss.config.cjs
  frontend-react/yarn.lock
Labels: experience

#10698 desktop only position sticky
  frontend-react/src/components/Content/MarkdownLayout.module.scss
  frontend-react/src/components/Content/MarkdownLayout.tsx
  frontend-react/src/global-modules.scss
Labels: experience

#10603 Update release-notes.md June 2023
  frontend-react/src/content/product/release-notes.md
Labels: experience

#10723 Update USWDS to 3.4.1
  frontend-react/package.json
  frontend-react/patches/@trussworks+react-uswds+5.1.1.patch
  frontend-react/src/global.scss
  frontend-react/src/shared/Alert/Alert.module.scss
  frontend-react/src/styles/_uswds_settings.scss
  frontend-react/yarn.lock
Labels: experience

#10725 Add frontmatter and table-of-contents to MDX
  frontend-react/package.json
  frontend-react/src/components/Content/MarkdownRenderer.tsx
  frontend-react/vite.config.ts
  frontend-react/yarn.lock
Labels: experience

#10684 10212: document send step
  prime-router/docs/universal-pipeline/send.md
Labels: platform

#10730 Fix useOrganizationReceiversFeed test faultiness
  frontend-react/src/hooks/UseOrganizationReceiversFeed.test.ts
Labels: experience

#10582 [9302] Host RS API Docs Swagger UI from Azure Storage Server
  prime-router/build.gradle.kts
  prime-router/docker-compose.yml
  prime-router/docs/api/README.md
  prime-router/docs/api/swagger-ui/favicon-16x16.png
  prime-router/docs/api/swagger-ui/favicon-32x32.png
  prime-router/docs/api/swagger-ui/index.css
  prime-router/docs/api/swagger-ui/index.html
  prime-router/docs/api/swagger-ui/oauth2-redirect.html
  prime-router/docs/api/swagger-ui/swagger-initializer.js
  prime-router/docs/api/swagger-ui/swagger-ui-bundle.js
  prime-router/docs/api/swagger-ui/swagger-ui-bundle.js.map
  prime-router/docs/api/swagger-ui/swagger-ui-es-bundle-core.js
  prime-router/docs/api/swagger-ui/swagger-ui-es-bundle-core.js.map
  prime-router/docs/api/swagger-ui/swagger-ui-es-bundle.js
  prime-router/docs/api/swagger-ui/swagger-ui-es-bundle.js.map
  prime-router/docs/api/swagger-ui/swagger-ui-standalone-preset.js
  prime-router/docs/api/swagger-ui/swagger-ui-standalone-preset.js.map
  prime-router/docs/api/swagger-ui/swagger-ui.css
  prime-router/docs/api/swagger-ui/swagger-ui.css.map
  prime-router/docs/api/swagger-ui/swagger-ui.js
  prime-router/docs/api/swagger-ui/swagger-ui.js.map
  prime-router/local.settings.json
  prime-router/src/main/kotlin/azure/ApiKeysFunctions.kt
  prime-router/start_func.sh
  prime-router/upload_swaggerui.sh
Labels: platform

#10478 Settings API - Use all authentication options
  prime-router/docs/api/settings.yml
  prime-router/src/main/kotlin/azure/SettingsFunctions.kt
  prime-router/src/main/kotlin/cli/tests/AuthTests.kt
  prime-router/src/main/kotlin/cli/tests/HistoryApiTest.kt
  prime-router/src/main/kotlin/cli/tests/SettingsTest.kt
  prime-router/src/main/kotlin/cli/tests/SftpcheckTest.kt
  prime-router/src/main/kotlin/history/azure/ReportFileFunction.kt
  prime-router/src/main/kotlin/tokens/AuthenticatedClaims.kt
Labels: platform

#10655 Fix MSH-2, MSH-3 for ELIMS message 52
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/resource/MessageHeader.yml
  prime-router/metadata/fhir_transforms/senders/CDC-ELIMS/elims-sender-transform.yml
  prime-router/metadata/hl7_mapping/OML_O21/base/service-request-order.yml
  prime-router/metadata/hl7_mapping/common/message-header.yml
  prime-router/src/main/kotlin/SubmissionReceiver.kt
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/HL7Utils.kt
  prime-router/src/test/kotlin/SubmissionReceiverTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/test/resources/fhirengine/engine/valid_data_five_encoding_chars.fhir
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001-xxx.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0006.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_40_4988249_33033-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_40_4988249_33033-with-truncation-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_40_4988249_33033-with-truncation.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_40_4988249_33033.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_52_24095_04204575_5120-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_52_24095_04204575_5120.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0001-expected-CO.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0001-expected-base.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0004-expected-base.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0014.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0019-expected-CO.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/sample_co_1_20220518-0019-expected-base.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/test_playground_20220930-0001-expected-CO.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: platform

#10727 Updated so that bad phone numbers no longer stop the message from bei…
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/PhoneUtilities.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/PhoneUtilitiesTests.kt
Labels: pipeline, platform

#10786 Use new grouping feature of dependabot
  .github/dependabot.yml
Labels: experience

#10799 Allow normal users to read settings
  prime-router/src/main/kotlin/azure/ApiKeysFunctions.kt
  prime-router/src/main/kotlin/azure/SettingsFacade.kt
  prime-router/src/main/kotlin/azure/SettingsFunctions.kt
  prime-router/src/main/kotlin/cli/tests/AuthTests.kt
  prime-router/src/main/kotlin/cli/tests/SettingsTest.kt
  prime-router/src/test/kotlin/azure/ApiKeysFunctionsTest.kt
Labels: platform

#10728 Experience/10726-Update-MarkdownLayout-for-new-features
  frontend-react/jest.config.ts
  frontend-react/package.json
  frontend-react/src/AppRouter.tsx
  frontend-react/src/__mocks__/mdxFrontmatterMock.tsx
  frontend-react/src/__mocks__/mdxModulesMock.ts
  frontend-react/src/__mocks__/reactHelmetAsyncMock.tsx
  frontend-react/src/components/Content/MarkdownLayout.test.tsx
  frontend-react/src/components/Content/MarkdownLayout.tsx
  frontend-react/src/content/resources/ResourcesIndex.mdx
  frontend-react/src/content/resources/index.ts
  frontend-react/src/content/resources/reportstream-api/ReportStreamApi.mdx
  frontend-react/src/content/resources/reportstream-api/Sidenav.mdx
  frontend-react/src/content/resources/reportstream-api/documentation/Documentation.mdx
  frontend-react/src/content/resources/reportstream-api/documentation/ResponsesFromReportStream.mdx
  frontend-react/src/content/resources/reportstream-api/documentation/SamplePayloadsAndOutput.mdx
  frontend-react/src/content/resources/reportstream-api/documentation/data-model/DataModel.mdx
  frontend-react/src/content/resources/reportstream-api/getting-started/GettingStarted.mdx
  frontend-react/src/content/resources/reportstream-api/getting-started/Method1.mdx
  frontend-react/src/content/support/index.ts
  frontend-react/src/global.scss
  frontend-react/src/layouts/Main/MainLayout.test.tsx
  frontend-react/src/layouts/Main/MainLayout.tsx
  frontend-react/src/layouts/Markdown/CallToAction.test.tsx
  frontend-react/src/layouts/Markdown/CallToAction.tsx
  frontend-react/src/layouts/Markdown/Context.ts
  frontend-react/src/layouts/Markdown/LayoutComponents.test.tsx
  frontend-react/src/layouts/Markdown/LayoutComponents.tsx
  frontend-react/src/layouts/Markdown/MarkdownLayout.module.scss
  frontend-react/src/layouts/Markdown/MarkdownLayout.test.tsx
  frontend-react/src/layouts/Markdown/MarkdownLayout.tsx
  frontend-react/src/layouts/Markdown/TableOfContents.test.tsx
  frontend-react/src/layouts/Markdown/TableOfContents.tsx
  frontend-react/src/pages/resources/ResourcesPage.stories.tsx
  frontend-react/src/pages/resources/ResourcesPage.tsx
  frontend-react/src/pages/resources/reportstream-api/GettingStarted.stories.tsx
  frontend-react/src/pages/resources/reportstream-api/GettingStarted.tsx
  frontend-react/src/pages/resources/reportstream-api/ReportStreamApi.stories.tsx
  frontend-react/src/pages/resources/reportstream-api/ReportStreamApi.tsx
  frontend-react/src/pages/resources/reportstream-api/documentation/DataModel.stories.tsx
  frontend-react/src/pages/resources/reportstream-api/documentation/DataModel.tsx
  frontend-react/src/pages/resources/reportstream-api/documentation/Documentation.stories.tsx
  frontend-react/src/pages/resources/reportstream-api/documentation/Documentation.tsx
  frontend-react/src/pages/resources/reportstream-api/documentation/ResponsesFromReportStream.stories.tsx
  frontend-react/src/pages/resources/reportstream-api/documentation/ResponsesFromReportStream.tsx
  frontend-react/src/pages/resources/reportstream-api/documentation/SamplePayloadsAndOutput.stories.tsx
  frontend-react/src/pages/resources/reportstream-api/documentation/SamplePayloadsAndOutput.tsx
  frontend-react/src/pages/support/faq/FaqPage.stories.tsx
  frontend-react/src/pages/support/faq/FaqPage.tsx
  frontend-react/src/shared/SideNavItem/SideNavItem.test.tsx
  frontend-react/src/shared/SideNavItem/SideNavItem.tsx
  frontend-react/src/shared/index.ts
  frontend-react/src/utils/LazyRouteMarkdown.test.tsx
  frontend-react/src/utils/LazyRouteMarkdown.tsx
  frontend-react/src/utils/MDXImports.ts
  frontend-react/src/vite-env.d.ts
  frontend-react/vite.config.ts
  frontend-react/yarn.lock
Labels: experience

#10834 Add Snyk workflow
  .github/workflows/snyk.yml
Labels: DevOps, github_actions

#10847 BUG: FAQ page unavailable
  frontend-react/src/AppRouter.tsx
  frontend-react/src/content/support/index.ts
  frontend-react/src/layouts/Markdown/MarkdownLayout.tsx
  frontend-react/src/pages/support/faq/FaqPage.tsx
  frontend-react/src/vite-env.d.ts
Labels: experience

#10694 Jessica/10370 orm mapping
  prime-router/metadata/fhir_mapping/config.properties
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Identifier_Gen.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Quantity.yml
  prime-router/metadata/fhir_mapping/hl7/message/ORM_O01.yml
  prime-router/metadata/fhir_mapping/hl7/resource/MessageHeader.yml
  prime-router/metadata/fhir_mapping/hl7/resource/MessageSender.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Observation.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Patient.yml
  prime-router/metadata/fhir_mapping/hl7/resource/ServiceRequest.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Specimen.yml
  prime-router/src/main/kotlin/SubmissionReceiver.kt
  prime-router/src/main/kotlin/fhirengine/translation/HL7toFhirTranslator.kt
  prime-router/src/main/kotlin/fhirengine/utils/HL7Reader.kt
  prime-router/src/test/kotlin/fhirengine/translation/HL7toFhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/utils/HL7ReaderTests.kt
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_orm_20230809-001.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_orm_20230809-001.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: pipeline, platform

#10775 10740: elims mega message
  prime-router/build.gradle.kts
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Specimen.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/Collection.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/Container.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/specimen.yml
  prime-router/src/main/kotlin/cli/tests/AuthTests.kt
  prime-router/src/main/kotlin/fhirengine/azure/FHIRFunctions.kt
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/47_04608646_11024_mega_specimen-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/47_04608646_11024_mega_specimen.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/47_32361_04608646_11034_mega_case-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/47_32361_04608646_11034_mega_case.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: platform

#10856 Preserve MSH-18 in HL7v2->FHIR->HL7v2
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/resource/MessageHeader.yml
  prime-router/metadata/hl7_mapping/common/message-header.yml
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_52_24095_04204575_5120-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_52_24095_04204575_5120.hl7
Labels: platform

#10880 Bump nodejs from 18.15 to 18.17
  .environment/yarn/run-yarnCheck.sh
  frontend-react/.nvmrc
  frontend-react/package.json
Labels: security, dependencies, javascript

#10864 Bump flyway and flyway-core to 9.21.1
  prime-router/build.gradle.kts
  prime-router/gradle.properties
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
Labels: platform

#10875 Upgrade com.avast.gradle.docker-compose to 0.17.4
  prime-router/build.gradle.kts
Labels: platform

#10840 10838: elims message part 4
  prime-router/metadata/fhir_mapping/hl7/message/ORU_R01.yml
  prime-router/metadata/fhir_mapping/hl7/resource/DiagnosticReport.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Observation.yml
  prime-router/metadata/fhir_mapping/hl7/resource/ServiceRequest.yml
  prime-router/metadata/hl7_mapping/ORU_R01/RADx_MARS/RADx_MARS-base.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/observation-result.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/order-observation.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/specimen.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/CA-receiver-transform.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/CA.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CO/CO.yml
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/converter/ConverterSchema.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReaderTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/converter/ConverterSchemaTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/fhirTransform/FhirTransformSchemaTests.kt
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_47_04608646_11024_mega_specimen-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_47_04608646_11024_mega_specimen.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_47_04608717_11184_mega_specimen-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_47_04608717_11184_mega_specimen.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_47_32361_04608646_11034_mega_case-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_47_32361_04608646_11034_mega_case.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: platform

#10863 Platform/arnej/10629 document data model
  prime-router/docs/assets/azure-reports-folders.png
  prime-router/docs/assets/lookup-table-row.png
  prime-router/docs/assets/lookup-table-version.png
  prime-router/docs/design/design/data-model.md
  prime-router/docs/design/design/topic.md
  prime-router/docs/design/metadata.md
  prime-router/docs/getting-started/standard-operating-procedures/livd-table-list.png
  prime-router/docs/getting-started/standard-operating-procedures/update-livd-table.md
  prime-router/docs/universal-pipeline/README.md
  prime-router/docs/universal-pipeline/convert-translate.md
Labels: platform

#10732 10774 Refactor and increase coverage for BlobAccess
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/main/kotlin/common/Environment.kt
  prime-router/src/test/kotlin/azure/BlobAccessTests.kt
Labels: platform

#10853 8876 add Hl7 truncation design document
  prime-router/docs/design/features/0006-hl7-field-truncation.md
Labels: onboarding-ops

#10939 Changed class to className in mdx files to prevent exception
  frontend-react/src/content/resources/ResourcesIndex.mdx
  frontend-react/src/content/support/faq/FaqIndex.mdx
Labels: bug, frontend, experience

#10813 Created the first pass of the fhir function documention
  prime-router/docs/getting-started/fhir-functions.md
  prime-router/src/main/kotlin/azure/BatchFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
Labels: pipeline, platform

#10969 Add orders endpoint for CDC-TI
  prime-router/settings/staging/0149-etor.yml
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
Labels: platform

#10928 10638: refactor fhir functions
  prime-router/metadata/hl7_mapping/ORU_R01/base/specimen.yml
  prime-router/src/main/kotlin/fhirengine/azure/FHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIREngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/DefaultFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/GetFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
  prime-router/src/test/resources/fhirengine/engine/valid_data_multiple_targets.fhir
Labels: platform

#10927 platform/jimfuqian/9345 Refactor duplicate code in ActionHistory
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/SubmissionReceiver.kt
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/test/kotlin/ReportTests.kt
  prime-router/src/test/kotlin/SubmissionReceiverTests.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/RoutingTests.kt
Labels: platform

#10992 Update project to Java 17
  .github/actions/build-frontend/action.yml
  .github/workflows/build_hub.yml
  .github/workflows/sonarcloud_master.yml
  prime-router/Dockerfile
  prime-router/Dockerfile.build
  prime-router/Dockerfile.dev
  prime-router/build.gradle.kts
  prime-router/docs/docs-deprecated/getting-started/Using-an-apple-silicon-mac.md
  prime-router/docs/docs-deprecated/getting-started/install-openjdk.md
Labels: platform

#10996 Adjust layout for convert/translate documentation
  prime-router/docs/design/design/data-model.md
  prime-router/docs/getting-started/standard-operating-procedures/changing-transforms.md
  prime-router/docs/universal-pipeline/README.md
  prime-router/docs/universal-pipeline/convert-translate.md
  prime-router/docs/universal-pipeline/convert.md
  prime-router/docs/universal-pipeline/translate.md
Labels: platform

#11005 Oo/oslynn/10995/add support for nbs to rest transport
  prime-router/settings/staging/0154-nbs-cdc-staging.yml
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
Labels: onboarding-ops

#10689 8912: handling duplicate items design
  prime-router/docs/design/features/0006-handling-sending-duplicate-items.md
Labels: platform

#11004 enable flywayClean for resetDB gradle task
  prime-router/build.gradle.kts
Labels: platform

#10970 Update route documentation
  prime-router/docs/getting-started/fhir-functions.md
  prime-router/docs/universal-pipeline/batch.md
  prime-router/docs/universal-pipeline/convert.md
  prime-router/docs/universal-pipeline/receive.md
  prime-router/docs/universal-pipeline/route.md
  prime-router/docs/universal-pipeline/send.md
  prime-router/docs/universal-pipeline/translate.md
Labels: platform

#11018 10918: document and tests coverage for duplicate elements
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReader.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/converter/ConverterSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/fhirTransform/FhirTransformSchema.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirTransformerTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/converter/ConverterSchemaTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/fhirTransform/FhirTransformSchemaTests.kt
Labels: platform

#11053 Fix filter for ignore.etor-ti receiver
  prime-router/settings/organizations.yml
Labels: platform

#11055 [SPIKE] Org/Status not being cleared after logging out of site
  frontend-react/src/utils/UserUtils.ts
Labels: experience

#10971 Jessica/10216 receive step documentation
  prime-router/docs/universal-pipeline/receive.md
  prime-router/src/main/kotlin/tokens/AuthenticatedClaims.kt
Labels: pipeline, platform

#11024 Tweak how API database calls are made in parallel
  prime-router/src/main/kotlin/azure/ApiSearch.kt
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/db/ReportFileDatabaseAccess.kt
  prime-router/src/main/kotlin/history/db/DeliveryDatabaseAccess.kt
  prime-router/src/main/kotlin/history/db/ReportGraph.kt
  prime-router/src/main/kotlin/history/db/SubmitterDatabaseAccess.kt
Labels: platform

#11022 Experience/10911/manage connection
  frontend-react/.storybook/UtilizedUSWDSComponents/Card.stories.tsx
  frontend-react/public/assets/img/DailyData.png
  frontend-react/public/assets/img/SubmissionHistory.png
  frontend-react/src/AppRouter.tsx
  frontend-react/src/content/manage-connection/manage-connection-index.mdx
  frontend-react/src/layouts/Markdown/MarkdownLayout.tsx
  frontend-react/src/shared/Card/Card.module.scss
  frontend-react/src/shared/Card/Card.stories.tsx
  frontend-react/src/shared/Card/Card.tsx
  frontend-react/src/shared/PageHeader/PageHeader.tsx
  frontend-react/src/shared/Tile/Tile.tsx
  frontend-react/src/shared/index.ts
Labels: frontend, experience, trialfrontend02

#10842 10706 Enable Authorization Methods on RS API Docs Swagger UI
  prime-router/src/main/kotlin/azure/ApiKeysFunctions.kt
Labels: platform

#10777 Enable DateTime Conversion Translation Setting in the UPn
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/common/DateUtilities.kt
  prime-router/src/main/kotlin/fhirengine/engine/CustomTranslationFunctions.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/TranslationFunctions.kt
  prime-router/src/test/kotlin/fhirengine/engine/CustomTranslationFunctionsTest.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctionsTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/FhirPathUtilsTests.kt
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
Labels: onboarding-ops, platform

#11033 10649 - Publish Release Notes - July 2023 - Publication
  frontend-react/src/content/product/release-notes.md
Labels: frontend, experience

#10933 Automate Okta login when the credentials are available
  prime-router/docs/getting-started/standard-operating-procedures/releases.md
  prime-router/src/main/kotlin/cli/OktaCommands.kt
Labels: platform

#11090 Bump jacoco from 0.8.9 to 0.8.10
  prime-router/build.gradle.kts
Labels: dependencies, java, platform

#11093 11050: handle cancelled OBX segments
  prime-router/metadata/fhir_mapping/hl7/datatype/CodeableConcept.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Entity_Identifier_Pair_2.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Observation.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Patient.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Specimen.yml
  prime-router/metadata/fhir_mapping/hl7/secondary/PatientContact.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/observation-result.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_1_20230220-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AOE_2_20230220-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_RADx_MARS_20230406-0002.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001-xxx.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0006-xxx.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0006.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0014-xxx.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0014.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_1_72_3029202646_5532_NoPII-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_1_72_3029202646_5532_NoPII.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_29_5065302_35227_NoPII_CANCELED-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_29_5065302_35227_NoPII_CANCELED.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_2_40_05059364_34872_MIN-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_2_40_05059364_34872_MIN.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_2_52_5068110_35230_NoPII-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_2_52_5068110_35230_NoPII.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_2_72_3029198209_5121_NoPII-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_2_72_3029198209_5121_NoPII.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: platform

#11140 Track how long the queries take to execute for the STLT dashboards
  prime-router/src/main/kotlin/azure/ApiSearch.kt
  prime-router/src/main/kotlin/cli/OktaCommands.kt
  prime-router/src/main/kotlin/history/db/DeliveryDatabaseAccess.kt
Labels: platform

#11143 Revert "Automate Okta login when the credentials are available (#10933)"
  prime-router/docs/getting-started/standard-operating-procedures/releases.md
  prime-router/src/main/kotlin/cli/OktaCommands.kt
Labels: platform

#11150 Adding Sender Staging Setting to NBS for them to send test message
  prime-router/settings/staging/0154-nbs-cdc-staging.yml
Labels: onboarding-ops

#10923 Oo/cloudmagic/10191/prime cli can convert fhir to fhir
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_FHIR/sample_AOE_1_20230220-0001-expected.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_FHIR/sample_AOE_1_20230220-0001.fhir
Labels: onboarding-ops, platform

#11153 Inline report id filter for delivery APIs
  prime-router/src/main/kotlin/history/db/DeliveryDatabaseAccess.kt
  prime-router/src/main/kotlin/history/db/ReportGraph.kt
  prime-router/src/main/kotlin/history/db/SubmitterDatabaseAccess.kt
Labels: platform
