Repository CDCgov/prime-reportstream, pull requests merged in 2024-10, with the labels that each got.

#16053 16052: enable FHIR transforms to change bundle with custom FHIR functions
  prime-router/build.gradle.kts
  prime-router/docs/universal-pipeline/translate.md
  prime-router/metadata/json_schema/fhir/fhir-to-fhir-transform.json
  prime-router/src/main/kotlin/config/validation/Validations.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirTransformer.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/fhirTransform/FhirTransformSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctions.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirTransformerTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctionsTests.kt
Labels: platform

#16079 Resolve open backend dependabots
  auth/build.gradle.kts
  prime-router/build.gradle.kts
Labels: platform

#16002 Address intermediate "Not Delivering" before routing a received report
  prime-router/src/main/kotlin/history/SubmissionHistory.kt
  prime-router/src/test/kotlin/common/ReportNodeBuilder.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverFilterIntegrationTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionFunctionIntegrationTests.kt
Labels: platform

#16138 roadmap content update
  frontend-react/src/content/about/roadmap.mdx
Labels: experience, trialfrontend03

#16137 15223: generate empty in convert
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRDestinationFilterIntegrationTests.kt
Labels: platform

#16055 Add test cases for partially delivered submissions
  prime-router/src/test/kotlin/common/ReportNodeBuilder.kt
  prime-router/src/test/kotlin/history/azure/SubmissionFunctionIntegrationTests.kt
Labels: platform

#16188 14609: findDetailedDeliveryHistory handles actions that produce multiple reports
  prime-router/src/main/kotlin/history/DeliveryHistory.kt
  prime-router/src/main/kotlin/history/azure/DeliveryFacade.kt
  prime-router/src/main/kotlin/history/azure/DeliveryFunction.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFacadeTests.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFunctionTests.kt
Labels: platform

#16203 Send Failure Log Enhancement
  prime-router/src/main/kotlin/azure/SendFunction.kt
Labels: platform

#16200 Check submission table when computing submission history
  prime-router/src/main/kotlin/history/azure/ReportFileFunction.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFunctionTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionFunctionIntegrationTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionFunctionTests.kt
  shared/src/main/kotlin/gov/cdc/prime/reportstream/shared/Submission.kt
Labels: platform

#16249 Suppress QST schema and translation test fixes
  prime-router/settings/STLTs/MO/mo-phd.yml
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/Common/observation-fields/observation-fields.yml
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/STLTs/MD/MD-receiver-transform.yml
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/STLTs/MO/MO-receiver-transform.yml
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/STLTs/OH/OH-observation-fields.yml
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/STLTs/OH/OH-receiver-transform.yml
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/STLTs/WA/WA-observation-fields.yml
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/STLTs/WA/WA-receiver-transform.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_MO_20240628-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_MO_20240628-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_OH_20240718-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_OH_20240718-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_WA_20240719-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_WA_20240719-0001.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
  prime-router/src/testIntegration/resources/settings/organizations.yml
Labels: onboarding-ops

#16197 Update service request form link across ReportStream website#16135
  frontend-react/src/config/index.ts
  frontend-react/src/content/developer-resources/reportstream-api/ReportStreamApi.mdx
  frontend-react/src/content/managing-your-connection/index.mdx
  frontend-react/src/content/site.json
  frontend-react/src/content/support/index.mdx
Labels: experience, trialfrontend01

#14646 add remove sa runner ip
  .github/actions/build-backend/action.yml
Labels: DevOps, reportstream

#16237 16084: add support for submitting reports via blob trigger
  prime-router/build.gradle.kts
  prime-router/docs/onboarding-users/sender-onboarding/SFTP-add-user.png
  prime-router/docs/onboarding-users/sender-onboarding/SFTP-directories.png
  prime-router/docs/onboarding-users/sender-onboarding/SFTP-settings.png
  prime-router/docs/onboarding-users/sender-onboarding/SFTP-user-permissions.png
  prime-router/docs/onboarding-users/sender-onboarding/sftp-ingestion.md
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventData.kt
  prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
Labels: platform

#16023 Importing JoshiaSiegel GitHub Actions
  .github/actions/action-connect-ovpn/.gitignore
  .github/actions/action-connect-ovpn/README.md
  .github/actions/action-connect-ovpn/action.yml
  .github/actions/action-connect-ovpn/example.ovpn
  .github/actions/deploy-backend/action.yml
  .github/actions/vpn-azure/action.yml
  .github/dependabot.yml
  .github/vpn/config.ovpn
  .github/workflows/alert_terraform_changes.yml
  .github/workflows/deploy_terraform.yml
  .github/workflows/log_management.yml
  .github/workflows/prepare_deployment_branch.yaml
  .github/workflows/release_to_azure.yml
  .github/workflows/scan_action_logs.yml
Labels: DevSecOps

#16258 16140: manually populate poison queue when a step encounters an error
  prime-router/src/main/kotlin/azure/QueueAccess.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventData.kt
  prime-router/src/main/kotlin/fhirengine/azure/FHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRDestinationFilter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIREngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiver.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiverFilter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/test/kotlin/SubmissionReceiverTests.kt
  prime-router/src/test/kotlin/azure/FHIRFunctionsTests.kt
  prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRDestinationFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRTranslatorIntegrationTests.kt
Labels: platform

#16292 15864 Spring Cloud Gate configuration with Swagger
  auth/build.gradle.kts
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/AuthApplication.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/AuthApplicationConstants.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/config/ApplicationConfig.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/config/RouteConfig.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/config/SecurityConfig.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/config/SubmissionsConfig.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/controller/AuthController.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/model/Environment.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/service/ProxyURIStrategy.kt
  auth/src/main/resources/application.yml
  auth/src/test/kotlin/gov/cdc/prime/reportstream/auth/controller/AuthControllerTest.kt
  auth/src/test/kotlin/gov/cdc/prime/reportstream/auth/controller/HealthControllerTest.kt
  auth/src/test/resources/application.yml
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/config/SecurityConfig.kt
  submissions/src/test/kotlin/SubmissionControllerIntegrationTest.kt
  submissions/src/test/kotlin/SubmissionControllerTest.kt
Labels: platform

#16335 Modifying the Allowed Users settings to use env.ALLOWED_USERS
  .github/workflows/deployment_rollback.yml
Labels: tech-debt, reportstream, DevSecOps

#16337 update submission history test
  frontend-react/e2e/spec/chromium-only/authenticated/daily-data-page-user-flow.spec.ts
  frontend-react/e2e/spec/chromium-only/authenticated/submission-history-page-user-flow.spec.ts
Labels: experience

#16308 Platform/angela/16191/always execute send
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/TransportType.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/transport/NullTransport.kt
  prime-router/src/test/kotlin/ReceiverTests.kt
  prime-router/src/test/kotlin/azure/SendFunctionTests.kt
Labels: platform

#16395 update product roadmap
  frontend-react/src/content/about/roadmap.mdx
Labels: experience, trialfrontend03

#16369 Create Platform _Epic_Template.md
  .github/ISSUE_TEMPLATE/Platform _Epic_Template.md
Labels: Epic, platform
