Repository CDCgov/prime-reportstream, pull requests merged in 2024-01, with the labels that each got.

#12807 Bump Debian 11.8 to 12.4
  prime-router/Dockerfile.build
Labels: security

#12526 12224 Original Message Passthrough design proposal
  prime-router/docs/design/proposals/0024-original-message-passthrough.md
Labels: platform

#12781 12440- Added RequireGate to message-details route
  frontend-react/src/AppRouter.tsx
Labels: frontend, experience

#12764 11341 - Removed migration alert from login
  frontend-react/src/pages/Login.tsx
Labels: frontend, experience

#12846 Add Winsconsin to Where We'r live map and change status to Active
  frontend-react/src/content/live.json
  frontend-react/src/content/usa_w_territories.svg
  yarn.lock
Labels: onboarding-ops, Wisconsin

#12761 8588 - Show filtered values in Daily Data date filter and other misc updates
  frontend-react/src/components/DataDashboard/ReceiverServices/ReceiverServices.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsSummary.tsx
  frontend-react/src/components/MessageTracker/MessageReceivers.tsx
  frontend-react/src/components/Table/TableFilters.tsx
  frontend-react/src/hooks/filters/UseDateRange.ts
  frontend-react/src/hooks/network/History/DeliveryHooks.ts
  frontend-react/src/pages/deliveries/Deliveries.tsx
  frontend-react/src/pages/deliveries/daily-data/DailyData.test.tsx
  frontend-react/src/pages/deliveries/daily-data/DailyData.tsx
  frontend-react/src/pages/deliveries/daily-data/ReportLink.tsx
  frontend-react/src/pages/deliveries/daily-data/ReportsUtils.test.ts
  frontend-react/src/pages/deliveries/daily-data/ReportsUtils.ts
  frontend-react/src/pages/deliveries/daily-data/ServicesDropdown.tsx
  frontend-react/src/pages/deliveries/daily-data/TableReportsData.tsx
  frontend-react/src/pages/deliveries/details/Summary.tsx
Labels: frontend, experience, trialfrontend01

#12853 12347 - Removed the Example Data Models from API Guide
  frontend-react/src/content/developer-resources/reportstream-api/documentation/SamplePayloadsAndOutput.mdx
Labels: frontend, experience

#12724 Removed the old code needed for queue message processing
  prime-router/src/main/kotlin/azure/Event.kt
  prime-router/src/test/kotlin/azure/EventTest.kt
  prime-router/src/test/kotlin/azure/batch/CovidBatchFunctionTests.kt
  prime-router/src/test/kotlin/azure/batch/UniversalBatchFunctionTests.kt
Labels: pipeline, platform

#12808 12495: add documentation on observability local dev setup
  prime-router/docs/observability/local-dev-setup.md
Labels: documentation, platform

#12799 12554-Move-creation-of-ObjectMapper-to-JacksonMapperUtilities
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/azure/DatabaseLookupTableAccess.kt
  prime-router/src/main/kotlin/azure/EmailSenderFunction.kt
  prime-router/src/main/kotlin/azure/Event.kt
  prime-router/src/main/kotlin/cli/CommandUtilities.kt
  prime-router/src/main/kotlin/cli/tests/AuthTests.kt
  prime-router/src/main/kotlin/cli/tests/BasicTests.kt
  prime-router/src/main/kotlin/cli/tests/HistoryApiTest.kt
  prime-router/src/main/kotlin/cli/tests/Hl7Tests.kt
  prime-router/src/main/kotlin/cli/tests/LivdApiTest.kt
  prime-router/src/main/kotlin/cli/tests/LoadTests.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/common/JacksonMapperUtilities.kt
  prime-router/src/main/kotlin/fhirengine/utils/CompareFhirData.kt
  prime-router/src/main/kotlin/tokens/AuthUtils.kt
  prime-router/src/main/kotlin/tokens/Jwk.kt
  prime-router/src/test/kotlin/azure/TokenFunctionTests.kt
  prime-router/src/test/kotlin/tokens/JwkTests.kt
  prime-router/src/test/kotlin/tokens/Server2ServerAuthenticationTests.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
Labels: platform

#12758 Adds enrichments
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/TranslatorConfiguration.kt
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/cli/SettingCommands.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/test/resources/enrichments/testing.yml
  prime-router/src/test/resources/enrichments/testing2.yml
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_orm_20230809-001-with-enrichment.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_40_4988249_33033_with_double_enrichment.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/elims_40_4988249_33033_with_enrichment.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
  prime-router/src/testIntegration/resources/settings/organizations.yml
Labels: pipeline, platform

#12753 Implement Payload File name with date for LA-PHL
  prime-router/settings/staging/0162-la-phl-staging-new-rest-setting.yml
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
Labels: onboarding-ops, etor

#12817 Added documentation for retrieving unmapped bundles
  prime-router/docs/getting-started/standard-operating-procedures/observation-mapping-table.md
Labels: platform

#12562 12462: remove deprecated batch queue
  prime-router/src/main/kotlin/azure/batch/DeprecatedBatchFunction.kt
Labels: platform

#12854 Platform/jessica/10490 copy blobs to a local directory
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/test/kotlin/azure/BlobAccessTests.kt
Labels: pipeline, platform

#12870 12413: PV1/PV2 to Encounter mapping
  prime-router/docs/design/design/HL7v2-FHIR-Inventory.md
  prime-router/metadata/fhir_mapping/fhir/resourcemapping.yml
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/CX/Identifier.yml
  prime-router/metadata/fhir_mapping/hl7/datatypes/XCN/Practitioner.yml
  prime-router/metadata/fhir_mapping/hl7/message/ORU_R01.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Encounter.yml
  prime-router/metadata/fhir_mapping/hl7/segments/ORC/PractitionerRole.yml
  prime-router/metadata/fhir_mapping/hl7/segments/ORC/ServiceRequest.yml
  prime-router/metadata/fhir_mapping/hl7/segments/PV1/Encounter.yml
  prime-router/metadata/fhir_mapping/hl7/segments/PV1/EpisodeOfCare.yml
  prime-router/metadata/fhir_mapping/hl7/segments/PV1/PV1Extension.yml
  prime-router/metadata/fhir_mapping/hl7/segments/PV1/PV2Extension.yml
  prime-router/metadata/hl7_mapping/ORU_R01/ORU_R01-base.yml
  prime-router/metadata/hl7_mapping/resources/Encounter/PV1.yml
  prime-router/metadata/hl7_mapping/resources/Encounter/PV1Extension.yml
  prime-router/metadata/hl7_mapping/resources/Encounter/PV2.yml
  prime-router/metadata/hl7_mapping/resources/Encounter/PV2Extension.yml
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/pv1pv2/PV1PV2ToEncounterTests.kt
  prime-router/src/testIntegration/resources/datatests/mappinginventory/dld/DLD-to-Location.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/ei/EI-to-Device-UDI-Carrier.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/ei/EI-to-Identifier-default-assigner.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/ei/EI-to-Identifier-organization-assigner.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/id/ID-to-Encounter-pv2-22-F.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/id/ID-to-Encounter.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/nm/nm-to-quantity.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-all-leaves.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-missing-pl1-pl3.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-missing-pl1.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-missing-pl7.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-only-pl3-pl1-pl4.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-only-pl3-pl4.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pl/PL-to-Location-only-pl4.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pv1pv2/PV1-PV2-to-Encounter-pv22-n.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pv1pv2/PV1-PV2-to-Encounter-pv22-n.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pv1pv2/PV1-PV2-to-Encounter-pv22-y.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pv1pv2/PV1-PV2-to-Encounter-pv22-y.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pv1pv2/PV1-PV2-to-Encounter.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pv1pv2/PV1-PV2-to-Encounter.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pv1pv2/PV1-to-Encounter-pv12-p.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pv1pv2/PV1-to-Encounter-pv12-p.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pv1pv2/PV1-to-Encounter-pv145-valued.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pv1pv2/PV1-to-Encounter-pv145-valued.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pv1pv2/PV1-to-Encounter.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/pv1pv2/PV1-to-Encounter.hl7
Labels: platform

#12499 Bump @adobe/css-tools from 4.3.1 to 4.3.2 in /frontend-react
  frontend-react/yarn.lock
Labels: security, dependencies, javascript

#12927 Update original passthrough design with payloadname finding
  prime-router/docs/design/proposals/0024-original-message-passthrough.md
Labels: platform

#12984 Bump actions/[upload|download]-artifact from 3.x to 4.1.x
  .github/actions/build-backend/action.yml
  .github/actions/build-frontend/action.yml
  .github/actions/deploy-backend/action.yml
  .github/actions/deploy-frontend/action.yml
  .github/workflows/release_to_github.yml
  .github/workflows/restore_databases.yml
Labels: dependencies, github_actions

#13010 Update google-site-verification tag
  frontend-react/index.html
Labels: experience

#12899 platform/jimfuqian/12766-Enhance-prime CLI with per ENV folder to save access token
  prime-router/src/main/kotlin/cli/OktaCommands.kt
Labels: platform

#12425 platform/jimfuqian/11441-Remove-UP-default-filters-associated-with-topics
  prime-router/docs/design/features/0001-universal-pipeline-filter-reporting.md
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirRouterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/DefaultFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/GetFilterTests.kt
Labels: pipeline, platform

#12874 Update dependabot process
  prime-router/docs/docs-deprecated/playbooks/dependabot-updates.md
Labels: security, dependencies

#12916 Bump ktlint from 1.0.0 to 1.1.1 in /prime-router
  prime-router/.editorconfig
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/cli/LookupTableCommands.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirTransformer.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
Labels: security, dependencies, java

#12713 Bump kotlin from 1.9.10 to 1.9.22 in /prime-router
  prime-router/gradle.properties
Labels: security, dependencies, java

#13035 Experience/12309/e2e updates
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: frontend, experience

#13016 SPM to Specimen Mapping
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/message/ORM_O01.yml
  prime-router/metadata/fhir_mapping/hl7/message/ORU_R01.yml
  prime-router/metadata/fhir_mapping/hl7/resource/Specimen.yml
  prime-router/metadata/fhir_mapping/hl7/segments/SPM/EIP/Specimen.yml
  prime-router/metadata/fhir_mapping/hl7/segments/SPM/SPMExtension.yml
  prime-router/metadata/fhir_mapping/hl7/segments/SPM/Specimen.yml
  prime-router/metadata/fhir_transforms/senders/SimpleReport/simple-report-sender-transform.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/order-observation.yml
  prime-router/metadata/hl7_mapping/datatypes/annotation/ST.yml
  prime-router/metadata/hl7_mapping/resources/Specimen/SPM.yml
  prime-router/metadata/hl7_mapping/resources/Specimen/SPMExtension.yml
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/spm/SPMtoSpecimen.kt
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_orm_20230809-001-with-enrichment.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_orm_20230809-001.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cq/quantity/cq_29_null.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cq/quantity/cq_all_fields.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/cwe/annotation/cwe-4-test-value-cwe1.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/eip/EIP-to-Identifier-Both.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/eip/EIP-to-Identifier-FillerAssignedIdentifier.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/eip/EIP-to-Identifier-PlacerAssignedIdentifier.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/nk1/nk1.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/nte/annotation_author_string_resource_test_file.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/nte/nte_segment_author_string_test_file.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/nte/nte_segment_author_string_test_file.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/spm/SPM-with-17-2-not-populated.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/spm/SPM-with-17-2-not-populated.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/spm/SPM-with-17-2-populated.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/spm/SPM-with-17-2-populated.hl7
Labels: platform

#13061 Experience/12309/e2e updates
  frontend-react/playwright.config.ts
Labels: frontend, experience

#13060 Convert action version to hash
  .github/workflows/log_management.yml
Labels: github_actions

#13083 group skrapeit
  .github/dependabot.yml
Labels: dependencies

#13064 12905: remove unused FHIR extensions
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/fhir_mapping/hl7/datatype/Annotation.yml
  prime-router/metadata/fhir_transforms/senders/SimpleReport/simple-report-sender-transform.yml
  prime-router/metadata/hl7_mapping/ORU_R01/ORU_R01-base.yml
  prime-router/metadata/hl7_mapping/ORU_R01/base/order-observation.yml
  prime-router/metadata/hl7_mapping/common/observation-result.yml
  prime-router/metadata/hl7_mapping/datatypes/annotation/NTE.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/CA-receiver-transform.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-order-note.yml
  prime-router/metadata/hl7_mapping/receivers/STLTs/CA/ca-patient-note.yml
  prime-router/metadata/hl7_mapping/resources/Observation/OBX.yml
  prime-router/src/testIntegration/resources/datatests/mappinginventory/nte/NTE-to-annotation.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/nte/annotation_author_string_resource_test_file.fhir
Labels: platform

#12966 12722: Enrich logs with additional queryable data
  prime-router/build.gradle.kts
  prime-router/docs/observability/logging.md
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/resources/jsonTemplate.json
  prime-router/src/main/resources/log4j2.xml
Labels: platform, observability

#13099 13073 fix last mile failures api
  prime-router/src/main/resources/db/migration/V67__update_list_send_failure.sql
Labels: platform

#13163 Experience/12309/e2e updates
  .github/actions/build-frontend/action.yml
Labels: frontend, experience

#12704 Implement condition based routing and pruning
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/ActionLog.kt
  prime-router/src/main/kotlin/ActionMessages.kt
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/ReportStreamFilter.kt
  prime-router/src/main/kotlin/azure/SettingsFacade.kt
  prime-router/src/main/kotlin/cli/SettingCommands.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/test/kotlin/ReceiverTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirRouterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/GetFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/utils/FHIRBundleHelpersTests.kt
  prime-router/src/test/resources/fhirengine/engine/routing/valid.fhir
  prime-router/src/test/resources/fhirengine/engine/valid_data.fhir
  prime-router/src/testIntegration/kotlin/MetadataIntegrationTests.kt
  prime-router/src/testIntegration/resources/settings/organizations.yml
Labels: platform

#13173 Experience/13077/content updates
  frontend-react/src/content/getting-started/index.mdx
  frontend-react/src/content/home/index.mdx
Labels: experience

#13168 12750 remove exception handling from coding extension function
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
Labels: platform
