Repository CDCgov/prime-reportstream, pull requests merged in 2024-05, with the labels that each got.

#14203 increase sonarcloud coverage
  .github/actions/sonarcloud/action.yml
Labels: security

#14183 13507: FHIR Converter integration tests
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/Sender.kt
  prime-router/src/main/kotlin/SettingsProvider.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/ProcessedFHIRItem.kt
  prime-router/src/main/kotlin/fhirengine/utils/HL7Reader.kt
  prime-router/src/main/resources/metadata/fhir_transforms/senders/SimpleReport/simple-report-sender-transform.yml
  prime-router/src/test/kotlin/ReportTests.kt
  prime-router/src/test/kotlin/azure/BlobAccessTests.kt
  prime-router/src/test/kotlin/common/TestcontainersUtils.kt
  prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/SyncSchemaE2ETests.kt
  prime-router/src/test/kotlin/fhirengine/translation/TranslationSchemaManagerTests.kt
Labels: platform

#14240 Experience/8958/daily data table replacement
  frontend-react/e2e/spec/daily-data-page.spec.ts
  frontend-react/src/components/MessageTracker/MessageTracker.test.tsx
  frontend-react/src/pages/deliveries/daily-data/DailyData.test.tsx
  frontend-react/src/pages/deliveries/daily-data/DailyData.tsx
  frontend-react/src/shared/Table/Table.module.scss
  frontend-react/src/shared/Table/Table.tsx
Labels: experience, trialfrontend02

#14204 14102: disable dedupe detection parameter for the UP
  prime-router/src/main/kotlin/SubmissionReceiver.kt
  prime-router/src/test/kotlin/SubmissionReceiverTests.kt
Labels: platform

#14246 Experience/14179/e2e daily data updates
  frontend-react/e2e/spec/daily-data-page.spec.ts
Labels: frontend, experience

#14185 13794 add radxmars hl7 java class
  prime-router/src/main/java/fhirengine/translation/hl7/structures/radxmars251/group/ORU_R01_OBSERVATION.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/radxmars251/group/ORU_R01_ORDER_OBSERVATION.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/radxmars251/group/ORU_R01_PATIENT_RESULT.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/radxmars251/group/ORU_R01_SPECIMEN.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/radxmars251/group/ORU_R01_SPECIMEN_OBSERVATION.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/radxmars251/message/ORU_R01.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/radxmars251/segment/OBX.java
  prime-router/src/test/kotlin/fhirengine/translation/RadxMarsTests.kt
Labels: platform

#14319 BUG: E2E Daily Data Details Test Broken
  frontend-react/e2e/spec/daily-data-details-page.spec.ts
Labels: bug, frontend

#14182 SOP for adding new HL7 spec
  prime-router/docs/standard-operating-procedures/adding-conformance-profile.md
Labels: platform

#14284 Update condition mapping to indicate correct item index in log
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/resources/fhirengine/engine/batch_valid_data.fhir
Labels: platform

#14251 14109 organizations yaml validation
  prime-router/metadata/json_schema/organizations/organizations.json
  prime-router/settings/organizations.yml
  prime-router/settings/readme.md
  prime-router/src/main/kotlin/cli/SettingCommands.kt
  prime-router/src/main/kotlin/common/JacksonMapperUtilities.kt
  prime-router/src/main/kotlin/config/validation/ConfigurationType.kt
  prime-router/src/main/kotlin/config/validation/JsonSchemaValidationService.kt
  prime-router/src/test/kotlin/config/validation/JsonSchemaValidationServiceTest.kt
  prime-router/src/test/kotlin/config/validation/JsonSchemaValidationTest.kt
  prime-router/src/test/kotlin/config/validation/ValueValidationTest.kt
Labels: platform

#14236 KS onboarding to UP
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/STLTs/KS/KS-receiver-transform.yml
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/STLTs/KS/ks-doh.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_KS_20240429-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_KS_20240429-0001.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: onboarding-ops, Kansas

#14338 14206 - fixed issue where ELIMS messages not returning in Daily Data
  prime-router/src/main/kotlin/history/azure/ReportFileFunction.kt
  prime-router/src/test/kotlin/history/azure/ReportFileFunctionTests.kt
Labels: experience

#14345 Create E2E tests on Org Settings Page
  frontend-react/e2e/mocks/organizations.ts
  frontend-react/e2e/mocks/prime-orgs.csv
  frontend-react/e2e/spec/last-mile-failures-page.spec.ts
  frontend-react/e2e/spec/organization-settings-page.spec.ts
  frontend-react/src/components/Admin/OrgsTable.tsx
  frontend-react/src/shared/RequireGate/RequireGate.tsx
Labels: frontend

#14255 13798: additional obx mappings for Radxmars
  prime-router/metadata/HL7/catchall/hl7/segments/OBX/OBXExtension.yml
  prime-router/metadata/HL7/catchall/hl7/segments/OBX/Observation.yml
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/fhirengine/utils/HL7Reader.kt
  prime-router/src/main/resources/metadata/fhir_transforms/senders/SimpleReport/simple-report-sender-transform.yml
  prime-router/src/main/resources/metadata/hl7_mapping/resources/Observation/OBX.yml
  prime-router/src/main/resources/metadata/hl7_mapping/resources/Observation/OBXExtension.yml
  prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/catchall/obx/OBXToObservationTests.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AK_20240220-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_CO_20240403.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_KS_20240429-0001.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_oml_20240319-001.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_orm_20230809-001-with-enrichment.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_orm_20230809-001.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/etor_ORU_20240220-expected.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/obx/OBX-to-Observation-obx25-obx24-not-valued.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/obx/OBX-to-Observation-obx25-obx24-not-valued.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/obx/OBX-to-Observation-st-value.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/obx/OBX-to-Observation-st-value.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: platform

#13902 Added flyway migration to add index to report_file
  prime-router/src/main/resources/db/migration/V68__add_index_report_file.sql
Labels: DevOps, reportstream

#14352 13436 - e2e documentation
  frontend-react/README.md
  frontend-react/docs/standard-operating-procedures/e2e-frontend-guidance.md
Labels: frontend, experience

#14344 14115: further convert cleanup
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/ProcessedItem.kt
  prime-router/src/main/kotlin/history/SubmissionHistory.kt
  prime-router/src/main/kotlin/history/azure/DatabaseSubmissionsAccess.kt
  prime-router/src/main/kotlin/validation/IItemValidator.kt
  prime-router/src/main/kotlin/validation/MarsOtcElrValidator.kt
  prime-router/src/main/kotlin/validation/NoopItemValidator.kt
  prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/history/SubmissionHistoryTests.kt
  prime-router/src/test/kotlin/validation/MessageValidatorTests.kt
Labels: platform

#14283 De-identified schema
  prime-router/src/main/resources/metadata/hl7_mapping/ORU_R01/ORU_R01-deidentified.yml
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/ORU_deidentified-expected.hl7
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR_to_HL7/ORU_deidentified.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: onboarding-ops

#14400 13538: send original filename format report_id-original_name
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/test/kotlin/ReportTests.kt
Labels: platform

#14360 Add Mars OTC ELR scenarios to E2E UP Test
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/cli/tests/BasicTests.kt
  prime-router/src/main/kotlin/cli/tests/CompareData.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/test/resources/fhirengine/smoketest/Expected_FHIR_to_FHIR_MARSOTC.fhir
  prime-router/src/test/resources/fhirengine/smoketest/Expected_HL7_to_FHIR_MARSOTC.fhir
  prime-router/src/test/resources/fhirengine/smoketest/Expected_HL7_to_HL7_MARSOTC.hl7
  prime-router/src/test/resources/fhirengine/smoketest/valid_mars.fhir
  prime-router/src/test/resources/fhirengine/smoketest/valid_mars.hl7
Labels: platform

#14406 Platform/angela/14257/circular json
  .environment/gitleaks/gitleaks-config.toml
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirTransformer.kt
  prime-router/src/main/resources/metadata/fhir_transforms/senders/SimpleReport/simple-report-sender-transform.yml
  prime-router/src/main/resources/metadata/fhir_transforms/senders/test-sender-transform.yml
  prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
Labels: platform

#14407 14393 - E2E tests for the MessageID Search page
  frontend-react/e2e/mocks/messages.ts
  frontend-react/e2e/pages/message-id-search.ts
  frontend-react/e2e/pages/submission-history.ts
  frontend-react/e2e/spec/message-id-search-page.spec.ts
Labels: frontend, experience

#14388 14110: add validation service
  prime-router/src/main/kotlin/ReportStreamFilterDefinition.kt
  prime-router/src/main/kotlin/config/validation/ConfigurationType.kt
  prime-router/src/main/kotlin/config/validation/ConfigurationValidationResult.kt
  prime-router/src/main/kotlin/config/validation/ConfigurationValidationService.kt
  prime-router/src/main/kotlin/config/validation/ConfigurationValueValidationService.kt
  prime-router/src/main/kotlin/config/validation/JsonSchemaValidationService.kt
  prime-router/src/main/kotlin/config/validation/Validations.kt
  prime-router/src/test/kotlin/config/validation/ConfigurationValidationServiceTest.kt
  prime-router/src/test/kotlin/config/validation/ConfigurationValueValidationServiceTest.kt
  prime-router/src/test/kotlin/config/validation/JsonSchemaValidationServiceTest.kt
  prime-router/src/test/kotlin/config/validation/JsonSchemaValidationTest.kt
Labels: platform

#14454 Experience/14405/message details e2e
  frontend-react/docs/standard-operating-procedures/e2e-guidance.md
  frontend-react/e2e/mocks/delivery.ts
  frontend-react/e2e/mocks/messages.ts
  frontend-react/e2e/pages/message-details.ts
  frontend-react/e2e/spec/daily-data-details-page.spec.ts
  frontend-react/e2e/spec/message-details-page.spec.ts
  frontend-react/e2e/spec/message-id-search-page.spec.ts
  frontend-react/src/components/MessageTracker/MessageDetails.test.tsx
  frontend-react/src/components/MessageTracker/MessageDetails.tsx
  frontend-react/src/components/MessageTracker/MessageReceivers.test.tsx
  frontend-react/src/components/MessageTracker/MessageReceivers.tsx
Labels: frontend, experience

#14325 Add Encryption for files sent to NATUS LA
  prime-router/src/main/kotlin/Cryptography.kt
  prime-router/src/main/kotlin/TransportType.kt
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/test/kotlin/CryptographyTest.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
Labels: onboarding-ops, etor

#14412 14158 yaml validation cli task
  prime-router/src/main/kotlin/cli/ValidateYAMLCommand.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/main/kotlin/config/validation/JsonSchemaValidationService.kt
  prime-router/src/main/kotlin/config/validation/Validations.kt
  prime-router/src/test/kotlin/cli/ValidateYMLCommandTests.kt
  prime-router/src/test/resources/yaml_validation/failure/invalid.yml
  prime-router/src/test/resources/yaml_validation/failure/recursive/not-yaml.txt
  prime-router/src/test/resources/yaml_validation/failure/valid.yml
  prime-router/src/test/resources/yaml_validation/success/recursive/test3.yml
  prime-router/src/test/resources/yaml_validation/success/test1.yml
  prime-router/src/test/resources/yaml_validation/success/test2.yml
Labels: platform

#14483 Update RadxMars OTC validation profile to latest version
  .environment/gitleaks/gitleaks-config.toml
  prime-router/build.gradle.kts
  prime-router/docs/standard-operating-procedures/adding-conformance-profile.md
  prime-router/src/main/resources/metadata/hl7_validation/v251/radxmars/coconstraints.xml
  prime-router/src/main/resources/metadata/hl7_validation/v251/radxmars/constraints.xml
  prime-router/src/main/resources/metadata/hl7_validation/v251/radxmars/profile.xml
  prime-router/src/main/resources/metadata/hl7_validation/v251/radxmars/slicings.xml
  prime-router/src/main/resources/metadata/hl7_validation/v251/radxmars/value-set-bindings.xml
  prime-router/src/main/resources/metadata/hl7_validation/v251/radxmars/value-sets.xml
  prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionIntegrationTests.kt
Labels: platform

#14495 14280 - unskip Daily Data Detail tests
  frontend-react/e2e/spec/daily-data-details-page.spec.ts
Labels: frontend, experience

#14500 14420 - Fixed ReportId link in Daily Data page
  frontend-react/docs/standard-operating-procedures/e2e-guidance.md
  frontend-react/src/pages/deliveries/daily-data/DailyData.tsx
Labels: frontend, experience

#14508 13895 - Removed alerts from Daily Data and Data Dashboard
  frontend-react/src/pages/data-dashboard/DataDashboard.tsx
  frontend-react/src/pages/deliveries/Deliveries.tsx
Labels: frontend, experience

#14399 Implemented destination filter
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/Event.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportReceiverSelectedEvent.kt
  prime-router/src/main/kotlin/fhirengine/azure/FHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRDestinationFilter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIREngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiverFilter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/engine/QueueMessage.kt
  prime-router/src/main/resources/db/migration/V69__add_split_routing_taskactions.sql
  prime-router/src/main/resources/db/migration/V70__add_split_routing_finishedfields.sql
  prime-router/src/test/kotlin/azure/SendFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirDestinationFilterTests.kt
  prime-router/src/testIntegration/kotlin/transport/AS2TransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/GAENTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/SftpTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/SoapTransportIntegrationTests.kt
Labels: platform

#14510 14159 ci pipeline yaml validation
  .github/workflows/build_hub.yml
Labels: platform

#14519 14084 - Track interactions with the new Search and Filter features on the Daily Data page
  frontend-react/src/components/Table/TableFilterSearch.tsx
  frontend-react/src/components/Table/TableFilters.tsx
Labels: frontend, experience, trialfrontend01

#14539 14084 - Updated Event name
  frontend-react/src/components/Table/TableFilterSearch.tsx
  frontend-react/src/components/Table/TableFilters.tsx
Labels: frontend, experience

#14552 [Snyk] Security upgrade requests from 2.31.0 to 2.32.0
  operations/app/functions/admin/requirements.txt
Labels: security, dependencies, python

#14520 14413: fetch all conditions for mapping at once
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/main/kotlin/metadata/LookupTable.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/metadata/LookupTableTests.kt
Labels: platform

#14553 14457: only use bundle identifier for tracking element id
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
Labels: platform

#14541 Update FHIRRouter Azure Events to Store messageID
  prime-router/build.gradle.kts
  prime-router/docs/design/design/transformations.md
  prime-router/docs/getting-started/running-tests.md
  prime-router/docs/observability/azure-events.md
  prime-router/docs/observability/local-dev-setup.md
  prime-router/src/main/kotlin/azure/observability/event/AzureEventUtils.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportAcceptedEvent.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportRouteEvent.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRDestinationFilter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/test/kotlin/azure/observability/event/AzureEventUtilsTest.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirDestinationFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirRouterTests.kt
  prime-router/src/test/resources/fhirengine/engine/fhir_without_birth_time.fhir
  prime-router/src/test/resources/fhirengine/engine/fhir_without_patient.fhir
  prime-router/src/test/resources/fhirengine/engine/routing/valid.fhir
  prime-router/src/test/resources/fhirengine/engine/routing/valid_no_identifier.fhir
Labels: platform

#14355 14249 add fhir inventory java class
  prime-router/docs/design/design/HL7v2-FHIR-Inventory.md
  prime-router/metadata/HL7/catchall/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/HL7/catchall/hl7/segments/NTE/Annotation.yml
  prime-router/metadata/HL7/catchall/hl7/segments/NTE/NTEExtension.yml
  prime-router/metadata/HL7/catchall/hl7/segments/OBX/OBXExtension.yml
  prime-router/metadata/HL7/catchall/hl7/segments/OBX/Observation.yml
  prime-router/metadata/HL7/catchall/hl7/segments/ORC/OBRExtension.yml
  prime-router/metadata/HL7/catchall/hl7/segments/ORC/ORCExtension.yml
  prime-router/metadata/HL7/catchall/hl7/segments/ORC/ServiceRequest.yml
  prime-router/metadata/HL7/catchall/hl7/segments/PID/Patient.yml
  prime-router/metadata/HL7/catchall/hl7/segments/PRT/Device.yml
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/group/ORU_R01_OBSERVATION.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/group/ORU_R01_ORDER_OBSERVATION.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/group/ORU_R01_PATIENT.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/group/ORU_R01_PATIENT_OBSERVATION.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/group/ORU_R01_PATIENT_RESULT.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/group/ORU_R01_SPECIMEN.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/group/ORU_R01_SPECIMEN_OBSERVATION.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/group/ORU_R01_VISIT.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/message/ORU_R01.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/segment/NTE.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/segment/OBR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/segment/OBX.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/segment/ORC.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/segment/PD1.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/segment/PID.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/segment/PRT.java
  prime-router/src/main/kotlin/fhirengine/utils/HL7Reader.kt
  prime-router/src/main/resources/metadata/hl7_mapping/datatypes/annotation/NTE.yml
  prime-router/src/main/resources/metadata/hl7_mapping/datatypes/annotation/NTEExtension.yml
  prime-router/src/main/resources/metadata/hl7_mapping/resources/Observation/OBXExtension.yml
  prime-router/src/main/resources/metadata/hl7_mapping/resources/ServiceRequest/OBRExtension.yml
  prime-router/src/main/resources/metadata/hl7_mapping/resources/ServiceRequest/ORCExtension.yml
  prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/NistElrTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/RadxMarsTests.kt
  prime-router/src/test/resources/fhirengine/smoketest/Expected_HL7_to_FHIR_FULLELR.fhir
  prime-router/src/test/resources/fhirengine/smoketest/Expected_HL7_to_FHIR_MARSOTC.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/nte/NTE-to-annotation.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/nte/NTE-to-annotation.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/obx/OBX-to-Observation-st-value.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/obx/OBX-to-Observation-st-value.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/orc_obr-to-servicerequest_diagnosticreport-obr-populated.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/orc_obr-to-servicerequest_diagnosticreport-obr-populated.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/orc_obr-to-servicerequest_diagnosticreport-orc-obr-populated.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/orc_obr-to-servicerequest_diagnosticreport-orc-populated.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/orc_obr-to-servicerequest_diagnosticreport-orc-populated.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orur01/oru_r01-full.fhir
Labels: platform

#14509 Experience/14004/programmatic check link e2e
  frontend-react/e2e/helpers/external-links.ts
  frontend-react/e2e/helpers/internal-links.ts
  frontend-react/e2e/pages/public-pages-link-check.ts
  frontend-react/e2e/spec/chromium-only/public-pages-link-check.spec.ts
  frontend-react/e2e/spec/homepage.spec.ts
  frontend-react/package.json
  frontend-react/playwright.config.ts
  frontend-react/src/content/about/roadmap.mdx
  frontend-react/src/shared/DAPScript/DAPScript.tsx
  frontend-react/src/utils/PermissionsUtils.ts
Labels: frontend, experience

#14491 Bump braces from 3.0.2 to 3.0.3 in /frontend-react
  frontend-react/yarn.lock
Labels: security, dependencies, javascript
