Repository CDCgov/prime-reportstream, pull requests merged in 2024-03, with the labels that each got.

#13457 13020 load schema mapping support
  prime-router/metadata/test_fhir_mapping/config.properties
  prime-router/metadata/test_fhir_mapping/hl7/message/ORM_O01.yml
  prime-router/metadata/test_fhir_mapping/hl7/message/ORU_R01.yml
  prime-router/metadata/test_fhir_mapping/hl7/segments/MSH/MessageHeader.yml
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/translation/HL7toFhirTranslator.kt
  prime-router/src/main/kotlin/fhirengine/utils/HL7Reader.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/HL7toFhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/utils/HL7ReaderTests.kt
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
Labels: platform

#13559 submissions bug fix + test fix
  frontend-react/src/components/Table/Table.test.tsx
  frontend-react/src/pages/deliveries/daily-data/DailyData.test.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.test.tsx
  frontend-react/src/pages/submissions/SubmissionDetails.tsx
  frontend-react/src/resources/ActionDetailsResource.ts
  frontend-react/src/resources/TestResponse.ts
  frontend-react/src/utils/DateTimeUtils.test.ts
  frontend-react/src/utils/DateTimeUtils.ts
  frontend-react/yarn.lock
Labels: experience

#13498 12891 - Implement preview images to ReportStream website pages
  .github/actions/build-frontend/action.yml
  frontend-react/.env
  frontend-react/404.html
  frontend-react/index.html
  frontend-react/public/assets/img/opengraph/howwehelpyou-1.png
  frontend-react/public/assets/img/opengraph/howwehelpyou-2.png
  frontend-react/public/assets/img/opengraph/howwehelpyou-3.png
  frontend-react/public/assets/img/opengraph/reportstream-tagline.png
  frontend-react/public/assets/img/opengraph/reportstream.png
  frontend-react/src/App.test.tsx
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/components/ManagePublicKey/ManagePublicKey.tsx
  frontend-react/src/config/index.ts
  frontend-react/src/content/about/case-studies.mdx
  frontend-react/src/content/about/index.mdx
  frontend-react/src/content/about/news.mdx
  frontend-react/src/content/about/our-network.mdx
  frontend-react/src/content/about/release-notes.mdx
  frontend-react/src/content/about/security.mdx
  frontend-react/src/content/developer-resources/index-page.mdx
  frontend-react/src/content/developer-resources/reportstream-api/ReportStreamApi.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/Documentation.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/ResponsesFromReportStream.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/SamplePayloadsAndOutput.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/data-model/DataModel.mdx
  frontend-react/src/content/developer-resources/reportstream-api/getting-started/GettingStarted.mdx
  frontend-react/src/content/getting-started/index.mdx
  frontend-react/src/content/getting-started/receiving-data.mdx
  frontend-react/src/content/getting-started/sending-data.mdx
  frontend-react/src/content/home/index.mdx
  frontend-react/src/content/managing-your-connection/index.mdx
  frontend-react/src/content/managing-your-connection/refer-healthcare-organizations.mdx
  frontend-react/src/content/support/index.mdx
  frontend-react/src/layouts/Markdown/MarkdownLayout.tsx
  frontend-react/src/layouts/Markdown/utils.test.ts
  frontend-react/src/layouts/Markdown/utils.ts
  frontend-react/src/pages/Login.tsx
  frontend-react/src/pages/TermsOfService.tsx
  frontend-react/src/pages/admin/AdminLastMileFailures.tsx
  frontend-react/src/pages/admin/AdminMain.tsx
  frontend-react/src/pages/admin/AdminMessageTracker.tsx
  frontend-react/src/pages/admin/AdminOrgEdit.tsx
  frontend-react/src/pages/admin/AdminOrgNew.tsx
  frontend-react/src/pages/admin/AdminReceiverDashPage.tsx
  frontend-react/src/pages/admin/AdminRevHistory.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
  frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.tsx
  frontend-react/src/pages/data-dashboard/DataDashboard.tsx
  frontend-react/src/pages/deliveries/Deliveries.tsx
  frontend-react/src/pages/submissions/Submissions.tsx
  frontend-react/src/utils/LazyRouteMarkdown.test.tsx
  frontend-react/src/vite-env.d.ts
  frontend-react/yarn.lock
Labels: frontend, experience, trialfrontend01

#13530 10510: remove support for relative pathing and schema setting normalization
  prime-router/build.gradle.kts
  prime-router/docs/standard-operating-procedures/azure-storage-browser-default-emulator.png
  prime-router/docs/standard-operating-procedures/completed-schema-sync.png
  prime-router/docs/standard-operating-procedures/create-new-folder.png
  prime-router/docs/standard-operating-procedures/managing-translation-schemas-in-azure.md
  prime-router/docs/standard-operating-procedures/upload-edited-schema.png
  prime-router/docs/standard-operating-procedures/upload-new-file.png
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/azure/ValidateSchemasFunctions.kt
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/cli/SyncTranslationSchemaCommand.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/main/kotlin/common/BaseEngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/translation/TranslationSchemaManager.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirTransformer.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReader.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/converter/ConverterSchemaReader.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/fhirTransform/FhirTransformSchemaReader.kt
  prime-router/src/test/kotlin/cli/SyncTranslationSchemaCommandTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/LookupTableValueSetTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/TranslationSchemaManagerTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirTransformerTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReaderTests.kt
  prime-router/src/test/resources/fhir_sender_transforms/circular_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/extends_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/incomplete_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/invalid_lookup_value_set.yml
  prime-router/src/test/resources/fhir_sender_transforms/invalid_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/invalid_value_set.yml
  prime-router/src/test/resources/fhir_sender_transforms/lookup_value_set.yml
  prime-router/src/test/resources/fhir_sender_transforms/no_schema_nor_value.yml
  prime-router/src/test/resources/fhir_sender_transforms/sample_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/test_extension_schema.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01/order-observation.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01/patient.yml
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
Labels: platform

#13597 Revert "10510: remove support for relative pathing and schema setting normalization"
  prime-router/build.gradle.kts
  prime-router/docs/standard-operating-procedures/azure-storage-browser-default-emulator.png
  prime-router/docs/standard-operating-procedures/completed-schema-sync.png
  prime-router/docs/standard-operating-procedures/create-new-folder.png
  prime-router/docs/standard-operating-procedures/managing-translation-schemas-in-azure.md
  prime-router/docs/standard-operating-procedures/upload-edited-schema.png
  prime-router/docs/standard-operating-procedures/upload-new-file.png
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/azure/ValidateSchemasFunctions.kt
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/cli/SyncTranslationSchemaCommand.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/main/kotlin/common/BaseEngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/translation/TranslationSchemaManager.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirTransformer.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReader.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/converter/ConverterSchemaReader.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/fhirTransform/FhirTransformSchemaReader.kt
  prime-router/src/test/kotlin/cli/SyncTranslationSchemaCommandTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/LookupTableValueSetTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/TranslationSchemaManagerTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirTransformerTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReaderTests.kt
  prime-router/src/test/resources/fhir_sender_transforms/circular_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/extends_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/incomplete_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/invalid_lookup_value_set.yml
  prime-router/src/test/resources/fhir_sender_transforms/invalid_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/invalid_value_set.yml
  prime-router/src/test/resources/fhir_sender_transforms/lookup_value_set.yml
  prime-router/src/test/resources/fhir_sender_transforms/no_schema_nor_value.yml
  prime-router/src/test/resources/fhir_sender_transforms/sample_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/test_extension_schema.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01/order-observation.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01/patient.yml
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
Labels: platform

#13594 Bug: fix schema name to not exceed max width
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
Labels: platform

#13589 SC Onboarding also allow to replace FHS-2 and BHS-2
  prime-router/settings/prod/0163-sc-onboarding-to-up-receiver.yml
  prime-router/settings/staging/0169-sc-onboarding-to-up-receiver.yml
  prime-router/src/main/kotlin/fhirengine/utils/HL7MessageHelpers.kt
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/STLTs/SC/SC-receiver-transform.yml
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/STLTs/SC/sc-phd.yml
  prime-router/src/test/kotlin/fhirengine/utils/HL7QueueMessageHelpersTests.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SC_20240305-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SC_20240305-0001.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config-org.csv
Labels: onboarding-ops, South Carolina

#13576 10222: Backend readme updates
  README.md
  frontend-react/README.md
  frontend-react/yarn.lock
  prime-router/README.md
  prime-router/docs/README.md
  prime-router/docs/docs-deprecated/getting-started/Using-an-apple-silicon-mac.md
  prime-router/docs/docs-deprecated/getting-started/getting-started.md
  prime-router/docs/docs-deprecated/how-to-onboard-a-receiver.md
  prime-router/docs/getting-started/README.md
  prime-router/docs/getting-started/azure.md
  prime-router/docs/getting-started/contributing.md
  prime-router/docs/getting-started/gradle.md
  prime-router/docs/getting-started/install-git.md
  prime-router/docs/getting-started/install-openjdk.md
  prime-router/docs/getting-started/prime-cli.md
  prime-router/docs/getting-started/running-tests.md
  prime-router/docs/getting-started/signing-commits.md
  prime-router/docs/onboarding-users/receivers.md
Labels: platform

#13605 10510: cleanup and sop translation schema
  prime-router/build.gradle.kts
  prime-router/docs/standard-operating-procedures/azure-storage-browser-default-emulator.png
  prime-router/docs/standard-operating-procedures/completed-schema-sync.png
  prime-router/docs/standard-operating-procedures/create-new-folder.png
  prime-router/docs/standard-operating-procedures/managing-translation-schemas-in-azure.md
  prime-router/docs/standard-operating-procedures/upload-edited-schema.png
  prime-router/docs/standard-operating-procedures/upload-new-file.png
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/azure/ValidateSchemasFunctions.kt
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/cli/SyncTranslationSchemaCommand.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/main/kotlin/common/BaseEngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/translation/TranslationSchemaManager.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirTransformer.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReader.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/converter/ConverterSchemaReader.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/fhirTransform/FhirTransformSchemaReader.kt
  prime-router/src/test/kotlin/cli/SyncTranslationSchemaCommandTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/LookupTableValueSetTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/TranslationSchemaManagerTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirTransformerTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReaderTests.kt
  prime-router/src/test/resources/fhir_sender_transforms/circular_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/extends_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/incomplete_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/invalid_lookup_value_set.yml
  prime-router/src/test/resources/fhir_sender_transforms/invalid_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/invalid_value_set.yml
  prime-router/src/test/resources/fhir_sender_transforms/lookup_value_set.yml
  prime-router/src/test/resources/fhir_sender_transforms/no_schema_nor_value.yml
  prime-router/src/test/resources/fhir_sender_transforms/sample_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/test_extension_schema.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01/order-observation.yml
  prime-router/src/test/resources/fhirengine/translation/hl7/schema/schema-read-test-01/ORU_R01/patient.yml
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
Labels: platform

#13581 Experience/12978/filter status
  frontend-react/src/components/Table/Pagination.tsx
  frontend-react/src/components/Table/Table.test.tsx
  frontend-react/src/components/Table/TableFilterStatus.tsx
  frontend-react/src/components/Table/TableFilters.module.scss
  frontend-react/src/components/Table/TableFilters.tsx
  frontend-react/src/hooks/UsePagination.test.tsx
  frontend-react/src/hooks/UsePagination.ts
  frontend-react/src/hooks/filters/UseDateRange.ts
  frontend-react/src/pages/deliveries/daily-data/DailyData.test.tsx
  frontend-react/src/pages/deliveries/daily-data/DailyData.tsx
Labels: experience, trialfrontend02

#13593 Experience/13480/deliveries receiver status update
  prime-router/docs/api/waters-delivery.yml
  prime-router/src/main/kotlin/history/DeliveryHistory.kt
  prime-router/src/main/kotlin/history/ReportHistory.kt
  prime-router/src/main/kotlin/history/azure/DeliveryFacade.kt
  prime-router/src/main/kotlin/history/azure/DeliveryFunction.kt
  prime-router/src/main/kotlin/history/azure/HistoryDatabaseAccess.kt
  prime-router/src/main/kotlin/history/azure/ReportFileFunction.kt
  prime-router/src/test/kotlin/history/DeliveryHistoryTests.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFacadeTests.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFunctionTests.kt
Labels: frontend, experience

#13478 13136: query documentation
  prime-router/docs/observability/azure-events.md
  prime-router/src/main/kotlin/azure/observability/event/AzureEventUtils.kt
  prime-router/src/main/kotlin/azure/observability/event/ObservationSummary.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportAcceptedEvent.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportRouteEvent.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/test/kotlin/azure/observability/event/AzureEventUtilsTest.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirRouterTests.kt
Labels: platform, observability

#13653 Experience/13580/e2e submissions
  frontend-react/e2e/helpers/auth.setup.ts
  frontend-react/e2e/helpers/utils.ts
  frontend-react/e2e/mocks/history.ts
  frontend-react/e2e/mocks/submissions.ts
  frontend-react/e2e/pages/submission-history.ts
  frontend-react/e2e/spec/last-mile-failures-page.spec.ts
  frontend-react/e2e/spec/submission-history-page.spec.ts
  frontend-react/src/components/Table/Table.test.tsx
Labels: frontend, experience

#13665 Josiahsiegel/platform/kalish/10501 validate schemas during ci
  .github/actions/build-backend/action.yml
  .github/workflows/build_hub.yml
Labels: DevOps, reportstream

#13596 Massive dependabot upgrade
  prime-router/build.gradle.kts
Labels: security, dependencies, java, platform

#13678 Revert "Experience/13580/e2e submissions"
  frontend-react/e2e/helpers/auth.setup.ts
  frontend-react/e2e/helpers/utils.ts
  frontend-react/e2e/mocks/history.ts
  frontend-react/e2e/mocks/submissions.ts
  frontend-react/e2e/pages/submission-history.ts
  frontend-react/e2e/spec/last-mile-failures-page.spec.ts
  frontend-react/e2e/spec/submission-history-page.spec.ts
  frontend-react/src/components/Table/Table.test.tsx
Labels: experience, platform

#13625 FHIR Extension Registry
  prime-router/docs/design/design/RS-Extention-Registry.yml
  prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
Labels: platform

#13618 13021 nist elr java class
  .github/actions/sonarcloud/action.yml
  .sonarcloud.properties
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/CE_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/CNN_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/CQ_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/CWE_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/CX_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/DR_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/ED_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/EIP_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/EI_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/ERL_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/FC_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/FN_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/HD_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/MSG_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/NDL_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/PL_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/PRL_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/PT_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/RP_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/SAD_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/SN_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/TS_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/VID_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/XAD_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/XCN_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/XON_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/XPN_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/datatype/XTN_ELR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/group/ORU_R01_OBSERVATION.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/group/ORU_R01_ORDER_OBSERVATION.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/group/ORU_R01_PATIENT.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/group/ORU_R01_PATIENT_RESULT.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/group/ORU_R01_SPECIMEN.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/group/ORU_R01_TIMING_QTY.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/group/ORU_R01_VISIT.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/message/ORU_R01.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/segment/FT1.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/segment/MSH.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/segment/NK1.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/segment/NTE.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/segment/OBR.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/segment/OBX.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/segment/ORC.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/segment/PD1.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/segment/PID.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/segment/PV1.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/segment/PV2.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/segment/SFT.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/segment/SPM.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/segment/TQ1.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/nistelr251/segment/TQ2.java
  prime-router/src/test/kotlin/fhirengine/translation/NistElrTests.kt
Labels: platform

#13712 Bump follow-redirects from 1.15.4 to 1.15.6 in /frontend-react
  frontend-react/yarn.lock
Labels: security, dependencies, javascript

#13721 Bump Node.JS to 20.11.1
  frontend-react/.nvmrc
  frontend-react/README.md
  frontend-react/package.json
  frontend-react/src/utils/misc.test.ts
Labels: security, dependencies, javascript

#13758 The PDF version of the API Programmer's Guide does not download
  frontend-react/public/assets/pdf/ReportStream-Programmers-Guide-v4.4.pdf
Labels: design, frontend

#13785 Chore: react-uswds update
  frontend-react/package.json
  frontend-react/src/__mocks__/focus-trap-react.tsx
  frontend-react/src/global.scss
  frontend-react/src/styles/react-uswds-fixed.css
  frontend-react/yarn.lock
Labels: frontend

#13695 Experience/13480/deliveries receiver status
  prime-router/docs/api/waters-delivery.yml
  prime-router/src/main/kotlin/history/DeliveryHistory.kt
  prime-router/src/main/kotlin/history/azure/DeliveryFacade.kt
  prime-router/src/main/kotlin/history/azure/DeliveryFunction.kt
  prime-router/src/main/kotlin/history/azure/HistoryDatabaseAccess.kt
  prime-router/src/main/kotlin/history/azure/ReportFileFunction.kt
  prime-router/src/main/kotlin/history/azure/SubmissionsFacade.kt
  prime-router/src/test/kotlin/history/DeliveryHistoryTests.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFacadeTests.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFunctionTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionFunctionTests.kt
Labels: experience

#13763 13025: extract 251 datatypes fhir mappings
  prime-router/src/main/resources/metadata/hl7_mapping/v251-elr/datatypes/HumanName/XPN_ELR.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251-elr/datatypes/HumanName/XPN_ELRExtension.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251-elr/datatypes/Quantity/CQ_ELR.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251-elr/datatypes/codeableConcept/CWE_ELR.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251-elr/datatypes/extensionPRL_ELR/PRL_ELR.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251-elr/resources/Location/PL_ELR.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251-elr/resources/Location/PL_ELRBranch.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/Address/SADExtension.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/Address/XAD.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/Address/XADExtension.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/Attachment/ED.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/Attachment/EDExtension.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/HumanName/FN.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/HumanName/XPN.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/HumanName/XPNExtension.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/Quantity/CQ.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/Range/NR.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/URI/HD.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/annotation/NTE.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/annotation/ST.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/codeableConcept/CE.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/codeableConcept/CNE.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/codeableConcept/CWE.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/coding/MSG.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/contactPoint/XTN.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/contactPoint/XTNExtension.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/dateTime/DTMorDT.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/device-udiCarrier/EI.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/extensionAssigningAuthority/HD.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/extensionEI/EI.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/extensionHD/HD.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/extensionMOC/MOC.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/extensionPRL/PRL.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/extensionSN/SN.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/identifier-extension/EI.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/identifier-fillerAssignedIdentifier/EIP.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/identifier-placerAssignedIdentifier/EIP.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/identifier/CX.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/identifier/CXExtension.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/identifier/EI.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/identifier/HD.yml
  prime-router/src/main/resources/metadata/hl7_mapping/v251/datatypes/meta/PT.yml
Labels: platform

#13795 BUG: Chromatic deploy broken with latest msw
  frontend-react/.storybook/UtilizedUSWDSComponents/Select.stories.tsx
  frontend-react/.storybook/main.ts
  frontend-react/package.json
  frontend-react/vite.config.ts
  frontend-react/yarn.lock
Labels: bug, frontend

#13765 13025: test against profiles
  prime-router/metadata/HL7/v251-elr/hl7/segments/MSH/MessageHeader.yml
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/TranslateAndCompareFile.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/hd/HDToOrganizationTests.kt
Labels: platform

#13801 Replace react-uswds local story copies with direct reference
  frontend-react/.storybook/UtilizedUSWDSComponents/Alert.stories.ignore.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/Banner.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/Breadcrumb.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/Button.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/ButtonGroup.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/Card.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/Datepicker.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/FileInput.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/ProcessList.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/Select.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/SideNav.stories.tsx
  frontend-react/.storybook/UtilizedUSWDSComponents/Tooltip.stories.tsx
  frontend-react/.storybook/main.ts
Labels: frontend

#13792 13480 - Added conditional to receivingOrgSvcStatus
  prime-router/src/main/kotlin/history/azure/HistoryDatabaseAccess.kt
Labels: platform

#13781 Add STLTs to the list on the RS website
  frontend-react/src/content/about/our-network.mdx
Labels: design, frontend, trialfrontend03

#13591 10496: github workflow to sync schemas from staging to production
  .github/workflows/sync-translation-schemas.yml
Labels: platform

#13592 10501: validate schemas during ci
  .github/actions/build-backend/action.yml
  .github/workflows/build_hub.yml
  prime-router/src/main/kotlin/cli/ValidateTranslationSchemaCommand.kt
  prime-router/src/test/kotlin/cli/ValidateTranslationSchemaCommandTests.kt
Labels: platform

#13844 BUG: Storybook broken with current addons
  frontend-react/.storybook/main.ts
  frontend-react/.storybook/preview.tsx
  frontend-react/package.json
  frontend-react/src/layouts/Main/MainLayout.stories.tsx
  frontend-react/yarn.lock
Labels: frontend

#13791 Map Clearing Bug
  prime-router/src/test/kotlin/fhirengine/translation/HL7toFhirTranslatorTests.kt
Labels: platform

#13837 13578 - Fix to Daily Data API to include ELIMS files
  prime-router/src/main/kotlin/history/azure/DatabaseDeliveryAccess.kt
  prime-router/src/test/kotlin/history/azure/HistoryDatabaseAccessTests.kt
Labels: experience

#13797 Daily Data: Filename + Reportid Search
  frontend-react/e2e/spec/daily-data-page.spec.ts
  frontend-react/package.json
  frontend-react/src/components/DataDashboard/DataDashboardTable/DataDashboardTableFilters/DataDashboardTableFilters.tsx
  frontend-react/src/components/Table/Table.test.tsx
  frontend-react/src/components/Table/TableFilterSearch.tsx
  frontend-react/src/components/Table/TableFilterStatus.tsx
  frontend-react/src/components/Table/TableFilters.module.scss
  frontend-react/src/components/Table/TableFilters.tsx
  frontend-react/src/components/Table/TestTable.tsx
  frontend-react/src/components/Title.tsx
  frontend-react/src/hooks/UseAdminSafeOrganizationName.ts
  frontend-react/src/hooks/UsePagination.test.tsx
  frontend-react/src/hooks/UsePagination.ts
  frontend-react/src/hooks/network/History/DeliveryHooks.ts
  frontend-react/src/pages/deliveries/Deliveries.tsx
  frontend-react/src/pages/deliveries/daily-data/DailyData.test.tsx
  frontend-react/src/pages/deliveries/daily-data/DailyData.tsx
  frontend-react/src/styles/_components.scss
  frontend-react/yarn.lock
Labels: experience, trialfrontend01
