Repository CDCgov/prime-reportstream, pull requests merged in 2024-08, with the labels that each got.

#15422 Bug: add event props that were missed in first pass
  prime-router/src/main/kotlin/fhirengine/engine/FHIRDestinationFilter.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRDestinationFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirDestinationFilterTests.kt
Labels: platform

#15370 Pin org.apache.commons:commons-compress@1.26.0 in /submissions
  submissions/build.gradle.kts
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/TelemetryService.kt
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/config/AzureConfig.kt
  submissions/src/test/kotlin/SubmissionControllerIntegrationTest.kt
  submissions/src/test/kotlin/SubmissionControllerTest.kt
Labels: security, dependencies, java

#15371 Pin org.xmlunit:xmlunit-core@2.10.0 in /submissions
  submissions/build.gradle.kts
Labels: security, dependencies, java

#15367 Bump azure.spring:spring-cloud-azure-starter-storage from 5.13.0 5.14.0 in /submissions
  submissions/build.gradle.kts
Labels: security, dependencies, java

#15429 15423 - Daily Data e2e bug fixes and password change documentation.
  frontend-react/README.md
  frontend-react/docs/standard-operating-procedures/e2e-frontend-guidance.md
  frontend-react/e2e/helpers/utils.ts
  frontend-react/e2e/pages/daily-data-details.ts
  frontend-react/e2e/pages/daily-data.ts
  frontend-react/e2e/spec/all/daily-data-details-page.spec.ts
  frontend-react/e2e/spec/all/daily-data-page.spec.ts
Labels: frontend, experience

#15447 title casing + receiver ID fix
  frontend-react/e2e/spec/all/last-mile-failures-page.spec.ts
  frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx
  frontend-react/src/hooks/api/UseCreateResend/UseCreateResend.ts
  frontend-react/src/pages/admin/AdminLastMileFailures.tsx
Labels: experience, trialfrontend03

#15234 Clean up the route step
  prime-router/docs/universal-pipeline/route.md
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/fhirengine/azure/FHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIREngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/engine/QueueMessage.kt
  prime-router/src/test/kotlin/azure/BlobAccessTests.kt
  prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRRouterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirDestinationFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirReceiverFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirRouterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/DefaultFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/GetFilterTests.kt
  prime-router/src/test/kotlin/history/SubmissionHistoryTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionFunctionIntegrationTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionFunctionTests.kt
Labels: platform

#15449 add release notes for June 2024
  frontend-react/src/content/about/release-notes.mdx
Labels: experience, trialfrontend02

#15133 Platform/13925/singleton http client
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/cli/tests/AuthTests.kt
  prime-router/src/main/kotlin/common/HttpClientUtils.kt
  prime-router/src/test/kotlin/common/HttpClientUtilsTests.kt
Labels: platform

#15488 Bug: add receiver and bundle digest to item routed
  prime-router/src/main/kotlin/fhirengine/engine/FHIRDestinationFilter.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRDestinationFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirDestinationFilterTests.kt
Labels: platform

#15522 Revert "Platform/13925/singleton http client"
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/cli/tests/AuthTests.kt
  prime-router/src/main/kotlin/common/HttpClientUtils.kt
  prime-router/src/test/kotlin/common/HttpClientUtilsTests.kt
Labels: platform

#15506 updated roadmap
  frontend-react/e2e/helpers/external-links.ts
  frontend-react/e2e/spec/all/roadmap.spec.ts
  frontend-react/src/content/about/roadmap.mdx
Labels: experience, trialfrontend03

#15489 Resolve open backend dependabots
  prime-router/build.gradle.kts
  shared/build.gradle.kts
  submissions/build.gradle.kts
Labels: platform

#15531 Disable sending events except for local environments
  prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventBuilder.kt
Labels: platform

#15425 15397 valueset loading fix
  prime-router/src/main/kotlin/fhirengine/engine/LookupTableValueSet.kt
  prime-router/src/test/kotlin/fhirengine/engine/LookupTableValueSetTests.kt
Labels: platform

#15375 Pin org.apache.commons:commons-compress@1.26.2 in /shared
  shared/build.gradle.kts
Labels: security, dependencies, java

#15440 IL UP Migration Validate Test Data
  prime-router/settings/STLTs/IL/il-phd.yml
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/STLTs/IL/IL-receiver-transform.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_IL_20240802-0001.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_IL_20240802-0001.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: Wyoming

#15547 fix circular dependency
  frontend-react/e2e/helpers/utils.ts
  frontend-react/e2e/pages/daily-data.ts
Labels: experience

#15571 added receiving and sending e2e
  frontend-react/e2e/pages/getting-started/receiving-data.ts
  frontend-react/e2e/pages/getting-started/sending-data.ts
  frontend-react/e2e/spec/all/about-page.spec.ts
  frontend-react/e2e/spec/all/getting-started/receiving-data.spec.ts
  frontend-react/e2e/spec/all/getting-started/sending-data.spec.ts
Labels: experience

#15412 Refactor condition mapping lookups into service-like class
  prime-router/src/main/kotlin/ActionMessages.kt
  prime-router/src/main/kotlin/azure/ConditionMapper.kt
  prime-router/src/main/kotlin/azure/observability/event/TestSummary.kt
  prime-router/src/main/kotlin/cli/LookupTableCommands.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/main/kotlin/metadata/Constants.kt
  prime-router/src/test/kotlin/azure/observability/bundleDigest/FhirPathBundleDigestExtractorStrategyTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirReceiverFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/utils/FHIRBundleHelpersTests.kt
Labels: platform

#15431 15169: append fhir transform action
  prime-router/metadata/json_schema/fhir/fhir-to-fhir-transform.json
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirTransformer.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/fhirTransform/FhirTransformSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirTransformerTests.kt
  prime-router/src/test/resources/fhir_sender_transforms/convert-all-obs-to-note.yml
  prime-router/src/test/resources/fhir_sender_transforms/obs-to-note.yml
Labels: platform

#15613 Platform/13199/fhir function dynamic message routing REDUX
  prime-router/src/main/kotlin/SubmissionReceiver.kt
  prime-router/src/main/kotlin/fhirengine/azure/FHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIREngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/QueueMessage.kt
  prime-router/src/test/kotlin/SubmissionReceiverTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRDestinationFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRTranslatorIntegrationTests.kt
Labels: platform

#15611 15211 - daily data user flow smoke tests
  frontend-react/docs/standard-operating-procedures/e2e-frontend-guidance.md
  frontend-react/e2e/helpers/utils.ts
  frontend-react/e2e/mocks/deliveries.ts
  frontend-react/e2e/pages/daily-data.ts
  frontend-react/e2e/pages/report-details.ts
  frontend-react/e2e/spec/all/daily-data-page-user-flow.spec.ts
  frontend-react/e2e/spec/all/daily-data-page.spec.ts
Labels: frontend, experience

#15008 14765 add auth design document
  .environment/gitleaks/gitleaks-config.toml
  prime-router/docs/design/design/auth/auth-design.md
  prime-router/docs/design/design/auth/authMicroservice.png
  prime-router/docs/design/design/auth/authMicroservice.puml
  prime-router/docs/design/design/auth/clientCredentialsFlow.png
  prime-router/docs/design/design/auth/combo.png
  prime-router/docs/design/design/auth/combo.puml
  prime-router/docs/design/design/auth/reverseProxyMicroservice.png
  prime-router/docs/design/design/auth/reverseProxyMicroservice.puml
  prime-router/docs/design/design/auth/sharedCodeAuth.png
  prime-router/docs/design/design/auth/sharedCodeAuth.puml
Labels: platform

#15650 Shard timeout increase in frontend_ci.yml
  .github/workflows/frontend_ci.yml
Labels: DevOps, reportstream

#15661 15523 - added to the join to help speed up the query.
  prime-router/src/main/kotlin/history/db/DeliveryHistoryDatabaseAccess.kt
Labels: frontend, experience

#15658 Platform/david navapbc/13925/singleton http client/redux
  prime-router/src/main/kotlin/cli/tests/AuthTests.kt
  prime-router/src/main/kotlin/common/HttpClientUtils.kt
Labels: platform

#15712 Experience/15212/submission history user flow
  frontend-react/e2e/helpers/utils.ts
  frontend-react/e2e/pages/authenticated/submission-history.ts
  frontend-react/e2e/pages/authenticated/submissions-details.ts
  frontend-react/e2e/spec/all/authenticated/daily-data-page-user-flow.spec.ts
  frontend-react/e2e/spec/all/authenticated/submission-history-page-user-flow.spec.ts
  frontend-react/e2e/spec/all/authenticated/submission-history-page.spec.ts
  frontend-react/e2e/spec/all/authenticated/submissions-details-page.spec.ts
Labels: frontend, experience

#15674 Enhance integration tests w/ lineage and report metadata checks
  prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiverFilter.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRDestinationFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRTranslatorIntegrationTests.kt
Labels: platform

#15711 Create E2E tests for the API Getting Started, documentation pages
  frontend-react/e2e/helpers/internal-links.ts
  frontend-react/e2e/pages/public/developer-resources/api/documentation/index.ts
  frontend-react/e2e/pages/public/developer-resources/api/documentation/responses-from-reportstream.ts
  frontend-react/e2e/pages/public/developer-resources/api/documentation/sample-payloads-and-output.ts
  frontend-react/e2e/pages/public/developer-resources/api/getting-started.ts
  frontend-react/e2e/spec/all/public/developer-resources/api/documentation/index.spec.ts
  frontend-react/e2e/spec/all/public/developer-resources/api/documentation/responses-from-reportstream.spec.ts
  frontend-react/e2e/spec/all/public/developer-resources/api/documentation/sample-payloads-and-output.spec.ts
  frontend-react/e2e/spec/all/public/developer-resources/api/getting-started.spec.ts
Labels: frontend

#15710 Create E2E tests for the Release Notes and Case Studies pages
  frontend-react/e2e/pages/public/about/case-studies.ts
  frontend-react/e2e/pages/public/about/release-notes.ts
  frontend-react/e2e/spec/all/public/about/case-studies.spec.ts
  frontend-react/e2e/spec/all/public/about/release-notes.spec.ts
Labels: frontend

#15709 Create E2E tests for api page
  frontend-react/e2e/pages/public/developer-resources/api/api.ts
  frontend-react/e2e/pages/public/developer-resources/resources.ts
  frontend-react/e2e/spec/all/public/developer-resources/api/api.spec.ts
  frontend-react/e2e/spec/all/public/developer-resources/resources-page.spec.ts
Labels: frontend

#15730 Fix E2E test Filedownload issue
  frontend-react/e2e/helpers/utils.ts
  frontend-react/e2e/spec/chromium-only/authenticated/daily-data-page-user-flow.spec.ts
  frontend-react/e2e/spec/chromium-only/public-pages-link-check.spec.ts
Labels: experience
