Repository CDCgov/prime-reportstream, pull requests merged in 2024-02, with the labels that each got.

#13164 Remove lodash.pick per/method use
  frontend-react/package.json
  frontend-react/src/hooks/UseFileHandler.ts
  frontend-react/yarn.lock
Labels: security, dependencies, javascript

#13219 Remove frontend dummy Github Action #12288
  .github/actions/build-vars/action.yml
  .github/workflows/build_frontend.yaml
  .github/workflows/build_frontend_dummy.yaml
Labels: enhancement

#13222 Bump tocbot from 4.21.0 to 4.25.0 in /frontend-react
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: security, dependencies, javascript

#13018 Platform/jessica/12816 original message passthrough
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/SettingsProvider.kt
  prime-router/src/main/kotlin/SubmissionReceiver.kt
  prime-router/src/main/kotlin/cli/tests/BasicTests.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/fhirengine/azure/FHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIREngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/engine/QueueMessage.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirRouterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/testIntegration/resources/settings/organizations.yml
Labels: pipeline, platform

#13174 platform/jimfuqian/12004 Bug fix prime CLI diff with option hl7-diff-output give false positive
  prime-router/src/main/kotlin/cli/helpers/HL7DiffHelper.kt
  prime-router/src/test/kotlin/cli/helpers/HL7DiffHelperTests.kt
Labels: platform

#13248 Move swap to /mnt
  .github/workflows/build_hub.yml
  .github/workflows/sonarcloud.yml
Labels: DevOps

#13286 Bump codeql to 2.16.1
  .github/workflows/codeql.yml
  .github/workflows/sonarcloud.yml
Labels: security, dependencies, github_actions

#13287 13825: quiet JWT exception logging
  prime-router/src/main/kotlin/tokens/OktaAuthentication.kt
Labels: bug, platform

#13271 Update Develop Resources, Referral Guide, and Our Network page
  frontend-react/src/content/about/our-network.mdx
  frontend-react/src/content/developer-resources/index-page.mdx
  frontend-react/src/content/managing-your-connection/refer-healthcare-organizations.mdx
Labels: design, frontend

#13234 Add clarification to app insights local dev setup guide
  prime-router/docs/observability/local-dev-setup.md
Labels: platform

#13218 Improve build-frontend log readability
  .github/actions/build-frontend/action.yml
Labels: DevOps, experience

#13314 Frontend e2e tests need a place to store un/pw credentials
  .github/actions/build-frontend/action.yml
  .github/workflows/build_frontend.yaml
  .github/workflows/release_to_azure.yml
  .github/workflows/release_to_github.yml
  .github/workflows/release_trial_frontend.yml
Labels: enhancement

#13192 12774 - Daily data API updates
  prime-router/docs/api/waters-delivery.yml
  prime-router/src/main/kotlin/history/azure/DeliveryFacade.kt
  prime-router/src/main/kotlin/history/azure/DeliveryFunction.kt
  prime-router/src/main/kotlin/history/azure/HistoryDatabaseAccess.kt
  prime-router/src/main/kotlin/history/azure/ReportFileFunction.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFacadeTests.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFunctionTests.kt
Labels: backend, experience

#13249 13160: create report route event
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/observability/event/AzureEventService.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportRouteEvent.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIREngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/main/kotlin/history/db/ReportGraph.kt
  prime-router/src/main/kotlin/report/ReportService.kt
  prime-router/src/test/kotlin/azure/observability/event/AzureEventServiceTest.kt
  prime-router/src/test/kotlin/azure/observability/event/InMemoryAzureEventService.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirRouterTests.kt
  prime-router/src/test/kotlin/history/db/ReportGraphTest.kt
  prime-router/src/test/kotlin/report/ReportServiceTests.kt
Labels: platform, observability

#13316 14415: clean up exception logging for hl7 parsing
  prime-router/src/main/kotlin/fhirengine/utils/HL7Reader.kt
Labels: platform

#13194 Add testing for idle timeout
  frontend-react/e2e/fixtures/idletimeout.spec.ts
  frontend-react/e2e/helpers/auth.setup.ts
  frontend-react/package.json
  frontend-react/playwright.config.ts
  frontend-react/scripts/generateBrowserslistRegex.ts
  frontend-react/src/App.test.tsx
  frontend-react/src/App.tsx
  frontend-react/src/browsers.json
  frontend-react/src/config/index.ts
  frontend-react/src/contexts/AuthorizedFetch/index.tsx
  frontend-react/src/contexts/FeatureFlag/index.test.tsx
  frontend-react/src/contexts/FeatureFlag/index.tsx
  frontend-react/src/contexts/Toast/index.test.tsx
  frontend-react/src/contexts/Toast/index.tsx
  frontend-react/src/setupTests.ts
  frontend-react/src/unsupportedBrowser.ts
  frontend-react/src/utils/BrowserUtils.ts
  frontend-react/src/utils/CustomRenderUtils.tsx
  frontend-react/src/utils/SupportedBrowsers.ts
Labels: experience

#13352 remove pinning as no longer needed
  prime-router/build.gradle.kts
Labels: dependencies, java

#13375 Combined dependabot upgrade
  prime-router/build.gradle.kts
Labels: platform

#12897 12336 - daily data e2e
  .github/actions/build-frontend/action.yml
  frontend-react/.gitignore
  frontend-react/e2e/fixtures/organization-settings-page.spec.ts
  frontend-react/e2e/helpers/auth.setup.ts
  frontend-react/e2e/helpers/external-links.ts
  frontend-react/e2e/helpers/rs-test.ts
  frontend-react/e2e/helpers/utils.ts
  frontend-react/e2e/pages/getting-started.ts
  frontend-react/e2e/pages/header.ts
  frontend-react/e2e/pages/managing-your-connection.ts
  frontend-react/e2e/pages/our-network.ts
  frontend-react/e2e/pages/security.ts
  frontend-react/e2e/pages/support.ts
  frontend-react/e2e/spec/daily-data-page.spec.ts
  frontend-react/e2e/spec/homepage.spec.ts
  frontend-react/e2e/spec/idletimeout.spec.ts
  frontend-react/e2e/spec/organization-settings-page.spec.ts
  frontend-react/e2e/spec/our-network-page.spec.ts
  frontend-react/e2e/spec/resources-page.spec.ts
  frontend-react/e2e/spec/support-page.spec.ts
  frontend-react/package.json
  frontend-react/playwright.config.ts
  frontend-react/src/components/Admin/OrgsTable.tsx
  frontend-react/src/components/Table/Pagination.tsx
  frontend-react/src/components/Table/Table.tsx
  frontend-react/src/components/Table/__snapshots__/Pagination.test.tsx.snap
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/pages/deliveries/daily-data/ServicesDropdown.tsx
  frontend-react/vite.config.ts
Labels: frontend, experience

#13346 10492: translation schema validation
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/translation/TranslationSchemaManager.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/ConfigSchemaProcessor.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/Exceptions.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirTransformer.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReader.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/converter/ConverterSchemaReader.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/converter/HL7ConverterSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/fhirTransform/FhirTransformSchema.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/fhirTransform/FhirTransformSchemaReader.kt
  prime-router/src/test/kotlin/azure/BlobAccessTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/LookupTableValueSetTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/TranslationSchemaManagerTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirTransformerTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReaderTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/converter/HL7ConverterSchemaTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/fhirTransform/FhirTransformSchemaTests.kt
  prime-router/src/test/resources/fhirengine/translation/FHIR_to_FHIR/input.fhir
  prime-router/src/test/resources/fhirengine/translation/FHIR_to_FHIR/output.fhir
  prime-router/src/test/resources/fhirengine/translation/FHIR_to_FHIR/simple-transform.yml
  prime-router/src/test/resources/fhirengine/translation/FHIR_to_HL7/input.fhir
  prime-router/src/test/resources/fhirengine/translation/FHIR_to_HL7/output.hl7
  prime-router/src/test/resources/fhirengine/translation/FHIR_to_HL7/sender-transform.yml
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
Labels: platform

#13387 13385 - reverted to useOrganizationSettings() instead of useOrganizationSettings__
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/yarn.lock
Labels: frontend, experience

#13391 13166 - Content Updates to the Support Page
  frontend-react/src/content/support/index.mdx
Labels: frontend, experience, trialfrontend01

#13379 10493: create validate schemas command
  prime-router/src/main/kotlin/cli/ValidateTranslationSchemaCommand.kt
  prime-router/src/main/kotlin/cli/main.kt
  prime-router/src/main/kotlin/fhirengine/translation/TranslationSchemaManager.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/ConfigSchemaProcessor.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirTransformer.kt
  prime-router/src/test/kotlin/cli/ValidateTranslationSchemaCommandTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/TranslationSchemaManagerTests.kt
  prime-router/src/test/resources/fhirengine/translation/FHIR_to_HL7/input.fhir
  prime-router/src/test/resources/fhirengine/translation/FHIR_to_HL7/output-invalid.hl7
  prime-router/src/test/resources/fhirengine/translation/FHIR_to_HL7/output.hl7
  prime-router/src/test/resources/fhirengine/translation/FHIR_to_HL7/sender-transform.yml
Labels: platform

#13396 bump socks from 2.7.1 to 2.8.0 in /frontend-react
  frontend-react/yarn.lock
Labels: security, dependencies, javascript

#13397 12667 - Change one word on "Managing your connection"
  frontend-react/src/content/managing-your-connection/index.mdx
Labels: frontend, experience

#13431 Platform/arnej/13232/passthrough cleanup
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/kotlin/azure/observability/context/MDCUtils.kt
  prime-router/src/main/kotlin/cli/tests/BasicTests.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/test/kotlin/ReportTests.kt
  prime-router/src/test/kotlin/azure/observability/context/MDCUtilsTest.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/testIntegration/kotlin/transport/AS2TransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/TransportIntegrationTests.kt
Labels: platform

#13468 Pin org.apache.commons:commons-compress to 1.26.0 in /prime-router
  prime-router/build.gradle.kts
Labels: security, dependencies, java

#13470 13136: add human readable condition display to azure events
  prime-router/src/main/kotlin/azure/observability/event/AzureEventUtils.kt
  prime-router/src/main/kotlin/azure/observability/event/ConditionSummary.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportAcceptedEvent.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportRouteEvent.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/test/kotlin/azure/observability/event/AzureEventUtilsTest.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirRouterTests.kt
Labels: platform, observability

#13482 12875 - Remove more "Shared Secret" content from website
  frontend-react/src/content/developer-resources/reportstream-api/getting-started/GettingStarted.mdx
  frontend-react/src/content/site.json
Labels: frontend, experience

#13481 Split out FHIR function integration tests and fix BlobAccess mocking
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionTests.kt
  prime-router/src/test/resources/fhirengine/engine/valid_data_multiple_targets.fhir
Labels: platform

#13342 Jessica/13256 include root exception
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/FhirPathUtilsTests.kt
Labels: pipeline, platform

#13473 Bump codeql from v2.x to v3
  .github/workflows/codeql.yml
  .github/workflows/sonarcloud.yml
Labels: DevOps

#13467 10491: sync schemas workflow
  .github/actions/build-backend/action.yml
  prime-router/build.gradle.kts
  prime-router/docker-compose.yml
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/main/kotlin/azure/ValidateSchemasFunctions.kt
  prime-router/src/main/kotlin/cli/SyncTranslationSchemaCommand.kt
  prime-router/src/main/kotlin/cli/tests/SyncTranslationSchemasTest.kt
  prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
  prime-router/src/main/kotlin/fhirengine/translation/TranslationSchemaManager.kt
  prime-router/src/test/kotlin/azure/BlobAccessTests.kt
  prime-router/src/test/kotlin/azure/ValidateSchemasFunctionsTest.kt
  prime-router/src/test/kotlin/cli/SyncTranslationSchemaCommandTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/SyncSchemaE2ETests.kt
  prime-router/src/test/kotlin/fhirengine/translation/TranslationSchemaManagerTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReaderTests.kt
  prime-router/src/test/resources/fhirengine/translation/FHIR_to_FHIR/alternate/input.fhir
  prime-router/src/test/resources/fhirengine/translation/FHIR_to_FHIR/alternate/output.fhir
  prime-router/src/test/resources/fhirengine/translation/FHIR_to_FHIR/alternate/simple-transform.yml
Labels: platform

#13512 EnricoMi/publish-unit-test-result-action composite action deprecation
  .github/actions/build-backend/action.yml
Labels: dependencies, github_actions, deprecated

#13514 Bump setup-java from V3 to 4.0.0 (hash)
  .github/workflows/sonarcloud.yml
Labels: dependencies, github_actions

#13367 Replace momentjs with modern equivalent
  frontend-react/.eslintrc.cjs
  frontend-react/package.json
  frontend-react/src/components/Admin/AdminReceiverDashboard.tsx
  frontend-react/src/components/DataDashboard/ReportDetails/ReportDetailsSummary.test.tsx
  frontend-react/src/pages/deliveries/daily-data/TableReportsData.tsx
  frontend-react/src/pages/deliveries/details/DeliveryInfo.tsx
  frontend-react/src/utils/DateTimeUtils.test.ts
  frontend-react/src/utils/DateTimeUtils.ts
  frontend-react/yarn.lock
Labels: frontend

#13533 prepare merge queue functionality
  .github/workflows/build_frontend.yaml
  .github/workflows/build_hub.yml
Labels: DevOps
