Repository CDCgov/prime-reportstream, pull requests merged in 2024-04, with the labels that each got.

#13886 BUG: No way to control date range for TableFilters component
  frontend-react/package.json
  frontend-react/src/components/DataDashboard/DataDashboardTable/DataDashboardTable.test.tsx
  frontend-react/src/components/DataDashboard/DataDashboardTable/DataDashboardTableFilters/DataDashboardTableFilters.test.tsx
  frontend-react/src/components/DataDashboard/DataDashboardTable/DataDashboardTableFilters/DataDashboardTableFilters.tsx
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilitiesProvidersTable.test.tsx
  frontend-react/src/components/Table/Table.test.tsx
  frontend-react/src/components/Table/TableFilters.tsx
  frontend-react/src/components/Table/TestTable.tsx
  frontend-react/src/globalSetup.ts
  frontend-react/src/hooks/UsePagination.test.tsx
  frontend-react/src/hooks/filters/UseDateRange.ts
  frontend-react/src/hooks/filters/filters.fixtures.ts
  frontend-react/src/hooks/filters/mocks/MockCursorManager.ts
  frontend-react/src/pages/deliveries/daily-data/DailyData.test.tsx
  frontend-react/vite.config.ts
Labels: frontend

#13900 Revert "13578 - Fix to Daily Data API to include ELIMS files"
  prime-router/src/main/kotlin/history/azure/DatabaseDeliveryAccess.kt
  prime-router/src/test/kotlin/history/azure/HistoryDatabaseAccessTests.kt
Labels: experience

#13867 11129 - March release notes
  frontend-react/src/content/about/release-notes.mdx
Labels: frontend, experience, trialfrontend02

#13903 South Carolina Onboarding Go Live
  frontend-react/src/content/about/our-network.mdx
  frontend-react/src/content/live.json
  frontend-react/src/content/usa_w_territories.svg
Labels: onboarding-ops, South Carolina

#13866 Platform/jimfuqian/11928 refactor code to remove old dependencies resurrect
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/azure/CheckFunction.kt
  prime-router/src/main/kotlin/azure/EmailEngineFunction.kt
  prime-router/src/main/kotlin/cli/CommandUtilities.kt
  prime-router/src/main/kotlin/cli/LookupTableCommands.kt
  prime-router/src/main/kotlin/cli/OktaCommands.kt
  prime-router/src/main/kotlin/cli/SenderFilesCommand.kt
  prime-router/src/main/kotlin/cli/SettingCommands.kt
  prime-router/src/main/kotlin/cli/SettingsUtilities.kt
  prime-router/src/main/kotlin/cli/tests/AuthTests.kt
  prime-router/src/main/kotlin/cli/tests/HistoryApiTest.kt
  prime-router/src/main/kotlin/cli/tests/LivdApiTest.kt
  prime-router/src/main/kotlin/cli/tests/SettingsTest.kt
  prime-router/src/main/kotlin/cli/tests/SftpcheckTest.kt
  prime-router/src/main/kotlin/common/HttpClientUtils.kt
  prime-router/src/main/kotlin/credentials/HashicorpVaultCredentialService.kt
  prime-router/src/main/kotlin/transport/GAENTransport.kt
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/main/kotlin/transport/TokenInfo.kt
  prime-router/src/test/kotlin/cli/ApiMockEngine.kt
  prime-router/src/test/kotlin/cli/LookupTableCommandsTest.kt
  prime-router/src/test/kotlin/credentials/HashicorpVaultCredentialServiceTests.kt
  prime-router/src/test/kotlin/tokens/JwkTests.kt
  prime-router/src/test/kotlin/tokens/Server2ServerAuthenticationTests.kt
  prime-router/src/testIntegration/kotlin/transport/ApiMockEngineForIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/GAENTransportIntegrationTests.kt
Labels: platform

#13927 Frontend CLI tool
  .environment/frontend/run-frontend.sh
  .github/actions/build-frontend/action.yml
  .github/workflows/sonarcloud.yml
  frontend-react/.husky/pre-commit
  frontend-react/lint-staged.config.js
  frontend-react/package.json
  frontend-react/playwright.config.ts
  frontend-react/scripts/cli-entrypoint.js
  frontend-react/scripts/cli/cli.ts
  frontend-react/scripts/cli/commands/browserslist.ts
  frontend-react/scripts/cli/commands/build.ts
  frontend-react/scripts/cli/commands/dev.ts
  frontend-react/scripts/cli/commands/e2e.ts
  frontend-react/scripts/cli/commands/git.ts
  frontend-react/scripts/cli/commands/lint.ts
  frontend-react/scripts/cli/commands/prepare.ts
  frontend-react/scripts/cli/commands/preview.ts
  frontend-react/scripts/cli/commands/test.ts
  frontend-react/scripts/cli/generateBrowserslistRegex.ts
  frontend-react/scripts/cli/utils.ts
  frontend-react/scripts/postinstall.sh
  frontend-react/src/browsers.json
  frontend-react/tsconfig.json
  frontend-react/vite.config.ts
  frontend-react/yarn.lock
Labels: frontend, tech-debt

#13969 Experience/13622/e2e daily data report details
  frontend-react/README.md
  frontend-react/e2e/helpers/utils.ts
  frontend-react/e2e/mocks/delivery.ts
  frontend-react/e2e/mocks/facilities.ts
  frontend-react/e2e/mocks/historyReport.ts
  frontend-react/e2e/pages/daily-data.ts
  frontend-react/e2e/pages/report-details.ts
  frontend-react/e2e/pages/submission-history.ts
  frontend-react/e2e/spec/daily-data-details-page.spec.ts
  frontend-react/e2e/spec/submission-history-page.spec.ts
Labels: frontend, experience

#13991 BUG: Frontend build step using incorrect backend url
  frontend-react/scripts/cli/commands/e2e.ts
  frontend-react/scripts/cli/utils.ts
  frontend-react/yarn.lock
Labels: bug, frontend

#13864 Experience/13620/submissions filename
  frontend-react/e2e/mocks/submissions.ts
  frontend-react/e2e/pages/submission-history.ts
  frontend-react/e2e/spec/submission-history-page.spec.ts
  frontend-react/src/pages/deliveries/Deliveries.tsx
  frontend-react/src/pages/deliveries/daily-data/DailyData.test.tsx
  frontend-react/src/pages/deliveries/daily-data/DailyData.tsx
  frontend-react/src/pages/submissions/SubmissionTable.test.tsx
  frontend-react/src/pages/submissions/SubmissionTable.tsx
  frontend-react/src/resources/SubmissionsResource.ts
  prime-router/docs/api/waters-submissions.yml
  prime-router/src/main/kotlin/cli/tests/HistoryApiTest.kt
  prime-router/src/main/kotlin/history/SubmissionHistory.kt
  prime-router/src/test/kotlin/history/SubmissionHistoryTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionFunctionTests.kt
Labels: experience

#13984 Resolve open backend dependabots
  prime-router/build.gradle.kts
Labels: security, dependencies, java, platform

#13994 Platform/13269/log4j formatting error
  prime-router/build.gradle.kts
  prime-router/src/main/resources/jsonTemplate.json
Labels: platform

#13932 Apply the latest patches between image releases
  prime-router/Dockerfile.build
Labels: security

#14017 experience/13606/daily-data-for-all
  frontend-react/public/assets/img/DailyData.png
  frontend-react/public/assets/img/DataDashboard.png
  frontend-react/src/components/header/ReportStreamHeader.test.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/content/managing-your-connection/index.mdx
  frontend-react/src/hooks/UseOrganizationSettings.ts
  frontend-react/src/pages/data-dashboard/DataDashboard.tsx
  frontend-react/src/pages/deliveries/Deliveries.tsx
Labels: experience, trialfrontend03

#14015 Bump jacoco from 0.8.10 to 0.8.12
  prime-router/build.gradle.kts
Labels: dependencies, java, platform

#13975 Use "docker compose" instead of deprecated "docker-compose" with gradle
  prime-router/build.gradle.kts
Labels: security, dependencies, java

#14061 Update priority dependencies marked security
  prime-router/build.gradle.kts
Labels: security, dependencies, java, platform

#7276 Upgrade Terraform and AzureRM Provider
  .github/workflows/alert_terraform_changes.yml
  .github/workflows/deploy_terraform.yml
  .github/workflows/destroy_demo_environment.yml
  .github/workflows/release_to_azure.yml
  .github/workflows/validate_terraform.yml
  operations/README.md
  operations/app/terraform/modules/app_service_plan/main.tf
  operations/app/terraform/modules/app_service_plan/~outputs.tf
  operations/app/terraform/modules/application_insights/alert_availability.tf
  operations/app/terraform/modules/common/private_endpoint/main.tf
  operations/app/terraform/modules/common/sftp/main.tf
  operations/app/terraform/modules/data_factory/dataset.tf
  operations/app/terraform/modules/data_factory/linked_service.tf
  operations/app/terraform/modules/data_factory/pipeline.tf
  operations/app/terraform/modules/data_factory/runtime.tf
  operations/app/terraform/modules/data_factory/trigger.tf
  operations/app/terraform/modules/front_door/main.tf
  operations/app/terraform/modules/function_app/autoscale.tf
  operations/app/terraform/modules/log_analytics_workspace/alert_rules.tf
  operations/app/terraform/modules/log_analytics_workspace/main.tf
  operations/app/terraform/modules/metabase/main.tf
  operations/app/terraform/modules/nat_gateway/main.tf
  operations/app/terraform/modules/sftp/storage.tf
  operations/app/terraform/modules/sftp_container/main.tf
  operations/app/terraform/modules/storage/candidate_slot.tf
  operations/app/terraform/modules/storage/main.tf
  operations/app/terraform/modules/storage/trial_frontends.tf
  operations/app/terraform/vars/demo/azure.tf
  operations/app/terraform/vars/prod/azure.tf
  operations/app/terraform/vars/staging/azure.tf
  operations/app/terraform/vars/test/azure.tf
  operations/docker-compose.yml
Labels: DevOps, enhancement, terraform

#14083 Experience/13540/daily data cleanup
  frontend-react/src/components/Table/Table.test.tsx
  frontend-react/src/components/Table/TableFilterSearch.tsx
  frontend-react/src/components/Table/TableFilterStatus.tsx
  frontend-react/src/components/Table/TableFilters.tsx
  frontend-react/src/hooks/network/History/DeliveryHooks.ts
  frontend-react/src/pages/deliveries/daily-data/DailyData.tsx
Labels: experience, trialfrontend03

#14091 Update receive step documentation to include more detail
  prime-router/docs/universal-pipeline/receive.md
Labels: platform

#14030 Experience/13578/api elims fix using feature flag
  prime-router/src/main/kotlin/history/azure/DatabaseDeliveryAccess.kt
  prime-router/src/test/kotlin/history/azure/HistoryDatabaseAccessTests.kt
Labels: experience

#14123 Roll back dokka to 1.8.20.
  prime-router/build.gradle.kts
Labels: security, dependencies, java

#14111 doc update to make things easier for the next new colleague
  prime-router/docs/getting-started/README.md
  prime-router/docs/getting-started/img/development_org_sender_settings.png
  prime-router/docs/getting-started/img/postman_example.png
  prime-router/docs/getting-started/img/report_stream_organizations.png
  prime-router/docs/getting-started/postman/README.md
  prime-router/docs/getting-started/postman/ResportStream HL7 Demo (Local).postman_collection.json
Labels: platform

#14143 Bump gradle from 8.3 to 8.7 in /prime-router
  prime-router/Dockerfile.build
  prime-router/docs/docs-deprecated/getting-started/install-gradle.md
  prime-router/gradle/wrapper/gradle-wrapper.properties
Labels: security, java

#13711 Bump kotlin from 1.9.22 to 1.9.23 in /prime-router
  prime-router/gradle.properties
Labels: dependencies, java

#13918 13796: update convert step to integrate validation
  prime-router/build.gradle.kts
  prime-router/metadata/HL7/v251-elr/hl7/segments/ORC/Specimen.yml
  prime-router/src/main/kotlin/ActionLog.kt
  prime-router/src/main/kotlin/ActionMessages.kt
  prime-router/src/main/kotlin/SettingsProvider.kt
  prime-router/src/main/kotlin/common/BaseEngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/ProcessedFHIRItem.kt
  prime-router/src/main/kotlin/fhirengine/translation/HL7toFhirTranslator.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReader.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirBundleUtils.kt
  prime-router/src/main/kotlin/fhirengine/utils/FhirTranscoder.kt
  prime-router/src/main/kotlin/fhirengine/utils/HL7Reader.kt
  prime-router/src/main/kotlin/logging/LogMeasuredTime.kt
  prime-router/src/main/kotlin/validation/IItemValidator.kt
  prime-router/src/main/kotlin/validation/MarsOtcElrValidator.kt
  prime-router/src/main/kotlin/validation/NoopItemValidator.kt
  prime-router/src/main/resources/metadata/hl7_validation/v251/radxmars/coconstraints.xml
  prime-router/src/main/resources/metadata/hl7_validation/v251/radxmars/constraints.xml
  prime-router/src/main/resources/metadata/hl7_validation/v251/radxmars/profile.xml
  prime-router/src/main/resources/metadata/hl7_validation/v251/radxmars/slicings.xml
  prime-router/src/main/resources/metadata/hl7_validation/v251/radxmars/value-set-bindings.xml
  prime-router/src/main/resources/metadata/hl7_validation/v251/radxmars/value-sets.xml
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/ProcessedFHIRItemTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirTransformerTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/FhirBundleUtilsTests.kt
  prime-router/src/test/kotlin/fhirengine/utils/HL7ReaderTests.kt
  prime-router/src/test/kotlin/logging/LogMeasuredTimeTests.kt
  prime-router/src/test/kotlin/validation/MarsOtcElrValidatorTests.kt
  prime-router/src/test/kotlin/validation/MessageValidatorTests.kt
  prime-router/src/test/kotlin/validation/NoopMessageValidatorTests.kt
  prime-router/src/test/resources/fhirengine/smoketest/valid_hl7.hl7
  prime-router/src/test/resources/validation/badProfile/coconstraints.xml
  prime-router/src/test/resources/validation/badProfile/constraints.xml
  prime-router/src/test/resources/validation/badProfile/slicings.xml
  prime-router/src/test/resources/validation/badProfile/value-set-bindings.xml
  prime-router/src/test/resources/validation/badProfile/value-sets.xml
  prime-router/src/test/resources/validation/marsotcelr/sample_1.hl7
  prime-router/src/test/resources/validation/marsotcelr/sample_2.hl7
  prime-router/src/test/resources/validation/sparseProfile/profile.xml
Labels: platform

#14167 Bump xalan from 2.7.2 to 2.7.3 in /prime-router
  prime-router/build.gradle.kts
Labels: security, dependencies, java

#14090 Experience/12974/e2e daily data updates
  frontend-react/e2e/helpers/utils.ts
  frontend-react/e2e/mocks/deliveries.ts
  frontend-react/e2e/pages/daily-data.ts
  frontend-react/e2e/pages/report-details.ts
  frontend-react/e2e/spec/daily-data-details-page.spec.ts
  frontend-react/e2e/spec/daily-data-page.spec.ts
  frontend-react/e2e/spec/last-mile-failures-page.spec.ts
  frontend-react/e2e/spec/organization-settings-page.spec.ts
  frontend-react/e2e/spec/submission-history-page.spec.ts
  frontend-react/src/components/Table/TableFilters.tsx
  frontend-react/yarn.lock
Labels: frontend, experience

#14049 13985: yaml validation doc
  prime-router/build.gradle.kts
  prime-router/docs/design/design/yaml-validation/yaml-cli-task.md
  prime-router/docs/design/design/yaml-validation/yaml-intellij-setup.md
  prime-router/docs/design/design/yaml-validation/yaml-structure-validation.md
  prime-router/docs/design/design/yaml-validation/yaml-value-validation.md
  prime-router/docs/design/proposals/0026-yaml-validation/0026-yaml-validation.md
  prime-router/docs/getting-started/intellij-tips.md
  prime-router/metadata/json_schema/testing/documentation.json
  prime-router/metadata/json_schema/testing/documentation.yml
  prime-router/metadata/json_schema/testing/person.json
  prime-router/src/main/kotlin/common/JacksonMapperUtilities.kt
  prime-router/src/test/kotlin/validation/JsonSchemaValidationTest.kt
  prime-router/src/test/kotlin/validation/ValueValidationTest.kt
  prime-router/src/test/resources/yaml_validation/extra-property.yml
  prime-router/src/test/resources/yaml_validation/missing-property.yml
  prime-router/src/test/resources/yaml_validation/valid-person.yml
Labels: platform

#14020 Fix duplicate auth header
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
Labels: platform

#14237 Experience/12974/e2e daily data updates
  frontend-react/e2e/helpers/auth.setup.ts
  frontend-react/e2e/helpers/utils.ts
  frontend-react/e2e/mocks/deliveries.ts
  frontend-react/e2e/mocks/organizations.ts
  frontend-react/e2e/pages/daily-data.ts
  frontend-react/e2e/pages/organization.ts
  frontend-react/e2e/pages/report-details.ts
  frontend-react/e2e/spec/daily-data-details-page.spec.ts
  frontend-react/e2e/spec/daily-data-page.spec.ts
  frontend-react/e2e/spec/last-mile-failures-page.spec.ts
  frontend-react/e2e/spec/submission-history-page.spec.ts
  frontend-react/playwright.config.ts
Labels: frontend, experience

#14166 Experience/14140/dap fix
  frontend-react/vite.config.ts
Labels: experience, trialfrontend03
