Repository CDCgov/prime-reportstream, pull requests merged in 2024-11, with the labels that each got.

#16339 16148: send reports from the submissions directly to FHIR Convert
  prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventService.kt
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/fhirengine/azure/FHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRDestinationFilter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIREngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiver.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiverFilter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/engine/PrimeRouterQueueMessage.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/azure/FHIRFunctionsTests.kt
  prime-router/src/test/kotlin/azure/observability/event/ReportEventServiceTest.kt
  prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRDestinationFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRTranslatorIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FHIRReceiverTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirDestinationFilterTests.kt
  shared/src/main/kotlin/gov/cdc/prime/reportstream/shared/QueueMessage.kt
  submissions/src/main/resources/application.yml
Labels: platform

#16411 remove dead link
  frontend-react/src/components/FileHandlers/FileHandler.tsx
  frontend-react/src/content/about/security.mdx
  frontend-react/src/content/support/index.mdx
Labels: experience

#16446 Experience/16445-Update-gitleaks-config-allowlist
  .environment/gitleaks/gitleaks-config.toml
  .environment/gitleaks/run-gitleaks.sh
Labels: DevSecOps

#16452 Update frontend dependabot groupings
  .github/dependabot.yml
Labels: frontend, DevSecOps

#16396 Integrating actions-connect-ovpn GitHub Action into project
  .github/actions/connect-ovpn/.gitignore
  .github/actions/connect-ovpn/README.md
  .github/actions/connect-ovpn/action.yml
  .github/actions/connect-ovpn/example.ovpn
  .github/actions/vpn-azure/action.yml
  .github/dependabot.yml
  .github/vpn/test.ovpn
Labels: tech-debt, reportstream, DevSecOps

#16485 Housekeeping connect-ovpn GitHub Action pending files
  .github/actions/connect-ovpn/config.ovpn
  .github/actions/connect-ovpn/example.ovpn
Labels: tech-debt, reportstream, DevSecOps

#16398 Updating all references of 'master' branch to 'main'
  .github/ISSUE_TEMPLATE/up-receiver-migration-set-up-receiver-settings.md
  .github/actions/connect-ovpn/config.ovpn
  .github/actions/connect-ovpn/example.ovpn
  .github/pull_request_template.md
  .github/workflows/build_frontend.yaml
  .github/workflows/build_hub.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency_review.yml
  .github/workflows/deploy_terraform.yml
  .github/workflows/publish_docker.yaml
  .github/workflows/release_chatops_app.yml
  .github/workflows/release_to_azure.yml
  .github/workflows/release_to_github.yml
  .github/workflows/snyk.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/validate_resources.yml
  .github/workflows/validate_terraform.yml
Labels: reportstream, DevSecOps, adoptions

#16497 Update prime-router docs to reference main branch
  .environment/chatops/help.txt
  CONTRIBUTING.md
  DEPLOYMENTS.md
  README.md
  open_practices.md
  operations/README.md
  operations/vpn/README.md
  prime-router/docs/design/proposals/0004-git-flow-and-versioning.md
  prime-router/docs/design/proposals/0019-website-api-payload-structure.md
  prime-router/docs/docs-deprecated/allowlist-gitleaks-false-positives.md
  prime-router/docs/docs-deprecated/how-to-onboard-a-receiver.md
  prime-router/docs/docs-deprecated/how-to-onboard-a-sender.md
  prime-router/docs/docs-deprecated/playbooks/dependabot-updates.md
  prime-router/docs/docs-deprecated/playbooks/platform_restore.md
  prime-router/docs/docs-deprecated/playbooks/shutdown.md
  prime-router/docs/docs-deprecated/workflows/BuildForReactApp.md
  prime-router/docs/docs-deprecated/workflows/Security/StaticCodeAnalysis.md
  prime-router/docs/docs-deprecated/workflows/Terraform.md
  prime-router/docs/docs-deprecated/workflows/branching.md
  prime-router/docs/getting-started/contributing.md
  prime-router/docs/getting-started/standard-operating-procedures/dependabot.md
  prime-router/docs/onboarding-users/receivers.md
  prime-router/docs/onboarding-users/sender-onboarding/senders.md
  prime-router/docs/onboarding-users/transport/rest.md
  prime-router/docs/onboarding-users/transport/soap.md
  prime-router/docs/standard-operating-procedures/Poison-queue/poison-queue-management.md
  prime-router/docs/standard-operating-procedures/adding-conformance-profile.md
  prime-router/docs/standard-operating-procedures/managing-translation-schemas-in-azure.md
  prime-router/docs/standard-operating-procedures/update-observation-mapping-table.md
  prime-router/docs/troubleshooting/README.md
  prime-router/docs/universal-pipeline/convert.md
  prime-router/examples/generate-jwt-python/README.md
  prime-router/src/main/kotlin/azure/TokenFunction.kt
  prime-router/src/main/kotlin/tokens/JtiCache.kt
  templates/azdashboard_readme.md
Labels: platform

#16501 additional fixes for main branch
  .github/actions/build-vars/action.yml
  .github/actions/demo-env/action.yml
  .github/changelog_config.json
  .github/scripts/alert_stale_branches/stale_branch_check.sh
  .github/workflows/frontend_chromatic_main.yml
  .github/workflows/snyk.yml
  .github/workflows/sonarcloud.yml
  prime-router/docs/api/admin.yml
  prime-router/docs/api/api-keys.yml
  prime-router/docs/api/check.yml
  prime-router/docs/api/covid-result-metadata.yml
  prime-router/docs/api/delivery.yml
  prime-router/docs/api/email-engine.yml
  prime-router/docs/api/email-sender.yml
  prime-router/docs/api/messages.yml
  prime-router/docs/api/reports.yml
  prime-router/docs/api/requeue.yml
  prime-router/docs/api/sender-files.yaml
  prime-router/docs/api/settings.yml
  prime-router/docs/api/submissions.yml
  prime-router/docs/api/token.yml
  prime-router/docs/api/validate.yml
  prime-router/docs/api/waters-delivery.yml
  prime-router/docs/api/waters-reports.yml
  prime-router/docs/api/waters-submissions.yml
Labels: platform

#16504 Correcting a networking validation issue on pushing Artifacts to Azure
  .github/actions/connect-ovpn/action.yml
Labels: tech-debt, reportstream, DevSecOps

#16449 Platform/david navapbc/04nov24/dependabot
  auth/build.gradle.kts
  prime-router/build.gradle.kts
  submissions/build.gradle.kts
Labels: platform

#16595 remove usage of downloadjs
  frontend-react/package.json
  frontend-react/src/pages/deliveries/daily-data/ReportLink.tsx
  frontend-react/src/pages/deliveries/daily-data/ReportsUtils.ts
  frontend-react/yarn.lock
Labels: experience, trialfrontend03

#16616 16609 part 2 fix
  prime-router/src/main/kotlin/fhirengine/azure/FHIRFunctions.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
Labels: platform

#16539 Remaining ORM/OML Updates
  prime-router/metadata/HL7/catchall/hl7/segments/ORC/OBRExtension.yml
  prime-router/metadata/HL7/catchall/hl7/segments/ORC/Specimen.yml
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/group/OML_O21_OBSERVATION.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/group/OML_O21_OBSERVATION_REQUEST.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/group/OML_O21_ORDER.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/group/OML_O21_PATIENT.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/group/OML_O21_PATIENT_VISIT.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/group/OML_O21_SPECIMEN.java
  prime-router/src/main/java/fhirengine/translation/hl7/structures/fhirinventory/message/OML_O21.java
  prime-router/src/main/kotlin/fhirengine/utils/HL7Reader.kt
  prime-router/src/main/resources/metadata/hl7_mapping/OML_O21/base/order/observation-request/observation-request-base.yml
  prime-router/src/main/resources/metadata/hl7_mapping/OML_O21/base/order/observation-request/observation-request.yml
  prime-router/src/main/resources/metadata/hl7_mapping/OML_O21/base/order/observation-request/observation/observation.yml
  prime-router/src/main/resources/metadata/hl7_mapping/OML_O21/base/order/observation-request/specimen/specimen.yml
  prime-router/src/main/resources/metadata/hl7_mapping/OML_O21/base/patient/patient.yml
  prime-router/src/main/resources/metadata/hl7_mapping/ORU_R01/base/patient-result/order-observation/order-observation.yml
  prime-router/src/main/resources/metadata/hl7_mapping/ORU_R01/base/patient-result/order-observation/specimen.yml
  prime-router/src/main/resources/metadata/hl7_mapping/resources/ServiceRequest/OBR.yml
  prime-router/src/main/resources/metadata/hl7_mapping/resources/ServiceRequest/OBRExtension.yml
  prime-router/src/main/resources/metadata/hl7_mapping/resources/Specimen/OBR.yml
  prime-router/src/main/resources/metadata/hl7_mapping/resources/Specimen/SPM.yml
  prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/catchall/orcobr/OBRToSpecimenTests.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/catchall/orcobr/ORCOBRToServiceRequestDiagnosticReportTests.kt
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_oml_20240319-001.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_orm_20230809-001-with-enrichment.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_orm_20230809-001.fhir
  prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_oru_20241015-001.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/ei/EI-to-Identifier-Extension.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/omlo21/oml_o21-full.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/omlo21/oml_o21-full.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/oml-obr-to-specimen.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/oml-obr-to-specimen.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/orc_obr-to-servicerequest_diagnosticreport-obr-populated.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/orc_obr-to-servicerequest_diagnosticreport-obr25-not-mapped.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/orc_obr-to-servicerequest_diagnosticreport-obr25-obrext-not-populated.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/orc_obr-to-servicerequest_diagnosticreport-obr25.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/orc_obr-to-servicerequest_diagnosticreport-obr8-not-populated.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/orc_obr-to-servicerequest_diagnosticreport-obr8-populated.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/orc_obr-to-servicerequest_diagnosticreport-orc-obr-populated.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/orc_obr-to-servicerequest_diagnosticreport-orc-populated.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/orm-obr-to-specimen.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/orm-obr-to-specimen.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/oru-obr-to-specimen.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orcobr/oru-obr-to-specimen.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/ormo01/orm_o01-full.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/ormo01/orm_o01-full.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/orur01/oru_r01-full.fhir
Labels: platform

#16550 Platform/bill/16144
  prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventData.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIREngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRTranslatorIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
Labels: platform

#16625 Platform/david navapbc/21nov24/dependabot
  auth/build.gradle.kts
  prime-router/build.gradle.kts
  submissions/build.gradle.kts
Labels: platform
