Repository CDCgov/prime-reportstream, pull requests merged in 2024-09, with the labels that each got.

#15788 Experience/e2e fixes
  frontend-react/e2e/spec/chromium-only/authenticated/daily-data-page-user-flow.spec.ts
  frontend-react/e2e/spec/chromium-only/authenticated/submission-history-page-user-flow.spec.ts
  frontend-react/playwright.config.ts
Labels: frontend, experience

#15793 testing re enabling file download
  frontend-react/e2e/spec/chromium-only/authenticated/daily-data-page-user-flow.spec.ts
Labels: experience

#15767 Fix Copy on: /developer-resources/api/documentation/responses-from-reportstream
  frontend-react/public/assets/pdf/ReportStream-Programmers-Guide-v4.5.pdf
  frontend-react/public/assets/pdf/ReportStream-Programmers-Guide-v4.6.pdf
  frontend-react/src/content/developer-resources/reportstream-api/documentation/ResponsesFromReportStream.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/SamplePayloadsAndOutput.mdx
  frontend-react/src/content/developer-resources/reportstream-api/getting-started/GettingStarted.mdx
  frontend-react/src/content/site.json
Labels: experience, trialfrontend03

#15785 15262 - Receiver Status smoke tests
  frontend-react/e2e/pages/authenticated/admin/receiver-status.ts
  frontend-react/e2e/spec/all/authenticated/admin/last-mile-failures-page.spec.ts
  frontend-react/e2e/spec/all/authenticated/admin/message-details-page.spec.ts
  frontend-react/e2e/spec/all/authenticated/admin/message-id-search-page.spec.ts
  frontend-react/e2e/spec/all/authenticated/admin/organization-settings-page.spec.ts
  frontend-react/e2e/spec/all/authenticated/admin/receiver-status-page.spec.ts
  frontend-react/e2e/spec/chromium-only/authenticated/receiver-status-page-user-flow.spec.ts
Labels: frontend, experience

#15824 Experience/15262/receiver status smoke
  frontend-react/e2e/spec/chromium-only/authenticated/receiver-status-page-user-flow.spec.ts
Labels: frontend, experience

#15764 Unwanted conditions to notes schema
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/Common/observation-to-nte/unwanted-conditions-to-notes.yml
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/STLTs/Test/test-receiver-transform.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/mars_unwanted_condition_to_notes.fhir
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/mars_unwanted_condition_to_notes.hl7
  prime-router/src/testIntegration/resources/datatests/translation-test-config.csv
Labels: onboarding-ops

#15843 #15217 - Implement smoke test user flow for Last Mile Failures
  frontend-react/e2e/pages/authenticated/last-mile-failures.ts
  frontend-react/e2e/spec/chromium-only/authenticated/last-mile-failures-page-user-flow.spec.ts
Labels: frontend, experience

#15829 MN UP Migration Validate Test Data - Filter out FLU
  prime-router/settings/STLTs/MN/mn-doh.yml
Labels: onboarding-ops, Montana

#15846 Track filter results for reports failing receiver filters
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiverFilter.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirReceiverFilterTests.kt
Labels: platform

#15850 Fixed CheckFunction to allow check report URL endpoint alive
  .environment/gitleaks/gitleaks-config.toml
  prime-router/src/main/kotlin/azure/CheckFunction.kt
  prime-router/src/main/kotlin/transport/RESTTransport.kt
Labels: onboarding-ops

#15863 pin ca.uhn.hapi.fhir:org.hl7.fhir.utilities:6.3.24 and ca.uhn.hapi.fhir:org.hl7.fhir.r4:6.3.24
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/fhirengine/engine/CustomFhirPathFunctions.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathFunctions.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/ConstantResolverTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/FhirPathUtilsTests.kt
Labels: security, dependencies, java

#15765 Authentication Microservice POC
  auth/.gitignore
  auth/build.gradle.kts
  auth/gradle/wrapper/gradle-wrapper.jar
  auth/gradle/wrapper/gradle-wrapper.properties
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/AuthApplication.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/AuthApplicationConstants.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/config/ApplicationConfig.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/config/SecurityConfig.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/controller/AuthController.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/controller/HealthController.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/model/ApplicationStatus.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/service/ProxyURIStrategy.kt
  auth/src/main/resources/application.yml
  auth/src/test/kotlin/gov/cdc/prime/reportstream/auth/controller/AuthControllerTest.kt
  auth/src/test/resources/application.yml
  settings.gradle.kts
  submissions/build.gradle.kts
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/config/SecurityConfig.kt
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/controllers/SubmissionController.kt
  submissions/src/main/resources/application.properties
Labels: platform

#15921 15839 - E2e tests (mock data) for all of Org/Receiver/Sender Settings Pages
  frontend-react/e2e/mocks/organizations.ts
  frontend-react/e2e/pages/BasePage.ts
  frontend-react/e2e/pages/authenticated/admin/last-mile-failures.ts
  frontend-react/e2e/pages/authenticated/admin/message-details.ts
  frontend-react/e2e/pages/authenticated/admin/message-id-search.ts
  frontend-react/e2e/pages/authenticated/admin/organization-edit.ts
  frontend-react/e2e/pages/authenticated/admin/organization.ts
  frontend-react/e2e/spec/all/authenticated/admin/last-mile-failures-page.spec.ts
  frontend-react/e2e/spec/all/authenticated/admin/message-details-page.spec.ts
  frontend-react/e2e/spec/all/authenticated/admin/message-id-search-page.spec.ts
  frontend-react/e2e/spec/all/authenticated/admin/organization-settings-edit-page.spec.ts
  frontend-react/e2e/spec/all/authenticated/admin/organization-settings-page.spec.ts
  frontend-react/e2e/spec/all/idletimeout.spec.ts
  frontend-react/e2e/spec/chromium-only/authenticated/last-mile-failures-page-user-flow.spec.ts
  frontend-react/e2e/spec/chromium-only/authenticated/organization-settings-page-user-flow.spec.ts
  frontend-react/src/components/Admin/CompareJsonModal.tsx
Labels: frontend, experience

#15965 15908 - Implement user flow for e2e smoke test for Org Settings Edit Page
  frontend-react/e2e/spec/chromium-only/authenticated/last-mile-failures-page-user-flow.spec.ts
  frontend-react/e2e/spec/chromium-only/authenticated/organization-settings-edit-page-user-flow.spec.ts
  frontend-react/e2e/spec/chromium-only/authenticated/organization-settings-page-user-flow.spec.ts
Labels: frontend, experience

#15903 Resolve open backend dependabots
  prime-router/build.gradle.kts
  shared/build.gradle.kts
  submissions/build.gradle.kts
Labels: security, dependencies, java, platform

#15902 15805 version in azure events
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventData.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventService.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/azure/observability/context/MDCUtilsTest.kt
  prime-router/src/test/kotlin/azure/observability/event/ReportEventServiceTest.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRDestinationFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirDestinationFilterTests.kt
Labels: platform

#15998 15905 - Implement user flow for e2e smoke test for Sender Settings Page
  frontend-react/e2e/spec/chromium-only/authenticated/organization-settings-edit-page-user-flow.spec.ts
Labels: frontend, experience

#14556 Bump kotlin from 1.9.23 to 1.9.25
  gradle.properties
  prime-router/gradle.properties
Labels: dependencies, java

#15920 15766: item sent event
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventData.kt
  prime-router/src/main/kotlin/history/db/ReportGraph.kt
  prime-router/src/main/kotlin/report/ReportService.kt
  prime-router/src/main/kotlin/transport/AS2Transport.kt
  prime-router/src/main/kotlin/transport/BlobStoreTransport.kt
  prime-router/src/main/kotlin/transport/EmailTransport.kt
  prime-router/src/main/kotlin/transport/GAENTransport.kt
  prime-router/src/main/kotlin/transport/ITransport.kt
  prime-router/src/main/kotlin/transport/NullTransport.kt
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/main/kotlin/transport/SftpTransport.kt
  prime-router/src/main/kotlin/transport/SoapTransport.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/azure/SendFunctionTests.kt
  prime-router/src/testIntegration/kotlin/transport/AS2TransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/GAENTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/SftpTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/SoapTransportIntegrationTests.kt
Labels: platform

#16004 15906 - Implement user flow for e2e smoke test for Receiver Settings Edit Page
  frontend-react/e2e/spec/chromium-only/authenticated/organization-settings-edit-page-user-flow.spec.ts
Labels: frontend, experience

#15990 update submission received event and delete v1 azure events
  prime-router/docs/observability/azure-events.md
  prime-router/docs/universal-pipeline/destination-filter.md
  prime-router/docs/universal-pipeline/receiver-filter.md
  prime-router/src/main/kotlin/azure/observability/event/ReceiverFilterFailedEvent.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportAcceptedEvent.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportCreatedEvent.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportNotRoutedEvent.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportRouteEvent.kt
  submissions/build.gradle.kts
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/SubmissionReceivedEvent.kt
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/config/AllowedParametersConfig.kt
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/controllers/SubmissionController.kt
  submissions/src/main/resources/application.properties
  submissions/src/main/resources/application.yml
  submissions/src/test/kotlin/SubmissionControllerIntegrationTest.kt
  submissions/src/test/kotlin/SubmissionControllerTest.kt
Labels: platform

#15226 Bump gradle from 8.8 to 8.10.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  prime-router/Dockerfile.build
  prime-router/docs/docs-deprecated/getting-started/install-gradle.md
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/controllers/SubmissionController.kt
Labels: dependencies, java

#15919 Experience/15823/fix link checker
  frontend-react/404.html
  frontend-react/e2e/helpers/utils.ts
  frontend-react/e2e/spec/all/authenticated/admin/last-mile-failures-page.spec.ts
  frontend-react/e2e/spec/all/authenticated/admin/message-id-search-page.spec.ts
  frontend-react/e2e/spec/all/authenticated/admin/organization-settings-edit-page.spec.ts
  frontend-react/e2e/spec/all/authenticated/admin/organization-settings-page.spec.ts
  frontend-react/e2e/spec/all/authenticated/admin/receiver-status-page.spec.ts
  frontend-react/e2e/spec/chromium-only/public-pages-link-check.spec.ts
  frontend-react/package.json
  frontend-react/playwright.config.ts
  frontend-react/src/AppRouter.tsx
  frontend-react/src/content/error/ErrorMessages.ts
  frontend-react/src/content/home/index.mdx
  frontend-react/src/pages/error/legacy-content/ErrorNoPage.tsx
  frontend-react/yarn.lock
Labels: experience
