Repository CDCgov/prime-reportstream, pull requests merged in 2024-07, with the labels that each got.

#14931 Bump action/checkout from 4.1.1/4.1.4 to 4.1.6
  .github/workflows/frontend_chromatic_main.yml
  .github/workflows/frontend_ci.yml
Labels: dependencies, github_actions

#14898 Implement frontend e2e link checking into new PR workflow
  .github/actions/build-frontend/action.yml
  .github/workflows/frontend_ci.yml
  frontend-react/.env
  frontend-react/e2e/spec/about-page.spec.ts
  frontend-react/e2e/spec/all/admin/receiver-status-page.spec.ts
  frontend-react/e2e/spec/chromium-only/public-pages-link-check.spec.ts
  frontend-react/e2e/test.ts
  frontend-react/package.json
  frontend-react/playwright.config.ts
Labels: frontend, engineering

#14967 BUG: Chromatic Analysis step running for dependabot
  .github/workflows/frontend_ci.yml
Labels: frontend, engineering

#14844 Experience/14827-Remove-Getting-Started-page
  frontend-react/e2e/pages/getting-started.ts
  frontend-react/e2e/pages/header.ts
  frontend-react/e2e/spec/all/homepage.spec.ts
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/content/getting-started/index.mdx
Labels: design, frontend, engineering, trialfrontend02

#14845 Update Refer Healthcare Organizations page
  frontend-react/src/content/managing-your-connection/refer-healthcare-organizations.mdx
Labels: frontend, engineering, trialfrontend02

#14848 API guide updated per Phase 2 Comms Plan
  frontend-react/public/assets/pdf/ReportStream-Programmers-Guide-v4.1.pdf
  frontend-react/public/assets/pdf/ReportStream-Programmers-Guide-v4.2.pdf
  frontend-react/public/assets/pdf/ReportStream-Programmers-Guide-v4.4.pdf
  frontend-react/public/assets/pdf/ReportStream-Programmers-Guide-v4.5.pdf
  frontend-react/src/AppRouter.tsx
  frontend-react/src/content/developer-resources/reportstream-api/Sidenav.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/Documentation.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/ResponsesFromReportStream.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/SamplePayloadsAndOutput.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/data-model/AskOnEntryTable.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/data-model/DataModel.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/data-model/OrderAndResultDataElementsTable.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/data-model/OrderingProviderDataElementsTable.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/data-model/PatientDataElementsTable.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/data-model/ReportingAndOrderingFacilityDataElementsTable.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/data-model/SpecimenDataElementsTable.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/data-model/TestingFacilityDataElementsTable.mdx
  frontend-react/src/content/developer-resources/reportstream-api/getting-started/GettingStarted.mdx
  frontend-react/src/content/developer-resources/reportstream-api/getting-started/Step4.mdx
  frontend-react/src/content/site.json
Labels: design, frontend, engineering, trialfrontend02

#14907 Bump gradle from 8.7 to 8.8
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  prime-router/Dockerfile.build
  prime-router/docs/docs-deprecated/getting-started/install-gradle.md
Labels: security, dependencies, java

#15019 BUG: Login state param initialization of state for widget isn't passed to auth client
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/pages/Login.tsx
Labels: frontend, engineering

#14453 Initial commit FL receiver UP migration
  prime-router/settings/STLTs/FL/fl-phd.yml
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/STLTs/FL/FL-receiver-transform.yml
Labels: onboarding-ops, Florida

#14909 Experience/14762/get deliveries history api
  prime-router/docs/api/waters-delivery.yml
  prime-router/src/main/kotlin/history/azure/DeliveryFunction.kt
  prime-router/src/main/kotlin/history/azure/ReportFileFunction.kt
  prime-router/src/main/kotlin/history/db/DeliveryHistoryDatabaseAccess.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFunctionTests.kt
Labels: experience

#14889 14721: verify action params and SQL param escaping
  prime-router/cleanslate.sh
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/RequestFunction.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportReceivedEvent.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
Labels: platform

#14661 North Dakota UP Receiver Migration Pre-Work
  prime-router/settings/STLTs/ND/nd-doh.yml
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/STLTs/ND/ND-receiver-transform.yml
Labels: onboarding-ops, North Dakota

#14976 Ignore linting/testing steps in build-frontend when in trialfrontend env
  .github/actions/build-frontend/action.yml
  frontend-react/e2e/spec/chromium-only/public-pages-link-check.spec.ts
Labels: frontend, engineering, trialfrontend03

#15040 Resolve open backend dependabots
  prime-router/build.gradle.kts
Labels: platform

#14933 Fixed LookupTableValueSet.kt to allow search more than one column
  prime-router/src/main/kotlin/fhirengine/engine/LookupTableValueSet.kt
  prime-router/src/test/kotlin/fhirengine/engine/LookupTableValueSetTests.kt
Labels: platform

#15067 Support Page e2e
  frontend-react/e2e/pages/support.ts
  frontend-react/e2e/spec/all/homepage.spec.ts
  frontend-react/e2e/spec/all/support-page.spec.ts
Labels: frontend, experience

#15136 Allow more Dependabot PRs for workflows
  .github/dependabot.yml
Labels: dependencies, github_actions

#15131 14929 - Archived File Validator
  frontend-react/e2e/spec/all/resources-page.spec.ts
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
  frontend-react/src/content/managing-your-connection/sidenav.mdx
Labels: frontend, experience, trialfrontend01

#15113 14654 - Added mobile view nav bar functionality
  frontend-react/src/components/header/ReportStreamHeader.module.scss
  frontend-react/src/components/header/ReportStreamHeader.tsx
Labels: frontend, experience, trialfrontend03

#15020 Updates to fhirpath exception handling
  prime-router/docs/getting-started/running-tests.md
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirTransformerTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/FhirPathUtilsTests.kt
Labels: platform

#15163 15152: add bundle digest extractor
  prime-router/src/main/kotlin/azure/observability/bundleDigest/BundleDigestExtractor.kt
  prime-router/src/main/kotlin/azure/observability/bundleDigest/FhirPathBundleDigestExtractorStrategy.kt
  prime-router/src/main/kotlin/azure/observability/bundleDigest/FhirPathBundleDigestLabResultExtractorStrategy.kt
  prime-router/src/test/kotlin/azure/observability/bundleDigest/FhirPathBundleDigestExtractorStrategyTests.kt
Labels: platform

#14951 14350: update submission to be agnostic of steps
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/history/ReportHistory.kt
  prime-router/src/main/kotlin/history/SubmissionHistory.kt
  prime-router/src/main/kotlin/history/azure/DeliveryFunction.kt
  prime-router/src/main/kotlin/history/azure/ReportFileFacade.kt
  prime-router/src/main/kotlin/history/azure/ReportFileFunction.kt
  prime-router/src/main/kotlin/history/azure/SubmissionFunction.kt
  prime-router/src/main/kotlin/history/azure/SubmissionsFacade.kt
  prime-router/src/main/kotlin/history/db/ReportGraph.kt
  prime-router/src/test/kotlin/azure/HttpTestUtils.kt
  prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
  prime-router/src/test/kotlin/history/SubmissionHistoryTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionFunctionIntegrationTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionFunctionTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionsFacadeTests.kt
Labels: platform

#15164 15051,15157: download report and file name fix
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/azure/HistoryFunctions.kt
  prime-router/src/test/kotlin/ReportTests.kt
  prime-router/src/test/kotlin/azure/HistoryFunctionsTests.kt
Labels: platform

#15165 14622: validate a receiver only has one kind of condition filter set
  prime-router/src/main/kotlin/config/validation/Validations.kt
  prime-router/src/test/kotlin/config/validation/ConfigurationValueValidationServiceTest.kt
  prime-router/src/testIntegration/resources/settings/organizations.yml
Labels: platform

#14900 Add validation during org creation via CLI tool
  prime-router/src/main/kotlin/cli/SettingCommands.kt
  prime-router/src/main/kotlin/cli/ValidateUtilities.kt
  prime-router/src/main/kotlin/cli/ValidateYAMLCommand.kt
  prime-router/src/main/kotlin/common/JacksonMapperUtilities.kt
  prime-router/src/test/kotlin/cli/SettingCommandsTests.kt
  prime-router/src/test/resources/settings/success/testOrg1.yml
  prime-router/src/test/resources/yaml_validation/settings/multiple-success.yml
  prime-router/src/test/resources/yaml_validation/settings/org-success.json
  prime-router/src/test/resources/yaml_validation/settings/org-success.yml
  prime-router/src/test/resources/yaml_validation/settings/receiver.yml
  prime-router/src/test/resources/yaml_validation/settings/sender.yml
Labels: platform

#14904 Integrate new routing functions
  prime-router/docs/standard-operating-procedures/configuring-filters.md
  prime-router/docs/universal-pipeline/README.md
  prime-router/docs/universal-pipeline/destination-filter.md
  prime-router/docs/universal-pipeline/receiver-filter.md
  prime-router/docs/universal-pipeline/route.md
  prime-router/src/main/kotlin/ReportStreamFilter.kt
  prime-router/src/main/kotlin/azure/Event.kt
  prime-router/src/main/kotlin/azure/observability/event/AzureEventService.kt
  prime-router/src/main/kotlin/fhirengine/azure/FHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/main/kotlin/report/ReportService.kt
  prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRDestinationFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRRouterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/DefaultFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/fhirRouterTests/GetFilterTests.kt
  prime-router/src/test/kotlin/history/SubmissionHistoryTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionFunctionIntegrationTests.kt
  prime-router/src/test/kotlin/report/ReportServiceTests.kt
  prime-router/src/test/resources/fhirengine/engine/bundle_multiple_observations.fhir
Labels: platform

#14555 IL UP Receiver migration Pre-Work
  prime-router/settings/STLTs/IL/il-phd.yml
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/STLTs/IL/IL-receiver-transform.yml
Labels: onboarding-ops, Illinois

#15207 Experience/15057/e2e smoke tests
  frontend-react/README.md
  frontend-react/e2e/helpers/auth.setup.ts
  frontend-react/e2e/pages/BasePage.ts
  frontend-react/e2e/pages/admin/receiver-status.ts
  frontend-react/e2e/pages/daily-data-details.ts
  frontend-react/e2e/pages/daily-data.ts
  frontend-react/e2e/pages/organization.ts
  frontend-react/e2e/spec/all/BasePage.spec.ts
  frontend-react/e2e/spec/all/about-page.spec.ts
  frontend-react/e2e/spec/all/admin/receiver-status-page.spec.ts
  frontend-react/e2e/spec/all/daily-data-details-page.spec.ts
  frontend-react/e2e/spec/all/daily-data-page.spec.ts
  frontend-react/e2e/spec/all/homepage.spec.ts
  frontend-react/e2e/spec/all/idletimeout.spec.ts
  frontend-react/e2e/spec/all/organization-settings-page.spec.ts
  frontend-react/e2e/spec/all/our-network-page.spec.ts
  frontend-react/e2e/spec/all/roadmap.spec.ts
  frontend-react/e2e/spec/all/support-page.spec.ts
  frontend-react/e2e/spec/all/timezone.spec.ts
  frontend-react/e2e/test.ts
  frontend-react/package.json
Labels: frontend, experience

#15270 fix broken support link
  frontend-react/src/content/support/index.mdx
Labels: experience, trialfrontend03

#15259 14794 - Added Managing Your Connection e2e.
  frontend-react/e2e/pages/about.ts
  frontend-react/e2e/pages/managing-your-connection.ts
  frontend-react/e2e/pages/support.ts
  frontend-react/e2e/spec/all/about-page.spec.ts
  frontend-react/e2e/spec/all/managing-your-connection-page.spec.ts
  frontend-react/e2e/spec/all/support-page.spec.ts
Labels: frontend, experience

#15187 Spring Submissions API
  .editorconfig
  buildSrc/src/main/kotlin/reportstream.project-conventions.gradle.kts
  prime-router/build.gradle.kts
  prime-router/docker-compose.yml
  shared/src/main/kotlin/gov/cdc/prime/reportstream/shared/SubmissionQueueMessage.kt
  submissions/build.gradle.kts
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/CustomMediaTypes.kt
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/ReportReceivedEvent.kt
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/SubmissionsApplication.kt
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/TelemetryService.kt
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/WebConfig.kt
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/config/AzureConfig.kt
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/controllers/SubmissionController.kt
  submissions/src/main/resources/application.properties
  submissions/src/test/kotlin/SubmissionControllerIntegrationTest.kt
  submissions/src/test/kotlin/SubmissionControllerTest.kt
  submissions/src/test/resources/application-test.properties
Labels: platform

#15235 15059 - added github action workflow for frontend smoke tests to be run against live data
  .github/workflows/start_frontend_smoke.yml
Labels: frontend, experience

#15297 prettier errors
  frontend-react/.eslintrc.cjs
  frontend-react/404.html
  frontend-react/index.html
  frontend-react/lint-staged.config.js
  frontend-react/package.json
  frontend-react/playwright.config.ts
  frontend-react/tsconfig.json
  frontend-react/tsconfig.node.json
  frontend-react/unsupported-browser.html
  frontend-react/vite.config.ts
Labels: frontend

#15299 Update playwright linting rules
  frontend-react/.eslintrc.cjs
Labels: frontend

#15300 e2e test for refer healthcare page
  frontend-react/e2e/pages/about-side-navigation.ts
  frontend-react/e2e/pages/refer-healthcare.ts
  frontend-react/e2e/spec/all/refer-healthcare-page.spec.ts
Labels: experience

#15293 Experience/15059/smoke GitHub action
  .github/workflows/start_frontend_smoke.yml
Labels: frontend, experience

#15291 skip checks on action checksums
  .github/workflows/dependency_review.yml
Labels: DevOps, security, dependencies, github_actions

#15318 Experience/15059/smoke GitHub action
  .github/workflows/start_frontend_smoke.yml
Labels: frontend, experience

#15321 Experience/15059/smoke GitHub action
  .github/workflows/start_frontend_smoke.yml
Labels: frontend, experience

#15224 15153: update FHIRConvert to create empty report/lineages for items with no next action
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
Labels: platform

#15183 Bump node.js from 20.14 to 20.15.1
  frontend-react/.nvmrc
  frontend-react/package.json
Labels: security, dependencies, javascript

#15332 Experience/15059/smoke GitHub action
  .github/workflows/start_frontend_smoke.yml
  frontend-react/e2e/spec/all/admin/receiver-status-page.spec.ts
  frontend-react/e2e/spec/all/organization-settings-page.spec.ts
Labels: frontend, experience

#15323 15310: add index on report_id in action_log
  prime-router/src/main/resources/db/migration/V71__add_report_id_index_to_action_log.sql
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
Labels: platform

#15263 15153: Implement new events pattern
  prime-router/src/main/kotlin/ActionLog.kt
  prime-router/src/main/kotlin/SubmissionReceiver.kt
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/kotlin/azure/observability/context/MDCUtils.kt
  prime-router/src/main/kotlin/azure/observability/event/AzureEventService.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportReceivedEvent.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportSentEvent.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventBuilder.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventData.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventService.kt
  prime-router/src/main/kotlin/common/AzureHttpUtils.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRDestinationFilter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIREngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiverFilter.kt
  prime-router/src/main/kotlin/history/db/ReportGraph.kt
  prime-router/src/main/kotlin/report/ReportService.kt
  prime-router/src/main/kotlin/transport/AS2Transport.kt
  prime-router/src/main/kotlin/transport/BlobStoreTransport.kt
  prime-router/src/main/kotlin/transport/EmailTransport.kt
  prime-router/src/main/kotlin/transport/GAENTransport.kt
  prime-router/src/main/kotlin/transport/ITransport.kt
  prime-router/src/main/kotlin/transport/NullTransport.kt
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/main/kotlin/transport/SftpTransport.kt
  prime-router/src/main/kotlin/transport/SoapTransport.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/azure/SendFunctionTests.kt
  prime-router/src/test/kotlin/azure/observability/context/MDCUtilsTest.kt
  prime-router/src/test/kotlin/azure/observability/event/AzureEventServiceTest.kt
  prime-router/src/test/kotlin/azure/observability/event/InMemoryAzureEventService.kt
  prime-router/src/test/kotlin/azure/observability/event/ReportEventServiceTest.kt
  prime-router/src/test/kotlin/common/ReportNodeBuilder.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRDestinationFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirDestinationFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirReceiverFilterTests.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFunctionTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionFunctionIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/AS2TransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/GAENTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/SftpTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/SoapTransportIntegrationTests.kt
Labels: platform

#15316 14776 - Added security page e2e
  frontend-react/e2e/pages/security.ts
  frontend-react/e2e/spec/all/security.spec.ts
Labels: frontend, experience

#15325 14548: add actions for FHIR Transforms
  prime-router/metadata/json_schema/fhir/fhir-to-fhir-transform.json
  prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirTransformer.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/fhirTransform/FhirTransformSchema.kt
  prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirTransformerTests.kt
  prime-router/src/test/resources/fhir_sender_transforms/circular_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/classpath_sample_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/extends_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/incomplete_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/invalid_lookup_value_set.yml
  prime-router/src/test/resources/fhir_sender_transforms/invalid_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/invalid_value_set.yml
  prime-router/src/test/resources/fhir_sender_transforms/lookup_value_set.yml
  prime-router/src/test/resources/fhir_sender_transforms/no_schema_nor_value.yml
  prime-router/src/test/resources/fhir_sender_transforms/observation.yml
  prime-router/src/test/resources/fhir_sender_transforms/sample_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/test_base_schema.yml
  prime-router/src/test/resources/fhir_sender_transforms/test_extension_schema.yml
Labels: platform

#15384 15314: use correct filename logic for new deliveries API
  prime-router/src/main/kotlin/azure/ApiSearch.kt
  prime-router/src/main/kotlin/history/azure/DeliveryFunction.kt
  prime-router/src/main/kotlin/history/db/DeliveryHistoryDatabaseAccess.kt
  prime-router/src/test/kotlin/azure/ApiResponseTest.kt
  prime-router/src/test/kotlin/common/ReportNodeBuilder.kt
  prime-router/src/test/kotlin/history/db/DeliveryHistoryDatabaseAccessTests.kt
Labels: platform

#15387 15154: document KQL example queries for looking at the events
  prime-router/docs/observability/azure-events.md
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRDestinationFilter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiverFilter.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRDestinationFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirDestinationFilterTests.kt
Labels: platform

#15255 Experience/14238/integrate pagination api daily data
  frontend-react/e2e/mocks/deliveries.ts
  frontend-react/e2e/pages/report-details.ts
  frontend-react/e2e/spec/all/daily-data-details-page.spec.ts
  frontend-react/e2e/spec/all/daily-data-page.spec.ts
  frontend-react/src/__mockServers__/DeliveriesHistoryMockServer.ts
  frontend-react/src/components/DataDashboard/DataDashboardTable/DataDashboardTable.tsx
  frontend-react/src/components/DataDashboard/FacilitiesProviders/FacilitiesProvidersTable.tsx
  frontend-react/src/components/Table/Table.test.tsx
  frontend-react/src/components/Table/TableFilterStatus.tsx
  frontend-react/src/components/Table/TableFilters.tsx
  frontend-react/src/config/endpoints/deliveries.ts
  frontend-react/src/hooks/api/deliveries/UseDeliveriesHistory/UseDeliveriesHistory.test.ts
  frontend-react/src/hooks/api/deliveries/UseDeliveriesHistory/UseDeliveriesHistory.ts
  frontend-react/src/pages/deliveries/daily-data/DailyData.test.tsx
  frontend-react/src/pages/deliveries/daily-data/DailyData.tsx
Labels: frontend, experience

#15304 14574 fhir translator tests
  prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRTranslatorIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FhirFunctionTests.kt
  prime-router/src/test/kotlin/history/db/DeliveryHistoryDatabaseAccessTests.kt
  prime-router/src/test/resources/fhirengine/engine/valid_data_multiple_targets_purple.fhir
Labels: platform
