Repository CDCgov/prime-reportstream, pull requests merged in 2024-06, with the labels that each got.

#14516 Bump glob from 7.2.3 to 9.3.5 in /frontend-react
  frontend-react/yarn.lock
Labels: security, dependencies, javascript

#14558 13124 - Updates to Nav bar to create auth sub nav.
  frontend-react/e2e/helpers/auth.setup.ts
  frontend-react/e2e/helpers/utils.ts
  frontend-react/e2e/pages/header.ts
  frontend-react/e2e/spec/daily-data-page.spec.ts
  frontend-react/e2e/spec/organization-settings-page.spec.ts
  frontend-react/e2e/spec/submission-history-page.spec.ts
  frontend-react/src/components/App/App.tsx
  frontend-react/src/components/header/ReportStreamHeader.module.scss
  frontend-react/src/components/header/ReportStreamHeader.test.tsx
  frontend-react/src/components/header/ReportStreamHeader.tsx
Labels: frontend, experience, trialfrontend01

#14559 14168 FHIR-to-FHIR transform validation
  .github/workflows/build_hub.yml
  prime-router/.idea/codeStyles/Project.xml
  prime-router/metadata/json_schema/fhir/fhir-to-fhir-transform.json
  prime-router/src/main/kotlin/common/JacksonMapperUtilities.kt
  prime-router/src/main/kotlin/config/validation/ConfigurationType.kt
  prime-router/src/main/kotlin/config/validation/ConfigurationValueValidationService.kt
  prime-router/src/main/kotlin/config/validation/Validations.kt
  prime-router/src/main/kotlin/fhirengine/engine/LookupTableValueSet.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/schema/ConfigSchemaReader.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
  prime-router/src/main/resources/metadata/fhir_transforms/common/use-pid-14-for-email.yml
  prime-router/src/main/resources/metadata/fhir_transforms/receivers/fhir-transform-sample.yml
  prime-router/src/main/resources/metadata/fhir_transforms/senders/Flexion/TILabOrder.yml
  prime-router/src/main/resources/metadata/fhir_transforms/senders/HCI/hci-sender-transform.yml
  prime-router/src/main/resources/metadata/fhir_transforms/senders/SimpleReport/datatypes/simple-report-telecom.yml
  prime-router/src/main/resources/metadata/fhir_transforms/senders/SimpleReport/simple-report-sender-transform.yml
  prime-router/src/main/resources/metadata/fhir_transforms/senders/baseline-sender-transform.yml
  prime-router/src/main/resources/metadata/fhir_transforms/senders/original-pipeline-transforms.yml
  prime-router/src/main/resources/metadata/fhir_transforms/senders/test-sender-transform.yml
Labels: platform

#14632 14572 - added banner back to Data Dashboard.
  frontend-react/src/pages/data-dashboard/DataDashboard.tsx
Labels: frontend, experience, trialfrontend01

#14631 14209 - Fixed Daily data render bug.
  frontend-react/e2e/pages/daily-data.ts
  frontend-react/src/components/Table/TableFilters.module.scss
  frontend-react/src/components/Table/TableFilters.tsx
Labels: frontend, experience

#14641 Resolve open backend dependabots
  prime-router/build.gradle.kts
Labels: security, dependencies, java, platform

#14554 Bump node.js from 20.12.* to 20.14.0
  frontend-react/.nvmrc
  frontend-react/package.json
Labels: dependencies, javascript

#14628 Remove unnecessary dependency pinning
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: dependencies, javascript

#14342 Experience/8370-Replace-hooks-for-Check-Settings-Commands-area
  frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx
  frontend-react/src/components/Admin/AdminReceiverDashboard.test.tsx
  frontend-react/src/components/Admin/AdminReceiverDashboard.tsx
  frontend-react/src/hooks/api/UseCreateResend/UseCreateResend.ts
  frontend-react/src/hooks/api/UseReceiversConnectionStatus/UseReceiversConnectionStatus.ts
  frontend-react/src/hooks/api/UseResends/UseResends.ts
  frontend-react/src/hooks/api/UseSendFailures/UseSendFailures.ts
  frontend-react/src/resources/AdmActionResource.ts
  frontend-react/src/resources/AdmConnStatusResource.ts
  frontend-react/src/resources/AdmSendFailuresResource.ts
Labels: frontend, experience

#14571 Implement base POM class for pages
  frontend-react/e2e/helpers/auth.setup.ts
  frontend-react/e2e/mocks/appInsightsConfig.json
  frontend-react/e2e/pages/BasePage.ts
  frontend-react/e2e/test.ts
  frontend-react/playwright.config.ts
Labels: frontend, experience

#14596 14451: ReportStream load test plan
  prime-router/docs/design/proposals/0027-report-stream-load-testing-strategy/0027-report-stream-load-testing-strategy.md
  prime-router/docs/design/proposals/0027-report-stream-load-testing-strategy/example-request-configured-via-ui.png
  prime-router/docs/design/proposals/0027-report-stream-load-testing-strategy/failed-load-test.png
  prime-router/docs/design/proposals/0027-report-stream-load-testing-strategy/prod-usage.png
  prime-router/docs/design/proposals/0027-report-stream-load-testing-strategy/successful-load-test.png
  prime-router/prime
  submissions/HELP.md
Labels: platform

#14688 Create dashboard showing cost per message in production #10546
  .github/workflows/export_cost_data.yml
Labels: DevOps, feature

#14717 14518 - Fixed CSP Header Issues
  frontend-react/src/config/index.ts
  frontend-react/vite.config.ts
Labels: frontend, experience, trialfrontend01

#14645 Filenames should prefix with none when translation schema is not present
  prime-router/docs/getting-started/running-tests.md
  prime-router/src/main/kotlin/FileNameTemplate.kt
  prime-router/src/testIntegration/kotlin/FileNameTemplateIntegrationTests.kt
Labels: platform

#14241 Platform/13506/int tests for fhir router
  prime-router/docs/getting-started/README.md
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
  prime-router/src/main/kotlin/fhirengine/utils/CompareFhirData.kt
  prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRRouterIntegrationTests.kt
  prime-router/src/test/resources/fhirengine/engine/bundle_multiple_observations_filtered_only_94558_5.fhir
Labels: platform

#14745 14742 - Reverted table due to bug issues
  frontend-react/src/components/Table/TableFilterStatus.tsx
  frontend-react/src/pages/deliveries/daily-data/DailyData.test.tsx
  frontend-react/src/pages/deliveries/daily-data/DailyData.tsx
Labels: frontend, experience

#14818 Bump terraform-stats to 1.6
  .github/workflows/alert_terraform_changes.yml
  .github/workflows/deploy_terraform.yml
Labels: dependencies, github_actions

#14847 Experience/14706/programmatic link checking process
  .github/actions/build-frontend/action.yml
  frontend-react/e2e/spec/chromium-only/public-pages-link-check.spec.ts
Labels: frontend, experience

#14724 14685 - Ingest OBX CE fields as CWE
  prime-router/docs/design/design/transformations.md
  prime-router/metadata/HL7/catchall/hl7/segments/OBX/Observation.yml
  prime-router/src/main/kotlin/fhirengine/translation/HL7toFhirTranslator.kt
  prime-router/src/main/kotlin/fhirengine/utils/HL7Reader.kt
  prime-router/src/main/resources/metadata/hl7_mapping/resources/Observation/OBXValue.yml
  prime-router/src/test/resources/fhirengine/smoketest/Expected_FHIR_to_FHIR_FULLELR.fhir
  prime-router/src/test/resources/fhirengine/smoketest/Expected_HL7_to_FHIR_FULLELR.fhir
  prime-router/src/test/resources/fhirengine/smoketest/Expected_HL7_to_HL7_FULLELR.hl7
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/catchall/ce/CEtoCodeableConceptTests.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/catchall/obx/OBXToObservationTests.kt
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/ce/CE-to-CodeableConcept.csv
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/ce/ce-test-values.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/ce/ce-test-values.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/obx/OBX-to-Observation-ce-value.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/obx/OBX-to-Observation-ce-value.hl7
Labels: platform

#14649 Internal blobstore names to reportid.ext and report_file.external to sent or received filename
  prime-router/docs/observability/local-dev-setup.md
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/Sender.kt
  prime-router/src/main/kotlin/SubmissionReceiver.kt
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/main/kotlin/azure/HistoryFunctions.kt
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportReceivedEvent.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportSentEvent.kt
  prime-router/src/main/kotlin/cli/FileUtilities.kt
  prime-router/src/main/kotlin/cli/ProcessDataCommands.kt
  prime-router/src/main/kotlin/cli/tests/BasicTests.kt
  prime-router/src/main/kotlin/common/JacksonMapperUtilities.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRDestinationFilter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiverFilter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRRouter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/history/DeliveryHistory.kt
  prime-router/src/main/kotlin/history/ReportHistory.kt
  prime-router/src/main/kotlin/history/SubmissionHistory.kt
  prime-router/src/main/kotlin/serializers/SoapSerializer.kt
  prime-router/src/main/kotlin/transport/AS2Transport.kt
  prime-router/src/main/kotlin/transport/BlobStoreTransport.kt
  prime-router/src/main/kotlin/transport/EmailTransport.kt
  prime-router/src/main/kotlin/transport/GAENTransport.kt
  prime-router/src/main/kotlin/transport/ITransport.kt
  prime-router/src/main/kotlin/transport/NullTransport.kt
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/main/kotlin/transport/SftpTransport.kt
  prime-router/src/main/kotlin/transport/SoapTransport.kt
  prime-router/src/test/kotlin/CsvFileTests.kt
  prime-router/src/test/kotlin/ReportTests.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/azure/BlobAccessTests.kt
  prime-router/src/test/kotlin/azure/HistoryFunctionsTests.kt
  prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
  prime-router/src/test/kotlin/azure/SendFunctionTests.kt
  prime-router/src/test/kotlin/history/azure/DeliveryFunctionTests.kt
  prime-router/src/test/kotlin/history/azure/SubmissionFunctionTests.kt
  prime-router/src/testIntegration/kotlin/SimpleReportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/AS2TransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/GAENTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/SftpTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/SoapTransportIntegrationTests.kt
Labels: platform

#10071 Optimize build-frontend workflow
  .github/actions/build-vars/action.yml
  .github/workflows/build_frontend.yaml
  .github/workflows/build_hub.yml
  .github/workflows/chromatic-master.yml
  .github/workflows/chromatic-pr.yml
  .github/workflows/frontend_chromatic_main.yml
  .github/workflows/frontend_ci.yml
  .github/workflows/release_to_azure.yml
  .github/workflows/sonarcloud.yml
  frontend-react/playwright.config.ts
  frontend-react/src/utils/DateTimeUtils.ts
Labels: frontend, experience

#14834 Platform/angela/14331/add loinc to azure events
  prime-router/src/main/kotlin/azure/observability/event/AzureEventUtils.kt
  prime-router/src/main/kotlin/azure/observability/event/CodeSummary.kt
  prime-router/src/main/kotlin/azure/observability/event/ConditionSummary.kt
  prime-router/src/main/kotlin/azure/observability/event/ObservationSummary.kt
  prime-router/src/main/kotlin/azure/observability/event/TestSummary.kt
  prime-router/src/test/kotlin/azure/observability/event/AzureEventUtilsTest.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirDestinationFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirReceiverFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirRouterTests.kt
  prime-router/src/test/resources/fhirengine/engine/routing/valid2.fhir
Labels: platform
