Repository CDCgov/prime-reportstream, pull requests merged in 2024-12, with the labels that each got.

#16689 reset pagination upon filtering
  frontend-react/src/components/Table/TableFilters.tsx
Labels: experience, trialfrontend03

#16707 Updating the azure/login version to latest (v2) and adding a validati…
  .github/actions/build-vars/action.yml
  .github/actions/vpn-azure/action.yml
  .github/workflows/alert_cert_expire.yml
  .github/workflows/alert_resource_costs.yml
  .github/workflows/alert_terraform_changes.yml
  .github/workflows/build_hub.yml
  .github/workflows/cleanup_acr_images.yml
  .github/workflows/deploy_terraform.yml
  .github/workflows/deployment_rollback.yml
  .github/workflows/destroy_demo_environment.yml
  .github/workflows/export_cost_data.yml
  .github/workflows/release_chatops_app.yml
  .github/workflows/release_to_azure.yml
  .github/workflows/release_trial_frontend.yml
  .github/workflows/restore_databases.yml
  .github/workflows/start_test_servers.yml
  .github/workflows/stop_test_servers.yml
  .github/workflows/sync-translation-schemas.yml
  .github/workflows/validate_resources.yml
Labels: github-actions, reportstream, DevSecOps, github-workflows

#16552 16394 add ack functionality
  prime-router/metadata/json_schema/organizations/organizations.json
  prime-router/src/main/kotlin/Sender.kt
  prime-router/src/main/kotlin/azure/HttpUtilities.kt
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/azure/service/SubmissionResponseBuilder.kt
  prime-router/src/main/kotlin/common/Environment.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/HL7ACKUtils.kt
  prime-router/src/main/kotlin/fhirengine/utils/HL7Reader.kt
  prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
  prime-router/src/test/kotlin/azure/service/SubmissionResponseBuilderTest.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/HL7ACKUtilsTest.kt
  prime-router/src/test/kotlin/fhirengine/utils/HL7ReaderTests.kt
Labels: platform, etor

#16695 #16585 Add Maine to Network Map SVG
  frontend-react/src/content/about/our-network.mdx
  frontend-react/src/content/live.json
  frontend-react/src/content/usa_w_territories.svg
Labels: onboarding-ops, needs-refinement

#16495 14601 authorization api
  auth/build.gradle.kts
  auth/docs/setup.md
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/AuthApplicationConstants.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/client/OktaGroupsClient.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/config/ApplicationConfig.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/config/OktaClientConfig.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/config/RouteConfig.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/config/SubmissionsConfig.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/controller/HealthController.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/filter/AppendOktaGroupsGatewayFilterFactory.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/service/OktaGroupsJWTWriter.kt
  auth/src/main/kotlin/gov/cdc/prime/reportstream/auth/service/OktaGroupsService.kt
  auth/src/main/resources/application.yml
  auth/src/test/kotlin/gov/cdc/prime/reportstream/auth/client/OktaGroupsClientTest.kt
  auth/src/test/kotlin/gov/cdc/prime/reportstream/auth/config/TestOktaClientConfig.kt
  auth/src/test/kotlin/gov/cdc/prime/reportstream/auth/controller/HealthControllerTest.kt
  auth/src/test/kotlin/gov/cdc/prime/reportstream/auth/filter/AppendOktaGroupsGatewayFilterFactoryTest.kt
  auth/src/test/kotlin/gov/cdc/prime/reportstream/auth/service/OktaGroupsJWTWriterTest.kt
  auth/src/test/kotlin/gov/cdc/prime/reportstream/auth/service/OktaGroupsServiceTest.kt
  auth/src/test/kotlin/gov/cdc/prime/reportstream/auth/util/KeyGenerationUtils.kt
  auth/src/test/resources/application.yml
  buildSrc/src/main/kotlin/reportstream.project-conventions.gradle.kts
  shared/build.gradle.kts
  shared/src/main/kotlin/gov/cdc/prime/reportstream/shared/StringUtilities.kt
  shared/src/main/kotlin/gov/cdc/prime/reportstream/shared/auth/AuthZService.kt
  shared/src/main/kotlin/gov/cdc/prime/reportstream/shared/auth/jwt/OktaGroupsJWT.kt
  shared/src/main/kotlin/gov/cdc/prime/reportstream/shared/auth/jwt/OktaGroupsJWTConstants.kt
  shared/src/main/kotlin/gov/cdc/prime/reportstream/shared/auth/jwt/OktaGroupsJWTReader.kt
  shared/src/test/kotlin/gov/cdc/prime/reportstream/shared/StringUtilitiesTests.kt
  shared/src/test/kotlin/gov/cdc/prime/reportstream/shared/auth/AuthZServiceTest.kt
  shared/src/test/kotlin/gov/cdc/prime/reportstream/shared/auth/jwt/OktaGroupsJWTReaderTest.kt
  submissions/build.gradle.kts
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/SubmissionsApplication.kt
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/config/AuthConfig.kt
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/config/SecurityConfig.kt
  submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/controllers/SubmissionController.kt
  submissions/src/main/resources/application.yml
  submissions/src/test/kotlin/SubmissionControllerIntegrationTest.kt
  submissions/src/test/kotlin/SubmissionControllerTest.kt
Labels: platform, microservice

#16619 Platform/david navapbc/15514/hl7 oml aui fhir mapping
  prime-router/metadata/HL7/catchall/hl7/datatypes/AUI/AUIExtension.yml
  prime-router/metadata/HL7/catchall/hl7/message/OML_O21.yml
  prime-router/metadata/HL7/catchall/hl7/segments/IN1/Coverage.yml
  prime-router/src/main/resources/metadata/hl7_mapping/OML_O21/OML_O21-base.yml
  prime-router/src/main/resources/metadata/hl7_mapping/datatypes/extensionAUI/AUI.yml
  prime-router/src/main/resources/metadata/hl7_mapping/resources/Coverage/IN1.yml
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/catchall/aui/AUIExtensionTests.kt
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/catchall/in1/IN1Tests.kt
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/aui/AUI-to-Extension.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/aui/AUI-to-Extension.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/in1/IN1-to-Coverage.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/in1/IN1-to-Coverage.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/omlo21/oml_o21-full.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/omlo21/oml_o21-full.hl7
Labels: platform

#16728 Integrating the checksum-validate GitHub Action into project
  .github/actions/checksum-validate/README.md
  .github/actions/checksum-validate/action.yml
  .github/actions/deploy-backend/action.yml
  .github/dependabot.yml
  .github/workflows/release_to_azure.yml
Labels: tech-debt, github-actions, reportstream, DevSecOps

#16767 Add CP to Extension mappings
  prime-router/docs/design/design/RS-Extention-Registry.yml
  prime-router/metadata/HL7/catchall/hl7/codesystem/ExtensionUrlMapping.yml
  prime-router/metadata/HL7/catchall/hl7/datatypes/CP/CPExtension.yml
  prime-router/metadata/HL7/catchall/hl7/datatypes/MOC/MOCExtension.yml
  prime-router/metadata/HL7/catchall/hl7/segments/IN1/Coverage.yml
  prime-router/metadata/HL7/catchall/hl7/segments/ORC/OBRExtension.yml
  prime-router/src/main/resources/metadata/hl7_mapping/OML_O21/OML_O21-base.yml
  prime-router/src/main/resources/metadata/hl7_mapping/OML_O21/OML_O21-test.yml
  prime-router/src/main/resources/metadata/hl7_mapping/datatypes/extensionCP/CP.yml
  prime-router/src/main/resources/metadata/hl7_mapping/resources/Coverage/IN1.yml
  prime-router/src/testIntegration/kotlin/datatests/mappinginventory/catchall/cp/CPTests.kt
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/cp/cp-to-extension.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/cp/cp-to-extension.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/in1/IN1-to-Coverage.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/in1/IN1-to-Coverage.hl7
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/omlo21/oml_o21-full.fhir
  prime-router/src/testIntegration/resources/datatests/mappinginventory/catchall/omlo21/oml_o21-full.hl7
Labels: platform

#16788 Allow alternate input on MSH for RADx_MARS
  prime-router/src/main/resources/metadata/hl7_validation/v251/radxmars/onboarding/constraints.xml
  prime-router/src/main/resources/metadata/hl7_validation/v251/radxmars/production/constraints.xml
  prime-router/src/test/kotlin/validation/MarsOtcElrValidatorTests.kt
  prime-router/src/test/resources/validation/marsotcelr/valid_altered_msh.hl7
Labels: platform

#16723 16409 do not use receive step to determine root report
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/history/db/ReportGraph.kt
  prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRTranslatorIntegrationTests.kt
Labels: platform

#16769 16722 authz documentation
  prime-router/docs/authz/authz-deprecated-implementation.md
  prime-router/src/test/kotlin/tokens/ScopeTests.kt
Labels: platform

#16792 Experience/16070/message bank page
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/Admin/EditReceiverSettings.tsx
  frontend-react/src/components/Admin/MessageTesting/CustomMessage.tsx
  frontend-react/src/components/Admin/MessageTesting/MessageTesting.tsx
  frontend-react/src/components/Admin/MessageTesting/RadioField.tsx
  frontend-react/src/config/endpoints/settings.ts
  frontend-react/src/hooks/api/messages/UseTestMessages.ts
  frontend-react/src/utils/FeatureName.ts
  frontend-react/src/utils/misc.ts
Labels: experience, trialfrontend03

#16835 Importing GitHub Repository (Action): AzViz (Azure Visualizer) action
  .github/actions/azviz/README.md
  .github/actions/azviz/action.yml
  .github/actions/azviz/viz_run.ps1
Labels: tech-debt, github-actions, reportstream, DevSecOps

#16834 Revert "16409 do not use receive step to determine root report"
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/history/db/ReportGraph.kt
  prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRTranslatorIntegrationTests.kt
Labels: platform

#16848 Importing GitHub Repository (Action): slack-boltjs-app
  .github/actions/slack-boltjs-app/.dockerignore
  .github/actions/slack-boltjs-app/.env.example
  .github/actions/slack-boltjs-app/.eslintignore
  .github/actions/slack-boltjs-app/.eslintrc.cjs
  .github/actions/slack-boltjs-app/.gitignore
  .github/actions/slack-boltjs-app/.glitch-assets
  .github/actions/slack-boltjs-app/.help.example
  .github/actions/slack-boltjs-app/Dockerfile.example
  .github/actions/slack-boltjs-app/Makefile
  .github/actions/slack-boltjs-app/README.md
  .github/actions/slack-boltjs-app/npm-shrinkwrap.json
  .github/actions/slack-boltjs-app/package.json
  .github/actions/slack-boltjs-app/src/index.js
  .github/actions/slack-boltjs-app/src/utils/github/default_branch.js
  .github/actions/slack-boltjs-app/src/utils/github/list_targets.js
  .github/actions/slack-boltjs-app/src/utils/github/lock_target.js
  .github/actions/slack-boltjs-app/src/utils/github/push.js
  .github/actions/slack-boltjs-app/src/utils/github/request.js
  .github/actions/slack-boltjs-app/src/utils/github/router.js
  .github/actions/slack-boltjs-app/src/utils/github/run_workflow.js
  .github/actions/slack-boltjs-app/src/views/app_home.js
Labels: tech-debt, reportstream, DevSecOps

#16864 Add GMT+12 MOJURO TimeZone to ReportStream
  frontend-react/src/utils/TemporarySettingsAPITypes.ts
  prime-router/src/main/kotlin/USTimeZone.kt
  prime-router/src/main/resources/metadata/fhir_transforms/common/datetime-to-local-majuro.yml
  prime-router/src/test/kotlin/ReceiverTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/CustomTranslationFunctionsTest.kt
Labels: onboarding-ops

#16909 platform/dependabot/2024-12-26
  auth/build.gradle.kts
  prime-router/build.gradle.kts
  prime-router/src/testIntegration/kotlin/transport/SftpTransportIntegrationTests.kt
  submissions/build.gradle.kts
Labels: platform
