Repository CDCgov/prime-reportstream, pull requests merged in 2025-04, with the labels that each got.

#17710 Update URL for Monday PD Action
  .github/workflows/alert_PD_schedule_Slack.yml
Labels: platform

#17712 fix 400 500 rendering
  frontend-react/src/components/Admin/AdminFormWrapper.tsx
  frontend-react/src/components/RSErrorBoundary/RSErrorBoundary.tsx
  frontend-react/src/components/RSErrorBoundary/RSErrorUnknownBoundary.tsx
  frontend-react/src/hooks/api/UseCodeMappingFormSubmit/UseCodeMappingFormSubmit.ts
  frontend-react/src/pages/onboarding/CodeMappingPage.tsx
  frontend-react/src/shared/RequireGate/RequireGate.tsx
Labels: experience, trialfrontend03

#17729 More documentation on how to update condition table manually
  prime-router/docs/standard-operating-procedures/update-observation-mapping-table.md
Labels: onboarding-ops

#17764 Document Process for Filtering by condition code and member OID value set
  prime-router/docs/design/proposals/0023-condition-to-code-mapping/0023-condition-to-code-mapping.md
  prime-router/docs/design/proposals/0023-condition-to-code-mapping/observation-mapping-filter-step2.PNG
  prime-router/docs/design/proposals/0023-condition-to-code-mapping/observation-mapping-filter-step3.PNG
  prime-router/docs/design/proposals/0023-condition-to-code-mapping/observation-mapping-select-memberOID.PNG
  prime-router/docs/design/proposals/0023-condition-to-code-mapping/observation-mapping-selections.PNG
Labels: onboarding-ops

#17756 [17510] - moving convert queue message call to report function
  prime-router/src/main/kotlin/SubmissionReceiver.kt
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/test/kotlin/SubmissionReceiverTests.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
Labels: platform

#17794 Resolve Synk Related Backend Dependabot PRs
  prime-router/build.gradle.kts
Labels: platform

#17847 Update LIVD Table 2025-03-05
  prime-router/metadata/tables/local/LIVD-SARS-CoV-2-2025-03-05 PRIME.xlsx
Labels: onboarding-ops

#17841 Resolve low impact dependabot updates
  prime-router/build.gradle.kts
Labels: platform

#17679 Create azure events for send step failures per item
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventData.kt
  prime-router/src/main/kotlin/transport/AS2Transport.kt
  prime-router/src/main/kotlin/transport/BlobStoreTransport.kt
  prime-router/src/main/kotlin/transport/EmailTransport.kt
  prime-router/src/main/kotlin/transport/GAENTransport.kt
  prime-router/src/main/kotlin/transport/ITransport.kt
  prime-router/src/main/kotlin/transport/NullTransport.kt
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/main/kotlin/transport/SftpTransport.kt
  prime-router/src/main/kotlin/transport/SoapTransport.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/azure/SendFunctionTests.kt
  prime-router/src/testIntegration/kotlin/transport/AS2TransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/GAENTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/SftpTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/SoapTransportIntegrationTests.kt
Labels: platform

#17862 Experience/17573/fix broken links
  frontend-react/e2e/spec/chromium-only/public-pages-link-check.spec.ts
  frontend-react/public/sitemap.xml
  frontend-react/src/content/about/security.mdx
  frontend-react/src/content/support/index.mdx
Labels: frontend, experience

#17880 Updating azure event docs for item-based send failures
  prime-router/docs/observability/azure-events.md
Labels: platform

#17940 Platform dependabot 2025-04-23
  auth/build.gradle.kts
  prime-router/Dockerfile.build
  prime-router/build.gradle.kts
  shared/build.gradle.kts
  submissions/build.gradle.kts
Labels: platform

#17855 Fix for HL7 message testing + new endpoint to retrieve list of senders
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
Labels: onboarding-ops, engineering

#17890 Experience/17825/integrate updated test message api
  frontend-react/src/components/Admin/MessageTesting/MessageTestingCustomMessage.tsx
  frontend-react/src/components/Admin/MessageTesting/MessageTestingForm.tsx
  frontend-react/src/components/Admin/MessageTesting/MessageTestingRadioField.tsx
  frontend-react/src/config/endpoints/reports.ts
  frontend-react/src/hooks/api/messages/UseTestMessageResult/UseTestMessageResult.ts
  frontend-react/src/hooks/api/messages/UseTestMessageSenders/UseTestMessageSenders.ts
  frontend-react/src/pages/admin/AdminMessageTestingPage/AdminMessageTestingPage.tsx
Labels: experience

#17913 add sender select dropdown
  frontend-react/e2e/pages/authenticated/admin/organization-receiver-message-test.ts
  frontend-react/e2e/spec/all/authenticated/admin/organization-receiver-message-test.spec.ts
  frontend-react/src/components/Admin/MessageTesting/MessageTestingCustomMessage.tsx
  frontend-react/src/components/Admin/MessageTesting/MessageTestingForm.tsx
  frontend-react/src/pages/admin/AdminMessageTestingPage/AdminMessageTestingPage.tsx
Labels: experience, trialfrontend03

#17934 Experience/17653/submission status errors page
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  README.md
  frontend-react/e2e/pages/public/developer-resources/documentation/submission-status-and-errors.ts
  frontend-react/e2e/spec/all/public/developer-resources/api/documentation/index.spec.ts
  frontend-react/e2e/spec/all/public/developer-resources/api/documentation/submission-status-and-errors.spec.ts
  frontend-react/public/sitemap.xml
  frontend-react/src/AppRouter.tsx
  frontend-react/src/content/developer-resources/reportstream-api/Sidenav.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/Documentation.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/ResponsesFromReportStream.mdx
  frontend-react/src/content/developer-resources/reportstream-api/documentation/SubmissionStatusAndErrors.mdx
  frontend-react/src/content/site.json
  prime-router/docs/getting-started/README.md
Labels: frontend, experience, trialfrontend01

#17950 Experience/16349/unskip e2e test
  frontend-react/e2e/spec/chromium-only/authenticated/daily-data-page-user-flow.spec.ts
Labels: frontend, experience

#17985 Platform dependabot 2025-04-28
  .gitignore
  auth/build.gradle.kts
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/azure/observability/AzureCustomDimensionsSerializable.kt
  prime-router/src/main/kotlin/cli/CommandUtilities.kt
  prime-router/src/main/kotlin/config/validation/ConfigurationType.kt
  prime-router/src/main/kotlin/docgenerators/CsvDocumentationFactory.kt
  prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
  submissions/build.gradle.kts
Labels: platform

#17988 Revert "Experience/16349/unskip e2e test"
  frontend-react/e2e/spec/chromium-only/authenticated/daily-data-page-user-flow.spec.ts
Labels: frontend, experience

#17928 Update UT Setting to accept CVS
  prime-router/settings/STLTs/UT/ut-phd.yml
Labels: onboarding-ops
