Repository CDCgov/prime-reportstream, pull requests merged in 2025-01, with the labels that each got.

#16857 Add retries to 429 errors for REST transport
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
Labels: platform, etor

#16939 Formatting parameters for changeTimeZone function
  prime-router/src/main/kotlin/common/DateUtilities.kt
  prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctions.kt
  prime-router/src/test/kotlin/common/DateUtilitiesTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctionsTests.kt
Labels: onboarding-ops

#16950 Update dependabot config to ignore specific dependencies' major versions
  .github/dependabot.yml
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: experience, DevSecOps

#16920 Flexion/jgilmore/update blob storage transport filenames
  prime-router/src/main/kotlin/azure/BlobAccess.kt
  prime-router/src/main/kotlin/transport/BlobStoreTransport.kt
  prime-router/src/test/kotlin/azure/BlobAccessTests.kt
Labels: platform, etor

#16859 Platform/angela/14116/read hl7
  prime-router/src/main/kotlin/SettingsProvider.kt
  prime-router/src/main/kotlin/SubmissionReceiver.kt
  prime-router/src/main/kotlin/azure/service/SubmissionResponseBuilder.kt
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/cli/ProcessHl7Commands.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/translation/TranslationSchemaManager.kt
  prime-router/src/main/kotlin/fhirengine/utils/HL7MessageHelpers.kt
  prime-router/src/main/kotlin/fhirengine/utils/HL7Reader.kt
  prime-router/src/test/kotlin/cli/helpers/HL7DiffHelperTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/HL7toFhirTranslatorTests.kt
  prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/HL7ACKUtilsTest.kt
  prime-router/src/test/kotlin/fhirengine/utils/FHIRBundleHelpersTests.kt
  prime-router/src/test/kotlin/fhirengine/utils/HL7QueueMessageHelpersTests.kt
  prime-router/src/test/kotlin/fhirengine/utils/HL7ReaderTests.kt
  prime-router/src/test/kotlin/validation/MarsOtcElrOnboardingValidatorTests.kt
  prime-router/src/test/kotlin/validation/MarsOtcElrValidatorTests.kt
  prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
Labels: platform

#16862 Update platform user story template
  .github/ISSUE_TEMPLATE/platform-user-story.md
Labels: platform

#16505 Update call to FhirToHl7Converter to pass in correct BlobContainerMetadata
  prime-router/src/main/kotlin/Receiver.kt
Labels: platform

#17034 Updated Washington STLT transform to ignore AOE 01.9.2025
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/STLTs/WA/WA-receiver-transform.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_WA_20240719-0001.hl7
Labels: onboarding-ops, Washington

#17023 Devsecops/emvaldes/runleaks
  .github/actions/runleaks/.gitignore
  .github/actions/runleaks/Dockerfile
  .github/actions/runleaks/LICENSE
  .github/actions/runleaks/README.md
  .github/actions/runleaks/action.yml
  .github/actions/runleaks/git-secrets/.pre-commit-hooks.yaml
  .github/actions/runleaks/git-secrets/CHANGELOG.md
  .github/actions/runleaks/git-secrets/CODE_OF_CONDUCT.md
  .github/actions/runleaks/git-secrets/CONTRIBUTING.md
  .github/actions/runleaks/git-secrets/LICENSE.txt
  .github/actions/runleaks/git-secrets/Makefile
  .github/actions/runleaks/git-secrets/NOTICE.txt
  .github/actions/runleaks/git-secrets/README.rst
  .github/actions/runleaks/git-secrets/git-secrets
  .github/actions/runleaks/git-secrets/git-secrets.1
  .github/actions/runleaks/git-secrets/install.ps1
  .github/actions/runleaks/git-secrets/test/bats/LICENSE
  .github/actions/runleaks/git-secrets/test/bats/bin/bats
  .github/actions/runleaks/git-secrets/test/bats/libexec/bats
  .github/actions/runleaks/git-secrets/test/bats/libexec/bats-exec-suite
  .github/actions/runleaks/git-secrets/test/bats/libexec/bats-exec-test
  .github/actions/runleaks/git-secrets/test/bats/libexec/bats-format-tap-stream
  .github/actions/runleaks/git-secrets/test/bats/libexec/bats-preprocess
  .github/actions/runleaks/git-secrets/test/commit-msg.bats
  .github/actions/runleaks/git-secrets/test/git-secrets.bats
  .github/actions/runleaks/git-secrets/test/pre-commit.bats
  .github/actions/runleaks/git-secrets/test/prepare-commit-msg.bats
  .github/actions/runleaks/git-secrets/test/test_helper.bash
  .github/actions/runleaks/lib/scan.sh
Labels: tech-debt, github-actions, reportstream, DevSecOps, imported-project

#17025 Devsecops/emvaldes/workflow housekeeper
  .github/actions/workflow-housekeeper/.gitignore
  .github/actions/workflow-housekeeper/README.md
  .github/actions/workflow-housekeeper/action.yml
  .github/actions/workflow-housekeeper/lib/housekeeper.sh
Labels: tech-debt, github-actions, reportstream, DevSecOps, imported-project

#17033 Updating Terraform Azure Service Principal PRIME-ReportStream-Terraform
  operations/app/terraform/modules/init/key_vault.tf
  operations/app/terraform/vars/demo/locals.tf
  operations/app/terraform/vars/prod/locals.tf
  operations/app/terraform/vars/staging/locals.tf
  operations/app/terraform/vars/test/locals.tf
  prime-router/docs/docs-deprecated/environment-provisioning.md
Labels: tech-debt, github-actions, documentation, reportstream, engineering, infrastructure, terraform, DevSecOps, github-workflows, github-secrets, github-variables

#17022 devsecops/emvaldes/remote-branch
  .github/actions/remote-branch/LICENSE
  .github/actions/remote-branch/README.md
  .github/actions/remote-branch/action.yml
Labels: tech-debt, github-actions, reportstream, DevSecOps, imported-project

#17024 devsecops/emvaldes/terraform-stats
  .github/actions/terraform-stats/.gitignore
  .github/actions/terraform-stats/LICENSE
  .github/actions/terraform-stats/README.md
  .github/actions/terraform-stats/action.yml
  .github/actions/terraform-stats/lib/tf_stats.sh
  .github/actions/terraform-stats/terraform/main.tf
Labels: tech-debt, github-actions, reportstream, DevSecOps, imported-project

#17082 Update Our network page with new senders
  frontend-react/src/content/about/our-network.mdx
Labels: design, experience

#17085 Update azure-events.md documentation
  prime-router/docs/observability/azure-events.md
Labels: onboarding-ops, platform

#16938 Experience 16074: Create test result page without download results
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/Admin/EditReceiverSettings.tsx
  frontend-react/src/components/Admin/MessageTesting/AddCustomTestMessageForm.tsx
  frontend-react/src/components/Admin/MessageTesting/MessageTesting.tsx
  frontend-react/src/components/Admin/MessageTesting/MessageTestingAccordion.tsx
  frontend-react/src/components/Admin/MessageTesting/MessageTestingCustomMessage.tsx
  frontend-react/src/components/Admin/MessageTesting/MessageTestingForm.tsx
  frontend-react/src/components/Admin/MessageTesting/MessageTestingRadioField.tsx
  frontend-react/src/components/Admin/MessageTesting/MessageTestingResult.fixtures.ts
  frontend-react/src/components/Admin/MessageTesting/MessageTestingResult.tsx
  frontend-react/src/components/Admin/MessageTesting/TestMessageLabel.tsx
  frontend-react/src/components/Admin/MessageTesting/language.json
  frontend-react/src/config/endpoints/reports.ts
  frontend-react/src/config/endpoints/settings.ts
  frontend-react/src/hooks/api/messages/UseTestMessageResult/UseTestMessageResult.ts
  frontend-react/src/hooks/api/messages/UseTestMessages/UseTestMessages.ts
  frontend-react/src/pages/admin/AdminMessageTestingPage/AdminMessageTestingPage.tsx
  frontend-react/src/shared/HL7Message/HL7Message.tsx
  frontend-react/src/styles/_components.scss
  frontend-react/src/utils/OpenAsBlob/OpenAsBlob.test.ts
  frontend-react/src/utils/OpenAsBlob/OpenAsBlob.ts
  frontend-react/src/utils/misc.ts
Labels: experience, trialfrontend03

#17146 Update documentation to deprecate ETOR NBS integration
  prime-router/docs/api/delivery.yml
  prime-router/docs/api/submissions.yml
  prime-router/docs/docs-deprecated/getting-started/getting-started.md
Labels: platform

#17184 devsecops/emvaldes/export-azure-resources
  operations/app/terraform/scripts/export-resources.ps1
  operations/app/terraform/scripts/export-resources.py
  operations/app/terraform/scripts/export-resources.shell
Labels: reportstream, infrastructure, DevSecOps

#17179 Release Notes - Dec 2024 - Publication
  frontend-react/src/content/about/release-notes.mdx
Labels: experience

#17121 Carbon Health Onboarding - Test with WA
  prime-router/settings/STLTs/WA/wa-phd.yml
  prime-router/src/main/resources/metadata/fhir_transforms/common/datetime-to-local-pacific.yml
Labels: onboarding-ops, Washington

#17207 Add time flexibility to Daily Data "onLoad / table has correct headers" Smoke Test
  frontend-react/e2e/spec/chromium-only/authenticated/daily-data-page-user-flow.spec.ts
Labels: experience

#16854 [16141] Implement ReceiverEnrichment Function
  prime-router/docs/design/design/transformations.md
  prime-router/docs/universal-pipeline/README.md
  prime-router/docs/universal-pipeline/destination-filter.md
  prime-router/docs/universal-pipeline/receiver-enrichment.md
  prime-router/docs/universal-pipeline/receiver-filter.md
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/azure/Event.kt
  prime-router/src/main/kotlin/azure/WorkflowEngine.kt
  prime-router/src/main/kotlin/fhirengine/azure/FHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRDestinationFilter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIREngine.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiverEnrichment.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/engine/PrimeRouterQueueMessage.kt
  prime-router/src/main/resources/metadata/fhir_transforms/receivers/fhir-message-header-sample.yml
  prime-router/src/test/kotlin/fhirengine/azure/FHIRDestinationFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverEnrichmentIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRTranslatorIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FHIRReceiverEnrichmentTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  shared/src/main/kotlin/gov/cdc/prime/reportstream/shared/QueueMessage.kt
Labels: platform

#17211 Experience/16073/message-testing-download-feature
  frontend-react/package.json
  frontend-react/src/components/Admin/MessageTesting/MessageTestingAccordion.tsx
  frontend-react/src/components/Admin/MessageTesting/MessageTestingPDF.tsx
  frontend-react/src/components/Admin/MessageTesting/MessageTestingResult.tsx
  frontend-react/src/pages/admin/AdminMessageTestingPage/AdminMessageTestingPage.tsx
  frontend-react/src/pages/error/Generic.tsx
  frontend-react/yarn.lock
Labels: experience

#17231 Update 0023-condition-to-code-mapping.md to correct broken Diagram
  prime-router/docs/design/proposals/0023-condition-to-code-mapping/0023-condition-to-code-mapping.md
Labels: documentation, platform
