Repository CDCgov/prime-reportstream, pull requests merged in 2025-02, with the labels that each got.

#17253 [16141] Amending new folder name.
  prime-router/src/main/kotlin/azure/BlobAccess.kt
Labels: platform

#17252 Remove unused devops issue template
  .github/ISSUE_TEMPLATE/devops_request.md
Labels: DevSecOps

#17256 update roadmap
  frontend-react/src/content/about/roadmap.mdx
Labels: experience, trialfrontend03

#17222 Create E2E test for the Test Message Bank Page
  frontend-react/e2e/mocks/message-test.ts
  frontend-react/e2e/pages/authenticated/admin/organization-receiver-message-test.ts
  frontend-react/e2e/pages/authenticated/admin/organization.ts
  frontend-react/e2e/spec/all/authenticated/admin/organization-receiver-message-test.spec.ts
  frontend-react/src/AppRouter.tsx
  frontend-react/src/components/Admin/MessageTesting/MessageTestingAccordion.tsx
  frontend-react/src/components/Admin/MessageTesting/MessageTestingCustomMessage.tsx
  frontend-react/src/components/Admin/MessageTesting/MessageTestingForm.tsx
  frontend-react/src/components/Admin/MessageTesting/MessageTestingResult.tsx
Labels: experience

#17266 Devsecops/emvaldes/export azure resources
  operations/app/terraform/scripts/compare-records.shell
  operations/app/terraform/scripts/export-resources.ps1
  operations/app/terraform/scripts/export-resources.py
  operations/app/terraform/scripts/export-resources.shell
  operations/app/terraform/scripts/requirements.txt
Labels: reportstream, infrastructure, Feature enhancement, DevSecOps

#17182 Remove storybook-addon-remix-react-router
  frontend-react/.storybook/main.ts
  frontend-react/package.json
  frontend-react/src/layouts/Main/MainLayout.stories.tsx
  frontend-react/yarn.lock
Labels: experience

#17293 Experience/17137/re update roadmap
  frontend-react/src/content/about/roadmap.mdx
Labels: experience, trialfrontend02

#17280 accommodate new BE testing/test result endpoint
  frontend-react/src/components/Admin/MessageTesting/MessageTestingAccordion.tsx
  frontend-react/src/components/Admin/MessageTesting/MessageTestingPDF.tsx
  frontend-react/src/components/Admin/MessageTesting/MessageTestingResult.fixtures.ts
  frontend-react/src/components/Admin/MessageTesting/MessageTestingResult.tsx
  frontend-react/src/config/endpoints/reports.ts
Labels: experience, trialfrontend03

#17254 Experience/16100-Create-E2E-test-for-the-Test-Results-Page
  frontend-react/e2e/pages/authenticated/admin/organization-receiver-message-test.ts
  frontend-react/e2e/spec/all/authenticated/admin/organization-receiver-message-test.spec.ts
Labels: experience

#17327 download PDF and check if it has contents
  frontend-react/e2e/pages/authenticated/admin/organization-receiver-message-test.ts
  frontend-react/e2e/spec/all/authenticated/admin/organization-receiver-message-test.spec.ts
Labels: experience

#17078 Oo/oslynn/17016/add sender id transform to c2 sense and mmtc and update routing filter
  prime-router/settings/STLTs/HHS-Protect/hhs-protect.yml
  prime-router/src/main/resources/metadata/fhir_transforms/senders/C2Sense/c2sense-sender-transform.yml
  prime-router/src/main/resources/metadata/fhir_transforms/senders/MMTC/mmtc-sender-transform.yml
Labels: onboarding-ops

#17326 Add migration creation and deployment guidance to postgres-database.md
  prime-router/docs/getting-started/postgres-database.md
Labels: platform

#17143 UP Deduplication Design Documentation
  prime-router/docs/design/design/data-model.md
  prime-router/docs/design/design/deduplication/Dedupe_Design.jpg
  prime-router/docs/design/design/deduplication/deduplication.md
  prime-router/docs/getting-started/postgres-database.md
  prime-router/docs/universal-pipeline/receive.md
Labels: platform

#17345 fix Message Testing Result caching
  frontend-react/src/hooks/api/messages/UseTestMessageResult/UseTestMessageResult.ts
Labels: experience

#17351 Devsecops/matts/docker.postgres
  operations/utils/postgres/Dockerfile.postgres
  operations/utils/postgres/Makefile
  operations/utils/postgres/README.md
Labels: reportstream, DevSecOps, Injection

#17377 vpn connection debug
  .github/actions/connect-ovpn/action.yml
Labels: reportstream, DevSecOps, Injection

#17334 [16142] Implement Updated ReceiverFilter Step Requirements
  prime-router/metadata/json_schema/organizations/organizations.json
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/Report.kt
  prime-router/src/main/kotlin/ReportStreamFilter.kt
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/cli/SettingCommands.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiverFilter.kt
  prime-router/src/test/kotlin/FileSettingsTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirReceiverFilterTests.kt
  prime-router/src/test/kotlin/history/SubmissionHistoryTests.kt
Labels: platform

#17379 add debug logging to openvpn
  .github/actions/connect-ovpn/action.yml
  .github/actions/vpn-azure/action.yml
Labels: reportstream, DevSecOps

#17391 add dev mode that removes browser overlays
  frontend-react/package.json
  frontend-react/vite.config.ts
Labels: experience

#17393 Update Hapi Libraries
  prime-router/build.gradle.kts
  prime-router/src/main/kotlin/transport/GAENTransport.kt
Labels: platform

#17037 Add Missing Timezone to RS
  frontend-react/src/utils/TemporarySettingsAPITypes.ts
  prime-router/src/main/kotlin/USTimeZone.kt
  prime-router/src/test/kotlin/fhirengine/engine/CustomTranslationFunctionsTest.kt
Labels: onboarding-ops

#17436 Experience/16759/code mapping results page
  frontend-react/src/components/CodeMapping/CodeMappingForm.tsx
  frontend-react/src/components/CodeMapping/CodeMappingResults.tsx
  frontend-react/src/hooks/api/UseCodeMappingFormSubmit/UseCodeMappingFormSubmit.ts
  frontend-react/src/pages/onboarding/CodeMappingPage.tsx
  frontend-react/src/shared/Table/Table.module.scss
  frontend-react/src/shared/Table/Table.tsx
Labels: experience, trialfrontend03

#17429 Set Hikari connection timeout to 60 seconds
  prime-router/src/main/kotlin/azure/DatabaseAccess.kt
Labels: platform
