Repository CDCgov/prime-reportstream, pull requests merged in 2025-05, with the labels that each got.

#18030 Revert "16059 Removed skip from last mile failure test"
  frontend-react/e2e/spec/chromium-only/authenticated/last-mile-failures-page-user-flow.spec.ts
Labels: frontend, experience

#18035 Add itemCount to REPORT_RECEIVED event
  prime-router/src/main/kotlin/azure/ReportFunction.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventData.kt
Labels: platform

#17948 docs(#17895): updates roadmap copy
  frontend-react/src/content/about/roadmap.mdx
Labels: experience, trialfrontend02

#18034 Experience/17792/code mapping e2e
  frontend-react/e2e/fixtures/codemapping_success.csv
  frontend-react/e2e/fixtures/codemapping_unmapped_codes.csv
  frontend-react/e2e/pages/authenticated/code-mapping.ts
  frontend-react/e2e/spec/all/authenticated/code-mapping-tool-page.spec.ts
Labels: frontend, experience

#18044 16059 -Unskips a last mile failures page user flow/smoke test
  frontend-react/e2e/spec/chromium-only/authenticated/last-mile-failures-page-user-flow.spec.ts
Labels: frontend, experience

#17869 Add timeBetweenBatches delay to space out batch messages
  prime-router/metadata/json_schema/organizations/organizations.json
  prime-router/settings/organizations.yml
  prime-router/src/main/kotlin/Receiver.kt
  prime-router/src/main/kotlin/azure/QueueAccess.kt
  prime-router/src/main/kotlin/azure/batch/BatchDeciderFunction.kt
  prime-router/src/test/kotlin/azure/batch/BatchDeciderTests.kt
  prime-router/src/testIntegration/resources/settings/organizations.yml
Labels: platform

#17989 17343 add queuemessage to azure events
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/azure/SendFunction.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventBuilder.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventData.kt
  prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventService.kt
  prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
  prime-router/src/main/kotlin/fhirengine/azure/FHIRFunctions.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRDestinationFilter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiverEnrichment.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiverFilter.kt
  prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
  prime-router/src/main/kotlin/fhirengine/engine/PrimeRouterQueueMessage.kt
  prime-router/src/main/kotlin/transport/AS2Transport.kt
  prime-router/src/main/kotlin/transport/BlobStoreTransport.kt
  prime-router/src/main/kotlin/transport/EmailTransport.kt
  prime-router/src/main/kotlin/transport/GAENTransport.kt
  prime-router/src/main/kotlin/transport/ITransport.kt
  prime-router/src/main/kotlin/transport/NullTransport.kt
  prime-router/src/main/kotlin/transport/RESTTransport.kt
  prime-router/src/main/kotlin/transport/SftpTransport.kt
  prime-router/src/main/kotlin/transport/SoapTransport.kt
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
  prime-router/src/test/kotlin/azure/FHIRFunctionsTests.kt
  prime-router/src/test/kotlin/azure/SendFunctionTests.kt
  prime-router/src/test/kotlin/azure/observability/context/MDCUtilsTest.kt
  prime-router/src/test/kotlin/azure/observability/event/ReportEventServiceTest.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRDestinationFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverFilterIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/azure/FHIRTranslatorIntegrationTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirDestinationFilterTests.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirTranslatorTests.kt
  prime-router/src/testIntegration/kotlin/transport/AS2TransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/GAENTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/SftpTransportIntegrationTests.kt
  prime-router/src/testIntegration/kotlin/transport/SoapTransportIntegrationTests.kt
  shared/src/main/kotlin/gov/cdc/prime/reportstream/shared/auth/AuthZService.kt
  shared/src/test/kotlin/gov/cdc/prime/reportstream/shared/auth/AuthZServiceTest.kt
Labels: platform

#18107 Experience Dependabot 2025-05-12
  frontend-react/package.json
  frontend-react/yarn.lock
Labels: frontend, experience

#18118 ignore submission table integration test
  prime-router/src/test/kotlin/fhirengine/azure/SubmissionTableServiceIntegrationTests.kt
Labels: platform

#18116 13598 address database varchar size limits
  prime-router/src/main/kotlin/azure/ActionHistory.kt
  prime-router/src/main/kotlin/common/AzureHttpUtils.kt
  prime-router/src/main/resources/db/migration/V75__extend_character_limits.sql
  prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
Labels: platform

#18121 LA CVS onboarding
  prime-router/src/main/resources/metadata/fhir_transforms/senders/CVSHealth/cvs-health-sender-transform.yml
  prime-router/src/main/resources/metadata/hl7_mapping/receivers/STLTs/LA/LA-receiver-transform.yml
  prime-router/src/test/kotlin/azure/batch/BatchDeciderTests.kt
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_LA_20240806-0001.hl7
Labels: onboarding-ops
