Repository CDCgov/prime-reportstream, pull requests merged in 2025-03, with the labels that each got.

#17438 daily data filename
  prime-router/src/main/kotlin/history/azure/DatabaseDeliveryAccess.kt
  prime-router/src/main/kotlin/history/db/DeliveryHistoryDatabaseAccess.kt
  prime-router/src/test/kotlin/common/ReportNodeBuilder.kt
  prime-router/src/test/kotlin/history/db/DeliveryHistoryDatabaseAccessTests.kt
Labels: platform

#17534 [17330] Log test result interpretations in Azure Event.
  prime-router/src/main/kotlin/azure/observability/event/AzureEventUtils.kt
  prime-router/src/main/kotlin/azure/observability/event/ObservationSummary.kt
  prime-router/src/test/kotlin/azure/observability/bundleDigest/FhirPathBundleDigestExtractorStrategyTests.kt
  prime-router/src/test/kotlin/azure/observability/event/AzureEventUtilsTest.kt
  prime-router/src/test/kotlin/fhirengine/engine/FhirDestinationFilterTests.kt
Labels: platform

#17512 Resolve Issue of removing slashes (' - ') from incoming date on OBX-4
  prime-router/src/main/resources/metadata/fhir_transforms/senders/SimpleReport/simple-report-sender-transform.yml
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_AL_20240624-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_CO_20240403.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_FL_20240702-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_ID_20240624-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_IN_20240618-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_KS_20240429-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_MH_20240701-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_MH_20241226-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_NH_202407016-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_NJ_20240719-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_NM_20240702-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_OK_20240628-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_OR_20240724-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_PA_20240703-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_PR_20240624-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_SD_20240718-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_TN_20240701-0001.hl7
  prime-router/src/testIntegration/resources/datatests/FHIR_to_HL7/sample_UT_20240624-0001.hl7
Labels: onboarding-ops

#17597 Update azurite version to 3.33.0 to work with latest azure core tools
  .environment/docker/docker-compose/Dockerfile.azurite
Labels: platform

#17094 16815 authz design
  auth/docs/setup.md
  auth/src/main/resources/application.yml
  auth/src/scripts/get_client_access_token.py
  prime-router/docs/authz/authz-design.md
  prime-router/docs/authz/authz-transition-plan.md
  prime-router/docs/authz/img/access-policy-rule.png
  prime-router/docs/authz/img/access-policy.png
  prime-router/docs/authz/img/default-access-policy-rule.png
  prime-router/docs/authz/img/groups-claim.png
  prime-router/docs/authz/img/okta-scope.png
  prime-router/docs/authz/img/submit-attr.png
  prime-router/docs/authz/img/user-profile.png
  prime-router/docs/authz/img/user-submit.png
Labels: platform

#17585 Update build_hub.yml
  .github/workflows/build_hub.yml
Labels: reportstream, DevSecOps

#17621 Update SC setting per request
  prime-router/settings/STLTs/SC/sc-phd.yml
Labels: onboarding-ops, South Carolina

#17582 Update dev postgreSQL version to 16.6
  .environment/docker/docker-compose/Dockerfile.postgres
Labels: platform

#17683 [17603] Fix incomplete History API response.
  prime-router/src/main/kotlin/history/SubmissionHistory.kt
  prime-router/src/test/kotlin/history/SubmissionHistoryTests.kt
Labels: platform

#17692 Issue_14974_New_Mexico
  prime-router/metadata/file_name_templates/file-name-templates.yml
  prime-router/settings/STLTs/NM/nm-doh.yml
  prime-router/settings/STLTs/WI/wi-dph.yml
Labels: onboarding-ops, New Mexico, engineering
